### ISSUE TITLE
KZ earbuds

### ISSUE THREAD

**Issue by augaug** [jaakkopasanen/AutoEq#1]
Any chance we could get profiles for the budget KZ ZST, ZS3, ZS5, etc.? Thanks!

**Comment by jaakkopasanen** [comment]
Some of the KZ buds / iems will be added with [Crinacles measurements](https://www.head-fi.org/threads/crinacles-iem-fr-measurement-database-29-06-update.830062/) which I intend to do in the future. I'll post an update here when they are available.

**Comment by jaakkopasanen** [comment]
Crinacle's measurements added. There is now 13 different KZ models covered.
