### ISSUE TITLE
[Request] TRN V80 EQ

### ISSUE THREAD

**Issue by RoboJin** [jaakkopasanen/AutoEq#10]
Measurement
https://www.head-fi.org/showcase/trn-v80.23225/reviews
http://www.thephonograph.net/trn-v80-review/
https://audiobudget.com/product/TRN/V80

**Comment by jaakkopasanen** [comment]
You can create eq settings for these yourself. See the guide here: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)
