### ISSUE TITLE
Is there any way to chart manually?

### ISSUE THREAD

**Issue by andrewb0922** [jaakkopasanen/AutoEq#101]
I wanted to apply auto eq to my new airpods pro
And I understand that you just can not update once a week so you won't be able to respond to all of the request of IEMs results coming out
Therefore I wanted to chart it manually and apply it 
But i just can't figure out how the charting was done

**Comment by jaakkopasanen** [comment]
Using the scraping tools is a bit of a mess right now. They're not really intended for end users and basically require some level of technical know-how. The results page has a guide linked for getting the data from graph images semi-manually if you would like to try that.

**Comment by jaakkopasanen** [comment]
AirPods Pro's can now be found in the the list.

I'll close this issue because I don't intend to make the scraping tools super user-friendly and the guide for semi-manual process exists already.
