### ISSUE TITLE
Add support for shelf filters for parametric equalizers

### ISSUE THREAD

**Issue by gordonel** [jaakkopasanen/AutoEq#102]
Most parametric equalisers have shelf filters on the lowest and the highest of bands, and while using peaking filters does the job, shelf filters could do a better job.

"All Peaking" configuration could be the default one unless user specifies an argument like --use_shelf

**Comment by jaakkopasanen** [comment]
Shelf filters are typically easier for humans to understand but are not necessary for the filter optimization algorithm in AutoEQ. Some devices have a few peaking filters with a single low shelf and a single high self and for these it would be beneficial to support shelf filters. Some of these however limit the frequency of the low shelf to bass frequencies and the high shelf to upper treble and as of now the optimization algorithm can't quarantee that the center frequency for the self filters would stay in those ranges. I would have to do bigger changes to support this.

I might add this at some point but this is not very high on my priority list because it's so niche use case. Don't hold your breath!

**Comment by ftrebien** [comment]
That would be very nice. I've been using a system-wide [LADSPA](https://github.com/swh/ladspa) _mbeq_ module (1024-point FFT-based equalizer) following Freedesktop's [docs](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-ladspa-sink), but people could definitely get better quality and much lower overhead with a filter like _triplePara_ (3 parametric biquads + low and high shelves), which already improves sound dramatically with just 3 bands, but it would perform even better taking advantage of the shelves.

**Comment by stinos** [comment]
@jaakkopasanen I noticed part of the code for this is actually implemented. Just to quickly try smething I put `n_ls` and `n_hs` to 1 in frequency_response.py and the resulting filter is different, but doesn't look correct (I'm not completely sure the plotting part knows how to plot shelves though, only had a quick look, but feeding it into Peace and changing the first and last into ls/hs respectively, the response in the treble region especially looks wrong). Anyway, discarding that the optimization algorithm cannot make guarantees about shelf frequencies, could you perhaps at a high level explain what should change in the code to support this?

**Comment by stinos** [comment]
Had a better look through everything. There's a bunch of changes needed, more than I have time to implement, but with some quick adjustments I think I have something which seems to work correctly. That is to say it generates and plots an acceptable response, not sure if it's the most optimal; the initial peak/gain estimation might need tuning as well. For reference (coefficients removed because unused anyway - saving of files etc not adjusted so if loading this into PEACE etc manually change first and last to shelve filters):

```
index 75adb39f7f..b3af9dfe11 100644
--- a/frequency_response.py
+++ b/frequency_response.py
@@ -299,7 +299,7 @@ class FrequencyResponse:
         # Equalization target
         eq_target = tf.constant(target, name='eq_target', dtype='float32')

-        n_ls = n_hs = 0
+        n_ls = n_hs = 1

         if parametric:
             # Fc and Q not given, parametric equalizer, find initial estimation of peaks and gains
@@ -451,8 +451,9 @@ class FrequencyResponse:

         # Filter design

+        n_pk = n_pk - n_ls - n_hs
+
         # Low shelf filter
-        # This is not used at the moment but is kept for future
         A = 10 ** (gain[:n_ls, :] / 40)
         w0 = 2 * np.pi * tf.pow(10.0, fc[:n_ls, :]) / fs_tf
         alpha = tf.sin(w0) / (2 * Q[:n_ls, :])
@@ -479,7 +480,6 @@ class FrequencyResponse:
         b2_pk = (1 - alpha * A) / a0_pk

         # High self filter
-        # This is not kept at the moment but kept for future
         A = 10 ** (gain[n_ls+n_pk:, :] / 40)
         w0 = 2 * np.pi * tf.pow(10.0, fc[n_ls+n_pk:, :]) / fs_tf
         alpha = tf.sin(w0) / (2 * Q[n_ls+n_pk:, :])
@@ -573,18 +573,25 @@ class FrequencyResponse:
         _Q = _Q[sorted_inds]
         _gain = _gain[sorted_inds]

-        # Expand dimensionality for biquad
-        _fc = np.expand_dims(_fc, axis=1)
-        _Q = np.expand_dims(np.abs(_Q), axis=1)
-        _gain = np.expand_dims(_gain, axis=1)
-        # Re-compute eq
-        a0, a1, a2, b0, b1, b2 = biquad.peaking(_fc, _Q, _gain, fs=fs)
-        frequency = np.repeat(np.expand_dims(frequency, axis=0), len(_fc), axis=0)
-        _eq = np.sum(biquad.digital_coeffs(frequency, fs, a0, a1, a2, b0, b1, b2), axis=0)
+        def compute_biquad_eq(func, fc, Q, gain, frequency):
+            if not any(fc):
+                return 0
+            # Expand dimensionality for biquad
+            fc = np.expand_dims(fc, axis=1)
+            Q = np.expand_dims(np.abs(Q), axis=1)
+            gain = np.expand_dims(gain, axis=1)
+
+            # Re-compute eq
+            a0, a1, a2, b0, b1, b2 = func(fc, Q, gain, fs=fs)
+            frequency = np.repeat(np.expand_dims(frequency, axis=0), len(fc), axis=0)
+            return np.sum(biquad.digital_coeffs(frequency, fs, a0, a1, a2, b0, b1, b2), axis=0)

-        coeffs_a = np.hstack((np.tile(a0, a1.shape), a1, a2))
-        coeffs_b = np.hstack((b0, b1, b2))
-        return _eq, rmse, np.squeeze(_fc, axis=1), np.squeeze(_Q, axis=1), np.squeeze(_gain, axis=1), coeffs_a, coeffs_b
+        low_shelf = compute_biquad_eq(biquad.low_shelf, _fc[:n_ls], _Q[:n_ls], _gain[:n_ls], frequency)
+        peakings = compute_biquad_eq(biquad.peaking, _fc[n_ls:n_ls+n_pk], _Q[n_ls:n_ls+n_pk], _gain[n_ls:n_ls+n_pk], frequency)
+        high_shelf = compute_biquad_eq(biquad.high_shelf, _fc[n_ls+n_pk:], _Q[n_ls+n_pk:], _gain[n_ls+n_pk:], frequency)
+        _eq = low_shelf + peakings + high_shelf
+
+        return _eq, rmse, _fc, _Q, _gain

     def optimize_parametric_eq(self, max_filters=None, fs=DEFAULT_FS):
         """Fits multiple biquad filters to equalization curve. If max_filters is a list with more than one element, one
@@ -615,11 +622,10 @@ class FrequencyResponse:

         self.parametric_eq = np.zeros(self.frequency.shape)
         fc = Q = gain = np.array([])
-        coeffs_a = coeffs_b = np.empty((0, 3))
         n_produced = []
         max_gains = []
         for n in max_filters:
-            _eq, rmse, _fc, _Q, _gain, _coeffs_a, _coeffs_b = self.optimize_biquad_filters(
+            _eq, rmse, _fc, _Q, _gain = self.optimize_biquad_filters(
                 frequency=self.frequency,
                 target=self.equalization - self.parametric_eq,
                 max_filters=n,
@@ -632,8 +638,6 @@ class FrequencyResponse:
             fc = np.concatenate((fc, _fc))
             Q = np.concatenate((Q, _Q))
             gain = np.concatenate((gain, _gain))
-            coeffs_a = np.vstack((coeffs_a, _coeffs_a))
-            coeffs_b = np.vstack((coeffs_b, _coeffs_b))

         filters = np.transpose(np.vstack([fc, Q, gain]))
         return filters, n_produced, max_gains
```
