### ISSUE TITLE
Momentum true wireless

### ISSUE THREAD

**Issue by starraiderx** [jaakkopasanen/AutoEq#106]
Can you add support for the momentum true wireless?

**Comment by jaakkopasanen** [comment]
Do you mean these?
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2017-1/Sennheiser%20Momentum%20True%20Wireless
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/usound/Sennheiser%20Momentum%20True%20Wireless

They have been there for a long time.
