### ISSUE TITLE
Missing free Mac OSX instructions.

### ISSUE THREAD

**Issue by timorohner** [jaakkopasanen/AutoEq#108]
The combination of [Hosting AU](http://ju-x.com/hostingau.html) and [Blackhole](https://github.com/ExistentialAudio/BlackHole) offers system-wide EQ on Mac osx.

BlackHole is a virtual audio driver, while Hosting AU offers routing between inputs/outputs and adding AU to the chain. 

Since the documentation doesn't provide any free usable solution on OSX that allows for full parametric EQ, I think it might be worth adding the above links.

I'm running this combination myself (with a pair of Sennheiser HD800 and an ODAC hooked up to the computer): 

![image](https://user-images.githubusercontent.com/38220377/71527191-9706ac80-28da-11ea-8f70-88caf57c4821.png)

**Comment by jaakkopasanen** [comment]
Thanks a lot! I added these to the OSX section.
