### ISSUE TITLE
AUNBandEQ's bandwidth has an extremely low max frequency

### ISSUE THREAD

**Issue by 2gotgrossman** [jaakkopasanen/AutoEq#111]
When using `AUNBandEQ` via SoundSource on MacOS, I use the Q conversion you provide (`bw = Fc / Q`). However,  `AUNBandEQ` has a maximum width of `5`. Am I doing something wrong?
<img width="546" alt="" src="https://user-images.githubusercontent.com/1361444/72411346-8601cc00-371f-11ea-899d-ecd5318b7d70.png">

As a slight tangent, `AUNBandEQ` allows users to import an exact curve. Is there a way to generate such a curve? 
<img width="558" alt="" src="https://user-images.githubusercontent.com/1361444/72411511-e1cc5500-371f-11ea-9fdb-64c4c2244685.png">

**Comment by jaakkopasanen** [comment]
Hi. Thanks for bringing this up!

What you're seeing here is actually a different thing because I'm fairly certain that the width in this case is not in Hertz but in octaves.

```
Q = 2^(N/2)/(2^N-1)
```
, where `N` is bandwidth in octaves.

So other way around it's
```
N = ln(1 + 1/(2*Q^2) + sqrt(((2*Q^2 + 1) / Q^2 )^2 / 4 - 1)) / ln(2)
```
, where `ln` is natural logarithm.

Probably you want to use an online calculator for this: http://www.sengpielaudio.com/calculator-bandwidth.htm

I added all this to the readme.

**Comment by 2gotgrossman** [comment]
Ah that'll do it! Thanks so much for your help. This project is my best find so far in venturing into the audiophile world. You are truly the best :)

**Comment by jaakkopasanen** [comment]
Thanks for your kind words :)

**Comment by jhon12346** [comment]
hz to octaves converter for mac users change the Q values and copy it and  run it [here](https://www.tutorialspoint.com/execute_nodejs_online.php)


`var Q1 = 5` 
`var Q2 = 5`
`var Q3 = 5`
`var Q4 = 5`
`var Q5 = 5`
`var Q6 = 5`
`var Q7 = 5`
`var Q8 = 5`
`var Q9 = 5 `
`var Q10  = 5`

`// don't touch anything down`


`var arr = [Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10 ]`
 ` arr.forEach(Q => { `
`var sqr = Q*Q`
`var j = ((2*sqr + 1) / sqr )`
`var m = Math.log(1 + 1/(2*sqr) + Math.sqrt(j*j / 4 - 1))`
`var final = m/Math.log(2)`
 `console.log(final); `
`} );`
