### ISSUE TITLE
Could you add the Sennheiser HD 206?

### ISSUE THREAD

**Issue by aesg97** [jaakkopasanen/AutoEq#112]
Recently I just bought some Sennheiser HD 206, a friend recommended me his program to equalize the headphones, however, the model does not appear on the list, and I have no idea how to get the graph, I already googled and I can't find  something

**Comment by jaakkopasanen** [comment]
Sorry. There's nothing I can do. AutoEQ always needs a frequency response measurement and if the headphone model not already supported then I don't have frequency response.
