### ISSUE TITLE
Plantronics RIG 500, 500E, 500HD, 500HS, 500HX

### ISSUE THREAD

**Issue by Devocub** [jaakkopasanen/AutoEq#113]
The all listed headphones have same ear cups.
Frequency response fix was made from graph shown on their official site **for isolated ear cups**.

```
# Plantronics RIG500 fix frequency response
GraphicEQ: 2 -11.8; 20 -15.8; 50.8 -17; 80.2 -17.4; 100.5 -17.4; 239.6 -15; 282.8 -14.4; 400 -10.8; 476.6 -8.6; 545.8 -8.6; 680 -11.3; 799.5 -11.3; 1002.2 -11.2; 1218.7 -11.1; 1445.8 -11.8; 1511 -11.5; 1583.5 -10.5; 1641.2 -10.4; 1990.4 -14.5; 2284.4 -14.5; 2903.7 -18.5; 3128.5 -18.6; 3227.3 -17.6; 4000 -10.8; 4914.6 -3.6; 5164.5 -3; 5427.1 -2.9; 5900 -4.5; 6581.8 -16.6; 6728.5 -17.7; 7090.2 -16.5; 7659 -10.7; 7894.7 -10.7; 8961.6 -19.8; 9250 -20.4; 9650 -19; 10350 -9.8; 11484 -7.3; 11903 -3.8; 12405 -3.3; 13400 -8.7; 13775 -10; 14475 -10.7; 15170 -9.6; 16752 -1.9; 17459 -1.2; 18859 -0.9; 19439 -0.4; 20000 0; 22000 -1
```
It's this but inverted:
![image](https://user-images.githubusercontent.com/2735824/72671842-fe3ef900-3a61-11ea-96ec-6294d547d79a.png)

* 500E have two graphs (isolated and vented ear cups)

https://www.plantronics.com/us/en/product/rig-500
https://www.plantronics.com/us/en/product/rig-500e
https://www.plantronics.com/us/en/product/rig-500hd
https://www.plantronics.com/us/en/product/rig-500hs
https://www.plantronics.com/us/en/product/rig-500hx

**Comment by jaakkopasanen** [comment]
Hi,

I'm not hosting results from other sources than the supported measurement databases in AutoEQ. I suggest you post these to [reddit](https://reddit.com/r/headphones) and/or [Head-Fi](https://head-fi.org/forums/).
