### ISSUE TITLE
Request for Sony MDR-1AM2.

### ISSUE THREAD

**Issue by DestroyTargetNo** [jaakkopasanen/AutoEq#115]
https://reference-audio-analyzer.pro/en/report/hp/sony-mdr-1am2.php

Thank you kindly!

**Comment by jaakkopasanen** [comment]
This will be added when I rework Reference Audio Analyzer crawler. As of now it doesn't really work and I have a completely new tooling for crawling.

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/HDM-X/OneOdio%20Studio%20Standard%20Professional%20DJ%20headphone

**Comment by DestroyTargetNo** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/HDM-X/Sony%20MDR-1AM2 *

**Comment by jaakkopasanen** [comment]
Indeed. I posted the wrong link. That one was also requested in another issue. Good thing you found the correct one!
