### ISSUE TITLE
SHP 9500 different sound for convolution vs parametric eq

### ISSUE THREAD

**Issue by kkanungo17** [jaakkopasanen/AutoEq#116]
Hi,

I'm using BlackHole+HostingAU with AUNBand for parametric eq and LAConvolver for convolution. I find that the parametric eq sounds quite different from the convolution filters (with the convolution filter sounding better, treble wise, to my ears, though both are an improvement over stock sound). Which one is the correct setting to apply? I have also tried oratory1990's eq preset on reddit, and I find it closer to the convolution filter.

I'm converting the Q values to BW using an online calculator for AUNBand.

**Comment by jaakkopasanen** [comment]
Interesting. To me both sound more or less the same although I did only a very short listening test. Also based on EqualizerAPO's frequency response display both very close to each other. Did you test both with normalized loudness? By default the parametric eq preamp values are about -0.5 dB lower than they absolutely should be. This is to add that a small bit of extra safety. If you didn't adjust the preamp manually then it could be that what you are hearing is the 0.5 dB loudness difference.

And of course as always the only "correct" one is the one you prefer :)
