### ISSUE TITLE
Readme for PulseEffects needs update

### ISSUE THREAD

**Issue by vhborges** [jaakkopasanen/AutoEq#117]
The [PulseEffects section](https://github.com/jaakkopasanen/AutoEq#pulseeffects) of the readme is relating to an older version of the app.
Currently there's no more a "Peak" filter type (according to my research the similar type is now "Bell") and you no longer set the band width, instead you directly set the quality for each filter.

Also, it would be nice to add that the preamp setting (mentioned in the results files) is the Input slider at the bottom.

Here's a screenshot of the most recent version: https://i.imgur.com/EakRd4F.png

**Comment by jaakkopasanen** [comment]
Thanks a lot for reporting this. I updated the screenshot and the instructions. https://github.com/jaakkopasanen/AutoEq#pulseeffects
