### ISSUE TITLE
Corsair Virtuoso request

### ISSUE THREAD

**Issue by inflextion** [jaakkopasanen/AutoEq#118]
Hi @jaakkopasanen,

Could you help with some Corsair Virtuoso AutoEq?
The results for can be found here:
https://www.rtings.com/headphones/reviews/corsair/virtuoso-rgb-wireless

**Comment by jaakkopasanen** [comment]
For some reason the Virtuoso is not in the index on Rtings.com (the graph tool). I downloaded Virtuoso manually to get it added to AutoEQ.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/Corsair%20Virtuoso%20RGB%20Wireless
