### ISSUE TITLE
Request for Logitech g560

### ISSUE THREAD

**Issue by natzal** [jaakkopasanen/AutoEq#119]
Thank you for the great work. I use your Senn 6XX, Senn TW, and Audeze mobius settings. Any chance you can do something for the Logitech G560 Lightsync?

Thanks again

**Comment by jaakkopasanen** [comment]
There's nothing I can do I'm afraid. If that ends up being measured by one of the supported parties (Rtings, oratory1990, ...) then it will find it's way in AutoEQ eventually.
