### ISSUE TITLE
How to import this frequency response?

### ISSUE THREAD

**Issue by shadowzoom** [jaakkopasanen/AutoEq#120]
https://reference-audio-analyzer.pro/en/report/hp/oneodio-studio.php

**Comment by hjroh0315** [comment]
Please follow the instructions provided in https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/HDM-X/OneOdio%20Studio%20Standard%20Professional%20DJ%20headphone
