### ISSUE TITLE
HD559

### ISSUE THREAD

**Issue by fanto88** [jaakkopasanen/AutoEq#122]
Hi, i'm actually using a pair of HD559. Are the settings for HD558 fine for the HD559 too?

PS: Should i FixedBandEQ.txt, GraphicEQ.txt, ParametricEQ.txt all together or i should choose only one? Sorry, new to the sector!

**Comment by gKrager** [comment]
I'm in the same boat. The HD 559 is apparently a redone of the HD 518, which has a pretty similar config file to the HD 558, but varies a little. I'm trying that one out, but guess none will be perfect since the driver is tuned slightly different.

**Comment by jaakkopasanen** [comment]
You should use only one of them, not all. HD 559 is probably closer to HD 518 than to HD 558 so you sould probably use that.
