### ISSUE TITLE
Dead links in readme

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#123]
Hi Jaakko,

In the results README.md there are a few listings that lead to a 404 page not found error:
- AKG K361
- Bang & Olufsen Beoplay H9
- Bang & Olufsen Beoplay H9i
- Sennheiser IE 40 Pro
- Sennheiser IE 400 Pro
- Sennheiser IE 500 Pro
- Sennheiser IE 80 Half
- Sennheiser IE 80 Max
- Sennheiser IE 80 Min
- Sennheiser IE 80 S Half
- Sennheiser IE 80 S Max

I ran a script to verify all links and these are all listings that lead to a 404.
Could you please take a look at this? Thanks in advance.

**Comment by jaakkopasanen** [comment]
Very true, thanks a lot for letting me know! I had forgotten to add these files to git in the last commit. They are added now and I checked that the links work.
