### ISSUE TITLE
Request for Mr.Speakers Ether 2

### ISSUE THREAD

**Issue by Animalwithstix** [jaakkopasanen/AutoEq#125]
Please!  I have them and love them, but I want a good baseline to adjust from.  Thank you

**Comment by jaakkopasanen** [comment]
There's nothing I can do if they have not been measured by any of the supported measurement databases.

**Comment by Animalwithstix** [comment]
Hi,

What about a measurement directly from Mr. Speakers.  I have tried doing it on my own, but I am confused on which settings to use depending on where the graph comes from.  Dan Clark, the owner, posted this graph and the following information:
 "Measurements on GRAS 45CA. No compensation. 11K "notch" is a measurement artifact.
Black = Stock Pad
Red = Perforated
Blue = Suede"


There are a few other graphs when I searched google, but I don’t know which ones are better than others.  I’ll keep trying on my own.

Thanks
