### ISSUE TITLE
Hesuvi no longer recommended on Windows? 

### ISSUE THREAD

**Issue by Frugipon** [jaakkopasanen/AutoEq#126]
Hello,
I was wondering why Hesuvi is no longer recommended for applying EQ on Windows whereas it was the go to choice a few months back?

Now, only plain EqualizerAPO and PEACE are being listed. 

Thanks and sorry if it was not the appropriate place to ask.

**Comment by Manu99it** [comment]
Maybe because it doesn't stay updated with the equalizations and new models

**Comment by jaakkopasanen** [comment]
@Manu99it is correct. HeSuVi's eq profile catalogue is not updated so I can't recommend it. I have some plans for HeSuVi but that will probably include eq profiles optimized for speaker virtualization instead of just normal headphone listening.
