### ISSUE TITLE
What program can use  Convolution Equalizers file?

### ISSUE THREAD

**Issue by soarteam** [jaakkopasanen/AutoEq#127]
Does anybody know how to use the WAV file? Such as VST or APO or something?

**Comment by hjroh0315** [comment]
For Windows, Equalizer APO works with convolution (Add->Advanced Filters->Convolution), and for android, Viper4Android works.

**Comment by jaakkopasanen** [comment]
I've also heard Foobar 2000 being used with impulse responses: https://www.foobar2000.org/components/view/foo_convolve
