### ISSUE TITLE
Sony MDR-ZX770BN - New  ParametricEQ Setting Creating Squeaking Sound

### ISSUE THREAD

**Issue by RoboJin** [jaakkopasanen/AutoEq#13]
The old one are just fine but as soon as i manually key in the setting or import it to peace, it started to squeaking

**Comment by jaakkopasanen** [comment]
I re-processed all results which have filters with center frequency above 22050 Hz. Could you confirm and close this issue if the problem has been solved?

**Comment by RoboJin** [comment]
Tested your new reprocess result and it's working for 44.1 kHz format. Thanks so much
