### ISSUE TITLE
Is it possible to increase the accuracy of parametric EQ by increasing the numbers of filters? 

### ISSUE THREAD

**Issue by stx1998x** [jaakkopasanen/AutoEq#130]
Even if the --max_filters option is not used, the numbers of filter appears to not exceed 15.  Is it possible to increase the accuracy of parametric EQ by increasing the numbers of filters used?

**Comment by jaakkopasanen** [comment]
The optimization algorithm currently throws away filters it thinks are not needed. This might change in the future when I redo the filter optimization algorithm but until then the number is limited automatically. You can follow #91
