### ISSUE TITLE
Incomplete README in listings

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#131]
I noticed a few listings have an incomplete README. Normally there's a summary of the files and a preAmp specified, but not for the ones listed below:

AKG K271 MK.II
Bang & Olufsen Beoplay E8 2.0
Custom Art Ei.3
Custom Art Harmony 8.2
Lear LCM BD4.2
MrSpeakers Ether C Flow 1.1
Parrot Zik 2.0
Parrot Zik 3.0
Sennheiser CX 1.00
Sennheiser CX 2.00
Sennheiser CX 3.00
Sennheiser HD 4.40
Sennheiser HD 4.50
Sennheiser Momentum 2.0
Sennheiser Momentum 2.0 On-Ear
Sennheiser Momentum 2.0 Wireless
Shozy Form 1.1
Symphonized NRG 3.0
TFZ No.3
Tralucent 1Plus1.2
Tralucent 1Plus2.3
Tralucent 1Plus5.2
Translucent Audio 1Plus 2.2
Vision Ears VE 3.2 custom
Vision Ears VE3.2

This is a complete list.

Could you take a look at this?

**Comment by jaakkopasanen** [comment]
Thanks again! There was a bug with handling file names that contain dots. It's fixed now and I redid all these results. They're all fine now.
