### ISSUE TITLE
Measurements disappeared unexpectedly

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#134]
I try to introduce the software to the community in our country,  
and received good rates and reviews.

The last time I update my usage tutorial is around 2019/12/20,  
at that time the measurements data in still contains in Git repository,  
so with my fast start script, people can get there customized  EQ.

Yet on 2020/03/02 (today),  
I update to the latest AutoEQ and discovered now data is   
separated from Git repository and need to download in-time.  
I'm not saying this is bad(I think it is good too),  
but even I can't make a successful download, I have a Github issue out there.  
https://github.com/jaakkopasanen/AutoEq/issues/133

I see crinacle have a Google Drive out there,  
can we grab all the downloaded measurements data together  
and make an archive then put it on Google Drive or something too?  
So the end-users can get all things to work at once.

**Comment by jaakkopasanen** [comment]
Data is still here in the Git repository it just moved under measurements. Previously oratory1990 folder was in the project root and now the same folder is under folder called measurements.

https://github.com/jaakkopasanen/AutoEq/tree/master/measurements/oratory1990/data

Or did I misunderstand something?

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen Ugh, they are there indeed, is the search index not update and I use HDD hard drive, it's so slow than normal search makes me thing the `csv` files are gone.  
Now I can find them again!

Also actually I'm looking for
```AutoEq-master\results\crinacle\harman_in-ear_2019v2\Final Audio E3000```
It has "results" but not the measurements.  
I guess this file should in crinacle's Google Drive I then look for it.

**Comment by jaakkopasanen** [comment]
Crinacle's raw data is not hosted in AutoEq because he has a Patreon tier which unlocks the Google Drive. He asked me not to publish the numerical data so I don't.
