### ISSUE TITLE
Is there a way to convolution response wav files in higher bitrates using the results info and the software?

### ISSUE THREAD

**Issue by oktayaa** [jaakkopasanen/AutoEq#135]
LDAC supports much higher values but currently only 41000 and 48000 are available in the results. I am having to use graphiceq in their stead and maybe that creates the same end result? Can you give me a few quick pointers please.

**Comment by jaakkopasanen** [comment]
You can change the sampling rate of the convolution WAV files with `--fs` parameter. Simply put the sampling rate in Hertz, like 48000 or 96000. The higher sampling rates are useful only for some very, very specific use cases. Humans don't hear that high and 44100 Hz sampling rate contains all there is to it.

**Comment by oktayaa** [comment]
Thank you. I bought a new Sony WH-1000XM3. With Android it will default to LDAC at 96000 and the convolution loader I have was complaining about the mismatch in the sampling rate, I guess because it has to do conversions on the fly. However it (JamesDSP) does have an offline converter which I used to convert the file downloaded from here.

By the way it might be nice to add JamesDSP to documentation for android. I had issues with Viper where various audio apps did not seem to hit its processing. It also can't work with high sampling rates. Also the recommended non-root app for Android is now horrible. It might have changed owners.

**Comment by oktayaa** [comment]
Thank you for adding jamesdsp.
