### ISSUE TITLE
Duplicates and naming issues in results README

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#137]
Hi Jaakko,
There's a few naming issues and some duplicates because of that in the results README. The list may not be complete but it covers a lot of them:

AKG K581LE should be AKG K518LE
AKG K702 65th Anniversary Edition = AKG K702 65th Anv Ed 2014
AKG K81 DJ = AKG K81DJ
AKG N60NC / AKG N60 NC
Alpha and Delta / Alpha & Delta
Astro / ASTRO Gaming
Astrotec AX-7 = Astrotec AX7
Audeze iSine 10 = Audeze iSine10
Audeze iSine 20 = Audeze iSine20
Beats PowerBeats2 Bluetooth = Beats PowerBeats 2 Wireless
Beyerdynamic Custom Pro One switch position 1 should be Beyerdynamic Custom One Pro switch position 1
Beyerdynamic DT 250 250 Ohm = Beyerdynamic DT 250-250
Bose Noise Cancelling Headphones 700 =  Bose Headphone 700
Creative Aurvana Live 2 = Creative Aurvana Live! 2
Dunu / DUNU
Earsonic Velvet (warm) should be Earsonics Velvet (warm)
Fearless Audio / Fearless
Fiio / FiiO
Final Audio / Final Audio Design
Fostex TH 900 = Fostex TH900
Grado GR* / Grado GR *
Grado SR 80 should be Grado SR80
HiFiMAN / Hifiman
Some Hifiman HE listings have a -, some don't. The he6 is a duplicate because of that
HiFiMan RE0 / HiFiMan ReZero
Jays / JAYS
JVC HA-FW1000 should be JVC HA-FW10000
Klipsch image / Klipsch
Klipsch Mode M40 = Klipsch M40 Mode
KZ AS10 = KZ AS-10
Massdrop x MEE Audio Planamic IEM = Massdrop x MEE Planamic
Massdrop Plus = Massdrop Plus Universal
MEElectronics / MEE audio
Meze classics xx / Meze xx Classics
Monoprice M1060 = Monoprice Monolith M1060
Noble / Noble audio
NuForce Primo 8 = NuForce Primo8
EarFun Free = Oluv x EarFun Free
Oriolus Finischi = Oriolus Finschi
Phiton PS500 = Phiaton PS 500
Phiaton Bridge M500 = Phiaton Bridge MS 500
Piaton should be Phiaton
Sennheiser HD 212Pro = Sennheiser HD 212 PRO
Sennheiser IEXX need spaces. There's some duplication here
Skullcandy Mix Master = Skullcandy Mix Master Mike MMM
Sony MDR-7550 = Sony MDR7550
Sony MDRV-SA5000 and Sony MDRV-CD3000 don't exist. The V needs to be removed
Street by 50 = SMS Audio STREET by 50 Active Noise Cancelling
VE Monk IE Biggie = Venture Electronics Monk IE Biggie
Vision Ears VE 8 (CIEM) = Vision Ears VE8 (CIEM)
VSonic GR07 Bass Edition = Vsonic GR07 BE

I wanted to create a pull request with updated names in some of the name_index.tsv files, but I couldn't find this file for innerfidelity and headphone.com

**Comment by jaakkopasanen** [comment]
Thanks for this. I'm currently unifying all the namings for all the models to remove the duplicates but it will still take a while. I'll keep these in mind while I do this.

**Comment by jaakkopasanen** [comment]
All the naming issues should be resolved now (probably aren't). I checked all of your findings and fixed them. If there was ambiguity, I consulted the manufacturer's website for correct naming and styling.

Thanks again for bringing these up!
