### ISSUE TITLE
Need HyperX Cloud 2

### ISSUE THREAD

**Issue by MrGrifff** [jaakkopasanen/AutoEq#140]
Hello,
It would be cool to make a preset for HyperX Cloud 2 because it lacks bass.
Do you think you'll ever make one?
Sincerely

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/HyperX%20Cloud%20II

**Comment by MrGrifff** [comment]
Thanks for you're help, i don't find this before you're help. Well, you're work are genius :)
