### ISSUE TITLE
[Request] ATH-AD900x

### ISSUE THREAD

**Issue by iknowyounaut** [jaakkopasanen/AutoEq#141]
First off I would like  to say thanks for all the work you've put into creating this project. It really shapes the way I listen. You've covered all but 1 of my headphones. The AD900(x) the updated version with improved bass and slightly changed acoustics. Ive tried the AD900 eq, however it just sound off putting and muffled, likely due to the bump in bass. So if its possible id love to see an FIR for the updated version!

**Comment by jaakkopasanen** [comment]
If it's not measured by one of the supported databases then there's nothing I can do. You can follow the guide linked in the results page if you happen to find a frequency response for this one.
