### ISSUE TITLE
Moondrop Starfield results seem weird and wrong.

### ISSUE THREAD

**Issue by alexsarmiento** [jaakkopasanen/AutoEq#142]
Equalization for my Moondrop Starfield IEM using the covolution IR or parametric EQ, results in a telephonic sound. The compensation  seems overdone and exaggerated. Some clues support my impression.  According to the Graph Comparison Tool from crinacle, the frequency response for  Moondrop's KXXS and Starfield are  very similar, almost identical. 

However,  according to the  autoEQ (crinacle) results for the Starfield and KXXS the compensation should very different, with several decibels of difference. For instance, according to the crinacle's graph tool both models should be compensated by the same amount of decibels at 2kHz, but according to autoEQ there's a difference of 6db compensation between the Starfield and KXXS.

**Comment by alexsarmiento** [comment]
I reverse engineered the Moondrop Starfield graph from crinacle's website using a tool called WebPlotDigitizer, to obtain some raw csv data. I no longer get a "telephonic" sound but rather a decent equalization that feels more transparent. . With this data I get a better result which is more similar to the result for the KXXS.

I am further convinced that the result for Moondrop Starfield in crinacles folder is wrong.

**Comment by jaakkopasanen** [comment]
I had a lot of Crinacle's measurements processed incorrectly. That should be fixed now. Could you check again if you think the problem persists?

**Comment by alexsarmiento** [comment]
So far, the result for the Moondrop Starfield in the crinacle's folder has not been updated, so the problem remains. Same as issue #148.

I still get good results using my own raw "measurement" data from a digitizer.

**Comment by jaakkopasanen** [comment]
Indeed. The measurements were updated and fixed but of course some of the pre-computed results are unaffected. I'll re-process all the results to get them all fixed up.

**Comment by jaakkopasanen** [comment]
Done. I compared the old and the new. Seems fixed now.
