### ISSUE TITLE
Duplicate entries for Sony WH-1000XM3

### ISSUE THREAD

**Issue by auanasgheps** [jaakkopasanen/AutoEq#145]
Hi,
There are two entries for the Sony WH 1000 XM3.

This one also has a wrong name
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Sony%20WH1000XM3

This one has the right name
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/Sony%20WH-1000XM3

Which is the "right" EQ?

**Comment by Pittvandewitt** [comment]
Hi,
I think Jaakko is aware of this: https://github.com/jaakkopasanen/AutoEq/issues/137#issuecomment-600654059

The recommendation priority is: oratory1990 > Crinacle > Innerfidelity > Rtings > Headphone.com > Reference Audio Analyzer. (Copied from the results README)
This means the

**Comment by auanasgheps** [comment]
Thanks for the quick response.
