### ISSUE TITLE
Sony WI-1000X Measurement

### ISSUE THREAD

**Issue by chanlkanthony** [jaakkopasanen/AutoEq#146]
Hi:
I would like to think you for making the measure for us.
I have question:
Sony WI-1000X measurement was made under what condition.
With ANC on/off, wired/wireless?

Thanks.

**Comment by jaakkopasanen** [comment]
I don't know and the measurement report by oratory1990 doesn't say.

**Comment by chanlkanthony** [comment]
Thanks for your reply.
