### ISSUE TITLE
Which Audio-Technica ATH-M50x result to choose?

### ISSUE THREAD

**Issue by jtagcat** [jaakkopasanen/AutoEq#147]
There's many ATH-M50x results, as expected.

The result vary, as I understand, significantly. Which should one use?

**Comment by jaakkopasanen** [comment]
There are four different of which one is the bluetooth version and two are with aftermarket earpads. If you have the normal wired one with the normal pads then use the standard M50x result.

**Comment by jtagcat** [comment]
I understand, but there are 6 versions of the 'original'.
Some of them are similar, some are quite different.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/crinacle_over-ear/Audio-Technica%20ATH-M50X

https://github.com/jaakkopasanen/AutoEq/tree/master/results/headphonecom/sbaf-serious/Audio-Technica%20ATH-M50x

https://github.com/jaakkopasanen/AutoEq/tree/master/results/innerfidelity/sbaf-serious/Audio-Technica%20ATH-M50x

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Audio-Technica%20ATH-M50x

https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/zero/Audio-Technica%20ATH-M50x

https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/Audio-Technica%20ATH-M50x

**Comment by jaakkopasanen** [comment]
Select the one from the recommended results. That would be oratory1990's one. Of course you can try them all and decide for yourself which one you like the best.

**Comment by jtagcat** [comment]
Thanks, sorry for troubling!
