### ISSUE TITLE
Incorrect Y axis scaling 1MORE stylish

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#148]
The scaling on the Y axis seems to be incorrect for the 1MORE Stylish. I used WebPlotDigitizer to extract the coordinates from the graph published by crinacle and ran AutoEq on that to compare. It looks like the result in the database has a scaling of around 200%:

![1MORE Stylish](https://user-images.githubusercontent.com/1721405/78948273-43018b80-7ab7-11ea-98b7-7791fd5721f8.png)
compared to 
![](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/crinacle/harman_in-ear_2019v2/1More%20Stylish/1More%20Stylish.png)

Could you take a look at it?

Edit: it may be the same issue as https://github.com/jaakkopasanen/AutoEq/issues/142

**Comment by jaakkopasanen** [comment]
I had a lot of Crinacle's measurements processed incorrectly. That should be fixed now. Your second picture disappeared so could you check again if you think the problem persists?

**Comment by Pittvandewitt** [comment]
It looks like the problem is resolved now. Thank you!

**Comment by Pittvandewitt** [comment]
I reopened the issue because I found this issue to be present on some more IEMs such as the ones from Shuoer

**Comment by jaakkopasanen** [comment]
Indeed. The measurements were updated and fixed but of course some of the pre-computed results are unaffected. I'll re-process all the results to get them all fixed up.

**Comment by jaakkopasanen** [comment]
Done. I compared the old and the new. Seems fixed now.
