### ISSUE TITLE
Q factor too small / bandwidth too large

### ISSUE THREAD

**Issue by zvl582** [jaakkopasanen/AutoEq#152]
I'm equalizing the CCA C12, and the q-factor given for frequency 19930 is 0.15. Converting this to bandwidth results in a bandwidth of 5.54, but AUNBandEQ, which I'm using, only allows for a maximum bandwidth of 5. In addition, using 5 as the bandwidth seems to result in a different EQ curve than the one shown in the graph for the CCA C12, whereas using a smaller bandwidth seems to result in a more similar one.

Using bandwidth of 5:
<img width="536" alt="Screen Shot 2020-04-13 at 7 24 56 AM" src="https://user-images.githubusercontent.com/63597527/79128221-0607f400-7d58-11ea-90e0-a84f0f2ff8cf.png">

Using bandwidth of 0.1:
<img width="527" alt="Screen Shot 2020-04-13 at 7 26 51 AM" src="https://user-images.githubusercontent.com/63597527/79128326-2cc62a80-7d58-11ea-9dfe-2932665782a8.png">

Provided EQ graph:
![CCA C12](https://user-images.githubusercontent.com/63597527/79128397-4b2c2600-7d58-11ea-9cff-1e71144613b2.png)

Could this be due to the recent changes made to Crinacle's measurement results? Thank you so much for your help!

**Comment by jaakkopasanen** [comment]
I'm afraid there's quite little I can do. The filter optimization is an automatic process so it does what it does. You could try to run these results yourself again to see if the optimizer produces different result. The filter optimization isn't exactly a deterministic process so there could be a change. Better yet, tweak the filters by ear.

**Comment by zvl582** [comment]
I see, I'll try running the results again. Just to be clear, however, the optimizer is definitely producing the right filter settings? I'm just confused by how using a large bandwidth seems to be making the entire EQ curve a few decibels lower than the EQ curve in the provided diagram.

**Comment by zvl582** [comment]
In addition, do you know how I can run autoeq.py for Crinacle-measured in-ears? I can't seem to find the correct input directory.

**Comment by zvl582** [comment]
@jaakkopasanen I noticed the recent note you added about missing Crinacle's raw data, so I'm guessing that I won't be able to run these results again by myself. Is it at all possible however that the provided filter settings aren't accurate, given that the equalization curve made by them looks significantly different from the provided EQ graph? Otherwise, I think I'm misunderstanding how my equalizer works. Thank you so much again for your help and for providing this resource!

**Comment by jaakkopasanen** [comment]
The provided settings seem correct. The super wide filter at 19.9 kHz takes down the whole upper treble range by some amount (down to 1 or 2 kHz. The difference with a filter that has bandwidth of 5 octaves is quite minimal so you could just use that. In addition the Harman target is not the absolute truth above 10 kHz because research shows preferences in this region change a lot between listeners. You could even omit the whole filter if you prefer a lot of "air".

**Comment by zvl582** [comment]
Thanks so much! Just to verify that I'm using AutoEQ correctly, the parameters made by AutoEQ for the filters create the same EQ curve shape but not necessarily at the same decibel level?

**Comment by jaakkopasanen** [comment]
Actually I don't know why your equalizer behaves like that. The 5 octave filter shouldn't bring down the whole frequency spectrum. However the curve shape looks correct and that's what matters the most. You could turn up the global gain until the maximum is at just under 0 dB.

**Comment by zvl582** [comment]
Thanks! It looks like AUNBandEQ doesn't handle large filters well at boundary points, e.g. at high or low frequencies, wide filters no longer resemble Gaussians. I ended up just changing the width of the filter to 0.6, which seems to be a close enough match to the provided graph. Barring a free parametric equalizer for OSX that doesn't have this issue, I think this is as good as I'm going to get.
