### ISSUE TITLE
88.2 and 96kHz convolution filters attenuate the sound too much

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#154]
Hi,

I’m using Roon together with convolution filters, and for my filters generated with REW and my loudspeakers everything is working fine.

When I use the filters I generated with autoeq for headphone listening, all goes well when Roon uses the 44.1kHz filter, but when I’m playing an 88.2 or 96kHz file, the sound is very soft. These higher sample frequency filters seems to attenuate the sound too much. I’m not sure, but since it is working correctly with Roon/REW filters, I assume this has to do with autoeq?

Regards,
Alex

**Comment by jaakkopasanen** [comment]
This has been mentioned by other people previously so it's probably in AutoEq. I'll look into it at some point. Thanks for reporting!

**Comment by khades** [comment]
I looked into that, and found that EqualiserAPO shows itself kinda same filters with 48khz/96khz/192khz settings, but sound is different.

Meanwhile parametric eq and IR convolver sound kinda same on 48khz. Likely bug of EqualizerAPO.

I was listening my headphones wrong since November 2019.

**Comment by jaakkopasanen** [comment]
I tested this by producing 48 kHz and 96 kHz impulse responses in AutoEq. I checked the frequency responses of both filters in Python and also in EqualizerAPO configuration editor. Both show exactly the same frequency responses and levels for both files. Listening test didn't show any level difference either.

I suspect AutoEq is behaving correctly. Did you play 96 kHz audio file when using 96 kHz filter and 48 kHz file with 48 kHz filter? Are you sure the files are equally loud? Or if you played the same file then are you sure the resampling doesn't do affect the levels?

**Comment by DeLub** [comment]
Roon automatically selects the filter matching the sample rate of the audio file. Roon also performs volume levelling so the files should be in the same range. The difference I heard is about 20dB or so, so it's quite significant. And when playing the files when I use the corresponding parametric equalizer settings the volume is in any case the same.

When generating the filters I used a bit depth of 32. Standard autoeq is using 16. Perhaps this leads to different results? I'll try later what happens when I generate 16 bit filters.

**Comment by DeLub** [comment]
Nope. No difference. I'll check with the Roon guys.

**Comment by jaakkopasanen** [comment]
@DeLub could you link the 48 kHz and 96 kHz FIR filters here. I'd like to take a look at them since I couldn't reproduce this issue myself.

**Comment by DeLub** [comment]
I put the files on [dropbox](https://www.dropbox.com/sh/66bozl6ur7a6dht/AACqtfBtyYg05RzW64dh4dUIa?dl=0).

**Comment by DeLub** [comment]
I've opened up the filters in REW (I imported them as audio data). Don't know if that actually makes any sense, but there's indeed quit a difference between them (top one is 44.1kHz, bottom is 96kHz)

![44100 and 96000  - 2jpg](https://user-images.githubusercontent.com/10213486/80867506-c1a3b000-8c94-11ea-904f-5dfe5ade7801.jpg)

**Comment by DeLub** [comment]
Response from Roon:

> Using the default settings, we’ve confirmed that AutoEQ generates filters that have higher attenuation at 96kHz vs 44.1kHz. Roon is behaving as expected and reflecting the difference in the filters provided by AutoEQ.

**Comment by jaakkopasanen** [comment]
Thanks. What exact command did you use to produce these filters?

**Comment by DeLub** [comment]
``
python3 autoeq.py --input_dir="measurements/oratory1990/data/onear/Sennheiser HD 600" --output_dir="output/hd 600" --compensation="compensation/loudspeaker_in-room_flat_2013.csv" --sound_signature="input/bk.csv" --equalize --convolution_eq --fs=44100,48000,88200,96000
``

For completeness, I've also uploaded my `bk.csv` to the above mentioned dropbox folder.

**Comment by jaakkopasanen** [comment]
The filters produced on my machine are looking good and the filters you provided have 30 dB of attenuation across the spectrum. Frequency response isn't the same for your high sampling rate filters either. I used your exact command to produce the filters.

What Python version do you have? When did you clone or download AutoEq? Maybe try newest version. Have you updated dependencies: `pip install -U -r requirements.txt`? Which operating system are you using?

**Comment by DeLub** [comment]
I'm using python 3.7.7 on macOS Catalina 10.15.4. I was and am running the most up to date version of AutoEq. However, I forgot to update the dependencies. But when I did that I still get the same result with the attenuated files. Since the guys from Roon apparently also generated attenuated files, might this be an operating system related issue? What are you running?

**Comment by jaakkopasanen** [comment]
I tested this on Windows. I can also try it out on Linux.

**Comment by jaakkopasanen** [comment]
Tested it on Linux as well and couldn't reproduce. I however made some changes to how minimum phase FIR filters are calculated and there is ever so slight chance this fixes your problem. Get the latest AutoEq and try again. If this doesn't solve it then I will have to resort to resampling all other sampling rates from 44.1 kHz.

**Comment by DeLub** [comment]
I'm still not sure wether it makes sense to import the filters into REW as audio files, but the plots look a lot better. The look very similar, but there is still an attenuation in the 96kHz version, although it is much smaller now.

![filter-plot](https://user-images.githubusercontent.com/10213486/82587591-bf4cbb80-9b99-11ea-9f18-6a6a5b3653c3.png)

I'll test how these filters sound tonight.

**Comment by jaakkopasanen** [comment]
Would you mind sharing these new filters. I'd like to take run spectrum analysis on them myself. They certainly look similar but maybe there's some odd going on beyond 20 kHz which causes normalization to attenuate the 96 kHz filter.

**Comment by DeLub** [comment]
Done. They're uploaded in the same folder again.

**Comment by jaakkopasanen** [comment]
![user_filters](https://user-images.githubusercontent.com/8393524/82927129-e71c9480-9f88-11ea-9740-a94f43a992b5.png)

This is how the frequency response looks like for all of the filters currently in your Dropbox folder. For some reason this doesn't really look like in your picture. Here the filters have exactly the same frequency repsonse and also same absolute level. Did you do listening test to check if they still have something weird going on?

**Comment by DeLub** [comment]
Finally came around to do a listening test. The filters now all sound the same. I don't hear the difference visible in my picture. (But, like I said, I'm not even sure it make sense to open the filters in REW like that.)

Thanks!

**Comment by DeLub** [comment]
I recreated the bk.csv using webplot and it turns out I should use diffuse field as compensation, but now it sounds very nice. Thanks!

**Comment by jaakkopasanen** [comment]
Thanks for sticking with me to the end! I'm super glad to hear this solved your issue!

I honestly didn't have very high hopes that the fix I made would solve this. I did the change for reducing FIR filter calculation time instead for fixing high sampling rate filters. I guess I got lucky this time.
