### ISSUE TITLE
SoundMagic TWS50

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#155]
Thanks for your effort in this project.
I was looking for TWS50 frequency response graph but it is quite hard to find something related to this model on the web. Have you found it in any of your mentioned sources?

**Comment by jaakkopasanen** [comment]
Doesn't look like that model can be found in the results. This means none of the supported databases have it and there's nothing I can do. You can follow the guide linked to results page if you happen to find the frequency response graph somewhere.
