### ISSUE TITLE
Using FFmpeg's firequalizer filter with AutoEq

### ISSUE THREAD

**Issue by ipaucek4680** [jaakkopasanen/AutoEq#156]
I use [mpv](https://github.com/mpv-player/mpv), which means I can use the [equalizer filter](https://ffmpeg.org/ffmpeg-filters.html#toc-equalizer) for parametric equalization (by specifying `--af=...` on command line).
I also use FFmpeg's [volume filter](https://ffmpeg.org/ffmpeg-filters.html#toc-volume) to set preamp, but I am not 100% sure if this is the correct way of doing it.

In the meantime, I notice that FFmpeg also has the [firequalizer filter](https://ffmpeg.org/ffmpeg-filters.html#toc-firequalizer).

1. Can the firequalizer filter be used as a convolution equalizer? If so, how can we use AutoEq to generate the necessary parameters?
2. Is convolution equalizer better than parametric equalizer (possibility of compensating for narrow notches and peaks better?)?

**Comment by jaakkopasanen** [comment]
It doesn't look like the firequalizer the the right tool. The documentation doesn't mention anything about supplying a WAV file for the firequalizer. AutoEq does produce filters for convolution equalizers, these are the WAV files in pre-computed results.

Convolution may or may not be better that parametric equalizer. In theory it could follow the eq target a bit closer but this is hardly an issue with 10 parametric eq filters. Narrow peaks in FIR filter or high Q, positive gain filters in parametric eq might cause ringing which mean one can be better than the other depending on the case. In general I wouldn't stress too much about it.

If what you have now works, keep doing that. Don't fix it if ain't broken!
