### ISSUE TITLE
A few more naming issues

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#157]
I took a quick look and found a few more incorrect names in the list:

AKG N90Q Nominal - AKG N90Q
Cypher Labs Astru IEM Bass Boo - Cypher Labs Astru IEM Bass Boost
Grado HF-1 Serial 69 - Grado HF-1
JAYS q-JAY = JAYS q-Jays, should be JAYS q-JAYS
Pioneer Monitor 10 II = Pioneer Monitor 10II B in box
Sleek SA6 Neutral = Sleek SA6
Sony MRD-7550 - Sony MDR-7550
Sony XBA-A3 S3 does not exist, maybe s3 is sample 3?
Stax SR-007 SZ3-1576 = Stax SR-007
Stax SR-507 SE1-1049 = Stax SR-507
The torque t402v has an over ear and an on ear model with both 4 color settings. The earpads indication is irrelevant and not correct here.

I think that's about it

**Comment by jaakkopasanen** [comment]
Thanks a lot! I'll take a look at these soon and fix them.

**Comment by jaakkopasanen** [comment]
I do believe it's all fixed now.
