### ISSUE TITLE
A suggestion for a AutoEQ for the Sony MDR-7520

### ISSUE THREAD

**Issue by misslooptux** [jaakkopasanen/AutoEq#159]
I do not see an autoEQ for the Sony MDR-7520. this is a suggestion.

**Comment by misslooptux** [comment]
There are graphs on this website that can be used: https://www.rtings.com/headphones/reviews/sony/mdr-7520

**Comment by jaakkopasanen** [comment]
Interesting. It looks like the Rtings' newest graph tool doesn't have all the measurements that exist in the old ones. This being one of them. I'll have to do something about the crawler so it grabs measurements from all versions.

Thanks a lot for reporting the issue!

**Comment by misslooptux** [comment]
I can also take the measurements if you would like them, but I am not sure how.

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/innerfidelity/sbaf-serious/Sony%20MDR-7520
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/avg/Sony%20MDR-7520

These were there in the results all along. Also my observation that newest Rtings graph tool doesn't have measurements from older versions was incorrect.
