### ISSUE TITLE
Having some trouble understanding whether the EQ setting will output flat or flat in accordance with Harman Target Response Curve

### ISSUE THREAD

**Issue by deama** [jaakkopasanen/AutoEq#160]
Basically, if I pick a headphone from the list and apply the graphicEQ settings for example, will it give me as close as possible to a flat EQ curve, or will it give me an EQ curve that is as close as possible to the Harman Target Response Curve?

**Comment by jaakkopasanen** [comment]
Harman target. You never want to go truly flat. And of course flat depends on how the headphone was measured. Measure at the ear canal opening and you should strive for close to flat, measure at ear drum and you should have Harman target. Ear canal introduces it's on EQ into the sound. Good measurement system simulates these ear canal and ear drum acoustics so they need to be present in the measurements. When you equalize with measurements done with an accurate system, you should go for Harman target, not flat.
