### ISSUE TITLE
Suggestion Tribit Xfree Tune (measurements linked in post)

### ISSUE THREAD

**Issue by jonasu19** [jaakkopasanen/AutoEq#161]
Hey,

I was wondering if it's possible to have the following headset added to the list.

Tribit Xfree Tune

Measurements: https://www.soundstagenetwork.com/index.php?option=com_content&view=article&id=1982:tribit-audio-xfree-tune-headphones&catid=263&Itemid=203

Thanks in advance!

**Comment by jaakkopasanen** [comment]
I don't intend to add any measurements outside of the currently supported six databases. The amount of work required to add and maintain these measurements would not be reasonable considering the benefits.

You can produce the results yourself by following the [guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9).
