### ISSUE TITLE
Changing bass boost without measurement data

### ISSUE THREAD

**Issue by zvl582** [jaakkopasanen/AutoEq#163]
I saw in the documentation that you apply a +6dB bass boost for in-ears, whereas Harman targets ask for +10dB for in-ears. I know that it's possible to run AutoEQ with different bass boosts, but for something like Crinacle-measured iems where non-patrons can't access the data, would adding a +4dB low shelf filter with fc=100Hz to the EQ filters have the same effect as changing bass boost from +6dB to +10dB? Thanks for the help!

**Comment by jaakkopasanen** [comment]
That is correct. You can always add more filters since they add up to the end result. Make sure you adjust preamp too!
