### ISSUE TITLE
Increasing --max_gain breaks the processing

### ISSUE THREAD

**Issue by NekoAlosama** [jaakkopasanen/AutoEq#164]
I've been using AutoEQ for a while to equalize my headphones and tweak them with some settings like `--bass_boost` and `--max_gain`. I've noticed that increasing `--max_gain` to very high numbers that the equalization will never get to will change the values noticeably. I understand that the values that can be produced might not be achievable by some headphones. I've tested values of `--max_gain` with `6`, `99`, `999`, `9999`, and `1.7976931348623157e+308` (or `sys.float_info.max`). ~~You can see the `--fixed_band_eq` results for said values on a pair of headphones [here](https://github.com/NekoAlosama/AutoEq-optimized/tree/master/research/max_gain%20example%20Status%20Audio%20BT%20One%20(wired)).~~(Deleted from updates)

I've [forked the repo](https://github.com/NekoAlosama/AutoEq-optimized) so I could produce results that increase the bass gain to reflect the Harman target (`--bass_boost +6.05` on on-ears and `--bass_boost +9.44` for in-ears) and apply a higher gain to other headphones (wanted to be `--max_gain 1.7976931348623157e+308`). For most headphones, they run the equalization perfectly fine. However, some headphones produced `RuntimeWarning`s and even `ValueError`s due to some headphones requiring a lot of gain. Those warnings and errors can be remedied by reducing the max_gain, but I want to know why they occur in the first place. I have prevented convolution EQ from being calculated, but I assume that the headphones which already produce warnings or errors will be the only ones that could produce more from processing convolution EQs.

~~Here's an [example with Innerfidelity's Howard Leight Sync processing](https://github.com/NekoAlosama/AutoEq-optimized/tree/master/research/RuntimeWarning%20example%20Howard%20Leight%20Sync) where many `RuntimeWarning`s occur with `sys.float_info.max`:
```
(venv) C:\*\AutoEq-optimized>py -3 autoeq.py --input_dir "measurements/innerfidelity/data/onear/Howard Leight Sync" --output_dir "my_results\Howard Leight Sync" --compensation "measurements/innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv" --equalize --parametric_eq --max_filters 5+5 --ten_band_eq --bass_boost 6.05 --max_gain 1.7976931348623157e+308
C:\*\AutoEq-optimized\frequency_response.py:540: RuntimeWarning: invalid value encountered in greater
  if min_loss is None or min_loss - step_loss > threshold:
C:\*\AutoEq-optimized\frequency_response.py:564: RuntimeWarning: invalid value encountered in greater
  sl = np.logical_and(np.abs(_gain) > 0.1, _fc > 10)
C:\*\AutoEq-optimized\frequency_response.py:540: RuntimeWarning: invalid value encountered in greater
  if min_loss is None or min_loss - step_loss > threshold:
C:\*\AutoEq-optimized\frequency_response.py:564: RuntimeWarning: invalid value encountered in greater
  sl = np.logical_and(np.abs(_gain) > 0.1, _fc > 10)
C:\*\AutoEq-optimized\frequency_response.py:540: RuntimeWarning: invalid value encountered in greater
  if min_loss is None or min_loss - step_loss > threshold:
C:\*\AutoEq-optimized\biquad.py:122: RuntimeWarning: invalid value encountered in log10
  (a0 + a1 + a2) ** 2 + (a0 * a2 * phi - (a1 * (a0 + a2) + 4 * a0 * a2)) * phi
1/1 (100.0%) 11s: Howard Leight Sync
```
For some headphones, only the first and last warning occur. The first warning can show but seemingly affect nothing, while the results with the first and any of other warnings produces a few problems. The parametric EQ results are not written (all), the ten band EQ results ask for a preamp of `nandB` (all), and the plot graph has a few rendering issues like incomplete ~~and overlapping(?)~~ lines (can occur with the first and last warning).

Here's an example with Innerfidelity's Koss KPH7 processing where `RuntimeWarning`s and a `ValueError` occur:
```
(venv) C:\*\AutoEq-optimized>py -3 autoeq.py --input_dir "measurements/innerfidelity/data/onear/Koss KPH7" --output_dir "my_results\Koss KPH7" --compensation "measurements/innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv" --equalize --parametric_eq --max_filters 5+5 --ten_band_eq --bass_boost 6.05 --max_gain 1.7976931348623157e+308
C:\*\AutoEq-optimized\frequency_response.py:540: RuntimeWarning: invalid value encountered in greater
  if min_loss is None or min_loss - step_loss > threshold:
C:\*\AutoEq-optimized\biquad.py:122: RuntimeWarning: invalid value encountered in log10
  (a0 + a1 + a2) ** 2 + (a0 * a2 * phi - (a1 * (a0 + a2) + 4 * a0 * a2)) * phi
Traceback (most recent call last):
  File "autoeq.py", line 300, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 100, in batch_processing
    fs=fs[0] if type(fs) == list else fs
  File "C:\*\AutoEq-optimized\frequency_response.py", line 1555, in process
    peq_filters, n_peq_filters, peq_max_gains = self.optimize_parametric_eq(max_filters=max_filters, fs=fs)
  File "C:\*\AutoEq-optimized\frequency_response.py", line 625, in optimize_parametric_eq
    fs=fs
  File "C:\*\AutoEq-optimized\frequency_response.py", line 296, in optimize_biquad_filters
    fr_target.smoothen_fractional_octave(window_size=1 / 7, iterations=1000)
  File "C:\*\AutoEq-optimized\frequency_response.py", line 1194, in smoothen_fractional_octave
    treble_f_upper=treble_f_upper
  File "C:\*\AutoEq-optimized\frequency_response.py", line 1143, in _smoothen_fractional_octave
    raise ValueError('None values present, cannot smoothen!')
ValueError: None values present, cannot smoothen!
```
The warnings and errors are the same between a few headphones. No folders or files were generated.~~(These are recorded in the fork's README, and have been deleted)

I want to know why these warnings and errors occur, since I can see that there may be interest in the results with these tweaks. I have tried reducing the `--max_gain` to `28.27...` and the errors are gone and the number of warnings are reduced, but the warnings still occur with the first or both warnings in the Koss KPH7 processing which may or may not produce a broken plot graph. Why exactly do these warnings and errors occur, and how can they be fixed in the code?

**Comment by NekoAlosama** [comment]
I have updated the results `sys.float_info.max`. In the [README.md](https://github.com/NekoAlosama/AutoEq-optimized), I document the headphones that produce warnings or an error, in which the error headphones are isolated so computing results can be completed for all other measurements and the headphones that produce warnings are intermixed with the rest but are also documented and lists the problems shown in each.

**Comment by NekoAlosama** [comment]
@jaakkopasanen

**Comment by jaakkopasanen** [comment]
Thanks for reporting this and the detailed info you provided!

Something deep in Tensorflow graph goes wrong here. I'm guessing numerical instability or some such. I'm not going to fix this now because the parametric equalizer filter optimizer will be redone completely and this has no significant practical implications.

For now you just need to limit the max gains to reasonable values. It's not like you could boost bass by 40 dB anyways.

**Comment by NekoAlosama** [comment]
I'm just going to write in the README.md that the values can be reduced when needed, just so people viewing don't focus too much on the increase.

**Comment by NekoAlosama** [comment]
Updated code, results, and error documentation. See the documentation [here](https://github.com/NekoAlosama/AutoEq-optimized)

**Comment by NekoAlosama** [comment]
Updated same as above.

**Comment by NekoAlosama** [comment]
Update: It seems that float('nan') does a better job than sys.float_info.max.

**Comment by NekoAlosama** [comment]
Updated results with `--max_gain nan`/ `DEFAULT_MAX_GAIN = float('nan')`. Compared to the results with `sys.float_info.max`, this seems to help the Parametric EQ, while the Fixed Band EQ normally stays the same. I don't think more warnings were created by changing the max_gain.

**Comment by NekoAlosama** [comment]
@jaakkopasanen A lot of the errors and bugs I've seen have been fixed (due to package updates and equalization changes) since the last comment was made. The errors and bugs are detailed on my fork's README,md.

As of now, there are only two problems when calculating compared to the seven from before, and there are less headphones in either category.

Compare [the one from before](https://github.com/NekoAlosama/AutoEQ-NekoMod/blob/8e5a6856a2c8d5cd3e28f8bdac4ba283428790bc/README.md) to [the current one](https://github.com/NekoAlosama/AutoEQ-NekoMod/blob/master/README.md)

**Comment by jaakkopasanen** [comment]
I merged a new algorithm for avoiding equalizing nulls to master yesterday and recalculated all the pre-computed results. That might be (partially) the reason for what you're seeing now.

By default the equalization algorithm limits derivative (slope) of the equalizer frequency to 18 dB per octave. If there are headphones which have very deep dips, these would not now result in high boosts.

**Comment by NekoAlosama** [comment]
Cool. At least now more headphones can be used in my fork.

**Comment by jaakkopasanen** [comment]
@NekoAlosama could you try if the problem persists? I reworked the parametric eq optimizer and there's a chance this got fixed.

**Comment by NekoAlosama** [comment]
@jaakkopasanen Before the update, I figured out that I could edit that specific line in `biquad.py`  to `10 * np.nan_to_num(np.log10(...` to at least replace the `NaN` value with `0.0`. The reworked PEQ has fixed this issue without this kind of patch. `float('NaN')` doesn't work still, but `sys.float_info.max` seems good enough.

**Comment by NekoAlosama** [comment]
After some additional testing, it doesn't seem that changing `--max_gain` to different large magnitudes above, say, 10, changes the generated results like before. A max gain of 99 used to have different results compared to 1e+310, but it doesn't anymore.
