### ISSUE TITLE
Don't understand the target

### ISSUE THREAD

**Issue by ddavidebor** [jaakkopasanen/AutoEq#165]
Hi, 

I am scratching my head a bit.

I have compensated my Melomania 1 using the provided WAV file... but where does the target frequency response come from?

**Comment by jaakkopasanen** [comment]
The WAV file contains the FIR filter which makes the headphones sound natural. The filter is based on frequency response measurement of the said headphone and a frequency response target. The AVG response target was developed specifically for AutoEq to be used with Rtings measurements. Did this answer your question?
