### ISSUE TITLE
"Final" comand line returns empty

### ISSUE THREAD

**Issue by MataRatos** [jaakkopasanen/AutoEq#166]
Hello. 
I'm not a programmer or anything, but I've learned a lot over the years following tutorials.
I've managed to find this project when searching for a way to improve my IEM's audio quality, instead of buying new ones. I use Neutron Music Player, eventually it led me to messing around with Parametric EQ, and then to your project.
I have a pair of Tin HIFI T2 and the file I found here just made them sound even better!
I have also a pair of JBL T210, much cheaper, and having also found the frequency response graph on The Phonograph, thought of also giving them a go.
I followed the tutorial, didn't install Python 3.8, manage to get everything working, until the final command line... I think there's nothing wrong with it, but still, when I run it, it doesn't return anything. Not even an error...
I may have track it down to something in the frequency_response.py file, because if I run it isolated, it will just open a cmd window and close immediatly. I've tried this on two different computers, both running Windows 10 Pro 1909, and the result is exactly the same.
I've also searched for a log file of some king, but not even that.
Can you help me out on this?
I'm sending the file I've made with the frequency response graph, to see if the issue is there, and the screenshot of my CMD:
Thank you in advance. Great work.
![2020-05-09](https://user-images.githubusercontent.com/65069810/81471223-96b2e200-91e7-11ea-9263-0a408907c419.png)
[jbl.txt](https://github.com/jaakkopasanen/AutoEq/files/4603275/jbl.txt)

**Comment by jaakkopasanen** [comment]
Maybe this snip from install instructions can point you to right direction:
>Download and install 64-bit Python3. Python 3.8 doesn't work yet. Make sure to check Install Python 3 to PATH

**Comment by MataRatos** [comment]
Yes, that's what I've done. On both computers. Made sure to select that option during install, and tested with 3.7.7, 3.6.4 and both the Python apps on the Microsoft store. It just wont do anything.

**Comment by jaakkopasanen** [comment]
Ah, my bad! For some reason I read you installed Python 3.8.

Here's another:
>python autoeq.py -h

`frequency_response.py` is no longer used directly but the command line interface is provided by `autoeq.py`.

**Comment by MataRatos** [comment]
This is wath I get
![2020-05-09 (1)](https://user-images.githubusercontent.com/65069810/81471507-74ba5f00-91e9-11ea-9b28-a3bf27ec9a02.png)

**Comment by jaakkopasanen** [comment]
That's what you're supposed to get. `-h` shows help.

**Comment by MataRatos** [comment]
Yes, but why won't it return or do anything with the full command line?

**Comment by jaakkopasanen** [comment]
Try running the other commands.

**Comment by MataRatos** [comment]
I think I'm on to something... On this page:

https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9

shouldn't the command line say python autoeq.py instead of frequency_response.py?

I changed and it's starting to show some errors, I'll try to sort them out...

**Comment by jaakkopasanen** [comment]
Now I see. I forgot to update the guide in Medium. I'll do that as soon as I have time. You're supposed to use `autoeq.py` at all times.

**Comment by MataRatos** [comment]
Thank you for your time. Will feedback here to tell the results.

**Comment by MataRatos** [comment]
That was it. Had another issue with tensor flow, but ran "pip install -U -r requirements.txt", and that solved it. Also the "--iem_bass_boost" argument in MEDIUM is outdated.

Thank you. Issue is solved.

**Comment by jaakkopasanen** [comment]
Thanks a lot for reporting. I fixed the Medium guide just now.
