### ISSUE TITLE
Beyerdynamic Custom Studio results no longer available

### ISSUE THREAD

**Issue by rowrawer** [jaakkopasanen/AutoEq#167]
Hello,

The results for Beyerdynamic Custom Studio headphones based on Reference Audio Analyzer data seems to no longer be available. Is there any particular reason as to why they were removed?

**Comment by jaakkopasanen** [comment]
Hey!

It's very possible that the name was originally wrong since Beyerdynamic Custom Studio cannot be found in Reference Audio Analyzer index. Another option is that this never existed in AutoEq. I tried searching for any indication of it in Git history but found nothing. Are you absolutely sure the Custom Studio was in AutoEq at some point?

**Comment by rowrawer** [comment]
Yes, absolutely. It was listed as Beyerdynamic Custom One Studio for some reason. It was initially in /results/referenceaudioanalyzer/zero.

**Comment by jaakkopasanen** [comment]
```
git log --full-history -- "results/referenceaudioanalyzer/zero/Beyerdynamic Custom One Studio/Beyerdynamic Custom One Studio.csv"
```
gives no results meaning that file never existed.

**Comment by jaakkopasanen** [comment]
Found it. I reworked the whole Reference Audio Analyzer crawler a while ago and deleted all the old files to make way for the new ones. Currently Reference Audio Analyzer site doesn't contain a headphone with that name so it's gone.

**Comment by jaakkopasanen** [comment]
The old Custom One Studio had a 4 switch positions and the only one in the current RAA results with 4 switch positions is Beyerdynamic Custom One Pro. That might the one you're looking for. Maybe the name was wrong all along and RAA fixed it on their site at some point.

**Comment by rowrawer** [comment]
The Custom One Pro different model. I'm talking about [this one](https://reference-audio-analyzer.pro/en/report/hp/beyerdynamic-custome-one-studio-step-1.php) - the Custom Studio. Only steps 1, 3, and 4 are available for some reason.

**Comment by jaakkopasanen** [comment]
I restored the measurement file from the depths of Git and did new results. Thank you for reporting this and all the help!

[Beyerdynamic Custom Studio (step 1)](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%201))
[Beyerdynamic Custom Studio (step 2)](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%202))
[Beyerdynamic Custom Studio (step 3)](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%202))
[Beyerdynamic Custom Studio (step 4)](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%204))

**Comment by rowrawer** [comment]
Great, thank you!

**Comment by SuperValue** [comment]
The step 1 measurements seems messed up.  Step 1 is supposed to be the setting with the least bass yet it has a huge huge peak.  Looks even different than these: https://reference-audio-analyzer.pro/en/report/hp/beyerdynamic-custome-one-studio-step-1.php (change the 1 to 2, 3, 4 for other steps)

**Comment by bicycleghost** [comment]
Hey @jaakkopasanen 
The links you provided are no longer working. seems like the project structure changed a bit since you posted those. Know where I can find them now?

Thanks

**Comment by ceLoFaN** [comment]
Hey uh, this is still the case... Any chance we can get these back?
