### ISSUE TITLE
How to contribute new results?

### ISSUE THREAD

**Issue by w-** [jaakkopasanen/AutoEq#168]
I tried searching past PRs and issues and all I could find is this
https://github.com/jaakkopasanen/AutoEq/pull/12

I'm guessing there is a contribution guide somewhere but I have totally missed it.

Would like to contribute results i generated for my bt headset so i can use with wavelet (android app).

**Comment by jaakkopasanen** [comment]
I saw you're ticket in Wavelet. That's the way to go about this. Hopefully we get some way to import custom eq curves into Wavelet.

I don't host custom results in AutoEq. Only the ones that are measured by one of the supported sources. Supporting custom results would become an impossible hassle for me with limited benefit.
