### ISSUE TITLE
[Request] Adding data from thephonograph.net

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#169]
Hi Jaakko,

I noticed multiple people requesting popular headphone models that are measured by [thephonograph.net](https://www.thephonograph.net/headphones-frequency-response/). I would like to ask if it is possible and feasible to add their measurement data to AutoEq. Apart from smoothing, their measurements appear to be uncompensated, unlike some of the data from reference audio analyzer.

**Comment by venkatesh63** [comment]
@Pittvandewitt https://www.thephonograph.net/headphones-frequency-response/blitzwolf/ in this page i'm seeing only blitzwolf-bw-es1-frequency-response-curve.
i want blitzwolf-bw-es2-frequency-response-curve view it on below page right now i'm using BlitzWolf ES-2 Headphones.
BlitzWolf ES-2. https://www.blitzwolf.com/Wired-Headphone-Dynamic-Drivers-p-192.html

**Comment by jaakkopasanen** [comment]
Adding new databases is a lot of work and I promised myself I won't add more. I'm however open to contributions if someone wants to develop the crawler and all the other required tools for supporting thephonograph.net measurements.

The best hope for the users who want headphones that cannot be found in AutoEq is to digitize the graphs with WebPlotDigitizer and run AutoEq to produce GraphicEQ.txt which then will be imported to Wavelet manually once (and if ever) Wavelet supports imports.

The ticket for Wavelet imports: https://github.com/Pittvandewitt/Wavelet/issues/8

**Comment by venkatesh63** [comment]
![blitz wolf es-2](https://user-images.githubusercontent.com/60499879/82545963-03799500-9b75-11ea-851a-a6581c0e487c.jpg)
@jaakkopasanen can develop my Blitz Wolf es2 EQ with WebPlotDigitizer.

**Comment by jaakkopasanen** [comment]
@venkatesh63 see here for a guid: https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9

**Comment by venkatesh63** [comment]
[Bltzwolf-ES2.txt](https://github.com/jaakkopasanen/AutoEq/files/4662326/Bltzwolf-ES2.txt)
This is my file can you recheck in you pc did i done correct results.

**Comment by venkatesh63** [comment]
[Bltzwolf-ES2.txt](https://github.com/jaakkopasanen/AutoEq/files/4662339/Bltzwolf-ES2.txt)
This is my file can you check in you pc did i done correct results.

**Comment by Pittvandewitt** [comment]
@venkatesh63 This is not the place to ask these type of questions. Please don't abuse it.

@jaakkopasanen Thank you for your response. I'll focus on an import function first and then see if I'm able to create a crawler.
