### ISSUE TITLE
[IRS issue] Impulse file is mono with 64bit resolution 

### ISSUE THREAD

**Issue by M0Rf30** [jaakkopasanen/AutoEq#17]
Hi,
I've tested the irs file generated for AKG Y50 and is invalid. This is the report of mediainfo on repo wav file

```
General
Complete name                            : AKG Y50 48000Hz.wav
Format                                   : Wave
File size                                : 375 KiB
Duration                                 : 1 s 0 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 3 072 kb/s

Audio
Format                                   : PCM
Format profile                           : Float
Codec ID                                 : 3
Codec ID/Hint                            : IEEE 
Duration                                 : 1 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 3 072 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 48.0 kHz
Bit depth                                : 64 bits
Stream size                              : 375 KiB (100%)
```
I've converted the file to 32bit, stereo and seems to work on PulseEffects and Viper4Android

**Comment by jaakkopasanen** [comment]
Oops, I forgot to set bit depth for WAV file write. I'd like to keep file size as small as possible because there are thousands of them so I'm going to set it to 16 bits. Could you test if mono files work with Viper4Android and Pulseeffects or do they have to be stereo?

**Comment by M0Rf30** [comment]
On pulseeffects I've tested 32 and 16 bit but mono files are not accepted.
On viper mono and stereo both 16 and 32 accepted by the convolver.
As regarding the storage of wav files I can humbly suggest to not upload and let the user generate them

**Comment by jaakkopasanen** [comment]
Thanks a lot for testing. Your suggestion makes sense since it seems different systems have different requirements for the files. However installing and running might be quite intimidating for many users.

**Comment by M0Rf30** [comment]
With the pass of the time this project is becoming more consistent, full of options, more documentated and reflects your ideas, based also on issues and requests. Don't be frightened and keep moving forward this project. Also a `git clone <repo>`  command can intimidate the users. ;)
