### ISSUE TITLE
All 3 Equalizer's in Equalizer APO?

### ISSUE THREAD

**Issue by JuanDaville** [jaakkopasanen/AutoEq#178]
Hi, I've been using your AutoEq software and find it very useful for flattening my headphones, but I'm going a little OCD over something. are supposed to use all 3 of the equalizers at the same time, Parametric EQ, Fixed Band EQ, Graphic EQ, and convolution minimum phase filter? Any help is appreciated.

**Comment by Yetcop** [comment]
I don't know if this is what you are looking for but I have several graphic EQs to use with different headphones. I also have multiple EQs for the same headphones. If you want to use several at once, just add and activate them. To add an EQ click on the + sign, then search for the data corresponding to your headphones, click on graphic.txt copy the text, then add it to your EQ. To do this, click on the icon of a notebook. I hope it is of help, regards.

![image](https://user-images.githubusercontent.com/66587712/83998919-46828900-a927-11ea-9f9c-e948bcf9dc79.png)
![image](https://user-images.githubusercontent.com/66587712/83998982-6619b180-a927-11ea-8972-d1f75752af8c.png)
![image](https://user-images.githubusercontent.com/66587712/83999046-8c3f5180-a927-11ea-8011-d35f5bbb69a3.png)
![image](https://user-images.githubusercontent.com/66587712/83998789-f9061c00-a926-11ea-9ec0-74a8337c328b.png)

**Comment by jaakkopasanen** [comment]
You should ever have only one eq active. At this point the convolution or EqualizerApo GraphicEQ is probably the best option. Parametric eq is perfectly fine in most cases too.

**Comment by JuanDaville** [comment]
Thanks for the advice, I thought you had to use all 4 at a time and all 4 sounds awful XD, now I'm only using 2 at a time, the graphic eq, and the minimum phase convolution, I think it sounds the best for me.

**Comment by DJKero** [comment]
> 
> 
> You should ever have only one eq active. At this point the convolution or EqualizerApo GraphicEQ is probably the best option. Parametric eq is perfectly fine in most cases too.

I'm kinda new to this, too. So we should use either Eq APO Convolution OR GraphicEQ then?

**Comment by jaakkopasanen** [comment]
Yes, only one. Convolution and GraphicEQ are equal in EqualizerAPO since GraphicEQ is actually convolution eq under the hood.

**Comment by DJKero** [comment]
> Yes, only one. Convolution and GraphicEQ are equal in EqualizerAPO since GraphicEQ is actually convolution eq under the hood.
Cool, thanks for the info! :D
