### ISSUE TITLE
Beyerdynamic Custom Studio Graphs

### ISSUE THREAD

**Issue by luema** [jaakkopasanen/AutoEq#179]
I'm pretty sure the frequency response graphs, step 1 through 4, are backwards. Step 1 (bass ports completely closed) looks like step 4. Step 4 (bass ports completely open) looks like step 1, etc.

**Comment by jaakkopasanen** [comment]
Bass ports completely colsed should produce the most bass and completely open the least. Step 1 in AutoEq has more bass than the others and step 4 has least. Is this not correct?

**Comment by luema** [comment]
> Bass ports completely colsed should produce the most bass and completely open the least.

It's the other way around. Open bass ports allows the drivers to move more air and therefore create a higher sound pressure level. The end result is higher perceived bass (or lower perceived bass if instead the ports were closed).

> Step 1 in AutoEq has more bass than the others and step 4 has least. Is this not correct?

That is correct, the EQ presets match the graphs so the important part is fine.
I reread my post and I don't think I was being clear so let me clarify: the EQs match the graphs, but the labels are backwards. 

That is to say, the titles "**Beyerdynamic Custom Studio (step #)**" are in reverse.
"Beyerdynamic Custom Studio (step **1**)" should be "Beyerdynamic Custom Studio (step **4**)"
"Beyerdynamic Custom Studio (step **2**)" should be "Beyerdynamic Custom Studio (step **3**)"
"Beyerdynamic Custom Studio (step **3**)" should be "Beyerdynamic Custom Studio (step **2**)"
"Beyerdynamic Custom Studio (step **4**)" should be "Beyerdynamic Custom Studio (step **1**)"

This would match the bass port slider labels Beyerdynamic gives in manual [(download link warning)](https://europe.beyerdynamic.com/amfile/file/download/file_id/5924/product_id/3702/):
![2020-07-20 (14:06-52)](https://user-images.githubusercontent.com/48996448/87971632-9f4f5080-ca93-11ea-9467-b1c0afa77ec7.png)

It is pedantic, so this isn't a big concern, but I thought it would be more clear to have the labels match the manual.

**Comment by jaakkopasanen** [comment]
Thanks a lot for clarifying this up! They are fixed now:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%201)
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%202)
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%203)
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20Custom%20Studio%20(step%204)
