### ISSUE TITLE
KZ ZSN EQ Settings

### ISSUE THREAD

**Issue by paulobrnjac** [jaakkopasanen/AutoEq#18]
Please measure KZ ZSN graph as this graph is hard to find on the Internet, so please add it on this list... Thanks!

**Comment by jaakkopasanen** [comment]
You can create the eq settings yourself by following this guide: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)

Frequency response graph is here: https://www.reddit.com/r/headphones/comments/9uhvs3/kz_zsn_frequency_response_chart/

**Comment by godshades** [comment]
@jaakkopasanen hi, do you have version for ZSN Pro

**Comment by ARFR2** [comment]
plz someone do this for kz zs10 pro. i'm not in to it.

**Comment by jaakkopasanen** [comment]
@paulobrnjac [KZ ZSN](https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/KZ%20ZSN)
@godshades [KZ ZSN Pro](https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/KZ%20ZSN%20Pro)
@ARFR2 [KZ ZS10 Pro](https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/KZ%20ZS10%20Pro)

I can recommend checking the existing results before asking. Also new results appear when the models get measured by one of supported sources so it's wise to check again after a while if the specific model doesn't exist right now.
