### ISSUE TITLE
[Request]To include TaoTronics TT-BH085 in AutoEq

### ISSUE THREAD

**Issue by onlytanmoy** [jaakkopasanen/AutoEq#180]
Hiya, please can I request to include TaoTronics TT-BH085 under Headphone model in AutoEq? Currently it just lists the TT-BH060 model. Thanks.

**Comment by Pittvandewitt** [comment]
I already answered you that it's not possible.
Your best chance is to find a measurement of your headphone and run AutoEq on that, as described [in this article](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9).

**Comment by onlytanmoy** [comment]
Thanks for that article Thomas 👍
Closing this ticket.
