### ISSUE TITLE
Headphone name typo

### ISSUE THREAD

**Issue by grpan** [jaakkopasanen/AutoEq#184]
I think that [Superlux HD 668 (velour earpads)](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Superlux%20HD%20668%20(velour%20earpads)) should be Superlux HD 668B (velour earpads).

The measurements from [oratory1990](https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets) are pretty [clear](https://www.dropbox.com/s/evxu7g2br5ldrqc/Superlux%20HD-668B%20%28velours%20earpads%29.pdf?dl=0).

**Comment by jaakkopasanen** [comment]
Fixed. Thanks for reporting!

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Superlux%20HD%20668B%20(velour%20earpads)
