### ISSUE TITLE
Cannot resolve Python dependencies.

### ISSUE THREAD

**Issue by polygonalenippel** [jaakkopasanen/AutoEq#186]
Installing on Archlinux the python dependencies with `pip install -r requirements.txt` in the venv as instructed goes pretty well, until you're hit with:

```
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.0.0 (from -r requirements.txt (line 6)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow~=2.0.0 (from -r requirements.txt (line 6))
```

Looking on pip, this package is there: https://pypi.org/project/tensorflow/2.0.0/

My knowledge on pip is quite limited. Does anyone know what is going on here and how to resolve it?

**Comment by jaakkopasanen** [comment]
Are you perhaps running Python 3.8?

**Comment by polygonalenippel** [comment]
Yes, my bad, I started it with the wrong version. I will try again with 3.7 tomorrow, you can close this issue for now.

**Comment by polygonalenippel** [comment]
A little late, but can confirm it works perfectly on 3.7

**Comment by polygonalenippel** [comment]
Also, for the people on Arch trying to install python37 from AUR:

You'll need to import Python's release signing key (see PKGBUILD), but at the moment there's some issue with GPG somewhere that you can't fetch it, thus not being able to install the package. You can download the key manually:
`gpg --keyserver pool.sks-keyservers.net --recv-keys 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D`

Then proceed to build the package.

Also don't forget to use `pip3.7` and `python3.7` for fetching dependencies and running the program, respectively.

I referenced this thread to resolve the GPG issue https://bbs.archlinux.org/viewtopic.php?id=257441 hopefully it gets fixed soon, whatever is causing it.
