### ISSUE TITLE
ATH-ADG1X

### ISSUE THREAD

**Issue by Faerus** [jaakkopasanen/AutoEq#188]
Hi, first of all thanks for your amazing work.
I'm currently using Audio Technica ATH-ADG1X. Would it be possible to add it to the list ? Or should I rely on ATH-700X or 900X ?
Kind regards

**Comment by jaakkopasanen** [comment]
Hi. I'm afraid there's nothing I can do if it has not been measured by one of the supported sources. If you find the frequency response graph somewhere, you can do the thing yourself by following the guide linked to the beginning of the results page. You could also try 700X or 900X but the sound could become worse than it is without eq, they are different headphones afterall.

**Comment by Faerus** [comment]
Ok thanks for the answer. I won't use the equalizer since we don't have the data.
