### ISSUE TITLE
NeutronMP

### ISSUE THREAD

**Issue by Seve-s** [jaakkopasanen/AutoEq#189]
It is as if this instrument was created specifically for the parametric equalizer 4...60 bands of the NeutronMP. 
http://neutronmp.com/
https://play.google.com/store/apps/details?id=com.neutroncode.mpeval
![Screenshot_20200721-141435-753](https://user-images.githubusercontent.com/65365372/88048828-b3ab5000-cb5c-11ea-979e-09aeb04ce5a9.jpg)
![Screenshot_20200721-141945-919](https://user-images.githubusercontent.com/65365372/88049158-4e0b9380-cb5d-11ea-921a-3b5d3fab5caa.jpg)

**Comment by jaakkopasanen** [comment]
Neutron was once among the listed software but I removed it in favor of USB Audio Player Pro.
