### ISSUE TITLE
Solved: How to generate results folder but different argument

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#19]
I have a headphone data, and in results\rtings\avg there's a result.
I did a manual generate and by different argument, use "rtings_compensation_avg.csv"
but I got a different curve than the results\rings\avg one.

The reason I try again is I modify the argument to release the 6.0 db limit.
```
python .\frequency_response.py --input_dir="%inputDir%" --output_dir="%outputDir%" --compensation="%compensationFile%" --equalize --show_plot --max_gain %MAX_GAIN% --treble_max_gain %TREBLE_MAX_GAIN%
```

**Comment by mhtvsSFrpHdE** [comment]
All right, though the png looking different, but the result doesn't hear a different.

**Comment by jaakkopasanen** [comment]
Look results/update.py for parameters used for pre-computed results.

**Comment by mhtvsSFrpHdE** [comment]
The code are running now and release default gain limit have been confirmed to success.  
Paste all the command here to help others if needed.  

After edit "frequency_response.py", then  
```
REM This is the project folder
cd /d "C:\AutoEq-master"

REM load venv
venv\Scripts\activate

REM specify python search path, no "" in path
set PYTHONPATH=C:\AutoEq-master

REM run update script
python results\update.py
```
