### ISSUE TITLE
Using diffuse field–compensated measurements

### ISSUE THREAD

**Issue by davidofchatham** [jaakkopasanen/AutoEq#190]
I read your very helpful article, "[Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)," and decided to try running AutoEQ myself to generate correction for a pair of IEMs which isn't in your database. The only [measurement trace](https://rinchoi.blogspot.com/2012/09/brainwavz-b2-updated.html) that seems to be usable with WebPlotDigitizer is diffuse field–compensated. 

Your article says that such measurements should be used with flat compensation since they're already compensated. However, what if I want to convert to a different compensation? The CSV file header format suggests that I should be able to use "frequency,diffuse" and have AutoEQ de-compensate the source data, but that's not documented.

Is there a way yet to have AutoEQ process pre-compensated measurements, or at least generate a new CSV file that's de-compensated for subsequent processing?

Thanks!

**Comment by jaakkopasanen** [comment]
You could open Harman target (for example) and diffuse field CSV files in Excel and subtract one from another. This gives you a file which can turn diffuse field into Harman target. Use it with `--sound_signature`.
