### ISSUE TITLE
(Request) BeyerDynamic DT 770 Pro 80 Ohm

### ISSUE THREAD

**Issue by WHAMMBO** [jaakkopasanen/AutoEq#192]
Thanks

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Beyerdynamic%20DT%20770%2080%20Ohm

Search is a friend ;)

**Comment by WHAMMBO** [comment]
That is not the PRO model? 

Thanks, 
Eric B.

**Comment by jaakkopasanen** [comment]
There is no non-pro model of DT 770 except the M model which has a separate entry in AutoEq. The DT 880 has a non-pro version but as far as I know they are acoustically the same as the pro model. I've also heard that the different ohm versions of 770, 880 and 990 have less differences than what is the unit variance for these models so it could be that the ohm rating doesn't matter either. But then again I've heard that the 80 Ohm DT 770 is different from 32 and 250 Ohm ones. Summa summarum: it's a mess. Just use the DT 770, that's the PRO model even though I've decided not to separate between the PROs and non-PROs.

**Comment by WHAMMBO** [comment]
Okay, I appreciate the info. 

You might want to make note of that so other people don't annoy you like I have :) 

Eric B.
