### ISSUE TITLE
Feature Request: Add Harman Score before and after equalizing

### ISSUE THREAD

**Issue by ionizer999** [jaakkopasanen/AutoEq#196]
Oratory and others have the harman score as part of their measurements

As you have the harman curve already, it should be not too difficult to add the score before and after equalizing.

That would be really nice to have to see that all in one place.

Also would help to see if it significantly changes when using a parametric equalizer vs fixed band equalizer, etc.

**Comment by jaakkopasanen** [comment]
With what equalizer? Convolution equalizer can do pretty much perfect score every time. Also the scores are not very meaningful above 90 so it doesn't make sense to show them with EQ.
