### ISSUE TITLE
Question: Is AutoEQ when used by HeSuVi a convoluting equalizer

### ISSUE THREAD

**Issue by ionizer999** [jaakkopasanen/AutoEq#197]
I want to build a HeSuVi for Mac OS X with AutoEQ.

So my quick question is:

Is AutoEQ for HeSuVI using convolution to apply the target curve diff?

(Issue can be closed afterwards)

**Comment by jaakkopasanen** [comment]
HeSuVi uses GraphicEQ.txt files. There's a hesuvi.zip in the results folder which contains all of them.
