### ISSUE TITLE
Massdrop AKG K7XX parametric EQ error

### ISSUE THREAD

**Issue by Nic0-** [jaakkopasanen/AutoEq#2]
The 5th filter currently appears as :
29532 Hz | 3.16 | -4.4 dB
This causes Peace to instantly make a loud distorted sound which gets caught by the clipping filter until the pre amp hits -30 dB.
Based on the graphic EQ settings I assume the frequency was supposed to be 19532: changing it to this, or to anything under 20k, resolves the issue.

**Comment by jaakkopasanen** [comment]
Sometimes the optimizer produces filters with very high center frequencies. These will be folded (in theory) below 24kHz. Folding the center frequencies of these filters was not handled at all causing the final results to have the unfolded frequencies. I fixed the issue by folding them back to the correct range and this made the 29532 Hz filter to move to 18366 Hz.
