### ISSUE TITLE
Loudspeaker in room flat target for rtings

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#200]
Hi,

I’m intrigued by how you created the Harman target for Rtings measurements. Can you shed some light on that? Would it be possible to “translate” the Loudspeaker in room flat target to apply to Rtings measurements as well?

Regards,
Alex

**Comment by jaakkopasanen** [comment]
You could load Harman target and Harman loud speaker in room targets in Excel and subtract one from another. This gives you a difference curve which you can use with `--sound_signature` param. Or you could also load the Rtings calibrated Harman target and add the difference directly to that.
