### ISSUE TITLE
[Request] Wavelet setup for KZ ZS10 Pro

### ISSUE THREAD

**Issue by AMonreale** [jaakkopasanen/AutoEq#201]
Hi,

first of all I wanted to thank you for this, as a newbie it's an incredible resource. I'm sorry if something I'll write doesn't make perfect sense, as I said I'm new ot this.

I've been trying, unsuccesfully, to create a Wavelet setup for my KZs.

If you don't know, Wavelet uses different frequencies as other equalizer (as you can see [here](https://i.imgur.com/J3GuBay.png)), so the setup proposed in the readme is not quite fitting.

So after a little googleing I found this [guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9) and [this graph](https://i.imgur.com/6ie0j3p.png) for the FR, so I decided to give it a try.

But first I encountered the error `ValueError: Duplicate values found at frequency 22.0. Remove duplicates manually.`, which for a someone inexperienced is quite confusing. Which value should I remove?

I removed a few duplicate values and launched the command `python autoeq.py --input_dir="_my/input/data_" --output_dir="_my/output/data_" --compensation="compensation/harman_in-ear_2019v2_wo_bass.csv" --equalize --bass_boost=4.0 --fixed_band_eq --fc=75,150,300,600,1200,2400,4800,9600,19200 --q=1.05` and, oh boy, [this... atrocity came out](https://i.imgur.com/GduU2Ub.png) and the gains are all over the place. So, I'm surely doing something wrong, but I don't know what.

**Comment by Pittvandewitt** [comment]
You could just let AutoEq generate some data without the fixed_band_eq and the fc parameters. Wavelet supports importing GraphicEq files generated by AutoEq: https://pittvandewitt.github.io/Wavelet/Import
The result you get suggests to me that the data you got from webplotdigitizer is messed up. Please check if the axes are correct and if all coordinates are placed on the graph only.

**Comment by LencoDigitexer** [comment]
```
10,24, 95,47
10,71, 95,67
11,15, 95,82
11,62, 95,96
12,08, 96,07
12,68, 96,25
13,35, 96,42
```

https://apps.automeris.io/wpd/ makes a comma instead of a dot
