### ISSUE TITLE
[Request] Parametric filter width in octaves

### ISSUE THREAD

**Issue by ftrebien** [jaakkopasanen/AutoEq#203]
[sengpielaudio](http://www.sengpielaudio.com/calculator-bandwidth.htm) provides this simpler formula to calculate filter width in octaves from Q:
```N = arcsinh(0.5 / Q) * 2 / ln(2)```

Depending on the parametric equalizer in use, it would be interesting to have the value of N provided after Q in the `ParametricEQ.txt` and `README.md` files, so I'd like to request this feature. Doing so would also allow simplifying the documentation a bit.

**Comment by jaakkopasanen** [comment]
It can't be added to `ParametricEQ.txt` because that's in a specific format required by EqualizerAPO. I'm afraid adding that to READMEs would create more confusion that it helps when people start wondering if they should use Q or bandwidth. Therefore I'm not going to implement this request.
