### ISSUE TITLE
[Question] What are the settings used for standard results?

### ISSUE THREAD

**Issue by xykrr** [jaakkopasanen/AutoEq#204]
Hi, what settings do you use for the standard results?
These days, even when I choose the correct csv, my personalized bands always sound worse than what's in AutoEQ's main results folder. Even when I try to bass boost the same amount and do nothing else, it just sounds... slighly off. For example, there will be some sort of audible isolated (probably 100-200Hz wide) treble peak that doesn't exist in your settings. It's a subtle difference- I can only be decently sure it's there when I listen to (((pink))) noise.

**Comment by jaakkopasanen** [comment]
See here:
https://github.com/jaakkopasanen/AutoEq/blob/master/results/update_results.py#L65
