### ISSUE TITLE
[Request] Xiaomi Airdots Pro 2 (1 Gen) no response graphics 

### ISSUE THREAD

**Issue by C0nvert** [jaakkopasanen/AutoEq#205]
Hello Guys, could someone pls do an Impulse Resolve file for Xiaomi Airdots Pro 2 (1 Gen)?
Couldn't find a response response graphic.

**Comment by jaakkopasanen** [comment]
Unfortunately there's nothing I can do if the headphones haven't been measured by one of the supported sources.
