### ISSUE TITLE
Add Fabfilter Pro Q3 to Parametric EQ software list

### ISSUE THREAD

**Issue by Coder84619** [jaakkopasanen/AutoEq#206]
FYI I have no affiliation with Fabfilter, other than a super happy customer. They have various audio plugins, but for the purposes of AutoEQ the Pro Q3 product is what you want. It has an amazing UI, 'click next' installer, and even won a Grammy. 

It's available for both Mac and Windows. Certainly on the pricy side, though. 

https://www.fabfilter.com/products/pro-q-3-equalizer-plug-in

I think it would be worthwhile adding to the EQ software list. It's way easier to install than the listed Voxengo product.

**Comment by jaakkopasanen** [comment]
Done. Thanks for the tip!
