### ISSUE TITLE
[Request] Please add details for Xiaomi Redmi airdots S

### ISSUE THREAD

**Issue by coxackie** [jaakkopasanen/AutoEq#208]
there seems to be a raw frequency response graph here:
https://www.thephonograph.net/xiaomi-redmi-airdots-s-review-xiaomi-twsej05ls-review/
but I am seriously way out of my depth to do this by myself...

**Comment by jaakkopasanen** [comment]
Sorry but I don't do custom EQ settings. It's a lot better use of my time to focus on implementing the algorithms which serve everyone.
