### ISSUE TITLE
[Request] Sortable Columns in Headphone Ranking Table

### ISSUE THREAD

**Issue by mttu** [jaakkopasanen/AutoEq#210]
Thanks very much for adding the headphone ranking table. Could you you make all the columns sortable? This would make it even more useful, allowing for example easily comparing different models of the same brand when sorted by name, and grouping headphones into bright, neutral and warm sections when sorted by slope.

**Comment by jaakkopasanen** [comment]
I would love to have that but unfortunately these are just Markdown pages and it's not possible to do such a thing with them.
