### ISSUE TITLE
[Request] Add additional detail to instructions when using own measurements to make EQs

### ISSUE THREAD

**Issue by TNShark** [jaakkopasanen/AutoEq#211]
I tried to use my own measurements (made following instructions using WebPlotDigitizer) and make a EQ using AutoEQ to make my set of earbuds sound like something else. I found, however, that the data on the .csv files used needed to have at lease 127 points each to prevent an error similar to "ValueError: unexpected array size: new_size=695, got array with arr_size=0". It would help if the instructions included something to address this issue. (If I missed this in the instructions, please disregard.)

**Comment by jaakkopasanen** [comment]
Could you post the CSV files which didn't work here so that I could take a look? There shouldn't be any special requirements for the CSV files.

**Comment by TNShark** [comment]
I got the data myself following your guide on how to get data point frequency measurements using WebPlotDigitizer. I got the error when trying to use the AutoEQ python command lines to make an equalizer while experimenting with an attempt to make my inears sound like another (was curious how well it would work). I tried troubleshooting by making both files have the same number of measurements, but eventually decided to just redo the frequency measurements to have more data values in the files after looking at your measurements (which had like over 300 when one of mine just had <120 [KZ had 284 lines, Odin had 120]). After I did this I didn't get the error message anymore.

(Changed file extensions to attach .csv files.)
[KZ ZS10 Pro.txt](https://github.com/jaakkopasanen/AutoEq/files/5268901/KZ.ZS10.Pro.txt)
[Ultimate Ears Odin.txt](https://github.com/jaakkopasanen/AutoEq/files/5268902/Ultimate.Ears.Odin.txt)

**Comment by jaakkopasanen** [comment]
I looked into the files and they are not quite in the right format. You files have all the lines in quotes. This makes CSV parsers interpret them as if there's only one column whereas AutoEq expects at least two: frequency and raw. Try removing the quotes from the files and try again.

**Comment by jaakkopasanen** [comment]
I've never seen WebPlotDigitizer produce CSV data with full line quotes and the OP got things working so I'm closing this issue.
