### ISSUE TITLE
Ranking Table score discrepancies

### ISSUE THREAD

**Issue by mttu** [jaakkopasanen/AutoEq#212]
I've noticed the preference scores on the headphone ranking table (as well as the average error values) are often different to those calculated by Oratory1990 and displayed on his measurement/EQ pdfs. For example, the Koss ESP/95X scores 72 according to Oratory, but only 69 in your table, and the Sony MH755 scores 70 with an average error of 1.76 dB for Oratory, yet 69 with an average error of 1.5 dB here. What would explain these discrepancies?

**Comment by jaakkopasanen** [comment]
Oratory1990's MH755 uses 2017 target while AutoEq uses 2019 version.

I don't know about ESP/95X. My calculations are based on Listen Inc.'s excel and I believed oratory1990 uses the same but I could be mistaken.

**Comment by mttu** [comment]
That's odd...It's not just the ESP/95X, many other headphones show score discrepancies with Oratory's results too (using the same target).

**Comment by jaakkopasanen** [comment]
I think I finally realized what is the cause here. The scores in my ranking table are not normalized and the maximum is 114.49 while oratory1990's scores are normalized to maximum of 100.

**Comment by mttu** [comment]
> I think I finally realized what is the cause here. The scores in my ranking table are not normalized and the maximum is 114.49 while oratory1990's scores are normalized to maximum of 100.

Are you sure about this? His calculated scores after applying his EQ settings are often above 100. It seems odd he would normalize the 'Before EQ' scores to max 100 but not the 'After EQ' scores - then you wouldn't really be able to compare them to see how much the EQ improves the score.

**Comment by jaakkopasanen** [comment]
Now that you mention, I'm not sure. His PDFs state:
> The normalized preference ratings are used, where zero deviation from target equals a preference rating of 100
which makes me think he would normalize the scores but then the post EQ scores could not go over 100. Peculiar...

**Comment by mttu** [comment]
Well his (before EQ) score for the Apple Earpods is 39/100, whereas your calculated score is -51! So he must be normalizing the before EQ score (for in-ear headphones at least). But his after EQ scores don't seem to be normalized as they go above 100, strange. Maybe you can ask him about this. I would normalize your scores on the ranking table though, as negative scores aren't really intuitive, whereas a 0-100 scale is.
