### ISSUE TITLE
Support for Viper4Windows?

### ISSUE THREAD

**Issue by JDoawp** [jaakkopasanen/AutoEq#213]
I am probably stupid and don't really quite get how to work this but I'm using (a working) Viper4Windows on win 10, it can accept IRS and WAV files for it's convolver but the WAV files for the Beyerdynamics DT 990 250 Ohms only have a peak at the beginning and I don't know if it's supposed to be like so or if I'm doing something wrong.

Thanks for any help.

**Comment by jaakkopasanen** [comment]
Minimum phase impulse responses only have the peak in the beginning. Everything is as it should be. If the peak is in the middle, there is going to be delay.

**Comment by JDoawp** [comment]
Oh I see, I just didn't understand how it was supposed to be like. Thanks
for the clarification!
