### ISSUE TITLE
Sony WH-1000XM4 results

### ISSUE THREAD

**Issue by lrtherond** [jaakkopasanen/AutoEq#218]
I saw these results just dropped in...

Do they correspond to NC on or off?

Also, how do these results relate to Sony's "CLEAR BASS" setting? Do they assume a value of zero for "CLEAR BASS"?

Finally, are these results when used wired or wireless?

**Comment by jaakkopasanen** [comment]
Not sure because what's currently in AutoEq is measured by Rtings and they don't provide a lot of details about how they were measured. I belive ANC on and no customization in the app. Wireless or wired might not make a difference as long as the headphones are on.

**Comment by lrtherond** [comment]
Thanks, Jaakko!
