### ISSUE TITLE
Add Beyerdynamic DT 531 250Ohm

### ISSUE THREAD

**Issue by ariadarkkkis** [jaakkopasanen/AutoEq#219]
Hi,
Please add Beyerdynamic DT 531 250Ohm profile.

**Comment by jaakkopasanen** [comment]
There's nothing I can do if the headphone model has not been measured by one of the supported sources.

**Comment by ariadarkkkis** [comment]
If you or anyone knows a good EQ and setup for this headphone please tell. I want to use it for gaming and listening to music. I have problem with my current setup. Im using Asus Z170 Pro Gaming onboard soundcard. It can drive them but even at 100 its not that loud. The issue I have is gaming or music sound in general, I hear them like its a little bit behind my ears, not exactly on in center of my ears. I tried adjusting the headphone several times but still, the sound is a little bit like coming from behind. I cant pinpoint where the footsteps in games come from. I disabled every sound effect and EQ on my system but still same results. I dont know if the issue is the soundcard or its the headphone. Please someone help. Thanks
