### ISSUE TITLE
Guide for WebPlotDigitizer

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#22]
Write a simple user guide how to use WebPlotDigitizer to parse frequency response graph images and processing the output with AutoEQ. This will serve as a de facto way for supporting all the other measurements which are not included in the supported databases.

**Comment by jaakkopasanen** [comment]
Here it is: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)

Comment here if you have any problems or ideas for improvement.

**Comment by JoaoCosta-EQ** [comment]
Hello! Im called Joao and I'm from Brazil. I Have some questions abou the python EQ. When I use the code I got all those FR files. Let me ask about this one case in particular: 
python autoeq.py --input_dir="measurements/oratory1990/data/onear/HIFIMAN HE4XX" --output_dir="F:\EQ\EQ" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results/oratory1990/harman_over-ear_2018/Focal Elex/Focal Elex.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4 --convolution_eq --fs=44100,48000
The files of the Hifiman and the elex are both compensated By harman? any of them are? If both are compesated Do I have to use compesation like this one or compesation ="compensation/zero"?
About the bass boost, the value is based on what? the target headphone, the input headphone or the difference between them?
Thank you so much, this is the best audio tool I've ever seen.
