### ISSUE TITLE
Better Plots

### ISSUE THREAD

**Issue by JaKasb** [jaakkopasanen/AutoEq#220]
**Is your feature request related to a problem? Please describe.**
The plots for frequency-response can be improved.
- There is unused white space in the images (margins around the plot).
- The rendered images could be sharper. 
A sharper image increases font's readability and reduces aliasing effects on diagonal lines.

**Describe the solution you'd like**
- To eliminate the white margin around the plots use `plt.tight_layout(pad=x, h_pad=x, w_pad=x)`
Hint: the magnitude of `x` needs tuning.
Hint: `plt.savefig` adds another margin unless you set `plt.savefig(pad_inches=0)`
https://matplotlib.org/3.1.1/tutorials/intermediate/tight_layout_guide.html
- For sharper plots increase the parameters `figure.figsize` and `figure.dpi`.
https://matplotlib.org/3.1.1/tutorials/introductory/customizing.html?highlight=savefig.dpi#a-sample-matplotlibrc-file
https://stackoverflow.com/questions/47633546/relationship-between-dpi-and-figure-size

**Describe alternatives you've considered**
If you export the plots as `.pdf` or `.svg` instead of `.png`, the plots are always sharp and crisp.
On the other hand, a lot of datapoints increases the file size for these vector-based graphics formats.

**Additional context**
Annotaded Margins:
![margins](https://user-images.githubusercontent.com/10912469/94690408-9bf00500-031f-11eb-8f9d-34ec0162908d.png)
Fonts with aliasing effects:
![font](https://user-images.githubusercontent.com/10912469/94690421-a01c2280-031f-11eb-9b5b-32446c907221.png)

**Comment by jaakkopasanen** [comment]
Thanks for the idea. I've given this some thought and decided I'm not going to change anything. The margins in the graphs don't really harm and I feel like they look better this way. Images sizes have already been adjusted to be a compromise between resolution and file size. The repository contains almost 5000 images so increase in the file size is not inconsequential.
