### ISSUE TITLE
IE 80 S and IE 80 S (max) duplicates, IE 80 S (min) missing

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#222]
The IE 80 S result from Oratory1990 overwrites the IE 80 S (min) result from crinacle. This effectively makes the IE 80 S (max) result a duplicate while the (min) result is removed from the results list.

**Comment by jaakkopasanen** [comment]
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Sennheiser%20IE%2080%20S%20(min)
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Sennheiser%20IE%2080%20S%20(max)

I didn't rename oratory1990's measurement, it's still just IE 80 S.
