### ISSUE TITLE
Would it be possible to add results for crinacle's new GRAS 43AG-7 headphones' meansuments?

### ISSUE THREAD

**Issue by stx1998x** [jaakkopasanen/AutoEq#224]
https://crinacle.com/graphs/headphones/
Since the 43AG-7 is 100% compatible with Harman research without any fiddling with calibrations, those measurements can be useful to generate Harman Target compensations.

**Comment by jaakkopasanen** [comment]
It would and I plan to. I discussed this with Crinacle a while ago and now it looks like he has already added the CSV files which I needed. I will proceed with this quite soon.

**Comment by jaakkopasanen** [comment]
https://www.reddit.com/r/headphones/comments/jdifdc/equalizer_settings_for_crinacles_gras_measurements/
