### ISSUE TITLE
[ Error ] DT 1990 (Balanced Earpads). Parametric EQs vs GraphicEQ

### ISSUE THREAD

**Issue by vipqs123** [jaakkopasanen/AutoEq#226]
Hi
I'm a DT 1990 user. I found out in DT 1990 (Balanced Earpads) that Parametric EQs and GraphicEQ differ a lot. GraphicEQ for accurate sound. The Parametric EQs on your chart will look a lot like GraphicEQ, but in reality they differ a lot. Here is my illustration, I have drawn Parametric EQs according to the parameters you give. But they don't give similar curves. I really need Parametric EQs for my music production. Hope you let me know what's going on. Thank you very much
![1](https://user-images.githubusercontent.com/72915096/96104961-adcace00-0f03-11eb-94c1-4f40cbb03afd.png)
![2](https://user-images.githubusercontent.com/72915096/96104971-aefbfb00-0f03-11eb-9532-8f3d909a6c39.png)

**Comment by jaakkopasanen** [comment]
Looks like you have a high shelf filter at around 600 Hz with -5 dB of gain in your fabfilter. AutoEq doesn't produce shelf filters so you must have configured something wrong.

**Comment by vipqs123** [comment]
> Có vẻ như bạn có một bộ lọc giá cao ở khoảng 600 Hz với độ lợi -5 dB trong bộ lọc của bạn. AutoEq không tạo ra các bộ lọc giá, vì vậy chắc hẳn bạn đã định cấu hình sai.

I checked it again. I don't use shelf filters, I just use Bell in fabfilter. I have filled in the correct Parametric EQs parameters you gave. Below is a more detailed picture of my setting
![1](https://user-images.githubusercontent.com/72915096/96108180-7c540180-0f07-11eb-8e0c-5d5171bba13d.png)
![2](https://user-images.githubusercontent.com/72915096/96108182-7d852e80-0f07-11eb-9df6-2d6a4b4b3db4.png)
![3](https://user-images.githubusercontent.com/72915096/96108185-7e1dc500-0f07-11eb-93db-d2d4600dbde4.png)
![4](https://user-images.githubusercontent.com/72915096/96108188-7e1dc500-0f07-11eb-98a8-6e22a1be54aa.png)
![5](https://user-images.githubusercontent.com/72915096/96108189-7eb65b80-0f07-11eb-95f2-52648293d965.png)
![6](https://user-images.githubusercontent.com/72915096/96108192-7f4ef200-0f07-11eb-949d-1e15b879701c.png)
![7](https://user-images.githubusercontent.com/72915096/96108194-7fe78880-0f07-11eb-8b69-f81012e9580c.png)
![8](https://user-images.githubusercontent.com/72915096/96108195-7fe78880-0f07-11eb-8323-51bab89fcd41.png)
![9](https://user-images.githubusercontent.com/72915096/96108198-80801f00-0f07-11eb-95e4-5bcb90706372.png)
![10](https://user-images.githubusercontent.com/72915096/96108202-8118b580-0f07-11eb-856d-40b21d1dc9ab.png)

**Comment by vipqs123** [comment]
> Looks like you have a high shelf filter at around 600 Hz with -5 dB of gain in your fabfilter. AutoEq doesn't produce shelf filters so you must have configured something wrong.

I am still waiting for your reply. Hope it will come soon. This project of yours is awesome, thanks for all

**Comment by jaakkopasanen** [comment]
I see, it's the 18 kHz peaking filter with 0.04 Q. How does the result look like if you type the parametric eq filters to EqualizerAPO. The configuration editor (and Peace GUI for that matter) has a live frequency response graph which you can use to check the result.

**Comment by vipqs123** [comment]
> I see, it's the 18 kHz peaking filter with 0.04 Q. How does the result look like if you type the parametric eq filters to EqualizerAPO. The configuration editor (and Peace GUI for that matter) has a live frequency response graph which you can use to check the result.

Here are the results when I use ParametricEQ.txt to EqualizerAPO. And it works fine, everything looks the same as on autoEQ's graph. But when I used ParametricEQ in README.md for fabfilter, the wave curve appears not like the graph of AutoEQ
![13](https://user-images.githubusercontent.com/72915096/96118052-30a85480-0f15-11eb-9035-534f3358999f.png)
![14](https://user-images.githubusercontent.com/72915096/96118057-31d98180-0f15-11eb-9f10-965f64422a3b.png)
![12](https://user-images.githubusercontent.com/72915096/96118062-32721800-0f15-11eb-9609-49b116fff88c.png)

**Comment by jaakkopasanen** [comment]
So if the results look correct in EqualizerApo, then it sounds like the problem is with fabfilter. I do admit however that 0.04 Q value should be avoided but unfortunately the parametric eq algorithm doesn't have these safe guards at the moment.

You have two options
1. Try producing new equalizer settings yourself with AutoEq and change some parameters just a bit if needed to trick the parametric eq optimizer producing filters without extreme values like 0.04 Q
2. Use

**Comment by vipqs123** [comment]
> Vì vậy, nếu kết quả trông chính xác trong EqualizerApo, thì có vẻ như vấn đề là với fabfilter. Tuy nhiên, tôi thừa nhận rằng nên tránh giá trị 0,04 Q nhưng không may là thuật toán eq tham số không có các biện pháp bảo vệ an toàn này vào lúc này.
> 
> Bạn có hai lựa chọn
> 
> 1. Hãy thử tự tạo cài đặt bộ cân bằng mới bằng AutoEq và thay đổi một số thông số chỉ một chút nếu cần để đánh lừa trình tối ưu hóa eq tham số tạo ra các bộ lọc không có giá trị cực đoan như 0,04 Q
> 2. Sử dụng miếng đệm tai nghe phân tích

Tôi sẽ thử lựa chọn 1. Tôi đã nghe rất nhiều bản nhạc hàng đầu thế giới được sản xuất vào năm 2020 với cả hai tấm đệm. Tôi nhận ra rằng oratory1990 cho kết quả không chính xác như Rtings. Đó là lý do tại sao tôi chọn Balanced Earpads, bởi vì Rtings làm được điều đó. Cảm ơn rât nhiều. Chúc bạn ngày mới tốt lành.

**Comment by vipqs123** [comment]
> So if the results look correct in EqualizerApo, then it sounds like the problem is with fabfilter. I do admit however that 0.04 Q value should be avoided but unfortunately the parametric eq algorithm doesn't have these safe guards at the moment.
> 
> You have two options
> 
> 1. Try producing new equalizer settings yourself with AutoEq and change some parameters just a bit if needed to trick the parametric eq optimizer producing filters without extreme values like 0.04 Q
> 2. Use analytic earpads

I'm going to try option 1. I have listened to a lot of the world's top music produced in 2020 with both pads. I realize that oratory1990 gives not exactly the same result as Rtings. That's why I chose the Balanced Earpads, because Rtings does it. Thank you very much. Have a good day.

**Comment by jaakkopasanen** [comment]
Is there a reason why you are using Rtings? oratory1990's analytical earpad eq settings are different because the pads change the frequency response and therefore the needed equalizer AND oratory1990's measurements are a lot more accurate than Rtings' measurements.

**Comment by vipqs123** [comment]
> Is there a reason why you are using Rtings? oratory1990's analytical earpad eq settings are different because the pads change the frequency response and therefore the needed equalizer AND oratory1990's measurements are a lot more accurate than Rtings' measurements.

I really have no knowledge of measurement technology. I only listen with my ears. I work in a studio environment and also go to other studios regularly. Listening and comparison I find Rtings more accurate with the DT 1990. I have not tried AutoEQ with other headphones.

**Comment by vipqs123** [comment]
One more thing. Sonarwork is the worst result for DT 1990
