### ISSUE TITLE
Duplicates in Ranking Table

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#227]
**Describe the bug**
Ranking tables contain duplicate entries for the same headphone models.

**Expected behavior**
Each headphone model should be only once in the ranking table. But which one should be shown? oratory1990 over Crinacle? The better result? An average?

**Comment by vipqs123** [comment]
> **Describe the bug**
> Ranking tables contain duplicate entries for the same headphone models.
> 
> **Expected behavior**
> Each headphone model should be only once in the ranking table. But which one should be shown? oratory1990 over Crinacle? The better result? An average?

Thank you for updating the DT 1990 (balanced earpads) crinacle. Last time I told you DT 1990 BE Rtings > DT 1990 AE oratory1990. Now I'm going to check out BE crinacle vs BE Rtings. I will share my comparison report with you

**Comment by vipqs123** [comment]
Glad I got a better DT 1990 BE installation. BE crinacle> BE Rtings. It didn't take long to test this out. These two settings are nearly the same, they only differ by a few points. But the Crinacle was clean, balanced, and rather. Thanks for everything. What you do is wonderful

**Comment by mttu** [comment]
> **Describe the bug**
> Ranking tables contain duplicate entries for the same headphone models.
> 
> **Expected behavior**
> Each headphone model should be only once in the ranking table. But which one should be shown? oratory1990 over Crinacle? The better result? An average?

Oratory uses the Gras RA0045 coupler with the 43AG whereas Crinacle uses Gras's 'high frequency' coupler. Measured frequency response seems to differ slightly between these two couplers. The Harman in-ear target was developed using the RA0045 coupler, so measurements using this would be more likely to get you closer to the target using EQ. I think this same coupler was used when developing the over-ear target as well. Given all this, I think you should take Oratory's results over Crinacle's for the ranking table, also considering he's a professional acoustic engineer who measures headphones for a living, with a very thorough methodology, which he describes here:

>I measure at 5 positions (ctr, up, down, front, back) with multiple reseats.
I also forcibly break the seal on some reseats, to see how it affects this particular headphones.

>For headphones with little variation I take the average.
For seal-dependent headphones (where some individual reseats would have a much lower bass response) I take the average of the best-sealing individual results at low frequencies and cross over to a total-average of all measurements somewhere in the mid-range (where the seal stops having an effect).

**Comment by jaakkopasanen** [comment]
As I understand the two couplers really only differ in the +10 kHz range which is not used for the preference score calculations. Crinacle is measuring multiple reseats too.

**Comment by mttu** [comment]
From GRAS's own measurements, the couplers start to noticeably differ from around 6kHz up, with a 6dB difference at 10kHz (at least for in-ear headphones). This seems fairly significant, especially when determining closeness to or EQing to the Harman target. See here: 

https://www.grasacoustics.com/files/792-2710_low_gras1810High%20Res%20Ear%20Simulator%20for%20Headphone%20Testing_04.pdf

Crinacle may measure reseats, but he's not a professional, and I don't think he does as many reseat measurements or as methodically as Oratory.

**Comment by jaakkopasanen** [comment]
That seems to be the case. However that doens't mean that the end result would be much different below 10 kHz if a calibration curve is used, which I assume is. Take a look at my own data analyzis of Crinacle's vs oratory1990's measurements: https://i.imgur.com/Ro53A2B.png

The average error below 9 kHz are less than 1 dB in Crinacle's measurements compared to oratory1990's. This is actually quite remarkably low considering the unit variance in headphones.

Still I might choose to use oratory1990's measurements over Crinacle's in the ranking table. That's what I already do in recommended results so it would be consistent.

**Comment by jaakkopasanen** [comment]
oratory1990 preferred over Crinacle now.
