### ISSUE TITLE
dt 250 80 ohm question

### ISSUE THREAD

**Issue by Beyondsix** [jaakkopasanen/AutoEq#228]
Hi, just was wondering: this profile:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm1_harman_over-ear_2018/Beyerdynamic%20DT%20250%2080%20Ohm
Regarding the Beyerdynamic dt250 80 ohm. Does the resulting target include a Harman profile or is it to be considered "flat"...I'm a bit slow in the head today... :-)

**Comment by jaakkopasanen** [comment]
The target frequency response is as close as it gets to Harman over-ear 2018 on the Reference Audio Analyzer's HDM-1 measurement system. Different measurement systems are not directly compatible so I've "calibrated" the Harman target for different systems by comparing measurements of the same headphone models from different sources. In other words this DT 250 80 Ohm will get you as close to neutral as it's possible with the given measurements.

Beyerdyamic headphones (at least DT 770, DT 880 and DT 990) have larger unit variance than what is the difference between different Ohm models. Take a look at the oratory1990 measurement too and give it a try: https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Beyerdynamic%20DT%20250

**Comment by Beyondsix** [comment]
Hi! I also found this Crinacle measurement:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Beyerdynamic%20DT%20250%2080%20Ohm

My feeling is that 80 ohm vs 250 at least for this model varies a LOT. So I think it’s best to look at the 80 ohm....

Is Crinacle that much better than Reference audio?

**Comment by Beyondsix** [comment]
Hmmm... would it be possible to calculate the eq values without the harman curve?

**Comment by jaakkopasanen** [comment]
@Beyondsix 

>Is Crinacle that much better than Reference audio?

Yes, Crinacle's new measurements are as good as they come.

> would it be possible to calculate the eq values without the harman curve?

What does this mean? Equalization always requires some target frequency response.

**Comment by Beyondsix** [comment]
From Harman to flat menar jag :-)

**Comment by jaakkopasanen** [comment]
Flat as in flat frequency response measured at the ear drum as the measurement systems do? That's not useful in any situation. Human ears affect the frequency response (such as the 3 kHz amplification) and brains expect these effects to be there. Therefore they should not be removed.

**Comment by Beyondsix** [comment]
It’s just that the autoeq crinacle setting for my Beyerdynamic dt250 is like superbright. It hurts my ears:

**Comment by jaakkopasanen** [comment]
Here are a couple of suggestions:
1. Try all the other DT 770 presets, including the 250 and 32 ohm ones. This model has so much unit variance that what you end up depends on luck.
2. Use the Crinacle's 80 ohm results but disable the 3709 Hz filter.
3. Create your own equalization settings and adjust the brightness with `--tilt`. Use negative values (dB/octave) to make the result darker.
4. Adjust the eq settings to your liking by ear. If you use EqualizerAPO or some other parametric eq which has more filters available, you can just add more filters.

I'm going to close the ticket since there isn't anything that needs to be implemented or fixed on AutoEq.
