### ISSUE TITLE
Convolution Curve Upper Frequency Limit

### ISSUE THREAD

**Issue by skycyclepilot** [jaakkopasanen/AutoEq#229]
Some articles I've read on taking headphones measurements suggest that, due to resonances, difference in the ears of listeners, etc., measurements taken above about 5 KHz or so tend to be unreliable.  Just repositioning the headphones a little on the test rig can significantly change the measurements of higher frequencies.  Some have suggested simply equalizing the lows and mids on our headphones, leaving the highs alone.

I'm playing around with equalizing my HiFiMan Arya headphones with the Oratory parametric settings, and the convolution curve.  For these headphones, both methods significantly reduce everything above about 6 KHz, making the headphones sound dull.  Delicate high hat work just disappears.  I've deleted the higher frequency points in the parametric settings, and adjusted the other points to keep them where they were before the deletions, and that seems to work.

Unfortunately, there is no way to "turn off" the upper frequencies in the convolution curve.

Not sure what I'm asking for, but comments and suggestions would be apprciated.

**Comment by jaakkopasanen** [comment]
You can control this when creating eq presets yourself. `--treble_f_lower` controls the lower bound of the transition region, `--treble_f_upper` controls the upper bound and `--treble_gain_k` controls the gain coefficient for the treble frequencies. You could, for example, disable equalization above 6 kHz by `--treble_f_lower=4000 --treble_f_upper=6000 --treble_gain_k=0.0`. The equalization power would be 100% of the normal at 4 kHz and 0% at 6 kHz and above.

**Comment by skycyclepilot** [comment]
Thanks!  That's very helpful!

Michael
