### ISSUE TITLE
Crinacle HD650 with fresh pads?

### ISSUE THREAD

**Issue by holomiik** [jaakkopasanen/AutoEq#231]
Hi,

Could you add Crinacle's latest HD650 w/ fresh pads results here aswell?
This GRAS measurement you currently have here is with old pads.

Thank you for your hard work!

**Comment by jaakkopasanen** [comment]
Here you go: https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Sennheiser%20HD%20650%20(sample%202)

The HD 650 measurements with worn earpads are marked as such, I never mark fresh earpad measurements with anything extra.
