### ISSUE TITLE
New Crinacle results

### ISSUE THREAD

**Issue by Long-FA** [jaakkopasanen/AutoEq#232]
In October 10, Crinacle updated his headphone database, with over 100 new headphones measured with GRAS. Please include these new results to AutoEq. This is not a duplicate of #224 .
[https://crinacle.com/2020/10/10/the-spicy-update-170-headphones-ranked/](https://crinacle.com/2020/10/10/the-spicy-update-170-headphones-ranked/)

His database was also updated in October 18 and October 29.

**Comment by jaakkopasanen** [comment]
Done. Should include all of the latest ones now.
