### ISSUE TITLE
How can I generate results based on crinacle's measuments?

### ISSUE THREAD

**Issue by stx1998x** [jaakkopasanen/AutoEq#235]
I found the filters with positive gain above 9k generally annoying. Is it possible to generate customized results based on crinacle's measuments?

**Comment by jaakkopasanen** [comment]
It is, but you'll need to have access to the numerical data. Crinacle has a Patreon subscription tier which unlocks the numeric data and therefore asked me not to publish the data in AutoEq. If you decide to toss a coin to the man, you'll find instructions in measurements folder README.md on how to produce the AutoEq friendly data which you can then use to generate your own results. Be aware, this was never intended to be user friendly process so there might be complications along the way.

Easiest way of course would be to adjust the existing filter presets if you're using parametric eq. You can change values of the existing filters or add new ones if you have more filters available.

**Comment by stx1998x** [comment]
Thanks for replying
