### ISSUE TITLE
[Windows 7] Installation error

### ISSUE THREAD

**Issue by JoseHidalgo** [jaakkopasanen/AutoEq#238]
Hi, I'm currently trying to install AutoEQ on my Windows 7 SP1 x64 rig, following the instructions in https://github.com/jaakkopasanen/AutoEq#usage
I had a previously installed Python 3.7.2, and I added it to PATH.
I think I have followed the step-by-step instructions, as shown by this screen cap.
Everything was going fine, but at the end...

![2020-12-06_171057](https://user-images.githubusercontent.com/10851603/101285552-218fa580-37e6-11eb-85b6-724362406553.png)

What's going wrong ? Thank you.

EDIT - there seems to be a problem with tensorflow and my CPU. I have a 10-years old Core i3 530.

**Comment by JoseHidalgo** [comment]
EDIT 2 - nevermind, I'll update to Windows 10 as there seem to be too many issues with Windows 7.
Case closed.

**Comment by jaakkopasanen** [comment]
@JoseHidalgo this is the same problem as #239 and should be fixed now in the latest version of AutoEq.
