### ISSUE TITLE
Unable to install requirements.txt

### ISSUE THREAD

**Issue by deoxygen** [jaakkopasanen/AutoEq#239]
Attempting to run "pip install -r requirements.txt" but when I do I get the following error:
`ERROR: Could not find a version that satisfies the requirement tensorflow~=2.0.0`
`ERROR: No matching distribution found for tensorflow~=2.0.0`

Currently I'm using Windows 10 and Python 3.9.1x64 but I can replicate this error across 3.9.0 and 3.7.0.

**Comment by jaakkopasanen** [comment]
Thanks for reporting the issue. I wonder if Tensorflow has removed 2.0.X from the supported releases. I'll look into it. If you're in a hurry, you can try to change line 6 in `requirements.txt` from `tensorflow~=2.0.0` to `tensorflow^=2.0.0` and see if the install works with that.

**Comment by deoxygen** [comment]
Here are the results once I made that change:
`(venv) E:\Downloads\AutoEq-master>pip install -r requirements.txt
ERROR: Invalid requirement: 'tensorflow^=2.0.0' (from line 6 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?`

**Comment by jaakkopasanen** [comment]
Fixed the version number in `requirements.txt`. Get the latest version and try again.

Tensorflow has dropped 2.0 version from modern Pythons and the requirements only accepted 2.0.x.

**Comment by freestylemaster** [comment]
Hi,

I have the latest `requirements.txt` however still having the same error both on Debian 10 and Ubuntu 20.04. 


```
Collecting tensorflow<3.0.0,>=2.0.0 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.0.0 (from -r requirements.txt (line 6)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow<3.0.0,>=2.0.0 (from -r requirements.txt (line 6))
```

**Comment by jaakkopasanen** [comment]
@freestylemaster can you try running
```bash
python -m pip install -U pip
```
and then try to install the dependencies again.

**Comment by devinbhatt** [comment]
@freestylemaster Make sure your python is 64-bit and not 32-bit.

**Comment by freestylemaster** [comment]
> @freestylemaster Make sure your python is 64-bit and not 32-bit.

Thanks. For future reference, the issue was because of an old CPU model that I had. Taking the same steps on a newer CPU went through without any issue.
