### ISSUE TITLE
Reference Audio Analyzer Measurements

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#24]
Reference Audio Analyzer has several hundred of measurements for all kinds of headphones and therefore would be valuable addition to this collection. They have several different measurement systems and have not published (to my knowledge) the compensation curves. All of their graphs are compensated. Therefore it's better and simpler to take the compensated data as is and use zeros as the target curve. These will be the lowest priority for recommendation among all databases.

1. Create script for crawling links to graph images
2. Create image graph parser
3. Download all measurements and fix potential conflicting naming conventions
4. Process images and check that all were parsed correctly
5. Process results for all Reference Audio Analyzer measurements
6. Update recommendations, full index and add a note to documentation

**Comment by M0Rf30** [comment]
Hi Jaakko, I've written a simple piece of code to better automatize raa parsing with no js console interaciton
```
from lxml import html

import requests
page = requests.get('https://reference-audio-analyzer.pro/en/report/hp/')
content = page.content
tree = html.fromstring(content.decode('utf-8','ignore'))
models = tree.xpath('//a[contains(@href,".php")]')
indexval = 0
for m in range(len(models)):
    model = models[indexval].text_content()
    stripped=model.strip('.php')
    splitted=stripped.split('-')
    vendor=splitted[0]
    url = 'https://reference-audio-analyzer.pro/report/hp/' + vendor + '/' + stripped + '/' + stripped + '_def.png'
    print(url)
    r = requests.get(url, allow_redirects=True)
    open(stripped + '_def.png', 'wb').write(r.content)
    indexval += 1
```
I hope could be useful

**Comment by M0Rf30** [comment]
It has some problems with vendors like allen healf because splitted[0] refers only to allen and doesn't resolve the image link, but should be simple to check for the existence of splitted[0] (if doesn't exist it can also append splitted[1]).

**Comment by M0Rf30** [comment]
why akg y50 disappeared from computed results?

**Comment by jaakkopasanen** [comment]
I thought there was no Y50 and it's Y50BT but turns out they are different models. I renamed the Y50BT back to Y50.
