### ISSUE TITLE
Usound rankign table

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#241]
I understand you moved to Harman 2019 in-ear target. But could you share just a top 20 ranking table based on the Usound target here?

**Comment by jaakkopasanen** [comment]
You can change the target curve file path in [results/update_indexes.py#L249](https://github.com/jaakkopasanen/AutoEq/blob/master/results/update_indexes.py#L249). After than just run the script
```
python results/update_indexes.py
```
It will take some time because it updates everything, including the HeSuVi ZIP.

**Comment by markanini** [comment]
I was able to run the script and generate the modified RANKING.md after running "pip install rapidfuzz".
