### ISSUE TITLE
KZ-EDX

### ISSUE THREAD

**Issue by Xismo2020** [jaakkopasanen/AutoEq#243]
Just saying. I think these are good to be here. Sick. You have an effort to do it, known. Ty.

**Comment by jaakkopasanen** [comment]
Unfortunately there's nothing I can do since these haven't been measured by one of the supported sources yet. If they do get measured, they will eventually end up here.

**Comment by thefexcos791** [comment]
> Unfortunately there's nothing I can do since these haven't been measured by one of the supported sources yet. If they do get measured, they will eventually end up here.

https://reference-audio-analyzer.pro/en/report/hp/kz-edx.php

**Comment by diegoandrade-iuv** [comment]
> > Unfortunately there's nothing I can do since these haven't been measured by one of the supported sources yet. If they do get measured, they will eventually end up here.
> 
> https://reference-audio-analyzer.pro/en/report/hp/kz-edx.php

With this link this issues could be reopened?
