### ISSUE TITLE
New target: Oratory1990 Optimum Hifi

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#245]
Hi,

Oratory1990 has created his own target response for headphones (also over-ear) which sounds very nice. This `Oratory1990 Optimum HiFi' target can be seen in the graphs on [HeadphoneDatabase](https://headphonedatabase.com/). Can you please add this as a target to your project as well?

Kind regards,
Alex

**Comment by jaakkopasanen** [comment]
Thanks for letting me know! Here it is now.
https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/oratory1990_optimum_hifi.csv
![](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/compensation/oratory1990_optimum_hifi.png)

**Comment by jaakkopasanen** [comment]
And here is the difference. The target in this picture is Harman over-ear 2018 target without bass shelf.
![Oratory1990 Optimum HiFi vs Harman Over-ear 2018](https://user-images.githubusercontent.com/8393524/103134691-bb4ac400-46bb-11eb-80c2-f829ec30fba6.png)

**Comment by DeLub** [comment]
Thanks again for all your great work!

**Comment by NekoAlosama** [comment]
@DeLub 
Is there a reason to use the Optimum Hifi target over the Harman over-ear 2018 target? It doesn't seem like there's much difference.

**Comment by DeLub** [comment]
It's mainly personal. I think I belong to the group who likes a bit less bass than the Harman target curve does. And that's probably why I like the Optimum Hifi target very much.

Oratory1990 based this target on the classic B&K curve for speakers. And that's also the curve I calibrated my loudspeakers to. So it might also be familiarity.

**Comment by NekoAlosama** [comment]
I did some digging: The Optimum Hifi curve just confirms the Harman curve (for headphones, anyways). It has the same mid to treble curve, with the bass being slightly different. Bass is more personalized than mid and treble, so for me I don't have a reason to use it since I don't have loudspeakers.
