### ISSUE TITLE
A tool to set Music.app's fixed band EQ

### ISSUE THREAD

**Issue by kivikakk** [jaakkopasanen/AutoEq#246]
Getting any of the existing macOS solutions to run on an M1 Mac is somewhere between impossible and tricky, so I decided to cheap out and just go with Music.app's builtin fixed band EQ.

Unfortunately, it doesn't actually let you enter values yourself. I really wanted to give these a try, so I made a tool that takes AutoEQ's fixed band output files and writes them into your Music.app EQ settings file: [`music_auto_eq`](https://github.com/kivikakk/music_auto_eq). Feel free to link from the README if you like the look of it!

**Comment by jaakkopasanen** [comment]
I would be willing to merge a pull request in AutoEq repo which contained code to produce the Music.app config file directly. There's already similar function for Rockbox. However I'm not in the habit of linking to external tools. So feel free to create the PR and I'll take a look!
