### ISSUE TITLE
Request for min_gain

### ISSUE THREAD

**Issue by merc4derp** [jaakkopasanen/AutoEq#247]
**Is your feature request related to a problem? Please describe.**

Fixed band equalizers tend to have restricted adjustment ranges. Typically smaller than +/-15db; Usually 12 or less. 
Results asking for a -17 or -21 adjustment are not very useful.

**Describe the solution you'd like**

A min_gain option would be the solution, capping the negative gain to the specified number. It would obviously lead to a higher positive gain requirement, but that's up to the user to compensate if they wish to employ min_gain I suppose.

Ideally if the given min-max range can not fit the calculated adjustment, there would be a message informing us so and maybe even displaying the minimum required range for this calculation.

**Comment by jaakkopasanen** [comment]
Thanks for the issue. I intend to add this when I rework the parametric eq optimizer.

**Comment by merc4derp** [comment]
Great. Keep up the good work.
