### ISSUE TITLE
Incorrect curve for Stax SR-L300 using "peaking filter" settings

### ISSUE THREAD

**Issue by Mar-Shayal** [jaakkopasanen/AutoEq#248]
The settings given for this headphone [https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Stax%20SR-L300](url) are problematic, at least when one uses the given settings. The issue seems to be filter10: Peaking | 19857 Hz | 0.38 | -10.6 dB which results in this:

![Capture](https://user-images.githubusercontent.com/76500795/102943974-7fc7b400-4487-11eb-9483-74a878233d09.PNG)

which obviously looks nothing like it should. A high shelf would seem more correct, but all the settings (for all headphones) seem to be "peaking" only, and I'm a little confused why there are not more shelving filters applied. I am new to this so apologies if I am not understanding the process :)

**Comment by jaakkopasanen** [comment]
This is the same problem as #240. I'm moving the discussion there.
