### ISSUE TITLE
tensorflow 2.4.0 has requirement numpy~=1.19.2

### ISSUE THREAD

**Issue by penguinfuko** [jaakkopasanen/AutoEq#249]
Hello When I reinstall,  enter
` pip install -r requirements.txt` 
and then an error pops up
 `ERROR: tensorflow 2.4.0 has requirement numpy~=1.19.2, but you'll have numpy 1.17.5 which is incompatible.`

**Comment by jaakkopasanen** [comment]
Thanks for reporting. I fixed Tensorflow version to 2.3. Should be good now.
