### ISSUE TITLE
Hope to generate ViPER4Android vdc

### ISSUE THREAD

**Issue by a6886126** [jaakkopasanen/AutoEq#250]
Hope to generate ViPER4Android vdc

**Comment by jaakkopasanen** [comment]
Care to elaborate? What does this mean? What is VDC?

**Comment by a6886126** [comment]
ViPER-DDC 
![IMG_20201226_223837](https://user-images.githubusercontent.com/61091205/103153393-20d9a600-47cb-11eb-987c-0ce6df868ee3.jpg)

This feature allows users to load VDC headset correction files. These files are headphone-specific and are normally used to neutralize the frequency response. This means that the lows, mids and highs are not emphasized over another, which is similar to reference grade headphones. DDCs are based on Parametric EQ filters and can also be used for non-correction purposes.

**Comment by jaakkopasanen** [comment]
You could perhaps use the FIR option. AutoEq generated impulse response WAV files should be compatible.

**Comment by carvalhopatrick** [comment]
Generate a .wav FIR file and place it in /ViPER4Android/Kernel on your phone.
Then select it under "Convolver" in the app (the 7th option in your screenshot)

**Comment by Helena9666** [comment]
You can easyly also conwert the parametriceq.txt to vdc  file with ddctool it works for me so you can use convolver for other effects
