### ISSUE TITLE
HD 600 oratory1990/harman_over-ear_2018 gain value

### ISSUE THREAD

**Issue by severgun** [jaakkopasanen/AutoEq#251]
Is it bug, or I do not understand how it works?
Here it says -6.5
https://github.com/jaakkopasanen/AutoEq/blob/8602482e318a70bb49d3cd50e80e8bd428d3cb62/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20600/Sennheiser%20HD%20600%20ParametricEQ.txt#L1
But README says -7.1db
Which is correct one?

In all other configs README and config have equal values.

**Comment by jaakkopasanen** [comment]
I fidex HD 600. There might be some others but there too will get fixed eventually when I recompute all of the results.
