### ISSUE TITLE
Sennheiser Momentum M2 and 2.0 different topics but same headphones?

### ISSUE THREAD

**Issue by bloodevil96** [jaakkopasanen/AutoEq#254]
In the result folder there's 1 result for "Momentum 2.0" and another for "Momentum M2". 
I might be wrong but these are the exact same headphones, being this-> https://en-de.sennheiser.com/momentum-m2 
There's a separate result for the wireless version so i'm not confusing those 2! 
![chrome_2021-01-06_22-55-39](https://user-images.githubusercontent.com/66381447/103823527-8bfc6580-5072-11eb-8d49-732f8a35cfb6.png)

**Comment by jaakkopasanen** [comment]
I changed the Sennheiser Momentum M2 naming to 2.0.
