### ISSUE TITLE
KZ ZSX.csv file is not there

### ISSUE THREAD

**Issue by Mspy1** [jaakkopasanen/AutoEq#255]
I am trying to create 31 band equalizer values for KZ ZSX, however I cannot find the .CSV file for KZ ZSX in the directories. Can you add it as I am unable to find it on crinacle's website.

**Comment by jaakkopasanen** [comment]
Crinacle has a Patreon tier which unlocks numerical data and therefore asked me not to share the data in Github. You would have to subscribe there and then follow instructions in the measurements folder.
