### ISSUE TITLE
Some distortion in the lower frequencies when using parametric EQ with pulseeffects?

### ISSUE THREAD

**Issue by GNY-001F2** [jaakkopasanen/AutoEq#258]
So I tried using the parametric equaliser settings for the HD 800 noted in [this file](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20800/Sennheiser%20HD%20800%20ParametricEQ.txt), but I can't tell whether I am introducing audible distortion to the signal or if a pre-existing distortion in the files are becoming noticeable.

Basically there is a noticeable change in the tone of the thumps and I don't know the exact words to describe it, but there's a kind of "chatter" that follows the bass thumps, a bit like static from an FM radio or walkie talkie. I do appreciate that this curve completely eliminates the hiss in the upper range, but overall the sound does feel a bit like it got muffled, even after I increase the volume on my amp to compensate.

I am using these settings with the following setup:

1. OL DAC and O2 Amp from JDS Labs
2. Sennheiser HD 800
3. Pulseaudio with the following custom settings:
    * default-sample-format = s24le
    * default-sample-rate = 96000 (alternative-sample-rate is left at 48000hz)
    * resample-method = soxr-vhq
    * avoid-resampling = true

All the files are played back using the Music Player Daemon and the sources are web downloads or CD rips encoded as FLAC.

I don't know if this is intentional or if there's something weird with my equalizer. None of the other modules in pulseeffects are enabled AFAICT.

EDIT:

Apparently the curves were recomputed, literally a few hours after I applied the previous curve, and the woolen effect is either gone or reduced to negligible levels. However that low frequency "distortion" is still audible.

[Sennheiser HD 800 ParametricEQ.txt](https://github.com/jaakkopasanen/AutoEq/files/5826501/Sennheiser.HD.800.ParametricEQ.txt)

**Comment by jaakkopasanen** [comment]
What you describe sounds a bit like clipping to me. Did you set the equalizer input volume to -6.0 dB? If you did, try to setting it even lower such as -8.0 dB and see if that makes a difference.

**Comment by GNY-001F2** [comment]
@jaakkopasanen Ah crap, I did not touch the input volume at all! I thought importing the parametric EQ file would take care of it since there was a pre-amp parameter in it.

I'm going to try this out and report back.

**Comment by GNY-001F2** [comment]
@jaakkopasanen: So far it seems like lowering the input volume works! Thanks a lot!

**Comment by jaakkopasanen** [comment]
Happy to help!

**Comment by GNY-001F2** [comment]
@jaakkopasanen I hope these aren't dumb questions, but why is it important to apply a negative gain to the equaliser's input? How is the value determined?

In the case of my headphones (HD 800) is the input gain set to -6db because the maximum gain applied by the equaliser is 5.6db for one of the bands affected by the EQ?

So if the gain was actually say 8.2db at 23hz, would I have to apply a gain to the input of -9db to avoid clipping the signal?

Furthermore, if the required gain is only -6db, and I push it further to say -20db and increase the volume using my amplifier's volume knob, would I end up making some of the quieter portions of the audio track absolutely silent to the equaliser input? Would the equaliser then not be able to "increase" the volume of the now quietened parts of the input?

**Comment by jaakkopasanen** [comment]
You got it mostly right. The negative input gain is there to ensure no parts of the frequency response have positive gain in the equalizer because this could make the sound output exceed the maximum digital level which leads to clipping and massive amounts of distortion.

You should be fine if you don't use crazy negative preamp values. If you pull the input level down by say -60 dB you would be eating into the dynamic range. -20 dB is probably just fine.

**Comment by GNY-001F2** [comment]
@jaakkopasanen Thanks! Regarding the second part, do you say that -20 dB is just fine because the "lowest" signal level in a typical audio file (both 16 and 24) is usually well above the +20db point from the digital zero level?
