### ISSUE TITLE
Aurto EQ bug with png

### ISSUE THREAD

**Issue by Alexick6** [jaakkopasanen/AutoEq#261]
**Describe the bug**
So I wanted to EQ my Blon BL-03 to a Blessing 2 Dusk. Well, everything seemed to be ok, but the png file with graphs (target, headphones, equalization, error and so on). It is written:

C:\Users\User>cd AutoEq

C:\Users\User\AutoEq>venv\Scripts\activate.bat

(venv) C:\Users\User\AutoEq>python autoeq.py --input_dir="my_data/BLON BL-03" --output_dir="my_results/BLON BL-03" --compensation="compensation/DUSK.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --standardize_input --max_gain=30
Traceback (most recent call last):
  File "autoeq.py", line 313, in <module>
    batch_processing(**cli_args())
  File "autoeq.py", line 161, in batch_processing
    fr.plot_graph(
  File "C:\Users\User\AutoEq\frequency_response.py", line 1632, in plot_graph
    fig, ax = plt.subplots()
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\pyplot.py", line 1287, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\pyplot.py", line 687, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\User\AutoEq\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2273, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Program Files (x86)\CSR\BlueSuite 2.6.4} C:/Users/User/AppData/Local/Programs/Python/Python38/lib/tcl8.6 C:/Users/User/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/User/AppData/Local/Programs/lib/tcl8.6 C:/Users/User/AppData/Local/Programs/Python/library C:/Users/User/AppData/Local/Programs/library C:/Users/User/AppData/Local/Programs/tcl8.6.9/library C:/Users/User/AppData/Local/tcl8.6.9/library

This probably means that Tcl wasn't installed properly.

**To Reproduce**
I just installed Auto EQ according to the instrtuction on the home page of Auto EQ. Every step described in the "installation" and also a command:

python autoeq.py --input_dir="my_data/BLON BL-03" --output_dir="my_results/BLON BL-03" --compensation="compensation/DUSK.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --standardize_input --max_gain=30

Again, all EQ configs were created properly, the only thing that is not created is a png file.

**Expected behavior**
I obviously expected the png file to be created.

I'm not a professional programmer, in fact, I am an absolute zero in programming =)
I just followed all steps.

[CSV-s.zip](https://github.com/jaakkopasanen/AutoEq/files/5862529/CSV-s.zip)

**Comment by Alexick6** [comment]
I have Dell Vostro 5370
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz;
8,00 GB
Windows 10
20H2

**Comment by jaakkopasanen** [comment]
Here's a wild guess since I don't have this problem and can't reproduce.

Copy `tcl` folder from Python root to `venv\Lib` (or perhaps `venv\Lib\site-packages`). https://stackoverflow.com/a/30377257

Python root should be `C:\Python38` but it's possibly also in AppData. In any case you can find the location by running `python -c "import sys; print(sys.executable)"`
