### ISSUE TITLE
[Request] HYLA Sarda IEM

### ISSUE THREAD

**Issue by CANiSLAYu** [jaakkopasanen/AutoEq#262]
Hello,

Is it possible to add the HYLA Sarda? These were measured by Crinacle some time back. 

https://crinacle.com/graphs/iems/hyla-sarda/

Thank you!

**Comment by jaakkopasanen** [comment]
Should be added the next time I update the measurements and results.

**Comment by jaakkopasanen** [comment]
Looks like they're missing from Crinacle's Drive folder. I notified him so hopefully he adds the measurements.

**Comment by jaakkopasanen** [comment]
Here you go: https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/HYLA%20Sarda
