### ISSUE TITLE
[Request] Denon AH-D1200

### ISSUE THREAD

**Issue by godshades** [jaakkopasanen/AutoEq#263]
I found this graph: https://www.head-fi.org/threads/denon-ah-d1200-portable-over-ear-impressions-appreciation-and-discussion-thread.881154/page-3#post-16136335

can you add this
Thank you!

**Comment by jaakkopasanen** [comment]
You can create settings for it yourself by following this guide: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). AutoEq doesn't host any measurements or results outside of the supported sources.
