### ISSUE TITLE
[Request] Edifier W830BT

### ISSUE THREAD

**Issue by jovigom** [jaakkopasanen/AutoEq#264]
Hi. First of all, thank you for your time and help us all.

I would like to ask, if possible, the EQ parameters for my EDIFIER W830BT headphones and configuration file.
https://www.edifier.com/int/en/headphones-earphones/w830bt

Thank you very much from Spain !!

**Comment by jaakkopasanen** [comment]
You can create settings for it yourself by following this guide: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). AutoEq doesn't host any measurements or results outside of the supported sources.
