### ISSUE TITLE
[Request] Samsung Galaxy Buds Pro

### ISSUE THREAD

**Issue by marsd** [jaakkopasanen/AutoEq#268]
Hi, 

Could you please add the Buds Pro too? 

https://crinacle.com/graphs/iems/samsung-galaxy-buds-pro/

**Comment by jaakkopasanen** [comment]
Looks like they're missing from Crinacle's Drive folder. I notified him so hopefully he adds the measurements.

**Comment by jaakkopasanen** [comment]
Here you go: https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Pro
