### ISSUE TITLE
"Takstar Pro 80" the same as "HyperX Cloud"?

### ISSUE THREAD

**Issue by Jerrk** [jaakkopasanen/AutoEq#271]
I have the original HyperX Cloud headphones from Kingston and as i was looking for its configuration in the results folder but the original brand is the only one i could NOT find.

It appears the original HyperX Cloud is just the Takstar Pro 80 with added microphone support and branding.

Is it acceptable to add an entry for HyperX Cloud with mirrored results to the Takstar Pro 80s? or is that a big no-no?

I'm not really that knowledgeable so I'm not sure if the results would still be the same and since i couldn't find the measurement data from any of the recommended vendors this is what came up during my searching.

**Comment by jaakkopasanen** [comment]
The convention is to use the name of the headphone that was measured. So if Takstar Pro 80 was measured then that's what needs to be the name. Aliases are not supported in AutoEq. This leaves the responsibility to the user to know if one headphone is acoustically identical to the other. Trying to do this in AutoEq leads to an endless swamp of guesswork.
