### ISSUE TITLE
New headphone request anker soundcore spirit dot 2

### ISSUE THREAD

**Issue by seanie86** [jaakkopasanen/AutoEq#275]
**Is your feature request related to a problem? Please describe.**its not really a problem but my headphones weren’t listed so I wanted to request them to be added

**Describe the solution you'd like**
A clear and concise description of what you want to happen.If you could help me to add my headphones

**Describe alternatives you've considered**

**Additional context**

**Comment by jaakkopasanen** [comment]
There's nothing I can do. AutoEq only includes measurements from supported sources so if any of those haven't measured the headphone, it won't be in AutoEq.
