### ISSUE TITLE
Dekoni measurements implementation

### ISSUE THREAD

**Issue by Lertennator** [jaakkopasanen/AutoEq#279]
would it be possible to implement Dekoni's measurements? if so, this program could support padded headphones as well.
I personally tried to produce my own result following your guide with my dt1990 with the elite velour pads , but it didn't sound quite right... there is probably some information I'm missing about their measurements. Do dekoni's measurements have any issue that prevents implementation? thanks in advance

**Comment by jaakkopasanen** [comment]
Adding new sources requires a few things including a crawler to get the data, normalizing all of the names with the other sources and a frequency response target if the measurement system is not compatible with Harman targets. This is actually quite a lot of work and therefore I've promised myself that I'm not going to add new sources. Of course that might not be a final decision if a measurement database turns up which provides measurements for a lot of headphone models which aren't covered by the other sources yet.

When it comes to Dekoni's measurements, I'm not familiar with them. But I assume there aren't several hundreds of new headphones measured with industry standard rig and therefore this wouldn't make it above the bar. If the results you're getting aren't good, the chances are that their measurement system is not a standard one.

**Comment by Lertennator** [comment]
from what I read they use an audio precision based measured rig, and they have measurements for almost every headphone they offer pads for... though probably, not several hundred of different headphones (the number rises if we consider different pad options for a single pair of headphone, of course). thanks anyway!

**Comment by 1582343047** [comment]
i am glad to hear your email. although my english isn't good,i still can understang what you say in email.the mi air2pro is best ANC in 100 dollars.as mi data ，the effective of anc is better that wi1000xm2.you may be konw that it is more than 200dollars. but the disadvantage of air2 is too much bass .i think there is a
chance to change . let me listen more comfortable. the date i sent you before is on the internet, it was does by someone who have instrument .because mi don't give the date to the us.
excuse me,may be there some error of grammar.&nbsp;&nbsp;
i can collect more information that i&nbsp; will sent.
thanks





---Original---

**Comment by lukasubo** [comment]
@Lertennator based on this head-fi thread, they might actually be using Tyll from InnerFidelity's old rig. So you could probably CSV the curves you need yourself and use AutoEQ to EQ to the InnerFidelity target.

https://www.head-fi.org/threads/dekoni-audio-and-better-measurements.887247/

**Comment by jaakkopasanen** [comment]
I'm going to close this issue because I won't be adding support for Dekoni measurements in any time soon since I don't see the return on investment of my time here.

**Comment by 1582343047** [comment]
Hello, I have a qustion of EQ. I bought new&nbsp;
headphone.but i can't find how to make it to Harman curve. I find it&nbsp;Frequency Response Curve. May you help me change it to&nbsp;Harman curve?&nbsp;the type is&nbsp;Edifier w820nb.
