### ISSUE TITLE
zero.csv used with Oratory1990's presets.

### ISSUE THREAD

**Issue by maxemillianian** [jaakkopasanen/AutoEq#284]
I am taking one of Oratory1990's eq presets and running it through AutoEq to produce a matching graphiceq.txt file for use with wavelet. 

In the past--for a set of IEMs--I have used AutoEq with --input_dir="~\zero" and a compensation file containing data parsed from Oratory's charts using WebPlotDigitizer to generate a graphiceq.txt which quite closely matches Oratory's preset.

I attempted yesterday to do the same with a pair of Sennheiser HD 25-II headphones; the output does not match the original. 

I'm not sure if this is my error or an algorithm issue or if it's something else entirely; perhaps it is related to the large +10dB gain at 40Hz? 

Anyway here are some screenshots which describe my process and outcome; any help is much appreciated!

Oratory's preset:
![image](https://user-images.githubusercontent.com/22266723/112564596-882ce380-8e16-11eb-990f-2629ceff5629.png)

Oratory's EQ Curve: 
![image](https://user-images.githubusercontent.com/22266723/112563768-f5d81000-8e14-11eb-9476-572026003521.png)

Oratory's EQ Curve as graphed by Peace EQ: 
![image](https://user-images.githubusercontent.com/22266723/112563816-0be5d080-8e15-11eb-9a78-305e3697cfe3.png)

Oratory's EQ Curve as parsed by WebPlotDigitizer: 
![image](https://user-images.githubusercontent.com/22266723/112563849-1dc77380-8e15-11eb-9574-931c9d30be45.png)

WebPlotDigitizer settings:
![image](https://user-images.githubusercontent.com/22266723/112563857-21f39100-8e15-11eb-8141-58c98a3fea7b.png)
![image](https://user-images.githubusercontent.com/22266723/112563863-2455eb00-8e15-11eb-9982-b1329939e50f.png)

The resulting parametric eq profile as graphed by Peace EQ: 
![image](https://user-images.githubusercontent.com/22266723/112563890-2cae2600-8e15-11eb-94f8-75fc248138df.png)

WebPlotDigitizer data:
[hd25 oratory parsed.txt](https://github.com/jaakkopasanen/AutoEq/files/6208844/hd25.oratory.parsed.txt)

The AutoEq .png: 
![zero](https://user-images.githubusercontent.com/22266723/112563965-50716c00-8e15-11eb-8cb5-0bb6d271b023.png)

The AutoEq EQs: 
[zero GraphicEQ.txt](https://github.com/jaakkopasanen/AutoEq/files/6208761/zero.GraphicEQ.txt)
[zero ParametricEQ.txt](https://github.com/jaakkopasanen/AutoEq/files/6208762/zero.ParametricEQ.txt)

Thanks for all your work!

**Comment by maxemillianian** [comment]
Ah, I've just realized there's a max_gain setting. I think this might solve my "issue."

**Comment by maxemillianian** [comment]
Okay so now the bass area matches Oratory's preset more closely, but the mid and treble is elevated somewhat.

Any ideas?

Oratory's:
![image](https://user-images.githubusercontent.com/22266723/112565865-e78bf300-8e18-11eb-9b04-d57dfdd4a5dd.png)

AutoEq --max_gain=12:
![image](https://user-images.githubusercontent.com/22266723/112565881-efe42e00-8e18-11eb-8331-670cbbbee9ad.png)

**Comment by jaakkopasanen** [comment]
The shape is quite similar and that's what matters. If you add -3 dB preamp to the AutoEq result it's going to look very similar to the oratory1990 one.

**Comment by maxemillianian** [comment]
Okay sure, that makes sense. So for use with Wavelet, where there's no need to volume match and compare, the result is effectively the same?

**Comment by jaakkopasanen** [comment]
The graphic eq used by Wavelet has preamp built in and there's no way of adjusting that manually.

**Comment by maxemillianian** [comment]
Right. Okay thanks for your help!

**Comment by jaakkopasanen** [comment]
I may have originally overlooked a bit what your trying to achieve here. Do I now understand right that you're trying to achieve the exact same frequency response as oratory1990's parametric eq settings produce with EqualizerAPO's GraphicEq.txt? If that's the case then AutoEq definitely should be able to do that without a problem and with 100% accuracy.

Was the AutoEq curve in Peace with GraphicEq or ParametricEq? What exact command did you use to produce the results?

I know at least that for this purpose you should set `--treble_f_lower=22000 --treble_f_upper=22050` to ensure the high frequencies are not smoothed.

**Comment by maxemillianian** [comment]
_"Do I now understand right that you're trying to achieve the exact same frequency response as oratory1990's parametric eq settings produce with EqualizerAPO's GraphicEq.txt?"_

Yea that. Or really to convert any PeaceEQ profile to GraphicEQ.txt through parsing of data from PeaceEQ's graph.

My command was:

--input_dir="D:\AutoEq-master\my_data\zero" --output_dir="D:\AutoEq-master\my_results\hd25" --compensation="D:\AutoEq-master\oratory_parsed\hd25_parsed\hd25.csv" --equalize --parametric_eq

**Comment by jaakkopasanen** [comment]
@maxemillianian are you still interested in this?

It looks like you're taking the parametric eq settings from AutoEq and importing them to Peace (which doesn't work with anything else as far as I know). Parametric eq and graphic eq (EqualizerAPO GraphicEq) will produce slightly different equalizer frequency response and therefore you cannot use Peace's graph tool to check the GraphicEq frequency response.

I just create a script for turning parametric equalizers into EqualizerAPO's GraphicEQ. Update to the latest AutoEq master and run this to turn oratory1990's parametric eq presets for [Sennheiser HD25-1 II (bad seal)](https://www.dropbox.com/s/1qkfhixi2hc2byy/Sennheiser%20HD25-1%20II%20%28bad%20seal%29.pdf?dl=0) into GraphicEQ.
```
python research/peq2geq.py --fc 105 110 240 1100 2900 3800 5000 5200 6700 8400 --gain 5.5 -2.2 -2.8 -1.5 -5.7 -1.0 7.0 -2.6 -3.0 -9.1 --q 0.71 2.0 1.0 3.0 0.9 7.0 1.0 5.0 5.0 2.5 --type LS PK PK PK PK PK PK PK PK PK --normalize
```
or save configure the parametric equalizer in EqualizerAPO and do
```
python research/peq2geq.py --file "C:\Program Files\EqualizerAPO\config\config.txt" --normalize
```
More details about the arguments:
```
python research/peq2geq.py --help
```

**Comment by maxemillianian** [comment]
Hi!

Yes I am still interested; I'll update AutoEq and give it a try.

Thanks!

**Comment by jaakkopasanen** [comment]
@maxemillianian have your tried what I suggested? Is the issue solved for you or do you still experience some problems?

**Comment by dux1976** [comment]
Well I tried it and succeeded. Nice work, thank you very much!

What I don't understand is this:
frequency_response.py        Script to turn parametric equalizer into EqualizerAPO's GraphicEQ. Re…

I understand what peq2geq is for, but what is frequency_response.py for?
