### ISSUE TITLE
You should differentiate between versions of the HD280 Pro

### ISSUE THREAD

**Issue by PierBover** [jaakkopasanen/AutoEq#287]
Right now in the results, there are 4 measurements for the Sennheiser HD280.

The thing is that in 2019 or so, Sennheiser released v2 which has a different frequency response than v1. The physical product changed too.

It would be great if this was taken into account.

For example, I know for a fact the [Rtings measurements](https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Sennheiser%20HD%20280%20Pro) were done on v1. You can see in their pictures it's the old model.

I'm confident the [InnerFidelity measurements](https://github.com/jaakkopasanen/AutoEq/tree/master/results/innerfidelity/innerfidelity_harman_over-ear_2018/Sennheiser%20HD%20280%20Pro) were made before v2 was released. IIRC InnerFidelity shut down in 2019 or so?

Not sure about the [Headphone.com measurements](https://github.com/jaakkopasanen/AutoEq/tree/master/results/headphonecom/headphonecom_harman_over-ear_2018/Sennheiser%20HD%20280%20Pro) or the [Reference Audio Analyzer, HDM-X](https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Sennheiser%20HD%20280%20Pro) but I can investigate.

**Comment by jaakkopasanen** [comment]
Headphone.com measurements are very old so that one is definitely the v1 model. [Reference Audio Analyzer](https://reference-audio-analyzer.pro/en/title-report.php?id=885#gsc.tab=0) picture looks the same as Rtings so I'd assume it's the same v1 model.

**Comment by PierBover** [comment]
I think it would be safe to just mark all measurements as v1.

**Comment by jaakkopasanen** [comment]
I renamed them all as Sennheiser HD 280 Pro pre-2019.

Thanks for opening the issue!
