### ISSUE TITLE
Links on results pages are broken

### ISSUE THREAD

**Issue by wcsherrod** [jaakkopasanen/AutoEq#288]
All links on the results pages are broken. The results directory in the URL is duplicated accidentally.

Example:

The link for the Sennheiser HD 598 on the [oratory1990 results page](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990) points to https://github.com/jaakkopasanen/AutoEq/blob/master/results/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20598

The correct link should only contain 'results' once: https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20598

This seems to be due to the most recent change as the links were fine a week ago.

**Comment by jaakkopasanen** [comment]
Good catch! Thanks a lot for reporting. I'll fix this asap.

**Comment by jaakkopasanen** [comment]
Fixed!
