### ISSUE TITLE
LCD-X and LCD-XC 2021 Revision Measurements

### ISSUE THREAD

**Issue by HolyBiscuits** [jaakkopasanen/AutoEq#291]
Based on [this](https://www.head-fi.org/threads/lcd-x-and-xc-update.956949/) head-fi post, it looks like the LCD-X and LCD-XC's have had their drivers revised. Do the EQs for these new models exist, and if not, will the EQ's for these revised headphones be labeled separately from the old models?

**Comment by jaakkopasanen** [comment]
The LCD-X and LCD-XC results are older than the post in Head-Fi so I assume they are the old versions. oratory1990, Rtings and Crinacle have tendency to note these kinds of changes so the chances are that they will be labelled separately from the old ones if they ever end up being measured by these sources.
