### ISSUE TITLE
hesuvi.zip contains duplicate filenames

### ISSUE THREAD

**Issue by ThreeDeeJay** [jaakkopasanen/AutoEq#292]
**Describe the bug**
hesuvi.zip contains duplicate filenames, which on Windows causes extraction to ask which version of the file to keep, since multiple files have different versions with different capitalization [like this one](https://i.imgur.com/3y4CfGu.png).

**To Reproduce**
[Download](https://github.com/jaakkopasanen/AutoEq/raw/master/results/hesuvi.zip) and extract hesuvi.zip (tested with 7-Zip and WinRAR)

**Expected behavior**
Extract without confirming duplicates.

**Files**
https://github.com/jaakkopasanen/AutoEq/blob/master/results/hesuvi.zip

**System:**
 - OS: Windows 10
 - Version: latest ([e42f59f](https://github.com/jaakkopasanen/AutoEq/commit/e42f59fdca6c1f8a40ce49cdcb05d88da4f9a8f0))

**Additional context**
I know I can probably look up each file's last modified date by commit, but it'd be nice to just keep the best/more recent one and avoid this issue.

**Comment by jaakkopasanen** [comment]
Thanks for reporting. I completely missed this one. Windows' file name capitalization surely is a pain.

**Comment by ThreeDeeJay** [comment]
@jaakkopasanen Just a friendly reminder, I just noticed there's some new duplicates using slightly different capitalization in the filenames 😅
- 64 audio u18t (m20 apex module)
- audio-technica ath-anc7b
- beyerdynamic dt 770 pro (32 ohm)
- beyerdynamic dt 880 (600 ohm)
- tanchjim hana 2021

Converting the [results list](https://github.com/jaakkopasanen/AutoEq/tree/master/results) to lower case then running it through a duplicate detector can provide with a list of files that'd prompt the user to choose how to deal with each dupe
![ShareX_KDnigWWwFW](https://github.com/jaakkopasanen/AutoEq/assets/71472458/64b37f79-057d-474e-b0ee-6c09076ae8a4)

Maybe something [like this](https://7zip.bugaco.com/7zip/MANUAL/cmdline/switches/ssc.htm) would help, though I'm guessing additional logic would need to be put in place so it knows which file to keep (or rename?)
