### ISSUE TITLE
Consider linking to this Apple Music equalizer "editor"

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#298]
Hi,

EQing macos and ios is rather a pita. However, [here's](https://github.com/kivikakk/music_auto_eq) a nice little tool that let's you manipulate the eq of Apple music precisely according to the results generated by autoeq. Perhaps nice to mention this is README.md?

Unfortunately though, Apple Music doesn't sync the settings to iOS, so there's no solution to manipulate the settings there.

Regards,
Alex

**Comment by jaakkopasanen** [comment]
I don't much care for these kinds of external things and I've avoided recommending them. I intend to keep the list of solutions in usage instructions somewhat brief.
