### ISSUE TITLE
Allow generating preference score table given arbitrary reference curve (what headphone sounds closest to this one?)

### ISSUE THREAD

**Issue by assafmuller** [jaakkopasanen/AutoEq#299]
**Is your feature request related to a problem? Please describe.**
Given headphone X, what other headphones sound similar to it, in a ranked table, similar to [1]?

So, instead of ranking against the harman curve, you'd allow ranking against a measurement of another headphone. This could be used, for example, to find a cheaper alternate to an expensive headphone you liked, or to find a closed back that sounds similar to an open back you like, etc.

[1] https://github.com/jaakkopasanen/AutoEq/blob/master/results/RANKING.md

**Describe the solution you'd like**
Re-use the preference score code, but allow specifying an arbitrary measurement as the reference, instead of only comparing against the Harman curve.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jaakkopasanen** [comment]
I'm not sure if I'm too hot on making this a feature. However you can do this already by changing the target curve paths in `results/update_indexes.py` function `write_ranking_table()` https://github.com/jaakkopasanen/AutoEq/blob/master/results/update_indexes.py#L309. Change these paths
```
harman_inear = os.path.join(ROOT_DIR, 'compensation', 'harman_in-ear_2019v2.csv')
harman_inear = FrequencyResponse.read_from_csv(harman_inear)
harman_overear = os.path.join(ROOT_DIR, 'compensation', 'harman_over-ear_2018.csv')
harman_overear = FrequencyResponse.read_from_csv(harman_overear)
```
