### ISSUE TITLE
Create parametric EQ with more bands. Any benefit?

### ISSUE THREAD

**Issue by Ritte88** [jaakkopasanen/AutoEq#30]
If I generate a 30-band parametric EQ, would it bring me closer to the graphical EQ?

**Comment by jaakkopasanen** [comment]
Most probably it would. Might or might not be audible difference. Some headphones already have 10 band parametric eq which is very close to graphic eq. You can try it out and compare the graphs.

**Comment by Ritte88** [comment]
Thanks @jaakkopasanen. Is the graphical EQ the one called "Equalization Smoothed" in your plots?

**Comment by jaakkopasanen** [comment]
There is no "Equalization Smoothed". There is "Equalization" which is the GraphicEq or at least close. Actually GraphicEq doesn't match the equalization curve perfectly because it has limited frequency resolution. I wouldn't spend too much time worrying over 0.1 dB differences.
