### ISSUE TITLE
issue when installing on windows

### ISSUE THREAD

**Issue by leiker535** [jaakkopasanen/AutoEq#300]
Hello, I'm currently unable to install the autoeq when following the install guide for windows. WHen getting to the install requirements command it shows a error message:

PS F:\Bibliotecas Windows\Music\AutoEQ\AutoEq> py -m pip install -U -r requirements.txt
Collecting Pillow~=7.2.0
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
Collecting matplotlib~=3.3.3
  Using cached matplotlib-3.3.4-cp39-cp39-win_amd64.whl (8.5 MB)
Collecting pandas~=1.2.0
  Using cached pandas-1.2.4-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting scipy~=1.5.4
  Using cached scipy-1.5.4-cp39-cp39-win_amd64.whl (31.4 MB)
Collecting numpy~=1.19.5
  Using cached numpy-1.19.5-cp39-cp39-win_amd64.whl (13.3 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
ERROR: No matching distribution found for tensorflow~=2.4.0

Did I do something wrong?

**System:**
 - OS: [e.g. Windows 10]

**Additional context**
Im using powershell because I moved the AutoEQ to another drive and my windows is defaulted to it. Hope it isnt a problem;

**Comment by jaakkopasanen** [comment]
I'm guessing you are using some other version of Python 3.8. Currently only that one is supported.

**Comment by leiker535** [comment]
It's working so far after I downgraded to 3.8.x. Word of warning though, the command "python" has no reference in windows in the form it is in the guide, I had to abbreviate to "py" in order to cmd/powershell to correctly perform it. Minor nuisance but worthy of attention.
