### ISSUE TITLE
good and easy EQ in macOS

### ISSUE THREAD

**Issue by Ralf-Brauchler** [jaakkopasanen/AutoEq#302]
Hi there,
I just want to contribute that in macOS there is a very good, easy and cheap possibility to use parametric EQ: Combine Blackhole with Garageband. In Garageband you have a very nice parametric EQ with (only) 6 Bands, but you can use up to 4 of them on top of each other.
<img width="1623" alt="Bildschirmfoto 2021-05-31 um 15 44 45" src="https://user-images.githubusercontent.com/22255903/120202645-21b5ae80-c227-11eb-9be9-a07345e95bb7.png">
If you need more details, I would be happy to help.
Greetings 
   Ralf

**Comment by jaakkopasanen** [comment]
There are multiple of these already documented in the install instructions. I'll leave this one out.
