### ISSUE TITLE
EqualizerAPO

### ISSUE THREAD

**Issue by githubnavigator** [jaakkopasanen/AutoEq#303]
Is there a trusted GitHub repository for the Equalizer APO referenced in this project? I realize there's a SourceForge repository for Equalizer APO but don't know if it's still maintained. The last release was in 2019. I see there's a SourceForge repository for Peace that was updated fairly recently.

**Comment by jaakkopasanen** [comment]
SourceForge is the place to get it. That's the official one. The software is complete as far as I understand and therefore hasn't had any updates for a while.
