### ISSUE TITLE
Question on Fixed Band Equalizer

### ISSUE THREAD

**Issue by brilogan** [jaakkopasanen/AutoEq#306]
I am using a DAP that includes a fixed band equalizer with 20 frequencies that do not correspond to the 10 frequencies provided for fixed band equalization.  So, I downloaded the graphs for my particular headphones and plotted out the equalizer settings for the frequencies in my DAP using the fixed band equalizer curves.  I also plotted equalizer setting for the frequencies in my DAP using the error smoothed curve, multiplying by -1, of course.  My question is, for a 20 band graphical equalizer, which is the better and more accurate curve to plot out my equalizer settings?  Fixed band equalizer curve or error smoothed curve?  Thank you!

**Comment by jaakkopasanen** [comment]
You can have AutoEq generate the filter parameters for you. Simply set the center frequencies with `--fc` and set `--q=2.871`

**Comment by brilogan** [comment]
Thank you; I will give it a whirl.

________________________________
