### ISSUE TITLE
EQ measurements for TWS bluetooth adapters/amplifiers like Fiio UTWS3

### ISSUE THREAD

**Issue by frosty5689** [jaakkopasanen/AutoEq#307]
Hello,

I am curious what AutoEQ profile if any should be used when it comes to something like the Fiio UTWS3 (https://www.fiio.com/utws3) which allows any wired IEM with MMCX to be plugged into it and act as a bluetooth TWS earbud. The device supports up to aptX. If I use the AutoEQ profile for the actual wired IEM plugged into it. Would it be inaccurate as it was measured with the IEM plugged in physically? I am currently using Sennheiser IE 8 with UTWS3.

Thanks

**Comment by jaakkopasanen** [comment]
It's quite safe to assume all modern amps and DACs have flat frequency response and therefore don't affect the needed EQ profile. Just use the IEM's profile as is.

**Comment by frosty5689** [comment]
Makes sense. I tried the IE 8 AutoEq and it toned down the Senneheiser signature boosted bass and made it flat, what you'd expect.
