### ISSUE TITLE
Duplicated and missing result of Samsung Galaxy Buds+

### ISSUE THREAD

**Issue by Long-FA** [jaakkopasanen/AutoEq#309]
The Crinacle result of Samsung Galaxy Buds+ was removed in commit 9928b8e59c51b23abc433111b019a7c67efb0e89, I would like to know if this is intentional or not. Said commit also added Rtings Samsung Galaxy Buds+ result, which is a duplicate of the existing Samsung Rtings Galaxy Buds Plus result (understandable because scripts are not smart). Please review and manually restore or remove these results.

**Comment by jaakkopasanen** [comment]
Looks like the data has disappeared from Crinacle's Google Drive folder. Will see if Crinacle would add that back in.

I removed the duplicate Rtings Buds+ entry.

**Comment by jaakkopasanen** [comment]
Crinacle added the measurements to Drive and I updated it to AutoEq: https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Plus
