### ISSUE TITLE
Question about oratory1990 parser

### ISSUE THREAD

**Issue by gcv** [jaakkopasanen/AutoEq#31]
I've been looking into some oratory1990 measurements, and have found an offset between the graphs I'm looking at and the parsed CSV data. For example, looking at Campfire Audio Andromeda measurement, the raw values should be approximately these:

20Hz: -9dB
30Hz: -7.8dB
100Hz: +3dB
1kHz: -1.4dB

The CSV for the measurements has this instead:

20,2.45
30,3.78
100,4.49
1001,0.00

But when I look at rendered raw response charts, their shapes look pretty close to the ones oratory1990 published. Looks like things are normalized around 1kHz somehow? What is happening here?

**Comment by jaakkopasanen** [comment]
Did you look at the measurement data here: https://www.dropbox.com/s/ght2hps9taeldfd/Campfire%20Audio%20Andromeda.pdf?dl=0. If you did I don't quite understand how you read the graph to get those values. Did you look at the red curve and typoed sign for 1kHz?

Orange is the raw measurement data and red is Harman target compensated ie. deviation from harman target. Raw data in this project is the raw microphone data so orange curve. AutoEQ raw data is indeed normalized by 1kHz. That's the common way of doing it to produce comparable results but there are others as well.

**Comment by gcv** [comment]
You're right. I misread the graph. With the 1kHz normalization, the numbers in the CSV make sense.
