### ISSUE TITLE
Consider naming the Logitech G635 to Logitech G635/G633s

### ISSUE THREAD

**Issue by jamieernest** [jaakkopasanen/AutoEq#310]
As the Logitech G635 is the same in specs as the G633s but the G635 is the American/European model and the G633s is the Asian model I believe naming them together should be sensible, as to G633s owners can find it quite confusing when the headphone has a profile but not in the name you expected. Thank you!

**Comment by jaakkopasanen** [comment]
Headphone names are indeed messy when the manufactureres don't sometimes know themselves what they are called. However in this case I think I'll prefer simplicity and not change the name. I haven't named any of the others with multiple names either so I'll keep the policy.
