### ISSUE TITLE
Support for the Pioneer DJ HDJ-X5 Headphones

### ISSUE THREAD

**Issue by ClassifiedDuck** [jaakkopasanen/AutoEq#312]
**Is your feature request related to a problem? Please describe.**

No problem!

**Describe the solution you'd like**

I am a DJ and at the moment I use the Pioneer DJ HDJ-X5's. I would really appreciate the support for these headphones!

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jamieernest** [comment]
I'm pretty sure you are going to get ignored. The everything else template says: ```

**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

```
