### ISSUE TITLE
ViPER DDC EQ profiles for Viper4Android/JamesDSP

### ISSUE THREAD

**Issue by ThreeDeeJay** [jaakkopasanen/AutoEq#315]
**Is your feature request related to a problem? Please describe.**
Unfortunately, Wavelet [isn't compatible](https://github.com/Pittvandewitt/Wavelet/issues/3) with arguably the best Android custom ROM out there (LineageOS), so the best alternatives are [Viper4Android](https://forum.xda-developers.com/t/app-fix-100-working-viper4android-for-android-11-devices.4213647/) and JamesDSP. However, they aren't compatible with AutoEQ profiles out of the box, but require manual conversion.

**Describe the solution you'd like**
To make AutoEQ profiles compatible with Viper4Android/JamesDSP, luckily there's a tool called [DDCToolbox](https://github.com/ThePBone/DDCToolbox) that can import *ParametricEQ.txt and convert them to VDC (V4A/JDSP EQ file format). Perhaps you guys could consider looking into the code to generate VDC files for V4A/JDSP users as EQs are updated, but for now it's probably good enough to add a reference to DDCToolbox to the V4A/JDSP sections.

**Describe alternatives you've considered**
Wavelet (broken in LineageOS), built-in AudioFX app (lacks AutoEQ compatibility)

**Additional context**
Another reason to use V4A/JDSP is completely system-wide EQ, V4A/JDSP-exclusive features like convolution-based [crossfeed/HRTF](https://i.imgur.com/9eeebbM.mp4)
Note: HeSuVi HRIRs can be used by removing all but the first 4 channels: front left and front right, and swapping 3 and 4; or just keeping channels 1 and 2, and duplicating 2 into 3 and 1 into 4.

**Comment by jaakkopasanen** [comment]
This issue doesn't seem to be requesting anything or describing a bug. Viper4Android is already mentioned in the usage instructions so I'm closing the issue.

**Comment by ThreeDeeJay** [comment]
Fair enough, I was basically requesting AutoEQ VDC files but I gotta admit V4A/JSDP seems pretty niche so I figured it'd probably be more practical to just mention DDCToolbox in the instructions since it doesn't really specify _how_ to import AutoEQ profiles, at least without relying on convolution or manually setting bands.
Either way, hopefully anyone googling the subject comes across this, I have no issue converting files myself but just wanted to share this neat tool. 👍

**Comment by devnoname120** [comment]
@ThreeDeeJay You may be interested in this comment from the maintainer of the reverse engineered ViPER4Android who says that AutoEQ will be supported: https://github.com/AndroidAudioMods/ViPER4Android/issues/36#issuecomment-1556323943

**Comment by ThreeDeeJay** [comment]
@devnoname120 Thanks for the heads up! I didn't know about that -RE version
Any idea if convolver implementation is planned anytime soon? I like to use a custom stereo-to-surround upmix HRTF/HRIR convolver to expand/externalize music, which is so good that it's kind of a dealbreaker for me hahah 😅 
I don't have a recording of the upmixer, but here's one using some HeSuVi HRIRs converted to V4A convolver: https://i.imgur.com/9eeebbM.mp4
> Just needed to open the hesuvi WAV file in Audacity, then delete all but the first 2 HRIR channels, then duplicate the 2nd into the 3rd, and the 1st into the 4th, save as 32bit float WAV into the Kernel folder and boom, virtualized stereo.

**Comment by devnoname120** [comment]
@ThreeDeeJay I have no idea... I suggest you to ask the repo's owner directly.
