### ISSUE TITLE
Request a headset?

### ISSUE THREAD

**Issue by grayshirk** [jaakkopasanen/AutoEq#317]
Hi, I was wondering if it would be possible to request presets to be made for the MAONO AU-MH601

Or rather where the correct place to request this would be.

**Comment by jaakkopasanen** [comment]
AutoEq only has results for measurements by a few supported sources. There's a lot of work adding a support for a source so it's not feasible to support measurements outside of these. Results page has some pointers to doing this yourself if you find frequency response measurements but obviously I cannot guarantee the quality of the results.
