### ISSUE TITLE
[Feature Request] Option to disable automatic volume normalization of measurement and compensation target

### ISSUE THREAD

**Issue by staticV3** [jaakkopasanen/AutoEq#318]
**Is your feature request related to a problem? Please describe.**
When using the AutoEQ python script, I sometimes want it to simply use the alignment encoded into the CSV files. 
Instead, the script will always volume normalize the measurement to the target, even if that results in unnecessary, extra filters.

**Describe the solution you'd like**
I'd like to have a command line argument that disables this function.

**Comment by staticV3** [comment]
On second thought, it might've been user error. I'll close this issue until I'm certain.

**Comment by jaakkopasanen** [comment]
Hi. Are you talking about parametric equalizer settings?

**Comment by staticV3** [comment]
Hi, when using the AutoEQ python script, it will automatically align measurement curve and target curve on the y-axis to reduce the deviation between them.
After that, it will start building EQ parameters.
I would like to disable this volume-matching.

**Comment by jaakkopasanen** [comment]
The absolute level of the curves don't really matter when it comes to producing eq settings. Unless you don't have preamp in your eq software/device and would like to ensure the equalizer frequency response is all negative gain. That's a very rare case and not something I consider worth the effort to produce this kind of feature.
