### ISSUE TITLE
EQ for AKG K271 Studio (MK I)

### ISSUE THREAD

**Issue by jargonfilter** [jaakkopasanen/AutoEq#32]
Any chance we'll see an EQ for that model? The Mark II is already there but they have a different frequency response than the AKG K271 Studio Mark I headphones.

**Comment by jaakkopasanen** [comment]
If this is an older model then most probably not. People doing measurements tend to measure new headphones and since in this case the newer model is already covered the chances for somebody measuring the old one are slim. They'll appear in the results if that happens but don't hold your breath.
