### ISSUE TITLE
Sony MDR-EX150AP

### ISSUE THREAD

**Issue by iamthelara** [jaakkopasanen/AutoEq#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hey, please add Parametric settings for SONY MDR-EX150AP.
Thank you.

**Comment by jaakkopasanen** [comment]
Sorry but I can't. Only the models which have been measured by one of the supported sources are available.
