### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0 

### ISSUE THREAD

**Issue by ModernCRTGamer** [jaakkopasanen/AutoEq#324]
After running -m pip install -U -r requirements.txt  I get said tensorflow error
I tracked down tensorflow and installed that with pip install tensorflow after verifying it on their website. Still getting the error. 
When running python autoeq.py --help I get:

Traceback (most recent call last):
  File "C:\Users\jhutc\AutoEq\autoeq.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'

I checked the closed bug reports and a user had a similar error back in 2020. I've made sure to manually install libsndfile beforehand and I'm still getting that error. Unsure if the tensorflow requirement check error and the soundfile error are related or not. 

OS: Windows 10 Latest 7/27/21

![2021-07-28 (2)](https://user-images.githubusercontent.com/53107167/127370672-3eaab14f-116d-4093-a28b-25d26f77607d.png)

**Comment by Takifan** [comment]
Same issue with me. Got both of these errors.
For tensorflow, I've installed version 2.5.0.

Though I haven't installed libsndfile beforehand, I've just done so. Error still persists.

**Comment by jaakkopasanen** [comment]
Looks like you are using Python version 3.9 while only 3.8 is supported. Tensorflow is very picky about their distributions.

**Comment by ModernCRTGamer** [comment]
Going back and grabbing 3.8 instead of 3.9 solved the issue, thank you 😅
