### ISSUE TITLE
[Feature Request] Custom bands Graphic EQ

### ISSUE THREAD

**Issue by Suznyan** [jaakkopasanen/AutoEq#325]
**Is your feature request related to a problem? Please describe.**
Most equlizer on smartphone is graphicEQ. Especially those on ios. Autoeq only generates graphicEQ with the same 127 bands

**Describe the solution you'd like**
A similar option for generating custom bands graphicEQ like fixed band eq

**Comment by jaakkopasanen** [comment]
This is already possible. See options --fc and --q

**Comment by Suznyan** [comment]
Yes but I don't think it is the same. I just can't get the q value right
![image](https://user-images.githubusercontent.com/75526109/127726660-c3772dba-3346-419b-ba45-544810e5ba0a.png)
while with the graphic eq filter it is
![image](https://user-images.githubusercontent.com/75526109/127726709-1056e64c-87a7-4f31-bd9b-6765be2242d1.png)
which seem more accurate to this
![47a7e8060e21f97fa030](https://user-images.githubusercontent.com/75526109/127726777-f7818385-d0fb-4bfa-a268-f6b399b7c4a8.jpg)

**Comment by jaakkopasanen** [comment]
Looks like you have the Q value wrong. When you have 31 bands, you can calculate the bandwidth with `log2(31.5/25)` or `log(31.5/25) / log(2)` which gives `0.333`. Turn this into Q value with [Sengpiel's calculator](http://www.sengpielaudio.com/calculator-bandwidth.htm) and you'll get `4.32`.

**Comment by Suznyan** [comment]
Thank you. Guess I was just dumb
