### ISSUE TITLE
Questions on the difference between sound signature and compensation

### ISSUE THREAD

**Issue by yikai-wu** [jaakkopasanen/AutoEq#326]

**Comment by yikai-wu** [comment]
I read the instructions but am still unsure about what sound signature do. May I have a bit more explanations? What are the difference between using one headphone as sound signature and using its measurement directly as compensation? What if the compensation used for the results is different from the compensation used when applying sound signature of that headphone?

**Comment by jaakkopasanen** [comment]
If the two headphones have been measured with the same measurement system, you could use the measurement of one as the target curve for another. Sound signature is needed when the measurements have been made with different rigs. Sound signature option makes the process consistent across the board so I chose not to mention using one measurement as target for another headphone in the instructions.

**Comment by yikai-wu** [comment]
Thank you very much for your explanation.
