### ISSUE TITLE
Do we need to apply pre-amp when using convolution eq on Mac?

### ISSUE THREAD

**Issue by yikai-wu** [jaakkopasanen/AutoEq#327]
I am using LAConvolver plugin with AU Hosting on Mac OS X 10.14. When I apply parametric eq with pre-amp as required, the perceived volume always decreases. The perceived volume does not seem to change if I do not use pre-amp. From the instructions, it seems that the pre-amp is already included in the WAV file. However, when I use convolution eq on LAConvolver, the perceived volume does not decrease. Is it because I understood the instructions wrongs and I still need to apply pre-amps?

**Comment by jaakkopasanen** [comment]
The calculated FIR filters (the WAV file) contains preamp so additional preamp should not be needed. However I cannot guarantee that different EQ softwares don't do something shady like automatic gain normalization. If volume is not reduced at all, chances are that the software is doing something. If you you hear clipping, add preamp until you don't hear it clipping anymore or just pick a highest gain value from the CSV file and invert it.

**Comment by yikai-wu** [comment]
Thank you very much for your explanation. I just realize that I simply need to set the compensation to None.
PS: the problem still exists for Pulse from Lancaster Audio though, which seems to be the only convolution eq plug-in for OS X 10.15+.
