### ISSUE TITLE
Get different results using convolution eq on Mac with LAConvolver and  Pulse from Lancaster Audio

### ISSUE THREAD

**Issue by yikai-wu** [jaakkopasanen/AutoEq#328]
It seems that Pulse from Lancaster Audio is a free convolution eq on Mac (and also on Windows) which still have maintenance and can be used on OS X 10.15+. I have tried both LAConvolver and Pulse using AU Hosting with the same FIR wav file. However, they change the sound differently. Also, there is abnormal high frequency sound from Pulse which does not appear using LAConvolver.

I just would like to know if anyone encountered the same problem. I would be very helpful if anyone can try this on their side. Also, if we can make the convolution eq work on Mac, the problem on AUNBasspass can be less of a worry.

**Comment by jaakkopasanen** [comment]
It's sometimes difficult with all the different eq software out there. The manufacturers don't give out implementation details nor could (or should) I list all of them in the usage instructions.

I'll close this issue as there isn't anything to do on AutoEq's side.
