### ISSUE TITLE
[Request] ZMF Auteur

### ISSUE THREAD

**Issue by jbar2797** [jaakkopasanen/AutoEq#33]
**Here are measurements**

https://www.superbestaudiofriends.org/index.php?threads/zmf-auteur-impressions-and-measurements.5338/#post-178987

**Review**

https://headfonics.com/2018/02/zmf-auteur-review/

**Comment by jaakkopasanen** [comment]
You can create the eq settings yourself: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)
