### ISSUE TITLE
Missing measured headphones

### ISSUE THREAD

**Issue by Lertennator** [jaakkopasanen/AutoEq#330]
Hi, I'm looking for Eq settings for my Austrian Audio Hi-X65, wich Oratory1990 HAS measured, however I can only find the x55 in the results folder...
Since they have been measured and are missing, I'm asking when they will be added in.
Screenshot taken from oratory as proof
![Screenshot (2)](https://user-images.githubusercontent.com/79855455/127922749-b858f9a6-4c75-422f-9b12-91bd08e76690.png)

**Comment by jaakkopasanen** [comment]
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Austrian%20Audio%20Hi-X55
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Austrian%20Audio%20Hi-X65
