### ISSUE TITLE
Recently update and any linecode doesnt work

### ISSUE THREAD

**Issue by angelooo18** [jaakkopasanen/AutoEq#331]
I recently upgraded autoeq to the latest version until the publication of this problem, since then I am unable to process any equalization results, the line I have always used with the program is as follows:

python autoeq.py --input_dir="my_data/KZ ZSN PRO X RAW/" --output_dir="my_results/64 Audio/U12T Crinacle" --standardize_input --compensation="Targets/64 Audio/U12T Crinacle. csv" --equalize --parametric_eq --max_filters=100+100 --convolution_eq --fs=44100,48000 --max_gain=10 --treble_f_lower=9000 --treble_f_upper=10000

Previously this line worked perfectly, but since the update I only get this result, regardless of the line of code:

(venv) C:\Windows\System32\AutoEq>python autoeq.py --input_dir="my_data/KZ ZSN PRO X RAW/" --output_dir="my_results/64 Audio/U12T Crinacle" --standardize_input --compensation="Targets/64 Audio/U12T Crinacle. csv" --equalize --parametric_eq --max_filters=100+100 --convolution_eq --fs=44100,48000 --max_gain=10 --treble_f_lower=9000 --treble_f_upper=10000
Traceback (most recent call last):
File "autoeq.py", line 313, in <module>.
batch_processing(**cli_args())
File "autoeq.py", line 40, in batch_processing
compensation.center()
File "C:\Windows\System32\AutoEq\frequency_response.py", line 1002, in center
interpolator = InterpolatedUnivariateSpline(np.log10(equal_energy_fr.frequency), equal_energy_fr.raw, k=1)
File "C:\Windows\System32\AutoEq\venv\libriumsite-packages\scipy\interpolate\fitpack2.py", line 620, in __init__
x, y, w, bbox, self.ext = self.validate_input(x, y, w, bbox, k, None,
File "C:\Windows\System32\AutoEq\venv\lib\site-packages\scipy\interpolate\fitpack2.py", line 202, in validate_input
raise ValueError("x and y should have a same length")

--------------------------------------------------------------------------------

**Comment by jaakkopasanen** [comment]
Could you share all of the files used in this example so that I can reproduce? You can simply drag and drop them here.
