### ISSUE TITLE
equalization for studying

### ISSUE THREAD

**Issue by DavidSmolinski** [jaakkopasanen/AutoEq#334]
**Is your feature request related to a problem? Please describe.**
It would be useful to have EQ settings for understanding speech at high speeds.

**Describe the solution you'd like**
I was told that mid-centric is best for tutorial videos. I don't know when bass should roll off. I'm assuming 80 Hz.

Harman is too bass heavy. The best solution I have so far is to take mid forward headphones and only EQ the high frequencies.
oratory1990 has settings for this for some headphones. We can't do this with your settings because the filter bands might overlap.

**Describe alternatives you've considered**
I improved the SHP9500 by applying [filter bands 5-10 from oratory1990](https://www.dropbox.com/s/sc2wanrbrqe0qn7/Philips%20SHP9500.pdf?dl=0). His "EQ Curve
Individual Filters" graph showed that this group of higher frequency filters is independent of the lower frequency filters. It should sound the same up to 500 Hz. After that, it should be Harman.

**Comment by jaakkopasanen** [comment]
I believe what you're looking for is speech intelligibility. However this is not the focus of this project nor do I know how much can you affect that with eq after the recording and mixing has been done.
