### ISSUE TITLE
[Feature request] More detailed impact of eq parameters

### ISSUE THREAD

**Issue by mccarverone** [jaakkopasanen/AutoEq#335]
In the output .png it is not possible to estimate the real impact of the parametric eq filters because the "equalized" line is calculated from the "equalization" line which is definitely different from "parametric eq" line. In case of very few filters applied there are a lot of significant differences. Thanks

**Comment by jaakkopasanen** [comment]
The graphs also include "Parametric Eq" which is the thinner dark green line. This line is plotted only if the parametric equalizer settings have been produced. In the case of multiple parametric filter sets (such as the default 5 + 5), the curve is the frequency response of all the parametric filters and there is no curve for the smaller sets. This is a compromise for image readability.

**Comment by mccarverone** [comment]
My point is that generating a "Parametric Eq" that is derived exactly from the parametric filter set generated by AutoEQ according to user preference instead of always defaulting to a nearly perfect 5+5 would actually improve image readibility and would be a tad more intuitive from a user perspective.
I.e. if I choose `max_filters` different from 5+5 I would expect that the parametric eq line would reflect this choice by adhering less to the target compensation. Hope to have made myself clear.
Thank you for your time and work. Cheers

**Comment by mccarverone** [comment]
My point is that generating a "Equalized" curve that is derived exactly from the parametric filter set generated by AutoEQ according to user preference instead of always defaulting to a perfect equalization would be a tad more intuitive from a user perspective.
Instead when varying the `max_filters` parameter, while the "Parametric Eq" curve changes accordingly, the blue "Equalized" line is always the same.
Thank you for your time and work. Cheers

**Comment by jaakkopasanen** [comment]
Now I get it, you're talking about the frequency response after equalization. That is with the idea equalizer frequency response. There can only be one, once again due to the readability, and therefore it wouldn't be "correct" to use the parametric equalizer frequency response when calculating the equalized frequency response. There are fixed band eq and convolution eq as well.
