### ISSUE TITLE
Valco VMK20 equalizer settings from oratory1990

### ISSUE THREAD

**Issue by samulikarvinen** [jaakkopasanen/AutoEq#337]
[https://www.dropbox.com/s/au6r0nx8hsmw67m/Valco%20VMK20%20%28wireless%29.pdf?dl=0](url)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Valco%20VMK20
