### ISSUE TITLE
[Request] Samsung Galaxy Buds2

### ISSUE THREAD

**Issue by Generatoz** [jaakkopasanen/AutoEq#339]
Hello,

Could you add Crinacle's measurements of the Samsung Galaxy Buds2 please ?

https://crinacle.com/samsung-galaxy-buds2/

**Comment by jaakkopasanen** [comment]
Here you go: https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2
