### ISSUE TITLE
What mode to use in PulseEffects?

### ISSUE THREAD

**Issue by RustyRaptor** [jaakkopasanen/AutoEq#340]
The current documentation for pulseeffects addresses the Type (Bell) but nothing is mentioned of what mode to use. 

I wanna say its the APO filter but if it is then that means we need to update the doc to include that because its not set to APO by default. The reason i say APO is because according to this page 
https://lsp-plug.in/?page=manuals&section=para_equalizer_x16_stereo
it is the same as the one implemented in EqualizerAPO which is mentioned to be the one used as a reference in the docs.

**Comment by MalexTP** [comment]
you can use the parametric eq or the convolver file, i prefer the convolver

**Comment by jaakkopasanen** [comment]
Thanks a lot for the insights! I updated the description to mention that the APO mode should be used when using parametric eq.
