### ISSUE TITLE
[REQUEST] Earfun Free 2

### ISSUE THREAD

**Issue by dontobi** [jaakkopasanen/AutoEq#342]
Is your feature request related to a problem? Please describe.
I just got my Earfun Free 2's and am very pleased. Although there is an app called Wavelet which needs a Frequency response graph (actually an autoeq table) to improve the overall sound. I can't find that anywhere though. I just find the autoeq data for the Oluv Edition, the Free Pro or the Free (without Pro).

Describe the solution you'd like
AutoEq data for the Earfun Free 2's.

Describe alternatives you've considered
Other, similar headphones don't provide a satisfying result.

Additional context
I have already found a Frequency response graph for the earfun free 2 and created a CSV file from this graph.
[earfun_free_2.csv](https://github.com/jaakkopasanen/AutoEq/files/7177478/earfun_free_2.csv)
![EarFun-Free-2-FR-measurement](https://user-images.githubusercontent.com/19261667/133608272-9bbaf0ff-bb05-484f-97a6-84d1e8541d54.png)

THANKS IN ADVANCE!

**Comment by jaakkopasanen** [comment]
Only a few select measurement sources are supported for hosted data and results in AutoEq. However you can produce the results yourself by following the guide linked in the results page.

**Comment by dontobi** [comment]
I'm sorry, but since I only own devices with ARM processors, I'm stuck. Some packages are not available in an ARM version. So how should I create the AutoEq file then? So I would be grateful for someone to create the file and send it to me.

**Comment by jaakkopasanen** [comment]
You could kick up a Linux server in AWS / Google Cloud / Azure and install AutoEq there.

**Comment by jaakkopasanen** [comment]
You could kick up a Linux server in AWS / Google Cloud / Azure and install AutoEq there.
