### ISSUE TITLE
Question about the curves

### ISSUE THREAD

**Issue by heavymetalmixer** [jaakkopasanen/AutoEq#345]
Do the calculations done for the correction curves take into account EQ cramping?

Right now I'm using Equalizer APO as a VST host with TDR NOVA as the EQ for the correction, mostly because in Precise mode this EQ has no cramping whatsoever and it's a transparent EQ, but after the correction the sound is pretty dark (bare in mind, I'm already used to the sound with the correction but it always sounds dark to me).

Headphones used: Audio Technica ATH-M50x.

**Comment by jaakkopasanen** [comment]
Hi. If by cramping you mean the bell shape change near Nyquist frequency the there's another issue with quite a bit of details #240. AutoEq uses the same implementation as EqualizerApo for the parametric filters so with EqualizerApo you'll get what AutoEq promises. Some other eq softwares might have different implementations and I cannot guarantee what those do nor can I take it into account because the manufacturers don't publish the implementation details.

**Comment by heavymetalmixer** [comment]
I read the thread and now I get what you mean, now I can clearly say that the "all clean EQs do the same" saying is BS LOL.

Is there are way implement oversampling for the curves calculations in EqualizerAPO to eliminate the cramping/warping? (At least 4x at 44.1 KHz). If so, is there a way I could help you do it? I'm no dev or know about maths, but if what you need is PC processing and time then count me in.

**Comment by jaakkopasanen** [comment]
The filter parameters could be calculated for higher sampling rates but then the signal chain would have to be set to that sampling rate too. You can control the sampling rate in AutoEq with `--fs`. If you do `--fs=192000` and set DAC/DAW/OS/whatever controls your signal chain's sampling rate to 192 kHz you won't have problems with "cramping", most likely.

**Comment by heavymetalmixer** [comment]
I started trying other free EQs because I need to work with ASIO and Equalizer APO doesn't work with ASIO (for correction inside DAWs). One that caught my attention was the Melda Production's MEqualizer, because according to the Equalizer APO's curve on the lower part of the screen, it uses exactly the same filters as Equalizer APO's and it cramples the same way.

Here's two pics, the first is Equalizer APO and the second is MEqualizer
![2](https://user-images.githubusercontent.com/79920904/134940523-b97ac02b-77e6-45ff-b8dd-ca31fc17c915.png)

![4](https://user-images.githubusercontent.com/79920904/134940560-24258b0a-b2b5-42a3-a9f6-675f037f8cac.png)


Note: Make sure the thyat SMART INTERPOLATION in the MEqualizer settings is set it Extreme on both options.
