### ISSUE TITLE
Beyerdynamic DT 990/Pro difference.

### ISSUE THREAD

**Issue by JuanDaville** [jaakkopasanen/AutoEq#346]
Hi! I’ve been using your AutoEQ program for years, it’s it’s one of the best things I’ve encountered on the web for improving my audio and getting the right neutral sound for my different headphones! Anyway to the issue. I’ve a ordered pair of headphones that will be arriving soon, the headphones are the Beyerdynamic DT 990 Pro 250 ohms and I like to neutralize the sound with AutoEQ when I get it, I had searched for the headphone model in the files but I’m aware that there’s also different headphone from Beyerdynamic called DT 990, but without the Pro at the end of the name. I don’t know for sure if the DT 990 (the non pro version) has the same exact sound as the pro to flatten, you have the name listed but there’s no version with Pro at the end of the headphone name, and I don’t want to use the wrong flattening eq for my headphones cause I’m using the DT 990 pro to compose my movie scores. Hope you get what I’m saying, any help is appreciated thank you.

**Comment by jaakkopasanen** [comment]
Hi. There should not be a significant difference between the pros and editions so I decided to omit that in the naming. Just use 990 results that are available.
