### ISSUE TITLE
Missing high frequencies in some new measurements?

### ISSUE THREAD

**Issue by tshalev** [jaakkopasanen/AutoEq#347]
Hi,

I have really enjoyed using your AutoEQ software; however, I've noticed that for some profiles there are no higher frequency band settings in the latest measurements. For example, I am using the Philips X2HR and there are no settings for bands above 9800 Hz. previously there were settings available up to 20,000 Hz, so I'm wondering if there was some error? I get the same results when I try to reproduce the settings using oratory1990/harman over ear 2018. I can see this is the case with other Philips headphones and possibly others, although I have not looked exhaustively down the list.

Thanks,
Tal

**Comment by jaakkopasanen** [comment]
That is intended. I changed how the highest frequencies are handled some time ago.

**Comment by tshalev** [comment]
OK thanks. Should the top frequency be set to a low pass or shelf filter? It's just that the resulting graph does not resemble your equalization curve on the high end.

![philips_fidelio_x2hr_curve](https://user-images.githubusercontent.com/8867070/135125009-50671336-c615-4282-8cde-e7d30631a003.png)
