### ISSUE TITLE
[REQUEST] HeSuVi EQ for "KZ ZSN Pro"

### ISSUE THREAD

**Issue by Fardin48** [jaakkopasanen/AutoEq#348]
Hi,
Is it possible to add the HeSuVi EQ  for "KZ ZSN Pro"?

Thank You :)

**Comment by jaakkopasanen** [comment]
The results already exist https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/KZ%20ZSN%20Pro

If they are missing from HeSuVi an you want them there, take a look at HeSuVi's wiki is Sourceforge for instructions on updating the eqs.
