### ISSUE TITLE
Duplicate result for Sennheiser HD 25-1 II

### ISSUE THREAD

**Issue by shadowislord** [jaakkopasanen/AutoEq#353]
I noticed there are two results for HD 25-1 II. The only difference is the lack of space between "HD" and "25" in the name:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%2025-1%20II
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD25-1%20II

Going into this table from oratory we see this:
https://github.com/jaakkopasanen/AutoEq/blob/master/measurements/oratory1990/name_index.tsv
| false_name | true_name | form |
| --- | --- | --- |
| Sennheiser HD25-1 II | Sennheiser HD 25-1 II |  onear | 
| Sennheiser HD25-1 II (bad seal) | | ignore |
| Sennheiser HD25-1 II (good seal) |  Sennheiser HD25-1 II | onear |

So the space was added in the `true_name` for some reason. The one that says "good seal" didn't have a space added. It's not clear what the difference is between the "good seal" one and the one without any description, maybe it's an "average seal"? The inflated bass response in that one does suggest this to be the case. If so, then would it make sense to just have  the "good seal" result and remove the others? After all, if someone is going to go through the trouble of loading an EQ for their headphones they would probably ensure a good seal exists

**Comment by jaakkopasanen** [comment]
Thanks for reporting! It's fixed now.
