### ISSUE TITLE
[REQUEST] HeSuVi EQ for Samson SR850's

### ISSUE THREAD

**Issue by Manic137** [jaakkopasanen/AutoEq#354]
They just got a review on Rtings.com, here's the source: https://www.rtings.com/headphones/reviews/samson/sr850

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Samson%20SR850

HeSuVi you need to update manually if you're using that. See the HeSuVi wiki for instructions.

**Comment by Manic137** [comment]
I know you've closed this, I was tempted to open another issue but thought I'd try pointing it out here. What folder did you add the EQ into, because there were no SR850 EQ's in that zip file(I did a search when I couldn't find it), nor were there any Samson Folders

**Comment by ronelm2000** [comment]
It's on /results/rtings/rtings_harman_over-ear_2018

**Comment by Manic137** [comment]
> It's on /results/rtings/rtings_harman_over-ear_2018

I understand that, but just pointing out it's not on the zip file which is what he(More specifically the wiki) instructed me to get, which then sent me to a HeSuVi.zip file that was on this GitHub, it was updated 11 ours ago yet the files are not there

**Comment by Manic137** [comment]
No worries!
