### ISSUE TITLE
Error with requirements tensorflow~=2.4.0

### ISSUE THREAD

**Issue by mott0r** [jaakkopasanen/AutoEq#358]
**Describe the bug**
Installation of requirements breaks. Changing the reqs to tensorflow~=2.5.0 fixed it.

**To Reproduce**
(venv)  python -m pip install -U -r requirements.txt

**System:**
 - OS: Manjaro 21.1.6
 - Version: latest one in CHANGELOG.md

**Additional context**
error message I got

ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.7.0rc0, 2.7.0rc1)
ERROR: No matching distribution found for tensorflow~=2.4.0

**Comment by JaKasb** [comment]
I ran into the same problem.
The cause is that pypi provides wheels for tensorflow 2.4 only for python 3.8 and older.
https://pypi.org/project/tensorflow/2.4.0/#files

Another workaround would be the use of python3.8 in a docker container or install Ubuntu 21.04 in a VM

**Comment by JoaoCosta-EQ** [comment]
What do I need to change on requirements to solve this issue? Choose another tensor flow version? It is which one?

**Comment by jaakkopasanen** [comment]
The install instructions clearly (or maybe not clearly enough) that Python 3.8 is required.

So anyone who's having issues with Tensorflow not found need to switch to Python 3.8.
