### ISSUE TITLE
Add Neutron to app list

### ISSUE THREAD

**Issue by Keltere** [jaakkopasanen/AutoEq#36]
Hi, i wanted to suggest Neutron music player as an alternative to USB Audio Player PRO.
It has the best paramentric eq and with a lot of functionality for example streaming to Marantz/Denon amp.
https://play.google.com/store/apps/details?id=com.neutroncode.mp
There is also a demo version
https://play.google.com/store/apps/details?id=com.neutroncode.mpeval

**Comment by jaakkopasanen** [comment]
There is a mention about Neutron in the Android section. I prefer to keep the list of recommended software somewhat limited so I won't be adding a full entry about it. USB Audio Player Pro supports several streaming services and therefore it's the recommended one.
