### ISSUE TITLE
Beyerdynamic DT 770 Oratory1990 Measurements Outdated

### ISSUE THREAD

**Issue by kev4cards** [jaakkopasanen/AutoEq#360]
The current measurements for the Beyerdynamic DT 770 averaged across all models from oratory1990 is from April 2021. AutoEQ is listed as January 2021. May you re-crawl oratory1990's database to pick up the new measurements and update the results? I believe there are many other headphones that need updating.

Corresponding pdf for the Beyerdynamic DT 770 (fresh pads) (across all impedance models according to the comments in the sidebar) : https://www.dropbox.com/s/npqrz9dqdda292x/Beyerdynamic%20DT770%20%28new%20earpads%29.pdf?dl=0

Thanks in advance.

**Comment by heavymetalmixer** [comment]
This looks very useful, though how can you make the 696 bands results CSV out of this?

Like this: https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/Beyerdynamic%20DT%20770%20250%20Ohm/Beyerdynamic%20DT%20770%20250%20Ohm.csv

**Comment by jaakkopasanen** [comment]
I just did a complete refresh of the oratory1990 measurements so now this one too should be up to date.
