### ISSUE TITLE
Superlux Hd668b oratory measurements outdated

### ISSUE THREAD

**Issue by WeileeTheWeener** [jaakkopasanen/AutoEq#361]
Oratory1990 remeasured a lot of headphones including superlux hd668b can u update them,thank you.

new hd668b pdf link : https://www.dropbox.com/s/d83yjon3rfuwg2g/Superlux%20HD-668B.pdf?dl=0

**Comment by jaakkopasanen** [comment]
I just did a complete refresh of the oratory1990 measurements so now this one too should be up to date.
