### ISSUE TITLE
Measurements version

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#362]
Is there a way to check what is the version of the measurements?

Just to take the first one [1MORE Quad Driver.csv](https://github.com/jaakkopasanen/AutoEq/blob/master/measurements/oratory1990/data/inear/1MORE%20Quad%20Driver/1MORE%20Quad%20Driver.csv):

If I take it from the official list:
https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets

On the bottom right corner of the PDF it has a version/date, for this headphone we have `v2.9` and a date.

Do we handle this version in our measurements? If not how can check what kind of version we have stored in the csv cause I suppose it is going to impact our result right?

**Comment by bhack** [comment]
Just to add more context I don't know if there are cases where some version change it is going to impact AutoEq or not:

https://www.reddit.com/r/oratory1990/comments/k5fas6/versioning_question/

**Comment by jaakkopasanen** [comment]
That answers is pretty clear.
