### ISSUE TITLE
More options to optimize the Parametric Equalizer

### ISSUE THREAD

**Issue by Suznyan** [jaakkopasanen/AutoEq#365]
The PEQ result often using the frequency bands outside of the 20-20kHz range and Q value like 0.07 which is not support on most Equalizer so I think there should be some additional options to specify the range of frequency and Q it can use

**Comment by ktheticdev** [comment]
I'm unsure, but this seems to duplicate #150

**Comment by jaakkopasanen** [comment]
Also a duplicate of #253
