### ISSUE TITLE
Please add Denon AH-D7200

### ISSUE THREAD

**Issue by jacobacci** [jaakkopasanen/AutoEq#37]
Could you please add the parameters for Denon AH-7200
Thanks a lot

**Comment by jaakkopasanen** [comment]
Looks like the measurements aren't available in any of the current or planned databases so I cannot add it. If you happen to find the frequency response measurements you can follow this guide to do it yourself: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)
