### ISSUE TITLE
[Headphone request] KZ ZSN PRO X

### ISSUE THREAD

**Issue by supertiger1234** [jaakkopasanen/AutoEq#372]
**Headphone requests**
KZ ZSN PRO X 
https://crinacle.com/graphs/iems/kz-zsn-pro-x/

**Comment by FeugalFeugo** [comment]
I Hope The EQ For These Comes Out Soon

**Comment by supertiger1234** [comment]
Im a noob at the terms but these earphones have really high treble in my opinion which kinda hurt my ears on some music :(

**Comment by FeugalFeugo** [comment]
Same I want them to sound closer to the harmon curve

**Comment by FeugalFeugo** [comment]
Btw do u have any idea as to how long it might take for them to implement the auto eq also how long has it been since you uploaded your request

**Comment by raisilhamn** [comment]
someone already make it. Here's the link https://mega.nz/folder/W3JSHZDC#MawPb8POq5TCrtWxUguHIg
source : https://forum.hifiguides.com/t/autoeq-profile-for-kz-zsn-pro-x/24039

**Comment by raisilhamn** [comment]
someone already made it. Here's the link https://mega.nz/folder/W3JSHZDC#MawPb8POq5TCrtWxUguHIg
source : https://forum.hifiguides.com/t/autoeq-profile-for-kz-zsn-pro-x/24039

**Comment by raisilhamn** [comment]
Someone already made it. Here's the link https://mega.nz/folder/W3JSHZDC#MawPb8POq5TCrtWxUguHIg
source : https://forum.hifiguides.com/t/autoeq-profile-for-kz-zsn-pro-x/24039

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/KZ%20ZSN%20Pro%20X
