### ISSUE TITLE
Do I use all files or one of them?

### ISSUE THREAD

**Issue by idkman2021** [jaakkopasanen/AutoEq#375]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Superlux%20HD%20681%20EVO
I am confused by https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Superlux%20HD%20681%20EVO/Superlux%20HD%20681%20EVO.png
Do I have to use fixedEQ graphicEQ parametricEQ and convolution at the same time?

**Comment by jaakkopasanen** [comment]
Only one. I'd recommend convolution but parametric is good too.

**Comment by DarKDinDoN** [comment]
@jaakkopasanen So sorry, but I'm really confused about convolution files.

Using EqualizerAPO on PC. If I want to use Convolution, do I need only the "EqualizerAPO GraphicEQ" file and follow the steps here: https://github.com/jaakkopasanen/AutoEq#equalizerapo?
Or do I need smt else/more?

**Comment by DarKDinDoN** [comment]
Ok, after testing all files and all source. I think I just need to load the GraphicEQ file or the WAV file.
- FixedBandEQ: very different from the other EQ. Like it's a totally different one. Weird.
- ParametricEQ, GraphicEQ & Convolution sound about the same
