### ISSUE TITLE
A learner's small question

### ISSUE THREAD

**Issue by Demo36days** [jaakkopasanen/AutoEq#376]
Can I import my own audio file and get the output exported in my folder?
Because of my poor English, I can't understand the Equalizer's function.
This is my understanding: I can use this python project to equalize my audio files, and get some output files. Is that right?
sry if this is a stupid question...   :)
I'm a student, just interested in Equalizers.

**Comment by jaakkopasanen** [comment]
AutoEq is a tool for generating equalizer profiles for headphones, not for audio files. The outputs of AutoEq are eq settings you need to configure to an eq app or a music player which has an eq. AutoEq does not do any audio processing itself.
