### ISSUE TITLE
interval of recompute of all the measurements

### ISSUE THREAD

**Issue by henriklb** [jaakkopasanen/AutoEq#379]
Hi, what is the usual interval for recomputing of all the measurements in the repo? I see the latest one was in January.

**Comment by jaakkopasanen** [comment]
I don't recompute the results unless there is some significant change in the algorithm.

**Comment by henriklb** [comment]
Ok thanks. But what is then the reason I am getting a different EQ (especially in the bass region) than the pre-computed results?
Im using the following parameters:
`python3 autoeq.py --input_dir="measurements/rtings/data/onear/HyperX Cloud II Wireless/" --output_dir="my_results/henk_hyperxcloud2wireless" --compensation="compensation/harman_over-ear_2018.csv" --equalize  --parametric_eq`
![HyperX Cloud II Wireless](https://user-images.githubusercontent.com/11011393/144741264-f7962aca-927e-4c86-9070-aed019f61ed4.png)

Comparing to this pre-compted in the repo:
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/HyperX%20Cloud%20II%20Wireless/HyperX%20Cloud%20II%20Wireless.png

**Comment by jaakkopasanen** [comment]
The pre-computed results use Harman target without bass shelf and add a bass boost of 4 dB for over-ear headphones instead of the 6ish dB in the Harman target proper. The parameters used for pre-computed results isn't documented anywhere but can be deciphered from `results/update_results.py`

**Comment by henriklb** [comment]
ok, I get it now. Thanks again. I saw some examples with the parameter `--bass_boost 4`. However, I assumed it was just an example to illustrate that the command/bass/treble customization exist. I do tend to prefer a 2-3dB reduction in the bass region compared to the Harman target.
