### ISSUE TITLE
Pre-Amp Gain Not Reduced enough

### ISSUE THREAD

**Issue by joshfoss** [jaakkopasanen/AutoEq#38]
for the Audio Technica ATH-AD2000X the Parametric EQ has a Pre-amp gain of -7.4db but the 2692 Hz band is raised 9.6db

https://github.com/jaakkopasanen/AutoEq/tree/master/results/innerfidelity/sbaf-serious/Audio%20Technica%20ATH-AD2000X

**Comment by jaakkopasanen** [comment]
Gain of individual filters isn't important. What matters is the total gain of all the filters. If you look at the parametric eq curve you'll notice that the maximum gain is about 7dB so the recommended preamp is sufficient.
