### ISSUE TITLE
Beyerdynamic DT990 PRO 80 Ohm

### ISSUE THREAD

**Issue by Sunn91** [jaakkopasanen/AutoEq#380]
Hello

I can't see any results for Beyerdynamic DT990 PRO 80 Ohm. I found only these [Beyerdynamic DT 990](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Beyerdynamic%20DT%20990) but in the name of results there's no info about Ohms. This results are for that version of headset?

Regards.

**Comment by Mat-thieu** [comment]
This EQ setting is for the 250 ohms. I had to do a little digging, but this reddit comment from Oratory1990 confirms it.

https://www.reddit.com/r/headphones/comments/9o2f5n/psa_oratory1990s_list_of_eq_presets/e7xle1b/
