### ISSUE TITLE
Beyerdynamic DT 700 Pro X

### ISSUE THREAD

**Issue by Raibook1** [jaakkopasanen/AutoEq#381]
Hello guys! 

My friend told me about AutoEq a couple of weeks ago and that I should try it when I receive my new headphones. 

Unfortunately, I didn't find the Beyerdynamic DT 700 Pro x  (48 ohms). 

Will you work on this one? 
In the meantime, could I use another one or it's better to just let it with the standard parameter? 

Thanks for you incredible work!

Raibook

**Comment by ar1a** [comment]
Just bought some myself and was sad to see there was no eq for this!

**Comment by PaulDoesDev** [comment]
Yeah, I'm not sure why this issue has been closed @jaakkopasanen? An oratory1990 EQ exists but it hasn't been added.

**Comment by VallCode** [comment]
Made a preset for Pro q 3

[DT700PROX.zip](https://github.com/user-attachments/files/18232482/DT700PROX.zip)

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/over-ear/Beyerdynamic%20DT%20700%20Pro%20X
