### ISSUE TITLE
hello is my second time using the Auto EQ, my first headset is sennheiser PC38x, but now have switch to the EPOS H6pro unfortunately I didn't find the EPOS H6pro, would you add the measurement of EPOS H6proto the list. Thank you much appreciated <3

### ISSUE THREAD

**Issue by IDKwhat2get** [jaakkopasanen/AutoEq#383]
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by IDKwhat2get** [comment]
sorry first time using github i dong know this is the title

**Comment by TengkuJG** [comment]
Ayo! Any EQ presets for the Epos H6 Pro Closed-backed? I couldn't find anything, even on reddit for god's sake.

**Comment by glebsonik** [comment]
Hello there, it seems like there is a service with frequency response graph you needed. 
Here is the link to [Epos H6 Pro closed back](https://gadgetrytech.squig.link/headsets/?share=Harman_2018_Target,EPOS_H6PRO_Closed_(Stock_pad))

Also, there is an export option for this headset below the graph. Anyways, here is the export file from that website [EPOS H6PRO Closed Back [1].txt](https://github.com/user-attachments/files/18270847/EPOS.H6PRO.Closed.Back.1.txt)
