### ISSUE TITLE
Raw data CSV files missing in Crinacle results folder?

### ISSUE THREAD

**Issue by ThePBone** [jaakkopasanen/AutoEq#384]
Hello,

I just noticed that there are no CSV files with raw data in the crinacle results folder.

Example: https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/1Custom%20SA02

Is this intended? Is there a way I can generate them myself?
____
Edit: https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Shuoer%20Tape is the only folder in crinacle that contains a CSV file

**Comment by jaakkopasanen** [comment]
The numerical data is available for Crinacle's Patreon subscribers and therefore he asked me not to publish that in AutoEq. So yes, it's intentional.
