### ISSUE TITLE
Samson SR850

### ISSUE THREAD

**Issue by Tolga88** [jaakkopasanen/AutoEq#385]
Hey, firstly thanks for sharing equalizer settings for Samson SR850. I hope i am posting my issues on the right page. I don't know on which program to use Samson equalizer settings. How can i use my headphones with your EQ settings and stereo ? Can you suggest me program for this ? Do you have a video on how to do it ? Thanks and stay healthy.

**Comment by niyonsv** [comment]
Hey, please go to this subsection in the Usage section on the AutoEQ info page. You can find about different applications to use the equalisations (from Results page; https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Samson%20SR850 for Samson) on the respective OSs.

Though I'm not sure how to use it on stereo. Hope my comment answered your question.
