### ISSUE TITLE
Poweramp (Android) now allow import AutoEq presets 

### ISSUE THREAD

**Issue by peter9811** [jaakkopasanen/AutoEq#387]
Allow graphic, fixed and parametric
Chechk the forum:
[https://forum.powerampapp.com/topic/22708-poweramp-builds-912-914/?do=findComment&comment=103452](url)

Since version 911, works

**Comment by jaakkopasanen** [comment]
I'm aware of this but decided not to add this to the list of eq apps as there are already too many listed.
