### ISSUE TITLE
can use rtings raw data instead of parsing images

### ISSUE THREAD

**Issue by nevubm** [jaakkopasanen/AutoEq#39]
rtings actually sends raw data in their comparison tool, which can be directly extracted instead of parsing the images

For example: https://www.rtings.com/headphones/1-2/graph#342/2060 shows five measurements of the left channel along with the target curve, for which the raw data is at https://www.rtings.com/images/graphs/headphones/bose/quietcomfort-35/graph-raw-frequency-response-l.json

**Comment by jaakkopasanen** [comment]
I wish I had noticed this when I was working on Rtings measurements. Maybe I'll change the logic to download and use this numerical data at some point but don't hold your breath.

**Comment by jaakkopasanen** [comment]
Done. I actually had to rework the entire Rtings pipeline because the frequency response image URLs didn't anymore match the headphone reviews index page names. Now I'm using graphs tool in the crawler and download the JSON files instead of images.
