### ISSUE TITLE
[QUESTION] A bit confused about compensation(s)

### ISSUE THREAD

**Issue by kokoko3k** [jaakkopasanen/AutoEq#391]
Hello
I'm just approaching autoeq and so far so good; my in-ear 1MORE quad driver earbuds sounds a lot of better right now.
By now, i've used the easy path:
```python3 ./autoeq.py --input_dir="./measurements/rtings/data/inear/1MORE Quad Driver/" --output_dir="1more.quad/rtings_compensation_autoeq_in-ear" --compensation="compensation/autoeq_in-ear.csv" --equalize --rockbox --ten_band_eq  --show_plot```
But i hear some resonances here and there and the sound is much, maybe too much, clear and exhausting after 2 hours of listening.

From what i undesrtsood, since the docs say it is necessary, it seems to me that the "compensation" is some sort of "microphone post-calibration".
So i wonder, out of curiosity, don't the guys at rtings,innerfidelity and so on calibrate their mics before going to measure? And if they do, why do we still need to firther compensate? Sorry if this is already covered, probably i missed or misunderstanded it.

Next, i'm not very sure about what compensation to use at all.
As you see, i've used the most generic one (i think): compensation/autoeq_in-ear.csv
But i see there are:
AutoEq/compensation/*
...and, if i search for people that measured 1MORE Quad Driver, i see that there are other compensations from (or for) them:
AutoEq/rtings/resources/rtings_compensation
AutoEq/referenceaudioanalyzer/resources/rtings_compensation
I admit, i'm totally lost in the csvs... 

Also, i see that there is AutoEq/results/*
Are the values we find there already been "compensated"? how?

Thenk you for the attention!

**Comment by jaakkopasanen** [comment]
The autoeq in-ear target is only compatible with 7-11 couplers (oratory1990, Crinacle). You can find Harman target "equivalent" for Rtings measurements in measurements/rtings/resources
- [rtings_harman_in-ear_2019v2_wo_bass.csv](https://github.com/jaakkopasanen/AutoEq/blob/master/measurements/rtings/resources/rtings_harman_in-ear_2019v2_wo_bass.csv)
- [rtings_harman_in-ear_2019v2.csv](https://github.com/jaakkopasanen/AutoEq/blob/master/measurements/rtings/resources/rtings_harman_in-ear_2019v2.csv)

The results folder contain pre-computed equalizer settings with default parameters. These should serve most of the users most of the time.

**Comment by kokoko3k** [comment]
Thanks, picking the pre-made results made them sound even better.
