### ISSUE TITLE
(Headphone Request) KZ x crinacle CRN (ZEX Pro)

### ISSUE THREAD

**Issue by Terrigible** [jaakkopasanen/AutoEq#392]
https://crinacle.com/graphs/iems/kz-x-crinacle-crn-zex-pro/

Thanks!

**Comment by Collectathon** [comment]
An AutoEQ result for this iem would be nice. Until then, these values supposably assist the sharp high-end. 

8khz -5dB, 5.0Q Peak
12khz +10dB, 4.0Q Peak

**Comment by Collectathon** [comment]
> https://crinacle.com/graphs/iems/kz-x-crinacle-crn-zex-pro/
> 
> Thanks!

An AutoEQ result for this iem would be nice. Until then, these values supposably assist the sharp high-end.

8khz -5dB, 5.0Q Peak
12khz +10dB, 4.0Q Peak

**Comment by ianmustafa** [comment]
I made my ZEX Pro / CRN setting by myself by following @jaakkopasanen's [guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9), using [crin's own graph](https://crinacle.com/wp-content/uploads/2021/12/CRN.jpg) taken from [his BTS article](https://crinacle.com/2021/12/20/behind-the-scenes-kz-x-crinacle-crn-zex-pro/). I don't know if it's pull request worthy, but fi you guys want I can make one

**Comment by Dark-Noir** [comment]
> 

I would be interested ^^

**Comment by crian** [comment]
> I made my ZEX Pro / CRN setting by myself by following @jaakkopasanen's [guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9), using [crin's own graph](https://crinacle.com/wp-content/uploads/2021/12/CRN.jpg) taken from [his BTS article](https://crinacle.com/2021/12/20/behind-the-scenes-kz-x-crinacle-crn-zex-pro/). I don't know if it's pull request worthy, but if you guys want, I can make the PR

Can you share this?

**Comment by ianmustafa** [comment]
Sorry for late update. I decided to post my preset [here](https://gist.github.com/ianmustafa/89314aa3368ceccf09240cf134f3acda), since [I can't create PR for this](https://github.com/jaakkopasanen/AutoEq/pull/329#issuecomment-894652977). Hope this helps @Terrigible @Dark-Noir @crian

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/KZ%20x%20Crinacle%20CRN%20(ZEX%20Pro)

Enjoy!
