### ISSUE TITLE
[Headphone request] Moondrop Aria

### ISSUE THREAD

**Issue by PlsMoreSand** [jaakkopasanen/AutoEq#394]
Hello, the moondrop aria is not present on auto eq but it's been measured by crinacle.
https://crinacle.com/2021/03/29/moondrop-aria-2021-unboxing/
Thank you for your work, your auto eq is like magic ^^

**Comment by 6175352649** [comment]
Ol

**Comment by jaakkopasanen** [comment]
Thanks for pointing this one out. Looks like the measurements have existed for quite a while but for some reason didn't end up in AutoEq.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Moondrop%20Aria%202021
