### ISSUE TITLE
[Feature request] Treble boost similiar to Bass boost argument

### ISSUE THREAD

**Issue by Suznyan** [jaakkopasanen/AutoEq#395]
Treble boost using High shelf filter with the same format as --bass_boost " where the first is gain in dB, second is center frequency (Fc) in Hz and the last is quality (Q)". 
Thanks in advanced.

**Comment by jaakkopasanen** [comment]
Thanks for the idea. I think I will implement this at some point.

**Comment by jaakkopasanen** [comment]
`--treble-boost` is now available and works similarly to `--bass-boost` but of course uses high shelf filter to adjust treble frequencies. The boost is added to the target.
