### ISSUE TITLE
"File "autoeq.py", line 6, in <module>     import soundfile as sf ModuleNotFoundError: No module named 'soundfile'"

### ISSUE THREAD

**Issue by a-a-07** [jaakkopasanen/AutoEq#396]
Hi, 
I am trying to counteract the frequency response curve on my headphones using this program. I got through the installation process and also have the data from the frequency response curve notated in a csv file and moved into a folder in the "onear" folder inside of the "data" folder. When attempting to run this code :
`python autoeq.py --input_dir="measurements/innerfidelity/data/onear/OneOdioA70 --output_dir="my_results/A70 --compensation="measurements/innerfidelity/resources/innerfidelity_harman_over-ear_2018_wo_bass.csv" --equalize --bass_boost=4 --show_plot --convolution_eq --fs=44100,48000. 
`
Which is pulled from the examples section in the README file with the file names changed to match the ones I am trying to execute the script on. After attempting to run the code given above I am returned with the error message: 
`Traceback (most recent call last):
  File "autoeq.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'`

Any idea as to why this error message is being returned and any possible fixes. I have very basic programming and python knowledge so a detailed response would be appreciated.

**Comment by ThePBone** [comment]
It can't find a library it depends on. 
You can install the missing library using this command:
```
pip install SoundFile
```

**Comment by a-a-07** [comment]
thank you!
