### ISSUE TITLE
Issues installing AutoEQ on Fedora 35

### ISSUE THREAD

**Issue by Netherquark** [jaakkopasanen/AutoEq#397]
**Describe the bug**
I tried to follow the instructions for installation in the readme, but it seems they didn't work

**System:**
 - OS: Fedora 35 (Linux 5.15.12-200.fc35.x86_64 x86_64 GNU/Linux)
 - Version: Latest

Logs:
[logs1.txt](https://github.com/jaakkopasanen/AutoEq/files/7801343/logs1.txt)
[logs2.txt](https://github.com/jaakkopasanen/AutoEq/files/7801369/logs2.txt)

**Comment by jaakkopasanen** [comment]
You are at least running Python 3.10 while only 3.8 is supported. There might be something else too with your distro but I can't say for certain or test since I don't have Fedora.

**Comment by jaakkopasanen** [comment]
I just updated AutoEq to use Python 3.10 by default. Also this is an old issue without any activity so I'll close it. Please reopen if the issue persists.
