### ISSUE TITLE
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

### ISSUE THREAD

**Issue by botik09** [jaakkopasanen/AutoEq#401]
Hello!
Can you please add "takstar hf 580" EQ preset?

**Comment by botik09** [comment]
https://www.headphonesty.com/wp-content/uploads/2020/08/HF_580_Pads_Graph_jpg-1100x621.jpg 

 here the FR graph

**Comment by NekoAlosama** [comment]
You didn't even read the sample title. I was about to call this a copy of #393 . That graph isn't supported by AutoEQ.

**Comment by botik09** [comment]
So what about this one?

https://forum.hifiguides.com/uploads/default/original/1X/5e76baf0c8ba7d6d69eb39a74762ba3702682a20.jpeg
