### ISSUE TITLE
Plot the actual output

### ISSUE THREAD

**Issue by stinos** [jaakkopasanen/AutoEq#402]
The plots lack the final output (the actual target reached with the calculated filters, and perhaps the deviation; basically the 'Compensated Frequency response' plots in Oratory's pdfs) which arguably is more important than some of the other things plotted by default.

In `plot_graph` this would come down to:
- rename 'Equalization' to 'Equalization Target' since it's the 'ideal' equalization and not what actually gets applied by the filters
- plot the results with something like

```
        if equalized and parametric_eq:
            ax.plot(
                self.frequency, self.raw + self.parametric_eq,
                **self.kwarg_defaults(equalized_plot_kwargs, label='Equalized with parameteric EQ', linewidth=2, color='cyan')
            )
            ax.plot(
                self.frequency, self.raw + self.parametric_eq - self.target,
                **self.kwarg_defaults(equalized_plot_kwargs, label='Equalized with parameteric EQ vs Target', linewidth=1, color='red')
            )
```

Here's an example with raw/error left out:

![Sennheiser HD 598](https://user-images.githubusercontent.com/1902997/148367899-374ce5fa-cc2f-472e-ac2a-ffc91fb36c28.png)

**Comment by jaakkopasanen** [comment]
I have thought about this but decided not to add parametric eq since there are several types of outputs and the parametric eq is not the most recommended one.
