### ISSUE TITLE
LCD2F version?

### ISSUE THREAD

**Issue by voodoochild1974** [jaakkopasanen/AutoEq#404]
Hi
Looking at the Audeze LCD2F EQ settings (3 different posters with slightly different recommendations) and unsure of which version they are. It might well be stated and I am blind, but do you/anyone happen to know if the settings are for the 2016 fazor (which I have) or the more recent ones that have a slightly different sound signature and different pads.

Thanks

https://github.com/jaakkopasanen/AutoEq/tree/master/results/innerfidelity/innerfidelity_harman_over-ear_2018/Audeze%20LCD-2%20Fazor

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Audeze%20LCD-2%20Fazor

https://github.com/jaakkopasanen/AutoEq/tree/master/results/referenceaudioanalyzer/referenceaudioanalyzer_hdm-x_harman_over-ear_2018/Audeze%20LCD-2%20Fazor

**Comment by NekoAlosama** [comment]
In https://github.com/jaakkopasanen/AutoEq/tree/master/results#readme :
"Recommendation priority is: oratory1990 > Crinacle > Innerfidelity > Rtings > Headphone.com > Reference Audio Analyzer. This means if there are measurements from multiple sources for the same headphone model only the highest priority result will be shown in this list."
