### ISSUE TITLE
New headphones measured

### ISSUE THREAD

**Issue by Chrippa2** [jaakkopasanen/AutoEq#406]
[**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

The Focal Clear MG Professional has been measured by headphones.com
](https://headphones.audiodiscourse.com/?share=Clear_Mg_Pro)

**Comment by jaakkopasanen** [comment]
AutoEq only sources measurements from certain sources and the Audiodiscourse measurements are not among them so these won't end up in AutoEq.

It's possible that these headphones will end up being measured by one of the supported ones. Or you could parse the graphs yourself by following the linked guide. The measurements are Harman target compatible though, so you should get very good results with this method.
