### ISSUE TITLE
[Headphone Requests] Shure AONIC 5

### ISSUE THREAD

**Issue by yabba235** [jaakkopasanen/AutoEq#408]
HI!
Im user of Qdelix 5k with fantastic PEQ, but I can't find in AutoEQ base my IEM - Aonic 5 :)
Over https://crinacle.com/graphs/iems/shure-aonic-5/ is measuring graph so maybe someone add this iem to AutoEq base ?

**Comment by jaakkopasanen** [comment]
It's missing from Crinacle's Google Drive. I'll add it to AutoEq once he adds the data to drive.

**Comment by Broccaaa** [comment]
Has this been added yet? I'd love to check the settings for my pair of Shure AONIC 5s :)

**Comment by jaakkopasanen** [comment]
[Shure Aonic 5 (bright filter)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Shure%20Aonic%205%20(bright%20filter))
[Shure Aonic 5 (default filter)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Shure%20Aonic%205%20(default%20filter))
[Shure Aonic 5 (warm filter)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Shure%20Aonic%205%20(warm%20filter))
