### ISSUE TITLE
How can i use the EQ variables in my DAW?

### ISSUE THREAD

**Issue by omerdn** [jaakkopasanen/AutoEq#409]
Hello. I have a question about using these settings in DAW. When i'm using windows as a workstation, when i opened any digital audio workstation ASIO skipping the windows audio so our graph eq settings doesnt work in the DAW's.

So i tried to add variables of fixed band to any EQ, it seems not exactly true to me. Because there was a different spectrums between Equalizer APO and Fab-filter Pro-Q, and you can hear the difference about them.

I actually add any vst plugin to output section when i'm working and i remove it while rendering. There is no problem about it. But i cant add the correct variables to any VST equalizer. Because i dont know how to do it. 

edit: If we use paramteric EQ variables it gonna be correct for output eq in daw. Not exactly true, but it works.

**Comment by jaakkopasanen** [comment]
Not all parametric equalizer implementations are equal. There is a quite comprehensive discussion and investigation about this in #240. AutoEq uses the same convention as EqualizerApo so that is guaranteed to provide the correct results.
