### ISSUE TITLE
eq doesn't match filter resaults on peace .

### ISSUE THREAD

**Issue by guy1997** [jaakkopasanen/AutoEq#411]
hey , i am using auto eq on my qc45 , and i have notice peace software shows me different reasults compared to the graph rtings provide.
i think the problem is in peace as wavelet shows the exact equalization as the graph on rtings .
peace calculate the equalization with a major downfall in high range . 
hope you can help me understand why

**Comment by PeterVerbeek** [comment]
I see the difference too if I take the parametricEQ file of the Bose QuietComfort 45. The calculation used to draw the graph (in Peace as well in the Configuration Editor of Equalizer APO) is exactly the same as actually filtering the sound (BiQuad calculations). So I don't know where this difference is coming from.

**Comment by jaakkopasanen** [comment]
I'm not sure I follow entirely here. What are different? If it's graphs you're talking about, please could you provide screenshots which demonstrate the problem.

**Comment by jaakkopasanen** [comment]
[CSV](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Bose%20QuietComfort%2045/Bose%20QuietComfort%2045.csv)
	2.12 dB @ 698 Hz
	1.89 dB @ 7989 Hz
	Δ = -0.23 dB

Configuration Editor
	-0.2 dB @ 698 Hz
	-1.4 dB @ 7990 Hz
	Δ = -1.2 dB
![QC45 Configuration Editor](https://user-images.githubusercontent.com/8393524/153757846-789e4e60-543c-4830-8ecf-8960dd0b27c6.png)

Peace (from @PeterVerbeek)
	2 dB @ 699 Hz
	-3.2 @ 7988 Hz
	Δ = -5.2 dB

There is more discussion about discrepancies in parametric equalizer implementations in #240. I was under the impression that AutoEq and EqualizerAPO matched perfectly but that doesn't seem to be the case here. Peace on the other hand is way off. @PeterVerbeek are you sure what Peace displays matches with the EqualizerAPO's configuration editor?

**Comment by PeterVerbeek** [comment]
I think you're right. The parametric graph line is the same as the one on the analysis panel in the Configuration Editor. However, this one does have the -2.3 dB included hence it's lower. As for the graph in Peace, I'm now under impression that the higher frequencies aren't properly displayed. Of course, my Peace graph image didn't include the -2.3 dB pre amp. I hadn't checked the "Add pre amp" checkbox. But that doesn't explain the difference so I have to investigate this. I'll get back with my findings.

Anyway, the number are now (included pre amp):
about -0.2 dB @ 700 Hz (spot on with Analysis panel)
-5.5 dB @ 8 kHz (which is even worse than previously compared to the Analysis panel)

![afbeelding](https://user-images.githubusercontent.com/98103481/153758808-3aa69c27-40da-442f-882a-d10d72412cc9.png)

**Comment by PeterVerbeek** [comment]
I've found the "issue". Peace is using a default sample rate of 96 kHz for its graph calculation which at higher frequencies will show a difference. The Configurator Editor uses a device sample rate like 48 kHz hence the difference. Both approaches have their issues. Of course, one default sample rate in Peace isn't ideal as any device may have a different sample rate. So it seems logical to take the device sample rate. However, there's more to it. By default the Equalizer APO commands are perform on **all** devices (input and output). So the graphs for all devices should be displayed (according to their sample rates). Another issue is that the Analysis panel shows the graph of  the selected device in the top dropdown box. This device could differ from the current selected input and output device in Windows. So the graph may be wrong. Only when a user has added a specific device selection command a graph can be properly displayed (as in with the right sample rate). But neither Peace nor the Configurator Editor has this "automatic" feature. As developer of Peace I should consider such a feature. I think, at least a sample rate/device selection dropdown box should be present on the Peace graph window although this has the same issue as the Configurator Editor.

**Comment by jaakkopasanen** [comment]
The sample rate thingy is always going to be at least a bit problematic but I hope alleviate it in the future when switching to shelf filter for the +10kHz region. I also though I saw somewhere that some kind of solution for this was implemented in Peace. I'll close this issue as there is another one about the AutoEq side of this in #240.

**Comment by PeterVerbeek** [comment]
The solution implemented in Peace is to get the sample frequency of the
selected (target) audio device and draw the graph accordingly. There can be
a mismatch in the higher frequency region if the graph on AutoEQ is of
another sample rate than of the audio device. However, in general this
isn't an issue at all knowing that most human ears aren't able to hear very
high frequencies and songs sound almost the same from sample rates of 44.1
kHz. In other words, it's a graph thing rather than an actual one.

You're right. By switching to a shelf filter for higher frequencies the
graph looks the same.

Op di 26 jul. 2022 om 18:49 schreef Jaakko Pasanen ***@***.***
