### ISSUE TITLE
Compensation and Sound Signature question.

### ISSUE THREAD

**Issue by Crossfeet606441** [jaakkopasanen/AutoEq#415]
Forgive me if I make any mistakes with what I'm saying here. Because, I'm still trying to figure this out. Also, please forgive me if the formatting of this post is weird. It's my first time posting an "issue" on GH.

Anyway...

I was able to finally get the AutoEQ cmd thing to work and generate my own headphones conversions. From what I understand, sans the input and output directories, I have to use "compensation=" if I'm to convert my headphones to sound like the Harman Target or diffused field or etc. And if I were to convert my headphones to another one (say, SHP 9500 to HD560s), I just use "sound_signature=" after the "compensation=" (and bass_boost=4) and it will add the sound signature of the target headphone on the compensation. Ok, got it.

Now, here's the question: Why can't I just skip the "sound_signature=" all together and just directly input it in the "compensation=" (and remove bass boost) if compensation is basically just tuning it to—what is essentially—another signature?

Like, instead of:

> --compensation="measurements\rtings\resources\rtings_harman_over-ear_2018_wo_bass.csv" --sound_signature="measurements\rtings\data\onear\Sennheiser HD 560S\Sennheiser HD 560S.csv"

...why can't I just go and do:

> --compensation="measurements\rtings\data\onear\Sennheiser HD 560S\Sennheiser HD 560S.csv"

Yes, I have tried both and have generated their results:

`python autoeq.py --input_dir="measurements\rtings\data\onear\Philips SHP9500" --output_dir="my_results\Test\1" --compensation="measurements\rtings\resources\rtings_harman_over-ear_2018_wo_bass.csv" --sound_signature="measurements\rtings\data\onear\Sennheiser HD 560S\Sennheiser HD 560S.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --bass_boost=4 --fs=44100,48000`

> Preamp: -6.1 dB
> Filter 1: ON PK Fc 31 Hz Gain 6.3 dB Q 1.41
> Filter 2: ON PK Fc 62 Hz Gain -0.9 dB Q 1.41
> Filter 3: ON PK Fc 125 Hz Gain -4.2 dB Q 1.41
> Filter 4: ON PK Fc 250 Hz Gain -4.7 dB Q 1.41
> Filter 5: ON PK Fc 500 Hz Gain -1.1 dB Q 1.41
> Filter 6: ON PK Fc 1000 Hz Gain -2.5 dB Q 1.41
> Filter 7: ON PK Fc 2000 Hz Gain 5.1 dB Q 1.41
> Filter 8: ON PK Fc 4000 Hz Gain 4.1 dB Q 1.41
> Filter 9: ON PK Fc 8000 Hz Gain 1.1 dB Q 1.41
> Filter 10: ON PK Fc 16000 Hz Gain -10.1 dB Q 1.41

`python autoeq.py --input_dir="measurements\rtings\data\onear\Philips SHP9500" --output_dir="my_results\Test\2" --compensation="measurements\rtings\data\onear\Sennheiser HD 560S\Sennheiser HD 560S.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --fs=44100,48000`

> Preamp: -6.3 dB
> Filter 1: ON PK Fc 31 Hz Gain 6.0 dB Q 1.41
> Filter 2: ON PK Fc 62 Hz Gain -0.3 dB Q 1.41
> Filter 3: ON PK Fc 125 Hz Gain -1.4 dB Q 1.41
> Filter 4: ON PK Fc 250 Hz Gain -0.4 dB Q 1.41
> Filter 5: ON PK Fc 500 Hz Gain 0.6 dB Q 1.41
> Filter 6: ON PK Fc 1000 Hz Gain -0.2 dB Q 1.41
> Filter 7: ON PK Fc 2000 Hz Gain 1.1 dB Q 1.41
> Filter 8: ON PK Fc 4000 Hz Gain -0.3 dB Q 1.41
> Filter 9: ON PK Fc 8000 Hz Gain -1.0 dB Q 1.41
> Filter 10: ON PK Fc 16000 Hz Gain 6.1 dB Q 1.41

Long story short, while low-bass seems to be practically similar, the mid-bass to mid-mid is lower on the 1st test than on the 2nd test (disregard the treble, for now).

Also, I checked the frequency responses of each headphones. The mids are almost similar. So, theoretically speaking, the "valley" on the 1st method should not exist and should be something similar to the 2nd method. But I feel like I'm doing something wrong here.

What is happening? Is there something I'm missing or should I do or not do?

If you're also interested, here's the parametric version:

First Method:

> Preamp: -7.1 dB
> Filter 1: ON PK Fc 19 Hz Gain 7.1 dB Q 0.36 
> Filter 2: ON PK Fc 163 Hz Gain -5.7 dB Q 0.32 
> Filter 3: ON PK Fc 3087 Hz Gain 7.2 dB Q 0.95 
> Filter 4: ON PK Fc 5772 Hz Gain -6.4 dB Q 4.44 
> Filter 5: ON PK Fc 8526 Hz Gain 2.1 dB Q 3.42 
> Filter 6: ON PK Fc 1280 Hz Gain -1.5 dB Q 1.91 
> Filter 7: ON PK Fc 2053 Hz Gain 2.3 dB Q 4.68 
> Filter 8: ON PK Fc 11034 Hz Gain 3.0 dB Q 1.02 
> Filter 9: ON PK Fc 19479 Hz Gain -7.3 dB Q 0.33 
> Filter 10: ON PK Fc 19890 Hz Gain -7.1 dB Q 0.45

Second Method:

> Preamp: -6.3 dB
> Filter 1: ON PK Fc 21 Hz Gain 6.1 dB Q 0.69 
> Filter 2: ON PK Fc 112 Hz Gain -1.6 dB Q 0.95 
> Filter 3: ON PK Fc 2286 Hz Gain 2.3 dB Q 4.69 
> Filter 4: ON PK Fc 6134 Hz Gain -4.5 dB Q 3.15 
> Filter 5: ON PK Fc 19177 Hz Gain 4.7 dB Q 0.23 
> Filter 6: ON PK Fc 592 Hz Gain 0.7 dB Q 1.90 
> Filter 7: ON PK Fc 4139 Hz Gain -0.9 dB Q 2.92 
> Filter 8: ON PK Fc 4413 Hz Gain 0.9 dB Q 5.47 
> Filter 9: ON PK Fc 4438 Hz Gain 2.0 dB Q 4.94 
> Filter 10: ON PK Fc 5228 Hz Gain -1.1 dB Q 4.62

**Comment by jaakkopasanen** [comment]
You can use other headphone as target without sound signature when both are from the same source (which they are in this case both from Rtings). Sound signature with normal target  (such as Harman-like) will make this possible with different sources for the measurement and the sound signature. When you use sound signature, that needs to be the result, not measurement. The sound signature is added to the target curve at each frequency so the sound signature needs to be target headphone's deviation from the same target. When you use result file, AutoEq picks up the sound signature data from the error column and if there is no error column, raw column is used. Here you are using measurement as the sound signature so in effect your doubling the normal (Harman) target.

**Comment by Crossfeet606441** [comment]
Thanks for the clarification.
