### ISSUE TITLE
[not an issue, just a heads up] Tool to parse Parametric EQ data to CamillaDSP config

### ISSUE THREAD

**Issue by Ebert-Hanke** [jaakkopasanen/AutoEq#417]
First of all: Thank you for this amazing project! I enjoy my headphones so much more because of this!

I started using [CamillaDSP](https://github.com/HEnquist/camilladsp) in [moOde player](https://github.com/moode-player/moode) to listen with headphones and since copying the values from here by hand was a bit cumbersome I started working on a little tool to do this automatically. I just wanted to let you know of it and check if it is ok with you to use the data from this repo in that kind of way. 
This is it: [autoeq2camilladsp](https://github.com/Ebert-Hanke/autoeq2camilladsp)

For the moment I prefer to use ParamEQ instead of the impulse response files, thats why I wrote this parser. Obviously using the `.wav` files makes it a lot easier to make a correction config for a set of headphones.
It is still a very rough prototype but if it is useful for others as well I will try to improve it soon. Just wanted to check with you first. 

Atm I am basically scraping the Parametric EQ data off this repo ... relatively quick and dirty.
Just let me know if this is basically ok with you and if there is any specific credit I should include in the generated config or something. 

Thank you!

**Comment by Ebert-Hanke** [comment]
Follow up:
I include a header comment for the built configuration file now which gives credit to you and AutoEq for the correction data. 

[Header Credits](https://github.com/Ebert-Hanke/autoeq2camilladsp/blob/main/src/data/header.yml)

**Comment by jaakkopasanen** [comment]
Very cool! This is, however, a bit out of scope of AutoEq itself and I try to keep the list of eq software somewhat limited and therefore cannot do anything else here but to hope people will find this issue or your tool directly.
