### ISSUE TITLE
The raw data I measured and the raw data used for the equalization differs significantly.

### ISSUE THREAD

**Issue by sudeep-ph** [jaakkopasanen/AutoEq#419]
Hi,
My OnePlus Buds Z2 have not been measured and so I found a frequency response graph and measured the raw data. After equalizing (I have used many different settings and compensation data) the raw data used for the equalization differs significantly from the raw data I measured. Subsequently, the graphs differ too. What am I doing wrong? 
Any help would be appreciated.
Thanks
[after equalization.csv](https://github.com/jaakkopasanen/AutoEq/files/8015739/after.equalization.csv)
[before equalization.csv](https://github.com/jaakkopasanen/AutoEq/files/8015753/before.equalization.csv)

**Comment by jaakkopasanen** [comment]
Did you use `--standardize_input` by any chance? That will interpolate and center the input ie. the measurement data file. The file will be overwritten.

**Comment by jaakkopasanen** [comment]
The measurement data is always interpolated and centered for the result file. This is expected behavior.

**Comment by jaakkopasanen** [comment]
That's probably the frequency response measurement you found and the potential compensation curve it uses. People out there use all sorts of creative headphone measurement systems many of which might not have a lot to do with how human ears load the headphones. Also if the measurement is compensated, then the compensation curve directly impacts the results. Rarely are the compensation curves used by random people out there sensible.

**Comment by sudeep-ph** [comment]
> That's probably the frequency response measurement you found and the potential compensation curve it uses. People out there use all sorts of creative headphone measurement systems many of which might not have a lot to do with how human ears load the headphones. Also if the measurement is compensated, then the compensation curve directly impacts the results. Rarely are the compensation curves used by random people out there sensible.

Oh ok. Thanks a lot! I've attached the frequency response graph, any suggestions on what I can do?
![OnePlus-Buds-Z2-Frequency-Chart](https://user-images.githubusercontent.com/99190885/153717031-18b82ad4-cba6-40d5-84bd-5d11069ee819.jpg)

**Comment by jaakkopasanen** [comment]
Looks like the purple is the target and the cyan is the measurement. Parse both separately use the parsed target CSV as your compnesation. If you already did this and don't like the results, you need to do manual adjustments.
