### ISSUE TITLE
AutoEQ won't accept q values

### ISSUE THREAD

**Issue by JD809** [jaakkopasanen/AutoEq#42]
After inputting frequences and q values for a fixed band preset within venv an error is returned: 
ValueError: Initializer type '<dtype: 'float64'>' and explicit dtype 'float32' don't match.

I'm unable to get around the issue and unable to generate a fixed band preset for my headphones.

**Comment by jaakkopasanen** [comment]
Thanks for reporting. This should be fixed now. Could you try it out and close this issue if the problem has disappeared?

**Comment by JD809** [comment]
Seems to be fixed!
