### ISSUE TITLE
ubuntu 0.24 - File "autoeq.py", line 6 No module named 'soundfile'

### ISSUE THREAD

**Issue by estemanito** [jaakkopasanen/AutoEq#420]
hi, im trying to use autoeq  on my new ubuntu 0.24 but im getting the soundfile error. I installed the libsndfile file by

`sudo apt-get install libsndfile-dev`

then i did:

`~/AutoEq$ python3 autoeq.py --input_dir='/home/max/AutoEq/my_data/letshouer_s12/' --output_dir="my_results/letshouer_s12" --compensation="compensation/harman_in-ear_2019v2_wo_bass.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --convolution_eq --bass_boost=6 --standardize_input`

and i get:

`Traceback (most recent call last):
  File "autoeq.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'`

My CSV file content:
[https://mega.nz/file/5aBy2Zba#BuMuCrPB7IY-4tNbsm0rtX3YgBJbejW27fkRrC_qIOg](url)

**System:**
 - OS: UBUNTU
 - Version 0.24
`~/AutoEq$ python3 --version
Python 3.8.10`

More info:

`~/AutoEq$ sudo python3 autoeq.py --help`

`Traceback (most recent call last):
  File "autoeq.py", line 6, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'`

`~/AutoEq$ sudo python3 -m pip install -U -r measurements/dev-requirements.txt`

`[sudo] password for max: 
Requirement already up-to-date: requests~=2.22.0 in /usr/lib/python3/dist-packages (from -r measurements/dev-requirements.txt (line 1)) (2.22.0)
Collecting PyPDF2~=1.26.0
  Downloading PyPDF2-1.26.0.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 4.0 MB/s 
Collecting ghostscript~=0.6
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Collecting beautifulsoup4~=4.8.2
  Downloading beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 26.1 MB/s 
Collecting selenium~=3.141.0
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 78.4 MB/s 
Collecting rapidfuzz~=0.2.1
  Downloading rapidfuzz-0.2.2-cp38-cp38-manylinux2010_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 71.6 MB/s 
Collecting ipywidgets
  Downloading ipywidgets-7.6.5-py2.py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 94.3 MB/s 
Collecting jupyterlab
  Downloading jupyterlab-3.2.9-py3-none-any.whl (8.5 MB)
     |████████████████████████████████| 8.5 MB 98.9 MB/s 
Requirement already satisfied, skipping upgrade: setuptools>=38.6.0 in /usr/lib/python3/dist-packages (from ghostscript~=0.6->-r measurements/dev-requirements.txt (line 3)) (45.2.0)
Collecting soupsieve>=1.2
  Downloading soupsieve-2.3.1-py3-none-any.whl (37 kB)
Requirement already satisfied, skipping upgrade: urllib3 in /usr/lib/python3/dist-packages (from selenium~=3.141.0->-r measurements/dev-requirements.txt (line 5)) (1.25.8)
Collecting pybind11>=2.4
  Downloading pybind11-2.9.1-py2.py3-none-any.whl (211 kB)
     |████████████████████████████████| 211 kB 85.9 MB/s 
Collecting traitlets>=4.3.1
  Downloading traitlets-5.1.1-py3-none-any.whl (102 kB)
     |████████████████████████████████| 102 kB 32.0 MB/s 
Collecting widgetsnbextension~=3.5.0
  Downloading widgetsnbextension-3.5.2-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 82.2 MB/s 
Collecting ipython>=4.0.0; python_version >= "3.3"
  Downloading ipython-8.0.1-py3-none-any.whl (747 kB)
     |████████████████████████████████| 747 kB 95.8 MB/s 
Collecting ipython-genutils~=0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting nbformat>=4.2.0
  Downloading nbformat-5.1.3-py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 95.1 MB/s 
Collecting ipykernel>=4.5.1
  Downloading ipykernel-6.9.0-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 76.5 MB/s 
Collecting jupyterlab-widgets>=1.0.0; python_version >= "3.6"
  Downloading jupyterlab_widgets-1.0.2-py3-none-any.whl (243 kB)
     |████████████████████████████████| 243 kB 87.2 MB/s 
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 15.7 MB/s 
Collecting jupyterlab-server~=2.3
  Downloading jupyterlab_server-2.10.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 15.2 MB/s 
Collecting tornado>=6.1.0
  Downloading tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl (427 kB)
     |████████████████████████████████| 427 kB 95.5 MB/s 
Collecting jinja2>=2.1
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 96.6 MB/s 
Collecting nbclassic~=0.2
  Downloading nbclassic-0.3.5-py3-none-any.whl (25 kB)
Collecting jupyter-core
  Downloading jupyter_core-4.9.1-py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 18.8 MB/s 
Collecting jupyter-server~=1.4
  Downloading jupyter_server-1.13.5-py3-none-any.whl (397 kB)
     |████████████████████████████████| 397 kB 92.7 MB/s 
Collecting notebook>=4.4.1
  Downloading notebook-6.4.8-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 97.0 MB/s 
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied, skipping upgrade: pexpect>4.3; sys_platform != "win32" in /usr/lib/python3/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->-r measurements/dev-requirements.txt (line 7)) (4.6.0)
Collecting black
  Downloading black-22.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 99.0 MB/s 
Collecting matplotlib-inline
  Downloading matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
     |████████████████████████████████| 380 kB 97.9 MB/s 
Collecting jedi>=0.16
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 92.8 MB/s 
Collecting pygments
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 95.3 MB/s 
Collecting stack-data
  Downloading stack_data-0.1.4-py3-none-any.whl (20 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 3.6 MB/s 
Collecting debugpy<2.0,>=1.0.0
  Downloading debugpy-1.5.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 95.5 MB/s 
Collecting jupyter-client<8.0
  Downloading jupyter_client-7.1.2-py3-none-any.whl (130 kB)
     |████████████████████████████████| 130 kB 98.2 MB/s 
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.4-py3-none-any.whl (5.1 kB)
Requirement already satisfied, skipping upgrade: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (2.4.6)
Collecting babel
  Downloading Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
     |████████████████████████████████| 8.8 MB 96.3 MB/s 
Collecting json5
  Downloading json5-0.9.6-py2.py3-none-any.whl (18 kB)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /usr/lib/python3/dist-packages (from jupyterlab-server~=2.3->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (0.3)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl (30 kB)
Collecting anyio<4,>=3.1.0
  Downloading anyio-3.5.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 22.5 MB/s 
Collecting websocket-client
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 6.3 MB/s 
Collecting pyzmq>=17
  Downloading pyzmq-22.3.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 96.1 MB/s 
Collecting prometheus-client
  Downloading prometheus_client-0.13.1-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 5.4 MB/s 
Collecting nbconvert
  Downloading nbconvert-6.4.2-py3-none-any.whl (558 kB)
     |████████████████████████████████| 558 kB 89.4 MB/s 
Collecting terminado>=0.8.3
  Downloading terminado-0.13.1-py3-none-any.whl (14 kB)
Collecting argon2-cffi
  Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting Send2Trash
  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting platformdirs>=2
  Downloading platformdirs-2.5.0-py3-none-any.whl (14 kB)
Collecting typing-extensions>=3.10.0.0; python_version < "3.10"
  Downloading typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting click>=8.0.0
  Downloading click-8.0.3-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 22.1 MB/s 
Collecting pathspec>=0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting tomli>=1.1.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 31.1 MB/s 
Collecting executing
  Downloading executing-0.8.2-py2.py3-none-any.whl (16 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting asttokens
  Downloading asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting importlib-resources>=1.4.0; python_version < "3.9"
  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting attrs>=17.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 24.1 MB/s 
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (119 kB)
     |████████████████████████████████| 119 kB 91.1 MB/s 
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets->-r measurements/dev-requirements.txt (line 7)) (2.7.3)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in /usr/lib/python3/dist-packages (from babel->jupyterlab-server~=2.3->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (2019.3)
Collecting sniffio>=1.1
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied, skipping upgrade: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<4,>=3.1.0->jupyter-server~=1.4->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (2.8)
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting testpath
  Downloading testpath-0.5.0-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 11.4 MB/s 
Collecting nbclient<0.6.0,>=0.5.0
  Downloading nbclient-0.5.10-py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 24.2 MB/s 
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting bleach
  Downloading bleach-4.1.0-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 86.2 MB/s 
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting ptyprocess; os_name != "nt"
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting argon2-cffi-bindings
  Downloading argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (86 kB)
     |████████████████████████████████| 86 kB 15.5 MB/s 
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from asttokens->stack-data->ipython>=4.0.0; python_version >= "3.3"->ipywidgets->-r measurements/dev-requirements.txt (line 7)) (1.14.0)
Collecting zipp>=3.1.0; python_version < "3.10"
  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied, skipping upgrade: webencodings in /usr/lib/python3/dist-packages (from bleach->nbconvert->jupyter-server~=1.4->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (0.5.1)
Requirement already satisfied, skipping upgrade: cffi>=1.0.1 in /usr/lib/python3/dist-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server~=1.4->jupyterlab->-r measurements/dev-requirements.txt (line 8)) (1.14.0)
Building wheels for collected packages: PyPDF2
  Building wheel for PyPDF2 (setup.py) ... done
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61084 sha256=8d35b2b80a882af564379f8d5594603a2c962f0bef53f44d58c8eede4c0f7e3d
  Stored in directory: /root/.cache/pip/wheels/b1/1a/8f/a4c34be976825a2f7948d0fa40907598d69834f8ab5889de11
Successfully built PyPDF2
Installing collected packages: PyPDF2, ghostscript, soupsieve, beautifulsoup4, selenium, pybind11, rapidfuzz, traitlets, tornado, pyzmq, MarkupSafe, jinja2, ipython-genutils, jupyter-core, zipp, importlib-resources, attrs, pyrsistent, jsonschema, nbformat, matplotlib-inline, debugpy, nest-asyncio, jupyter-client, pickleshare, backcall, mypy-extensions, platformdirs, typing-extensions, click, pathspec, tomli, black, decorator, wcwidth, prompt-toolkit, parso, jedi, pygments, executing, pure-eval, asttokens, stack-data, ipython, ipykernel, pandocfilters, testpath, nbclient, mistune, defusedxml, packaging, bleach, jupyterlab-pygments, nbconvert, prometheus-client, ptyprocess, terminado, Send2Trash, argon2-cffi-bindings, argon2-cffi, notebook, widgetsnbextension, jupyterlab-widgets, ipywidgets, babel, json5, sniffio, anyio, websocket-client, jupyter-server, jupyterlab-server, nbclassic, jupyterlab
  Attempting uninstall: click
    Found existing installation: Click 7.0
    Not uninstalling click at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Click'. No files were found to uninstall.
Successfully installed MarkupSafe-2.0.1 PyPDF2-1.26.0 Send2Trash-1.8.0 anyio-3.5.0 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 asttokens-2.0.5 attrs-21.4.0 babel-2.9.1 backcall-0.2.0 beautifulsoup4-4.8.2 black-22.1.0 bleach-4.1.0 click-8.0.3 debugpy-1.5.1 decorator-5.1.1 defusedxml-0.7.1 executing-0.8.2 ghostscript-0.7 importlib-resources-5.4.0 ipykernel-6.9.0 ipython-8.0.1 ipython-genutils-0.2.0 ipywidgets-7.6.5 jedi-0.18.1 jinja2-3.0.3 json5-0.9.6 jsonschema-4.4.0 jupyter-client-7.1.2 jupyter-core-4.9.1 jupyter-server-1.13.5 jupyterlab-3.2.9 jupyterlab-pygments-0.1.2 jupyterlab-server-2.10.3 jupyterlab-widgets-1.0.2 matplotlib-inline-0.1.3 mistune-0.8.4 mypy-extensions-0.4.3 nbclassic-0.3.5 nbclient-0.5.10 nbconvert-6.4.2 nbformat-5.1.3 nest-asyncio-1.5.4 notebook-6.4.8 packaging-21.3 pandocfilters-1.5.0 parso-0.8.3 pathspec-0.9.0 pickleshare-0.7.5 platformdirs-2.5.0 prometheus-client-0.13.1 prompt-toolkit-3.0.28 ptyprocess-0.7.0 pure-eval-0.2.2 pybind11-2.9.1 pygments-2.11.2 pyrsistent-0.18.1 pyzmq-22.3.0 rapidfuzz-0.2.2 selenium-3.141.0 sniffio-1.2.0 soupsieve-2.3.1 stack-data-0.1.4 terminado-0.13.1 testpath-0.5.0 tomli-2.0.1 tornado-6.1 traitlets-5.1.1 typing-extensions-4.0.1 wcwidth-0.2.5 websocket-client-1.2.3 widgetsnbextension-3.5.2 zipp-3.7.0`

ofc i activated venv first ... Any help would be appreciated, thank you :)

**Comment by jaakkopasanen** [comment]
Try this `sudo apt-get install libsndfile1`

**Comment by estemanito** [comment]
> Try this `sudo apt-get install libsndfile1`

its already installed and it changes nothing, i get the same error

**Comment by jaakkopasanen** [comment]
In that case I can't help you. Sorry.

**Comment by 4809381693** [comment]
9k

**Comment by estemanito** [comment]
> 

what is this...?


> In that case I can't help you. Sorry.

really, you have no idea...?

**Comment by jaakkopasanen** [comment]
Contrary to popular belief, I actually don't know everything.

**Comment by estemanito** [comment]
> Contrary to popular belief, I actually don't know everything.

lol, ok but you coded it yes...? what is that line 6 error? maybe i need to do something else to make it works...

**Comment by jaakkopasanen** [comment]
This is a problem with your OS, not in AutoEq. AutoEq depends on this `libsndfile` library to exist on your OS which should be installed correctly with `sudo apt-get` but in your case doesn't for one reason or another. I don't have this problem myself on Ubuntu (though haven't ran AutoEq on Ubuntu for quite a while now) so I can't really say what might be wrong with your OS.

**Comment by estemanito** [comment]
i installed pipewire in this computer, maybe it could be a relation...?
