### ISSUE TITLE
any chance Sennheiser HD 599 get most recent update?

### ISSUE THREAD

**Issue by TheBestKmanEver** [jaakkopasanen/AutoEq#423]
is there any chance that the Sennheiser HD 599 will get the "New measurements and results"??

**Comment by jaakkopasanen** [comment]
New measurements and results means new headphones were added. Existing ones are not typically updated as there's no need. Is there something you're not happy with your EQ settings?

**Comment by TheBestKmanEver** [comment]
Oh ok i was unaware of it meaning new headphones were added. No issue
