### ISSUE TITLE
[Headphone Request]  New oratory1990 onear measurements

### ISSUE THREAD

**Issue by eladri100** [jaakkopasanen/AutoEq#427]
First of all thank you so much for this brilliant project.

I have noticed that oratory1990 has measured new onears that are missing (a few of them are not actually new but they are missing anyway) such as:

1. Astro   A40 TR	
2. Audeze   LCD-5	
3. Beyerdynamic   Custom One Pro Plus   -   bass slider 3/4 (the velour earpads version is already added)
4. Beyerdynamic   DT250   -   80 ohm	
5. Beyerdynamic   DT700 Pro X	
6. Beyerdynamic   DT900 Pro X	
7. Beyerdynamic   T70	
8. Beyerdynamic   TYGR 300R	
9. Campfire Audio   Cascade	
10. Dan Clark Audio   Aeon X Closed	
11. Dan Clark Audio   Stealth	
12. Focal   Clear MG	
13. Hifiman   HE1000se	
14. Hifiman   HE-X4	
15. Massdrop   Panda   -   Pre production
16. Meze   Elite   -   Alcantara earpads
17. Meze   Elite   -   Hybrid earpads
18. Monoprice   Modern Retro   -   Dekoni Elite Hybrid Earpads
19. Monoprice   Modern Retro   -   Perfect seal
20. Sendy   Peacock	
21. Sennheiser   HD579	
22. Sennheiser   HD660S   -   Dekoni Fenestrated Sheepskin Earpads
23. Sennheiser   HD700   -   Dekoni Elite Velours Earpads
24. Sennheiser   HD800   -   SDR mod
25. Stax   SR Lambda Pro Classic   -   Bad seal
26. V-Moda   Crossfade LP2	
27. Yamaha   RH-5Ma	

Also there are some onears that oratory1990 has measured again or modified so their frequency response can posibly differ from the one in this project, like:

1. AKG   K240 Sextett   
2. AKG   K271 MK.II   
3. AKG   K371   
4. AKG   K712   
5. AKG   K7XX   
6. Apple   AirPods Max   
7. Audeze   LCD-2 Classic   
8. Audeze   LCD-3   
9. Audeze   LCD-4   
10. Audeze   LCD-4z   
11. Audeze   LCD-X   -   2021 revision
12. Audeze   LCD-XC   -   Pre 2021
13. Audeze   Sine   -   Cipher Cable
14. Audeze   Sine   -   MSR-7 earpads
15. Audeze   Sine   
16. Audio Technica   ATH-A2000Z   
17. Audio Technica   ATH-M50x   
18. Aurorus   Borealis   
19. Austrian Audio   Hi-X55   
20. Austrian Audio   Hi-X65   
21. Bang & Olufsen   H95   
22. Beats   Solo Pro   
23. Beyerdynamic   Amiron Home   
24. Beyerdynamic   Aventho Wireless   
25. Beyerdynamic   DT1990   -   Analytic earpads
26. Beyerdynamic   DT770   -   Dekoni hybrid earpads
27. Beyerdynamic   DT770   -   Fresh earpads
28. Beyerdynamic   DT770   -   Worn earpads
29. Beyerdynamic   DT770M   
30. Beyerdynamic   DT880   -   Fresh earpads
31. Beyerdynamic   T1 2nd   
32. Beyerdynamic   T5 3rd   
33. Creative   Aurvana Live!   
34. Dali   iO-4   
35. Dan Clark Audio   Aeon 2 Closed   
36. Dan Clark Audio   Aeon 2 Open   
37. Dan Clark Audio   Aeon X Open   
38. Denon   AH-D9200   
39. Focal   Celestee   
40. Focal   Clear   
41. Focal   Elear   
42. Focal   Elegia   
43. Focal   Elex   
44. Focal   Radiance   
45. Focal   Stellia   
46. Focal   Utopia   
47. Fostex   TH500RP   
48. Fostex   TH909   
49. Fostex   TH-X00 Purpleheart   
50. Grado   SR60e   
51. HarmonicDyne   Zeus   
52. Hifiman   Ananda   
53. Hifiman   Arya   
54. Hifiman   Deva   -   Wired
55. Hifiman   HE400i   -   2020
56. Hifiman   HE4XX   
57. Hifiman   HE5XX   
58. Hifiman   HE6se   
59. Hifiman   Jade II   
60. Hifiman   Sundara   -   2020 revised earpads
61. Koss   ESP/95X   
62. Koss   KSC75   
63. Koss   Porta Pro   -   Yaxi earpads
64. Meze   99 Noir   
65. Neumann   NDH20   
66. Oppo   PM3   
67. Philips   Fidelio X2   
68. Philips   SHP9500   
69. PSB   M4U 8   
70. Sendy   Aiva   
71. Sennheiser   G4ME ONE   
72. Sennheiser   HD25-1 II   -   Bad seal (the "HD 25-1 II" in this project is the Good seal version)
73. Sennheiser   HD560S   
74. Sennheiser   HD58X   
75. Sennheiser   HD598CS   
76. Sennheiser   HD598SR   
77. Sennheiser   HD600   
78. Sennheiser   HD650   
79. Sennheiser   HD660S   
80. Sennheiser   HD700   
81. Sennheiser   HD800   
82. Sennheiser   HD800S   -   Dekoni fenestrated sheepskin earpads
83. Sennheiser   HD800S   
84. Sennheiser   HE1   
85. Sennheiser   Momentum 3 Wireless   
86. Sennheiser   PC37X   
87. Sennheiser   PXC550-II
88. Shure   SRH1540   
89. Shure   SRH840   
90. Sony   MDR-7506   
91. Sony   WH1000XM3   
92. Sony   WH1000XM4   
93. Stax   SR-007mk1   
94. Stax   SR-009   
95. Stax   SR-009S   
96. Superlux   HD-668B   

I hope this information can help the project.

**Comment by douglascamata** [comment]
I'm trying to update all the oratory1990's measurements and generating the new results.

If I am successful, I'll look into adding the new onears later.

**Comment by douglascamata** [comment]
I think I've got the updated measurements in https://github.com/jaakkopasanen/AutoEq/pull/432. 💪

**Comment by eladri100** [comment]
Wow amazing job! Thank you so much. I checked my sheet and everything from the second list is updated.

The only thing is that in the branch _douglascamata/update-oratory1990-results_ it seems that some onears have disappeared, both from oratory1990's measurements and results:
1. Beyerdynamic DT 250   (this is the 250 ohm version)
2. Beyerdynamic T1 2nd Generation
3. Beyerdynamic T1 3rd Generation
4. Sennheiser "HD 25-1 II"   (the bad seal version, the "HD25-1 II" good seal version is still there)
5. Sennheiser HE 1 Orpheus 2
6. Sony WH-1000XM2
7. Sony WH-1000XM3
8. Sony WH-1000XM4

Again, thank you for your work.

**Comment by douglascamata** [comment]
@eladri100 thanks a lot for double checking, it's always good to have someone double check our work. Looks like the there was a change in the names somewhere. For example, the Sony WH-1000XM2 was present in the index with the "false name" `Sony WH1000XM2` (not dash), but after the updates it seems to have the false name `Sony WH-1000XM2` (with dash). 

I will investigate and fix them. Thx!

**Comment by eladri100** [comment]
Great! Thanks @douglascamata! Only the 27 new ones remain. Well, actually now they are 26 because the Beyerdynamic DT 250 80 ohm was added with your last fix.

**Comment by bhack** [comment]
If you are interested it was released s also HIFIMAN edition XS:

https://www.reddit.com/r/oratory1990/comments/td23j6/weekly_roratory1990_eq_thread_questions_requests/i1pm9yu/

**Comment by eladri100** [comment]
Thank you @bhack, it would be such a great addition since it´s a recommended and popular headphone lately. Personally, I would wait until oratory1990 publish the measurement at https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets, but @jaakkopasanen and @douglascamata decide.

**Comment by dinotheextinct** [comment]
Beyerdynamic DT700 Pro X seems to be still missing?

**Comment by eladri100** [comment]
> Beyerdynamic DT700 Pro X seems to be still missing?

Yes, because only those that were already have been updated (the second list: from AKG K240 Sextett to Superlux HD-668B). No new ones have been added (the first list: from Astro A40 TR to Yamaha RH-5Ma).

**Comment by jaakkopasanen** [comment]
I did a complete refresh of the oratory1990 measurements and re-computed all results.

Enjoy!
