### ISSUE TITLE
What does the "independent subset of filters" mean?

### ISSUE THREAD

**Issue by Qerbas** [jaakkopasanen/AutoEq#428]
On the results for any given headphones it'll have a line saying "In case of using parametric equalizer, apply preamp of  X and build filters manually with these parameters. The first 5 filters can be used independently. When using independent subset of filters, apply preamp of Y dB." where X is a dB value that sometimes differs from the Y value.

What exactly does it mean by this, especially the phrase in the title of this post?  For example, I'm using Peace and I assume I'm supposed to use the X value for the pre amp section.

**Comment by jaakkopasanen** [comment]
There are ten parametric eq filters given and if you can you should use all of them. If you can't (some EQ apps only have 5) you can use just then first 5 and in that case you need to set the preamp to a different value. The 5 first are the independent subset of filters.

**Comment by Qerbas** [comment]
Yeah makes sense thanks for the quick response.  The wording is just a little bit awkward in my opinion.  I would advise changing the wording to be like this then: "In case of using a parametric equalizer, apply a preamp of X and build filters manually with these parameters. If your EQ app can only use 5 filters, the first 5 can be used independently.  When using just the first 5 apply a preamp of Y dB."

**Comment by jaakkopasanen** [comment]
AutoEq can produce more than two sets of independent filters so the wording (which is generated automatically based on the number of filter sets) is the best I could do. It's surprisingly difficult to come up with a wording that can be generated easily and works with multiple pluralities.
