### ISSUE TITLE
German Mastro GMP435S is not in the list, it's been measured or not?

### ISSUE THREAD

**Issue by Dataitan** [jaakkopasanen/AutoEq#429]
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by Dataitan** [comment]
Seems reference-audio-analyzer measured GMP435S using HDM-X.

**Comment by jaakkopasanen** [comment]
Hmm. Looks like the page doesn't have the links to the reports even though Google finds the report alright. I can't really do anything but wait for them to fix this as it's not really possible to fix these things manually in AutoEq. You could of course try to contact them about this.

**Comment by jaakkopasanen** [comment]
Looks like RAA site has gone through quite large rework. I will most likely not update the crawler to encorporate this change but instead drop RAA completely from AutoEq. I've been thinking this for quite a while now because their measurements are very unreliable.

**Comment by jaakkopasanen** [comment]
As promised, I dropped Reference Audio Analyzer entirely. These measurements won't end up in AutoEq now.
