### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by aalbul** [jaakkopasanen/AutoEq#43]
Hello,

First of all, thanks for such a fantastic work! It looks really impressive.
Unfortunately, i don't have windows at all :( I think that wine or macports will not work with any of provided solution.
Do you know any software that i can use on Mac?

Thanks!

**Comment by jaakkopasanen** [comment]
There doesn't seem to be a system-wide parametric eq that is plug'n'play. I don't have a Mac so it's hard for me to recommend anything. However take a look at this Reddit thread for ideas: https://www.reddit.com/r/headphones/comments/7dcc89/systemwide_equalizer_app_for_mac_os_x/
