### ISSUE TITLE
[Headphone Requests] Tripowin Lea

### ISSUE THREAD

**Issue by Lofi69420** [jaakkopasanen/AutoEq#433]
Measurements:
https://crinacle.com/graphs/iems/tripowin-lea/

[Tripowin Lea.txt](https://github.com/jaakkopasanen/AutoEq/files/8336913/Tripowin.Lea.txt)
https://hbb.squig.link/?share=Tripowin_Lea
https://squig.link/?share=Tripowin_Lea

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Tripowin%20Le%C3%A1

Enjoy!
