### ISSUE TITLE
I would like to ask if anyone can do the autoeq of the sennheiser gsp 300 thanks

### ISSUE THREAD

**Issue by Pedr05** [jaakkopasanen/AutoEq#435]
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by jaakkopasanen** [comment]
I just updated the database and this model was not added meaning it has not been measured. Perhaps one day it will, or not. Closing the issue as headphone requests are not something I can do.
