### ISSUE TITLE
Wrong value in HIFIMAN HE1000se PEQ settings

### ISSUE THREAD

**Issue by FLiNT-13-7** [jaakkopasanen/AutoEq#438]
**Describe the bug**
[Here](https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/HIFIMAN%20HE1000se) Q value for 19470 Hz is given as 0.46. This will result in massive deviation (up to -4 dB) above 3 kHz. (See pic 1)

Changing the value to 1.75 will result in an almost perfect match. (See pic 2)

**To Reproduce**
Enter values in Peace (or whatever PEQ you use).

**Expected behavior**

**Files**
![bugged](https://user-images.githubusercontent.com/36166008/160674879-33f64666-35db-4336-806b-2a416ff79519.png)
![fixed](https://user-images.githubusercontent.com/36166008/160674897-db374513-aa75-46ae-b585-6e9a2a15a44a.png)

**System:**
 - OS: Any

**Comment by jaakkopasanen** [comment]
This is a known issue discussed in #240. Please take a look at that thread if you wish to know more.
