### ISSUE TITLE
Issue with current AutoEQ data for Aurorus Audio Australis

### ISSUE THREAD

**Issue by Exergist** [jaakkopasanen/AutoEq#439]
It looks like the source data for the Aurorus Australis comes from crinacle. However there are glaring differences between [crinacle's most recent Australis measurements](https://crinacle.com/graphs/headphones/aurorus-australis/) ([dated February 27-28, 2022](https://crinacle.com/2022/02/28/graph-database-update-27-02-22/)) and the [current Australis AutoEQ data](https://github.com/jaakkopasanen/AutoEq/tree/6e3f65c455f3f5e4209a58c6577340af1e6bfdd2/results/crinacle/gras_43ag-7_harman_over-ear_2018/Aurorus%20Australis) (added to the repo on November 28, 2021).

My understanding is that crinacle performed two rounds of measurements on the Australis because his first sample ([dated November 8, 2021](https://crinacle.com/2021/11/08/graph-database-update-08-11-21/)) was deemed to have a **broken left channel.** It looks like the current AutoEQ data corresponds with crinacle's "broken left channel" data instead of his more recent (and not borked) Australis measurements from earlier this year. 

I wanted to highlight this potential issue so that AutoEQ might be updated to leverage crinacle's most recent (i.e., good headphone sample) data.

**Comment by Exergist** [comment]
Crinacle recently incorporated AutoEQ functionality into his [Graph Comparison Tool](https://crinacle.com/graphs/headphones/graphtool/). I'm hoping that the measurement data for the Australis will be updated in the AutoEQ repo, however, as a stop-gap here is the AutoEQ output from Crinacle's graphing tool:

**Preamp**: -4.8 dB
| Type    | Fc       | Q    | Gain    |
|:--------|:---------|:-----|:--------|
| Peaking | 33 Hz    | 0.50 | 1.3 dB  |
| Peaking | 150 Hz  | 0.70 | -4.0 dB |
| Peaking | 230 Hz  | 2.00 | -1.0 dB  |
| Peaking | 370 Hz | 2.00 | 1.4 dB  |
| Peaking | 1000 Hz | 0.90 | -2.3 dB |
| Peaking | 2300 Hz    | 2.00 | 3.4 dB  |
| Peaking | 5900 Hz  | 2.00 | -5.7 dB  |
| Peaking | 6700 Hz  | 1.40 | 5.7 dB |
| Peaking | 7900 Hz  | 0.50 | 9.2 dB  |
| Peaking | 8300 Hz  | 2.00 | -5.5 dB |

![image](https://user-images.githubusercontent.com/31357974/162508774-1d6aef72-3838-4089-b09c-ab49d5e63696.png)

**Notes**:
1. The above AutoEQ output leverages Crinacle's most recent (February 2022) measurements of the Australis (i.e., both channels seemingly working properly).
2. The preamp gain is not shown on the user interface of Crinacle's Graph Comparison Tool. Instead, it is provided after exporting the AutoEQ results.

**Comment by jaakkopasanen** [comment]
This now ought to be the fixed version https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Aurorus%20Australis
