### ISSUE TITLE
HyperX Cloud Alpha S built-in bass volume switch

### ISSUE THREAD

**Issue by MettriQ** [jaakkopasanen/AutoEq#440]
Hyperx HyperX Cloud Alpha S headphones have a built-in bass volume switch on their case. What switch position are these settings for?
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/HyperX%20Cloud%20Alpha%20S
![hyperx-cloud-alpha-s-black-edition-4-1000x1000](https://user-images.githubusercontent.com/94065240/161955860-f0a0db96-c4c4-4de2-8ee6-9e1869529303.jpg)

**Comment by vysedits** [comment]
The normal setting, so with bass toggled off

**Comment by MettriQ** [comment]
> The normal setting, so with bass toggled off
I have doubts, because the off position almost completely removes low frequencies even without EQ, and EQ reduces them even more, so the choice between the middle and maximum value is probably

**Comment by jaakkopasanen** [comment]
> As we tested the HyperX Cloud Alpha S with both bass sliders are turned up, they have a sound profile that's slightly boomy and lacks detail.

It says this under the frequency response graph but that doesn't quite state which one they used for the published measurements.

The frequency response in AutoEq has quite pronounced upper bass hump which might indicate they have used the bass switches active.

You are obviously free to contact Rtings and ask but this is the extent I can help here and therefore I'm closing the issue.
