### ISSUE TITLE
(Headphone Request) Tin Hifi T3 plus

### ISSUE THREAD

**Issue by macki-sushi** [jaakkopasanen/AutoEq#442]
https://crinacle.com/graphs/iems/tin-hifi-t3-plus/

Hoping this one makes it to AutoEQ, thank you!

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Tin%20HiFi%20T3%20Plus
