### ISSUE TITLE
Samsung Galaxy Buds Pro equalization inconsistency depending on samplerate

### ISSUE THREAD

**Issue by AstellRozen** [jaakkopasanen/AutoEq#443]
Hi, I am using Samsung Galaxy Buds Pro with the AutoEq profile based on Crinacle's measurements in Neutron Music Player.
The last filter [Peaking | 19794 Hz | 0.33 | -10.5 dB] works as intended only if the samplerate of a track is exactly 44.1 kHz.
![44 1kHz](https://user-images.githubusercontent.com/54185595/163008734-c62f05e1-aaf7-49e4-a2ff-6fb8f57fd724.jpg)

If the samplerate is higher (96kHz here for example), this filter just makes the sound "go underwater":
![96kHz](https://user-images.githubusercontent.com/54185595/163009354-f4d1eceb-01bb-47f5-aa71-5386477e3e4b.jpg)

As a temporary workaround I changed this filter with [High-Shelf | 12500 Hz | 1.00 | -10.5 dB], which *kind of* gives me the same result, but this time does not depend on samplerate. Also I think it would be really good if AutoEq could use Shelf filters.

**Comment by jaakkopasanen** [comment]
This is a know issue and discussed quite a bit in #240. Please see the thread if you wish to know more.
