### ISSUE TITLE
(Submission) Nacon/Plantronics RIG 500 Pro

### ISSUE THREAD

**Issue by SirenBrink** [jaakkopasanen/AutoEq#444]
I recently got some headphones that weren't on the results list. SoundGuys happened to have a FR graph available so I made a run with it. Sorry if this is the wrong place to share results but I figured I should put this somewhere in case someone else wants it.

Also, note that the 16K on fixed band is -22.7, This is erroneous and I'd need to find a way to produce a CSV from the graph with more precision. I'm using -7.0 and it sounds pretty close to me.

### Parametric EQs
In case of using parametric equalizer, apply preamp of **-7.6dB** and build filters manually
with these parameters. The first 5 filters can be used independently.
When using independent subset of filters, apply preamp of **-7.0 dB**.

| Type    | Fc       |    Q | Gain     |
|:--------|:---------|:-----|:---------|
| Peaking | 23 Hz    | 0.54 | 3.7 dB   |
| Peaking | 228 Hz   | 0.48 | -5.0 dB  |
| Peaking | 1200 Hz  | 1.96 | -2.4 dB  |
| Peaking | 2882 Hz  | 1.24 | 6.5 dB   |
| Peaking | 5443 Hz  | 2.47 | 5.2 dB   |
| Peaking | 7173 Hz  | 1.11 | 3.7 dB   |
| Peaking | 10606 Hz | 1.46 | 1.1 dB   |
| Peaking | 19365 Hz | 0.2  | -9.3 dB  |
| Peaking | 19749 Hz | 0.35 | -10.4 dB |

### Fixed Band EQs
In case of using fixed band (also called graphic) equalizer, apply preamp of **-8.0dB**
(if available) and set gains manually with these parameters.

| Type    | Fc       |    Q | Gain     |
|:--------|:---------|:-----|:---------|
| Peaking | 31 Hz    | 1.41 | 3.8 dB   |
| Peaking | 62 Hz    | 1.41 | -0.1 dB  |
| Peaking | 125 Hz   | 1.41 | -2.7 dB  |
| Peaking | 250 Hz   | 1.41 | -4.6 dB  |
| Peaking | 500 Hz   | 1.41 | -1.8 dB  |
| Peaking | 1000 Hz  | 1.41 | -2.7 dB  |
| Peaking | 2000 Hz  | 1.41 | 2.6 dB   |
| Peaking | 4000 Hz  | 1.41 | 7.5 dB   |
| Peaking | 8000 Hz  | 1.41 | 3.2 dB   |
| Peaking | 16000 Hz | 1.41 | -22.7 dB |

[PlantronicsRig500Pro.zip](https://github.com/jaakkopasanen/AutoEq/files/8486739/PlantronicsRig500Pro.zip)

**Comment by jaakkopasanen** [comment]
I'll close the issue as Soundguys is not supported by AutoEq and I have not plans for adding the support. However maybe people in need can find this issue and use your outputs.
