### ISSUE TITLE
edifier w800bt plus

### ISSUE THREAD

**Issue by victoras136** [jaakkopasanen/AutoEq#445]
please add edifier w800bt plus or suggest a similar sounding sound stage of a headphone so i can put its auto eq

**Comment by victoras136** [comment]
edit : i created the excel for the values for my headphones but i cannot do the cmd command thing ,can someone help?

**Comment by jaakkopasanen** [comment]
I just updated the database and this model was not added meaning it has not been measured. Perhaps one day it will, or not. Closing the issue as headphone requests are not something I can do.
