### ISSUE TITLE
Arctis 7 2019 Edition Chat Channel

### ISSUE THREAD

**Issue by GuyontheGrassyKnoll** [jaakkopasanen/AutoEq#446]
Hello and thank you for compiling this impressive list of headphones EQ settings. I wanted to ask if it was possible to have the chat channels of the Arctis headsets reviewed and have their own EQ settings? I know this can be done in Equalizer APO, but my searching the internet has found zero information on the best way to equalize chat channel settings.

**Comment by jaakkopasanen** [comment]
What are these chat channels you talk about?

**Comment by GuyontheGrassyKnoll** [comment]
Some of the Arctis headsets have two output channels built into the headset. It's meant for allowing users to have separate channels for chat applications and other applications. My headset even has a channel mixer so I can turn down one or the other. Here's a screenshot of my audio output options showing the two different channels: 
![image](https://user-images.githubusercontent.com/77379756/182004072-95be18bb-3729-4bd1-aafa-06345a3ba890.png)

**Comment by jaakkopasanen** [comment]
Do these two channels sound different? I would imagine not.

In any case I'll close the issue as there's nothing I can do because Rtings doesn't mention which was measured and they only provide one set of measurements. I don't measure headphones myself.

**Comment by GuyontheGrassyKnoll** [comment]
No problem! The channels do sound different, but its really not a big deal. I'm splitting hairs with this request. Otherwise, the equalizer settings for the main channel sounds great! Thanks for your work and for taking time to respond to my request.
