### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by rostar99** [jaakkopasanen/AutoEq#45]
When verifying installation I get.
![image](https://user-images.githubusercontent.com/49513347/55939871-bbf3ac00-5bf3-11e9-86c4-92af05abdd6e.png)

**Comment by jaakkopasanen** [comment]
Which version of Python are you running? One user got similar error fixed by using Python 3.6.4.

**Comment by rostar99** [comment]
Python 3.6. Should I uninstall then install Python 3.6.4?

**Comment by rostar99** [comment]
After removing 3.6 completely and starting with a fresh setup of Autoeq all is well.
Thank you

**Comment by clodtrieste** [comment]
Hello

I have a similar problem to yours. Which version Python you have installed?
Thank you.

![cmd autoeq error](https://user-images.githubusercontent.com/50270885/57181397-5feb1300-6e93-11e9-9dd3-0189740d6f2a.GIF)
