### ISSUE TITLE
(Headphone Request) Moondrop Chu

### ISSUE THREAD

**Issue by rail01** [jaakkopasanen/AutoEq#450]
Crinacle has measured Moondrop Chu IEMs and yet EQ profile for them is not available in AutoEq repository. Can it be added?

[Link to the graph](https://crinacle.com/graphs/iems/moondrop-chu/)
![Measurements](https://crinacle.com/wp-content/uploads/2022/04/Chu.jpg)

**Comment by twyee2024** [comment]
Yes! Please add this 👍

**Comment by JoonSumisu** [comment]
plz! plz!

**Comment by dreamcat4** [comment]
*well somebody said today they tried the existing profile for the Moondrop Blessing 2, and it is a good substitute*

so at least this is a good stand-in for the meantime.

yet another person post this:

```sh
Preamp: -12 dB
Filter 1: ON PK Fc 2000 Hz Gain -2.0 dB Q 1.000
Filter 2: ON PK Fc 3000 Hz Gain -2.0 dB Q 2.000
Filter 3: ON PK Fc 4000 Hz Gain -1.5 dB Q 2.000
Filter 4: ON PK Fc 5000 Hz Gain -1.0 dB Q 2.000
Filter 5: ON PK Fc 6000 Hz Gain -1.0 dB Q 2.000
```

and result:

![chu-custom-eq-tweak-by-AlexAxel-discord-response-graph](https://user-images.githubusercontent.com/63074/166138922-62cda02c-8798-4df3-9bbe-d41b36082386.png)

**Comment by JoonSumisu** [comment]
I got one with https://apps.automeris.io/wpd/. as result, I feel it worked

here is the eq

`Preamp: -5.4 dB
Filter 1: ON PK Fc 12 Hz Gain -4.6 dB Q 0.75
Filter 2: ON PK Fc 47 Hz Gain -4.4 dB Q 0.42
Filter 3: ON PK Fc 809 Hz Gain 2.7 dB Q 1.27
Filter 4: ON PK Fc 1315 Hz Gain -2.7 dB Q 0.75
Filter 5: ON PK Fc 6896 Hz Gain 5.3 dB Q 1.47
Filter 6: ON PK Fc 25 Hz Gain -0.2 dB Q 0.12
Filter 7: ON PK Fc 99 Hz Gain 0.8 dB Q 4.95
Filter 8: ON PK Fc 10714 Hz Gain 0.6 dB Q 1.37
Filter 9: ON PK Fc 19785 Hz Gain -2.5 dB Q 0.43
`

**Comment by num421337** [comment]
How would I put this into wavelet?

**Comment by bululo** [comment]
you can download a wavelet file directly from https://crinacle.com/graphs/iems/graphtool/?share=Harman_IE_2019_v2_Target,Chu 
simply scroll down to the graph area, on the left click on equalizer, then AutoEQ just below the filter listing and then finally click on Export Graphic EQ(For Wavelet) next to it. (for this step you can refer to the EQig with graphs part of this video https://www.youtube.com/watch?v=PsijHAVLbuY if you have any doubts)

Then on wavelet youll go to autoeq, then import and choose the downloaded file from crinacle.

**Comment by num421337** [comment]
> you can download a wavelet file directly from https://crinacle.com/graphs/iems/graphtool/?share=Harman_IE_2019_v2_Target,Chu simply scroll down to the graph area, on the left click on equalizer, then AutoEQ just below the filter listing and then finally click on Export Graphic EQ(For Wavelet) next to it. (for this step you can refer to the EQig with graphs part of this video https://www.youtube.com/watch?v=PsijHAVLbuY if you have any questions still)
> 
> Then on wavelet youll go to autoeq, then import and choose the downloaded file from crinacle.


Thanks a lot, this is extremely helpful. I'm assuming this is how you can eq it to sound similar to other headphones as well

**Comment by yabo-boye** [comment]
> you can download it from an autoeq fork https://github.com/iwalton3/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Moondrop%20Chu

what other forks are out there? with other interesting targets perhaps?

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_in-ear_2019v2/Moondrop%20Chu
