### ISSUE TITLE
Sony WF-C500 [from Rtings]

### ISSUE THREAD

**Issue by quiet69** [jaakkopasanen/AutoEq#451]
Here is the graph from rtings. i'd be thankful if it gets added to AutoEq. Thanks :)
https://www.rtings.com/headphones/reviews/sony/wf-c500-truly-wireless

**Comment by quiet69** [comment]
tried following the ![guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9) and the result looks weird. Am i doing something wrong?
![Custom Art FIBAE 3](https://user-images.githubusercontent.com/43907678/167110930-68544f3a-816b-4b31-aa4d-5df0d7df9b03.png)

**Comment by quiet69** [comment]
[Sony WF-C500.pdf](https://github.com/jaakkopasanen/AutoEq/files/8737727/Sony.WF-C500.pdf)
oratory did a measurement of the earphones... i am attaching the pdf with graphs and eq here

**Comment by jaakkopasanen** [comment]
Also now in AutoEq: https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_in-ear_2019v2/Sony%20WF-C500
