### ISSUE TITLE
Samsung Galaxy Buds Live target response

### ISSUE THREAD

**Issue by Blackwing215** [jaakkopasanen/AutoEq#452]
Why has been chosen current target responce? For those earbuds it sounds pretty terrible - no bass, weak mid, unpleasent highs most of the time because of lack low and mid. Why not standart Harman Kardon target? Target that Rtings used in their review looks more reasonable.

**Comment by jaakkopasanen** [comment]
Thanks for pointing this out! I believe I marked them as earbuds when originally adding them to AutoEq based them not having the typical iear nozzles. Earbuds don't use bass boost in the target because they cannot produce strong bass due to open front volume. However, it looks like these can and therefore I will make AutoEq treat them as inears.

**Comment by Blackwing215** [comment]
@jaakkopasanen thanks for reply!
I was surprised too - they sure can bass) in general surprising sound for earbuds.

**Comment by jaakkopasanen** [comment]
Let there be bass!
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Live

**Comment by Blackwing215** [comment]
Thank you a lot! Will test this one

**Comment by junyaotan020517** [comment]
> Let there be bass! https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Live

may i know how to use it?

**Comment by Blackwing215** [comment]
> > Let there be bass! https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Live
> 
> may i know how to use it?

In README file (you will see content of it under the list of files) in the very beginning you will find link to the general user instruction. In README itself you will find values for preamp and equlizer.
