### ISSUE TITLE
250 Ohm profile for 80 Ohm headphones? (Beyerdynamic DT 990 Pro Black Edition 80 Ohm)

### ISSUE THREAD

**Issue by Mainixlul** [jaakkopasanen/AutoEq#453]
Hi,
I just wanted to know what profile I should use for the beyerdynamic dt 990 pro black edition 80 ohm because i found the dt 990 profile for 250 ohm by crinacle and i just thought that it probably is the best for my headphones. So am i correct or is there a better one for the pro version and 80 ohm?

**Comment by jaakkopasanen** [comment]
According to oratory1990 the unit variance in DT 770, DT 880 and DT 990 is greater than the difference between the drivers in the different Ohm models so you should be able to use any of the results provided. I might even drop the Ohms from the names at some point.
