### ISSUE TITLE
About the Sound Signatures 

### ISSUE THREAD

**Issue by JoonSumisu** [jaakkopasanen/AutoEq#454]
Hi Jaakko

Thank for your wonderful work

So I try to make my hd600 sound like focal utopia

with the code 

python autoeq.py --input_dir="measurements/oratory1990/data/onear/Sennheiser HD 600" --output_dir="my_results/600 to utopia" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="measurements/oratory1990/data/onear/Focal Utopia/Focal Utopia.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4 --convolution_eq --fs=17000

with Defaults --fs it gave me a PK Fc 19808 Hz Gain -8.4, which I am not sure it can work for me

by setting with fs 17000, and wish it can do something with the peak around 4k

as result 

![Sennheiser HD 600](https://user-images.githubusercontent.com/77182770/165971016-827c6f0e-1530-4de0-96ab-ddc17a7f677f.png)

which does not work, also does not work with max_filters 5+15, 5+10
can I do anything for the peak around 4k?  or the reality just can not work in this way?

**Comment by jaakkopasanen** [comment]
Parametric equalizer optimizer now has limits for filter parameters. By default the filters don't go above 10 kHz anymore so that should fix the issue. Please reopen, and elaborate more what's the problem, if the problem persists or I misunderstood it.
