### ISSUE TITLE
(Headphone Request) Hifiman Edition XS

### ISSUE THREAD

**Issue by lost-carrier** [jaakkopasanen/AutoEq#457]
Sry, I'm new here - so not exactly sure what you guys need...

However: I've found on some graph at https://forum.headphones.com/t/hifiman-edition-xs/16492

![1b3dc93b7facac9a835f81fac1338749ef93be67](https://user-images.githubusercontent.com/3090579/167496105-51a76189-4aca-4a77-a12f-144245d34880.jpeg)
.

**Comment by d3d43** [comment]
I agree. the headphones.com eq settings mess with the imaging / perceived soundstage a bit imo

**Comment by d3d43** [comment]
Already done @lost-carrier https://www.reddit.com/r/oratory1990/comments/td23j6/comment/i1pm9yu/?utm_source=share&utm_medium=web2x&context=3

**Comment by lost-carrier** [comment]
Thanks a lot, @d3d43 ! Posted 6 days ago… 😅

BTW: that guy over at headphones.com was targeting the Ananda - not Harman as far as i got it…

**Comment by bhack** [comment]
https://github.com/jaakkopasanen/AutoEq/issues/427#issuecomment-1079292029

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/HIFIMAN%20Edition%20XS
