### ISSUE TITLE
(headphone request) Monoprice AMT

### ISSUE THREAD

**Issue by hottyson** [jaakkopasanen/AutoEq#458]
I would really appreciate it if the Monoprice AMT headphone could be added.
There is a measurement taken by these guys: 
https://www.soundguys.com/monolith-by-monoprice-amt-review-65005/ 
![monoprice-monolith-amt-frequency-response](https://user-images.githubusercontent.com/86582905/168712546-90dbb61d-a4a8-4d71-8eb5-a23fd6e9b008.jpg)
Also, here is their suggested eq tuning:
![monoprice-monolith-amt-eq-suggestion-mobile-1200x788 jpg](https://user-images.githubusercontent.com/86582905/168712656-9eb2527c-45c9-4dda-bd18-a7cefe642c7e.png)
Thanks in advance if you can make a preset for the Monoprice AMT headphone.

**Comment by jaakkopasanen** [comment]
I just updated the database and this model was not added meaning it has not been measured. Perhaps one day it will, or not. Closing the issue as headphone requests are not something I can do.

Soundguys is not a supported measurement source and I have no plans of adding it, therefore these measurements won't end up in AutoEq.
