### ISSUE TITLE
About Final Audio A4000 Parametric EQs

### ISSUE THREAD

**Issue by MlCHAELJACK** [jaakkopasanen/AutoEq#459]
I am using Apple AUNBand EQ. When applying the 5th filter: Peaking | 20220 Hz | 0.43 | -8.5 dB, the whole curve drops instead of being like the graph provided by AutoEQ. Is it the problem with Apple AUNBand EQ or else I reckon the Q factor value of the 5th filter is wrong. Since I used 0.43 as bandwidth, the curve looks normal to me.

**Comment by MlCHAELJACK** [comment]
it's the issue with AUNBand. I tried one more time and it's working as normal. Please delete this issue thanks.

**Comment by jaakkopasanen** [comment]
This is a known issue discussed at length in #240. Please take a look at that thread if you wish to know more.
