### ISSUE TITLE
Sony WF-1000XM3 oratory1990 parametric recommended results huge diff to target at high frequency

### ISSUE THREAD

**Issue by Nyconing** [jaakkopasanen/AutoEq#461]
**Describe the bug**
[results/oratory1990/harman_in-ear_2019v2/Sony WF-1000XM3/README.md](https://github.com/jaakkopasanen/AutoEq/blob/89fd05b88f74307f68b8673563c07c5fcfdf3e73/results/oratory1990/harman_in-ear_2019v2/Sony%20WF-1000XM3)
Sony WF-1000XM3 oratory1990 parametric recommended result had a huge diff to the target at high frequency.
It is a huge diff and definitely hearable by anyone.
Also I found it didnt had adjustment at high frequency, maybe missing? 
![image](https://user-images.githubusercontent.com/39735988/170949885-8a74bad7-eb1a-4122-845b-b369370bb531.png)

**Expected behavior**
Maybe just like the rtings and crinacle result? It follows the target perfectly:
 [/results/rtings/rtings_harman_in-ear_2019v2/Sony%20WF-1000XM3](https://github.com/jaakkopasanen/AutoEq/tree/89fd05b88f74307f68b8673563c07c5fcfdf3e73/results/rtings/rtings_harman_in-ear_2019v2/Sony%20WF-1000XM3)
[/results/crinacle/harman_in-ear_2019v2/Sony%20WF-1000XM3](https://github.com/jaakkopasanen/AutoEq/tree/89fd05b88f74307f68b8673563c07c5fcfdf3e73/results/crinacle/harman_in-ear_2019v2/Sony%20WF-1000XM3)

**System:**
 - Poweramp parametric eq enabled

**remark**
crinacle and rtings do had adjustment at 19k frequency, oratory1990 dont have, highest adjustment is at 8k.
![image](https://user-images.githubusercontent.com/39735988/170955252-8548df7e-a5cf-4791-9adb-cc7f04914f2a.png)
fyi crinacle missing adjustment at low frequency too btw it didnt impact much...
rtings is better for me. Also obviously by looking at the curve, rtings had more complete curve.
Later I might want to dig into these on computer and make a complete adjustment by compare and mix them together

**Comment by Nyconing** [comment]
![image](https://user-images.githubusercontent.com/39735988/170949885-8a74bad7-eb1a-4122-845b-b369370bb531.png)

**Comment by jaakkopasanen** [comment]
AutoEq produces the parametric eq filters with an iterative approach which attempts to minimize the error between the ideal equalizer frequency response and the produced parametric equalizer frequency response. Sometimes the optimizer decides not to put any filters in the high frequencies if it thinks it can get better results by "investing" the filters somewhere else. In any case it's a bit questionable if the >10 kHz range should be equalized at all and especially with peak filters so I wouldn't worry about this one too much.
