### ISSUE TITLE
Hyper X cloud II connected thru jack.

### ISSUE THREAD

**Issue by Lupin972** [jaakkopasanen/AutoEq#465]
Good morning ,
First of all, I would like to congratulate you on the enormous work you have done, because it must have taken time
To get to the bottom of things, I currently own a Hyper X Cloud II and I plug it directly into the jack of my motherboard, in other words I do not use the USB 7.1 card supplied with this headset. The question: Do the EQ settings you provide in your research for this headset also apply to my case?

**Comment by jaakkopasanen** [comment]
I do not know. I took a quick look at the Rtings page for the measurements but they don't mention. Probably easiest if you just try both ways to check if they sound the same. If they do, you can use them with the provided eq settings with jack or USB.

Closing the issue as this is not anything that I can help further.
