### ISSUE TITLE
JLab Audio GO Air POP: which EQ settings were used in the measurement

### ISSUE THREAD

**Issue by buscon** [jaakkopasanen/AutoEq#467]
JLab Audio GO Air POP measurements are here:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/JLab%20Audio%20GO%20Air%20POP

These headphones have three EQ settings, which one was used for this measurement?

**Comment by jaakkopasanen** [comment]
> Using the 'JLab Signature' EQ, which produces the flattest EQ, the JLab Audio GO Air POP have a bass-rich sound profile.

It says this underneath the frequency response graph on Rtings [measurement report](https://www.rtings.com/headphones/reviews/jlab-audio/go-air-pop-true-wireless).
