### ISSUE TITLE
[Headphone Requests] Sony WH-1000XM5

### ISSUE THREAD

**Issue by EasyNV** [jaakkopasanen/AutoEq#468]
Hi!

Is it possible to add Sony WH-1000XM5 to auto eq settings?

Thanks!

**Comment by ColbyB722** [comment]
Seems like it was added to Wavelet (at least in the beta)

**Comment by null-dev** [comment]
RTINGS has a review up for it now: https://www.rtings.com/headphones/reviews/sony/wh-1000xm5-wireless

I've pulled down their measurements (using the [measurement downloader](https://github.com/jaakkopasanen/AutoEq/tree/master/measurements) that AutoEQ already has for RTINGS) and ran AutoEQ on them.

Here are the raw downloaded measurements (this would be in the `measurements/rtings/data/onear/Sony WH-1000XM5` folder):
[Sony WH-1000XM5.csv](https://github.com/jaakkopasanen/AutoEq/files/9078511/Sony.WH-1000XM5.csv)

Here are the AutoEQ results (these would be in the `results/rtings/rtings_harman_over-ear_2018/Sony WH-1000XM5` folder):
[Sony WH-1000XM5.zip](https://github.com/jaakkopasanen/AutoEq/files/9078512/Sony.WH-1000XM5.zip)

Alternatively, SOUNDGUYS also has an [AutoEQ GraphicEQ.txt](https://www.soundguys.com/wp-content/uploads/2022/05/Sony-WH-1000XM5SoundGuys-Consumer-Curve-v2_0-like-wavelet-file.txt) file for the XM5 in [their review](https://www.soundguys.com/sony-wh-1000xm5-review-71783/#id-eq-71783).

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Sony%20WH-1000XM5

Enjoy!

**Comment by randomsnowflake** [comment]
> https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Sony%20WH-1000XM5
> 
> Enjoy!

This does not work anymore:
```

The master branch of AutoEq does not contain the path results/rtings/rtings_harman_over-ear_2018/Sony WH-1000XM5.

```

**Comment by w1984** [comment]
> Alternatively, SOUNDGUYS also has a [Wavelet GraphicEQ.txt](https://www.soundguys.com/wp-content/uploads/2022/05/Sony-WH-1000XM5SoundGuys-Consumer-Curve-v2_0-like-wavelet-file.txt) file for the XM5 in [their review](https://www.soundguys.com/sony-wh-1000xm5-review-71783/#id-eq-71783).

Hello! Threre are EQ preset of sounguys for sony wf-1000xm4 ?
