### ISSUE TITLE
Fostex TH-610 mono format wav?

### ISSUE THREAD

**Issue by dinotheextinct** [jaakkopasanen/AutoEq#469]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Fostex%20TH610

I am trying to import the mentioned .wav file in EasyEffects Convolver and get the error that only stereo formats are supported. Is this an issue with the file or with EE Convolver?

Issue at EE Github: https://github.com/wwmm/easyeffects/issues/1582

**Comment by jaakkopasanen** [comment]
I wonder if this could be due to not using `.irs` file extension as mentioned in #434? I just added that instruction to EasyEffects documentation.
