### ISSUE TITLE
What does the unit 'dBr' of frequency response mean?

### ISSUE THREAD

**Issue by theeagleofthedesert** [jaakkopasanen/AutoEq#472]
Hi, I'm reading the measured data, but I can't find the definition of 'dBr'. Can you add an explanation? Thanks a lot!

**Comment by jaakkopasanen** [comment]
r here means relative to the reference level and the reference level is ~arbitrary. Only the levels relative to other frequencies matter in these frequency responses.

**Comment by theeagleofthedesert** [comment]
Thank you for your reply!
