### ISSUE TITLE
correct pre-amp gain

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#474]
**Describe the bug**
I see that auteq pre-amp gain calc is quite trivial:
https://github.com/jaakkopasanen/AutoEq/blob/master/autoeq.py#L117

**Expected behavior**
To mention oratory1990 and his presets:
> So the pre-amp gain is not equivalent to the highest gain parameter of any of the filters you enter, but it's equivalent to the highest gain resulting in the total transfer function (all filters combined).

https://www.reddit.com/r/oratory1990/comments/uaoxi5/weekly_roratory1990_eq_thread_questions_requests/i7jb2zp/

**Comment by dhnhgd** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/20adbc3e5c16670b18bb7ddd0580cc0480580cc3/autoeq.py

**Comment by dhnhgd** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/20adbc3e5c16670b18bb7ddd0580cc0480580cc3/autoeq.py

**Comment by dhnhgd** [comment]
[](https://github.com/jaakkopasanen/AutoEq/issues/474#issue-1284319186)

**Comment by jaakkopasanen** [comment]
`autoeq.py` gets the maximum gains for parametric equalizer filter sets already correctly calculated from the `FrequencyResponse.process()` method which gets them from `FrequencyResponse.optimize_parametric_eq()` method which calculates the values by taking the maximum gain value of the parametric eq frequency response. This is not the gain of individual filter with largest gain but the maximum of the parametric eq curve, as it should be.
