### ISSUE TITLE
Manually and Independent Subset of Filters

### ISSUE THREAD

**Issue by johnnybegoode77** [jaakkopasanen/AutoEq#475]
I'm using the Parametric EQs' data on
https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2019v2/KZ%20ZST

I don't understand what **manually** and **independently** on this statement means:
_"In the case of using a parametric equalizer, apply a preamp of -5.8dB and build filters manually with these parameters. The first 5 filters can be used independently. When using an independent subset of filters, apply a preamp of -6.0 dB."_

Yes I enter the values **manually** onto AUNBandEQ and 
every band seems to be **independent** too.
What do you exactly mean by an **independent subset of filters**?

Thank you!

<img width="551" alt="101760455-b963ec80-3a8f-11eb-8785-d0e1acc695f1" src="https://user-images.githubusercontent.com/97810541/176508244-d952fbef-cdc2-4b3d-bb64-63c60cf35e4b.png">

**Comment by jaakkopasanen** [comment]
AutoEq produces a set of parametric eq filters where you have to use all of them for a desired result. However, for the default set of parametric eq presets the filters are created in a way that the first 5 can be used without the rest. The last five cannot be used without the first five.

**Comment by johnnybegoode77** [comment]
Based on my above example, do I apply a preamp of -5.8dB or -6.0 dB."
Thank you!

**Comment by jaakkopasanen** [comment]
Use -5.8 dB as preamp if you use all 10 filters and -6.0 dB if you use only the first 5.

**Comment by jaakkopasanen** [comment]
I changed the phrasing to
> You can use filters 1-5 or 1-10. Apply preamp of -6.4 dB or -6.3 dB, respectively.

It's clearer IMO.
