### ISSUE TITLE
Announcement: AutoEQ interface incorporated into Peace Equalizer

### ISSUE THREAD

**Issue by PeterVerbeek** [jaakkopasanen/AutoEq#476]
Jaakko, I guess this isn't the best way to inform the AutoEQ community but I'm not sure how to this. So this isn't an issue but rather an announcement.

From version 1.6.2.6 the [Peace equalizer](https://sourceforge.net/projects/peace-equalizer-apo-extension/) app now has an built-in AutoEQ interface on which a user can easily find and apply an equalization of the vast AutoEQ results database. Also, I've created a stand-alone version of this interface which I've called [Bard](https://sourceforge.net/projects/bard-browser-autoeq/) (Browser for AutoEQ Results Database).

**Comment by jaakkopasanen** [comment]
Late to comment here but awesome news anyways! Looks like there was also a [Reddit post](https://www.reddit.com/r/headphones/comments/vlontp/latest_peace_makes_it_even_easier_to_import/) made by someone else at the time.

**Comment by PeterVerbeek** [comment]
Thanks, Jaakko, also for the link to the Reddit post.

Op ma 25 jul. 2022 om 08:59 schreef Jaakko Pasanen ***@***.***
