### ISSUE TITLE
[Headphone Requests] redmi buds 3 pro

### ISSUE THREAD

**Issue by RomioDiver** [jaakkopasanen/AutoEq#477]
Вибачте. Все що зміг знайти по цим навушникам, це осьцей графік на в якомусь з обзорів. Буду вдячний якщо зможете зробити пресет по ньому.
Google translate:
Sorry. All I could find on these headphones was this graph on one of the gaps. I would be grateful if you could make a presets on it.
[Schedule](https://ixbt.online/live/images/original/01/65/94/2021/08/05/5e751b93da.jpg)
[Article](https://www.ixbt.com/live/digs/xiaomi-redmi-buds-3-pro.html)

**Comment by jaakkopasanen** [comment]
I just updated the database and this model was not added meaning it has not been measured. Perhaps one day it will, or not. Closing the issue as headphone requests are not something I can do.
