### ISSUE TITLE
CCA CRA, can i use the NRA profile??

### ISSUE THREAD

**Issue by Milor123** [jaakkopasanen/AutoEq#478]
Guys i have a CCA CRA normal edition, but i dont found it in the list, could i use the CCA NRA profile for me ? Or which should be the best option for my headphones?

Thank u very much

**Comment by shikkoku** [comment]
Maybe you can refer this one:

https://github.com/iwalton3/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/CCA%20CRA
