### ISSUE TITLE
Parameters not used

### ISSUE THREAD

**Issue by Wei1234c** [jaakkopasanen/AutoEq#479]
The parameters "window_size, treble_window_size" in 
frequency_response.FrequencyResponse.process(... window_size=1 / 12, treble_window_size=2, ...)

are not passed to the following function call (line 1872):

self.smoothen_fractional_octave(
            window_size=1 / 12,
            treble_window_size=2,

**Comment by jaakkopasanen** [comment]
Good catch! Thanks a lot for pointing this out!

Turns out autoeq.py never even had these parameters.
