### ISSUE TITLE
Razer Opus 2021 model is missing

### ISSUE THREAD

**Issue by 5wHN28Dg** [jaakkopasanen/AutoEq#484]
This new model has been reviewed and measured by Rtings [here](https://www.rtings.com/headphones/reviews/razer/opus-wireless-2021)

**Comment by 5wHN28Dg** [comment]
Thanks 4 adding it

**Comment by 5wHN28Dg** [comment]
I could find the 2021 model in wavelet but it doesn't show up here in the results list, why is that?

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Razer%20Opus%202021

**Comment by silviotcs** [comment]
![Screenshot_20230927-183514-976.png](https://github.com/jaakkopasanen/AutoEq/assets/111669729/ac3ae7c1-cff8-4480-8563-e468e6810642)


Razer Opus firmware printscreen. 

Title meaning: What is new!

**Comment by silviotcs** [comment]
> This new model has been reviewed and measured by Rtings [here](https://www.rtings.com/headphones/reviews/razer/opus-wireless-2021) 

![IMG_20230929_193341068.jpg](https://github.com/jaakkopasanen/AutoEq/assets/111669729/8be9955b-1b04-4239-944f-63e3af79f731)

Right!
