### ISSUE TITLE
Still an Active Project?

### ISSUE THREAD

**Issue by Knot-The-Bees** [jaakkopasanen/AutoEq#485]
Is this still an active project as I have not seen any new updates in quite a while?

**Comment by NekoAlosama** [comment]
More that @jaakkopasanen has been inactive.
![firefox_kbmhXhqhE6](https://user-images.githubusercontent.com/47763383/179128073-5cf52c04-a713-4fd6-be4a-86bf65538ef3.png)

**Comment by Nyconing** [comment]
https://github.com/jaakkopasanen/AutoEq/commit/e8c362bfc88da952e390b59043345bce322401c7
[jaakkopasanen](https://github.com/jaakkopasanen) commited code bug fix just now, this project would already stable enough, especially for more headphones/ earphones support will need contributes from community to continue growing... ... ... although the required hardware was expensive btw

**Comment by jaakkopasanen** [comment]
This is still an active project although it was silent for a moment there. Nothing to worry, all measurements and results have just been updated.
