### ISSUE TITLE
Sound by Sweden Nero tx Pro (in-ear)

### ISSUE THREAD

**Issue by persjoberg** [jaakkopasanen/AutoEq#487]
Can you plz help with the auto eq för Sound by Sweden's Nero tx Pro? I really love the app and I think you are the right person helping me with this.

Best regards
Per Sjöberg

**Comment by jaakkopasanen** [comment]
I just updated the database and this model was not added meaning it has not been measured. Perhaps one day it will, or not. Closing the issue as headphone requests are not something I can do.
