### ISSUE TITLE
Graphs with togglable lines

### ISSUE THREAD

**Issue by Aasikki** [jaakkopasanen/AutoEq#488]
**Is your feature request related to a problem? Please describe.**
I find the graphs a little busy to look at. They have so many lines layered on top of each other, that I find it hard to focus or sometimes even see the one's I'm most interested in.

**Describe the solution you'd like**
It would be great if we could have graphs with togglable lines so we could choose which ones to view and compare. A nice bonus would be to be able to add other headphones to the graphs so you could compare between them, but that I don't find as important.

**Other notes**
I'm not really a dev but I'd by willing to help/work ln this if someone can point me to the right direction.

**Comment by jaakkopasanen** [comment]
I'm afraid this is not possible as of now. The graphs are simply pictures and the Github pages don't support any type of interactive elements.

I'll close this issue but I intend to do this if I ever get around to implementing a web app for AutoEq.
