### ISSUE TITLE
[Headphone request] Oratory1990 update eq list 07-19-2022

### ISSUE THREAD

**Issue by eladri100** [jaakkopasanen/AutoEq#489]
So Oratory1990 updated yesterday the eq list at https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets/.
Starting from @douglascamata branch https://github.com/douglascamata/AutoEq/tree/douglascamata/update-oratory1990-results, which is from 03-22-2022 and the most updated that I am aware of, these are the changes for over-ear only:

Modified:
 1. Audeze LCD-1
 2. Audio Technica ATH-M40x
 3. Audio Technica ATH-M50x
 4. Beyerdynamic  DT1770 - leather earpads
 5. Beyerdynamic  DT1770 - velour earpads
 6. Grado Hemp
 7. Hifiman Arya
 8. Hifiman HE400se
 9. Onkyo A800
10. Sennheiser HD660S
11. Sennheiser HD8XX
12. Sony MDR-Z7M2

Added or missing:
 1. AKG K701
 2. Apple AirPods Max - 3rd party pleather earpads
 3. Astro A40 TR
 4. Audeze LCD-2 Pre 2017
 5. Audeze LCD-5
 6. Audeze LCD-X - Dekoni Sheepskin Earpads
 7. Audeze LCD-XC 2021
 8. Austrian Audio Hi-X60
 9. Beyerdynamic Custom One Pro Plus - bass slider 3/4 (the velour earpads version is already added)
10. Beyerdynamic DT250 - 80 ohm
11. Beyerdynamic DT700 Pro X
12. Beyerdynamic DT900 Pro X
13. Beyerdynamic T70
14. Beyerdynamic TYGR 300R
15. Campfire Audio Cascade
16. Dan Clark Audio Aeon X Closed
17. Dan Clark Audio Stealth
18. Focal Clear MG
19. Hifiman Arya Stealth
20. Hifiman Deva Pro
21. Hifiman Edition XS
22. Hifiman HE1000se
23. Hifiman HE-X4
24. Hifiman HE6se V2
25. Hifiman Sundara - Dekoni Sheepskin pads
26. Massdrop Panda - Pre production
27. Meze Elite - Alcantara earpads
28. Meze Elite - Hybrid earpads
29. Meze Liric
30. Monoprice Modern Retro - Dekoni Elite Hybrid Earpads
31. Monoprice Modern Retro - Perfect seal
32. Nectar Hive
33. Ollo S4R 1.1
34. Sendy Peacock
35. Sennheiser HD579
36. Sennheiser HD660S - Dekoni Fenestrated Sheepskin Earpads
37. Sennheiser HD700 - Dekoni Elite Velours Earpads
38. Sennheiser HD800 - SDR mod
39. Sennheiser HD800 - SDR mod, Dekoni Fenestrated Sheepskin Earpads
40. Shure SRH440A
41. Shure SRH840A
42. Stax SR Lambda Pro Classic - Bad seal
43. T+A Solitaire P SE
44. V-Moda Crossfade LP2
45. Yamaha RH-5Ma
46. ZMF Verite

Hope this is helpful.

**Comment by douglascamata** [comment]
I can try another upgrade on the measurements & results when I get the time, @eladri100. 

I would like try to add new headphones at some point but I have to investigate a way to be sure I am doing it correctly. 😄

**Comment by eladri100** [comment]
Great, take your time.

**Comment by githubbapoopa** [comment]
Would be *very* thankfull for new wav files

25. Hifiman Sundara - Dekoni Sheepskin pads

Or some sort of help in coverting these by my own (Win10).

**Comment by jaakkopasanen** [comment]
Complete refresh of oratory1990's measurements and pre-computed results done just now. Enjoy!

**Comment by douglascamata** [comment]
Hey @jaakkopasanen, thanks for the update. I have some code laying around that enables parallel processing for results generation. I could achieve 95% processing time improvement with my CPU (Ryzen 7 3700X, 16 cores). Are you interested in such improvement to the project? :)

**Comment by douglascamata** [comment]
Also please have a look at #431 whenever you can.

**Comment by githubbapoopa** [comment]
@jaakkopasanen Thanks so much !!!
