### ISSUE TITLE
Samsung UE65MU6100 LCD TV

### ISSUE THREAD

**Issue by GGamer6458** [jaakkopasanen/AutoEq#496]
https://https://www.rtings.com/tv/1-2/graph#524/1854

https://www.rtings.com/tv/reviews/samsung/mu6100#page-verdict
![frequency-response-graph-small.jpg](https://user-images.githubusercontent.com/72705840/181828284-4f88f22b-d6d2-43ab-88e6-6db8d266eef9.jpg)

**Comment by jaakkopasanen** [comment]
This project is for headphones only.
