### ISSUE TITLE
Uncertainty about equalizing results

### ISSUE THREAD

**Issue by kamild1996** [jaakkopasanen/AutoEq#499]
My headset is Beyerdynamic DT 770 80 Ohm. I'd like to see if making them sound closer to the DT 880 (32 or 250 Ohm version, not sure) would make their high end sound more to my liking. Crinacle seems to have the data for both, but since these are apparently locked behind their Patreon, I'm trying to use other available results. 

**I'd only like to ask if I'm using the tool properly and my expectations are skewed - or did I make a misstep somewhere?**

First I tried Reference Audio Analyzer's DT 770 80 Ohm measurements against oratory's DT 880 250 Ohm results:
```
(venv) G:\AutoEQ\AutoEq>python autoeq.py --input_dir="measurements/referenceaudioanalyzer/data/onear/HDM-X/Beyerdynamic DT 770 80 Ohm" --output_dir="my_results/DT 770 like DT 880" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results/oratory1990/harman_over-ear_2018/Beyerdynamic DT 880 250 Ohm/Beyerdynamic DT 880 250 Ohm.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4 --convolution_eq --fs=44100,48000
```

Then I tried oratory's DT 770 250 Ohm measurements, thinking that having the same source of measurements and results would sound better, despite the difference in impedance:
```
(venv) G:\AutoEQ\AutoEq>python autoeq.py --input_dir="measurements/oratory1990/data/onear/Beyerdynamic DT 770 250 Ohm" --output_dir="my_results/DT 770 like DT 880 alt" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results/oratory1990/harman_over-ear_2018/Beyerdynamic DT 880 250 Ohm/Beyerdynamic DT 880 250 Ohm.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4 --convolution_eq --fs=44100,48000
```

**Comment by Suznyan** [comment]
Different impedances can still make a huge different in measurement and sound signature. You can get the data for DT 770 80Ohm and DT 880 32Ohm using these links: 
[DT 770](https://crinacle.com/graphing/data_hp_gras/DT770%20Pro%20(80%CE%A9)%20L1.txt)
[DT 880](https://crinacle.com/graphing/data_hp_gras/DT880%20Pro%20(32%CE%A9)%20L1.txt)
Change the last number of the url to L2, L3 and R1, R2, R3 for all the samples

**Comment by jaakkopasanen** [comment]
Assuming my comment answers the question. Closing the issue.
