### ISSUE TITLE
EQ for Massdrop x Sennheiser Jubilee 58X

### ISSUE THREAD

**Issue by pfrcks** [jaakkopasanen/AutoEq#5]
Hi,

Can you please add Sennheiser Jubilee 58X's EQ?

**Comment by jaakkopasanen** [comment]
Measurement is not available in any of the supported measurement databases. Maybe I'll add support for head-fi measurements at some point. I'll update here when it's available.

**Comment by jaakkopasanen** [comment]
This was measured by oratory1990 so now it's available.
