### ISSUE TITLE
[Headphone request] CCA CRA PLUS Version

### ISSUE THREAD

**Issue by FeyrisTan** [jaakkopasanen/AutoEq#502]
Got a sibilance issue with them

**Comment by kchousos** [comment]
Are the results available? I can't find them in the results index.

**Comment by rayserit** [comment]
> Are the results available? I can't find them in the results index.

I'm wondering the same, should i open a new issue?

**Comment by zhulal** [comment]
Bro little difference, Between CRA and CRA PLUS, on hi freq (hi more soft on PLUS) and bass (bass better on PLUS), please give new AutoEQ for CRA PLUS
