### ISSUE TITLE
Is it possible to make my own measurements?

### ISSUE THREAD

**Issue by FlorianKempenich** [jaakkopasanen/AutoEq#504]
Hi,

Let me start by saying, the work you're doing is absolutely incredible 😲 Thanks for your contributions 😍
I have a quick question. I've been looking at the realizer, hrtf, and other related topics for years now. I have a HeSuVi setup I'm very happy with, but I'm thinking of the next step, so I started looking at your impulcifier tool.

My question is: If I were to invest in the measurement tools recommended on the [impulcifier wiki](https://github.com/jaakkopasanen/Impulcifer/wiki/Measurements), could I use the same equipment to generate my own measurements for AutoEQ and then equalize my headphones based on these measurements?

My guess would be yes, but I haven't found any mention of that on either project 🤔 Or maybe I wasn't looking at the right place?

Anyway, if it's possible, I'd love to know how, because it might be the deciding factor that will get me to buy the measurement equipment 🙂

Thanks,
Flo

**Comment by jaakkopasanen** [comment]
In theory, yes. But unfortunately the measurements probably won't be very accurate, and this is also a problem with Impulcifer's headphone compensation. I have heard from other users that using microphones which leave ear canal open can produce pretty good results but you'd have to have some sort of calibration curve which only serves your mics and ear and therefore obviously doesn't exist.

I don't really have experience with this so can't help too much here. You might get better answers asking in [/r/oratory1990](https://www.reddit.com/r/oratory1990/).

I'll close the issue as these issues are for feature and bug tracking and this is neither.

**Comment by FlorianKempenich** [comment]
Hi,

Thanks for your answer. 

I hesitated about creating an issue, I didn't want to clutter the issue tracker, but at the bottom of the README it says
> Issues are the way to go if you are experiencing problems, have ideas **or if there is something unclear about how things are done or documented.**

Regarding the impossibility to do it, It's unfortunate really, it would have been kind of awesome 😁. Headphones custom EQed to your ears 😍. I'm a software engineer, but absolutely not a sound engineer. So, when I hear that it would require a custom calibration curve . . . that's out of my league, unfortunately. I may still post in [r/oratory1990](/https://www.reddit.com/r/oratory1990/) to see if someone could explain/streamline the process, but I'm not sure it's a rabbit hole I want to get into 😅

Anyway, thanks again for your work, it's mindblowing really 😃👍

**Comment by jaakkopasanen** [comment]
Perhaps you'd like to try out Impulcifer. It's of course a bit different than what you're asking here since it makes headphones sound like speakers but it is tailored to you ears and many would agree that it's far superior to what headphones can do naturally.

**Comment by FlorianKempenich** [comment]
I am **extremely** tempted to try Impulcifier, I've been for at least a year or so, since I discovered the project. 

The only barrier really is the £300 upfront cost for the microphone and the interface. It's much much much cheaper than a realizer, but still. And I mean if it is even better than OOYH (some preset work _really_ well for me, a shame the mac app is broken now), then it'd be worth it, but if it isn't . . . that's a lot of money invested for not much. 

I'm pretty sure at some point I **will** give it a try, this project is just too amazing for me not to try it out. But I'm waiting until I have a bit more disposable income, so I don't regret it in case it doesn't live up to the expectations. I think in this way I can also enjoy the process more, without worrying about the results 😌. So yeah, probably in a year or so I'll give it a shot 😁
