### ISSUE TITLE
[IEM REQUEST] KZ ZST X

### ISSUE THREAD

**Issue by hackmonker** [jaakkopasanen/AutoEq#505]
currently we have the kz zst but not the zst x. can it also be added if available?

**Comment by ted-devs** [comment]
@jaakkopasanen why was this closed? I can still not find the KZ ZST X profile on wavelet or the web app.

**Comment by ted-devs** [comment]
Okay thanks a lot for the explanation @jaakkopasanen. 

If its still relevant @hackmonker, I found this site which lets you autoeq, and HBB has ZST X measurements apparently so you can get a profile here: https://hbb.squig.link
