### ISSUE TITLE
[Headphones request] Sennheiser HD 350BT

### ISSUE THREAD

**Issue by shape93** [jaakkopasanen/AutoEq#507]
Hi,
is it possible to add this model to the list if available?
Thanks

**Comment by ft83** [comment]
hi there.first of all thank you for your work. i was going to ask for same request (sennheiser hd350bt) on the wavelet app i cant see autoeq for hd350bt.(not even on your github repository) can you help about adding preset?

**Comment by Cwavs** [comment]
I might be missing something, but I can't find these listed, is that to be expected?
