### ISSUE TITLE
Can we "AutoEQ" our Micrphone to Sounded similar like the neuman flagship or any other Microphone that can Produce a High Quality Voice when We talking?

### ISSUE THREAD

**Issue by Normalmeep** [jaakkopasanen/AutoEq#510]
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by jaakkopasanen** [comment]
Julia Krause has a video about the topic: https://www.youtube.com/watch?v=ctgZB4S-jz0

There's more to microphones than just frequency response, namely polar pattern, so it's not going to be perfectly the same but if the polar patterns are similar, you can get close.

You of course need to find frequency response measurements for both and save them to CSV files. Use the target mic (the flagship) as the compensation curve `--compensation`.

AutoEq is about headphones and I've no intention of adding microphones here and everything you need, except the measurements, is already in AutoEQ. I'll close the ticket as there's nothing to do here.
