### ISSUE TITLE
Bose QuietComfort 33 II by crinacle does not exist

### ISSUE THREAD

**Issue by Wrichik1999** [jaakkopasanen/AutoEq#513]
**Describe the bug**
A headphone listed as `Bose QuietComfort 33 II` with measurements from `cricacle`.
This is not a real headphone.

**To Reproduce**
Go to [results/crinacle/gras_43ag-7_harman_over-ear_2018/Bose QuietComfort 33 II](https://github.com/jaakkopasanen/AutoEq/tree/d8c90f5e7489f8f333a2041d8ea6a4601c70c5b5/results/crinacle/gras_43ag-7_harman_over-ear_2018/Bose%20QuietComfort%2033%20II)

**Expected behavior**
Should be changed to actual headphone, or removed

**Additional context**
I think this is most likely the Bose QuietComfort **35** II, not sure though.

**Comment by jaakkopasanen** [comment]
Thanks for flagging! It's fixed now.
