### ISSUE TITLE
[Feature Request] Some way to impose arbitrary constraints on EQ

### ISSUE THREAD

**Issue by nogaff** [jaakkopasanen/AutoEq#519]
**Is your feature request related to a problem? Please describe.**

Some audio players have weird EQ implementations that aren't as simple as a Fixed Band EQ but aren't fully functional Parametric EQs either.

As an example, many of the Cowon audio players and the "JetEffect" audio engine they use, have an EQ which functions as follows:

- No preamp setting
- Only five filters available
- Each filter has a choice of four centre frequencies:
    - Filter 1: 80, 105, 135 or 175
    - Filter 2: 220, 300, 385 or 500
    - Filter 3: 650, 780, 1100 or 1400
    - Filter 4: 1800, 2400, 3000 or 4100
    - Filter 5: 6900, 9000, 11700 or 13000
- Each filter has a choice of three Q factors:
    - Narrow: 1.0
    - Normal: 0.8
    - Wide: 0.6
- Filter gain is limited to integers only

As a result, there is no way to closely match the output of AutoEQ with the capabilities of the device. The fixed band EQ is too limited in its calculations and the parametric EQ is too flexible.

**Describe the solution you'd like**

It would be great if there was some way to specify an arbitrary set of constraints on the EQ calculations so that the user could essentially "describe" their device's capabilities to AutoEQ and it could then build the closest possible EQ around those capabilities.

I'm imagining a new `--custom_eq` argument, perhaps with a couple of helper arguments such as `--gain_increment` and `--no_preamp`. Then simply allow the `--fc` and `--q` arguments to be specified multiple times, once per filter.

For example, to describe the aforementioned Cowon devices, maybe something like this: `--custom_eq --no_preamp --gain_increment=1 --fc=80,105,135,175 --fc=220,300,385,500 --fc=650,780,1100,1400 --fc=1800,2400,3000,4100 --fc=6900,9000,11700,13000 --q=0.6,0.8,1.0 --q=0.6,0.8,1.0 --q=0.6,0.8,1.0 --q=0.6,0.8,1.0 --q=0.6,0.8,1.0`

**Comment by nogaff** [comment]
I guess it could also be useful if `--fc` and `--q` accepted ranges as well as lists, when using the proposed `--custom_eq`.

For example, a user may wish to specify something like: `--custom_eq --gain_increment=0.5 --fc=20-219 --fc=220-649 --fc=650-1799 --fc=1800-6899 --fc=6900-12999 --q=0.5-1.5 --q=0.5-1.5 --q=0.5-1.5 --q=0.5-1.5 --q=0.5-1.5`

Having said all that, it now occurs to me that describing EQ constraints purely via command line arguments could get very messy if there were more than a few filters.

An alternative might be to accept something like a JSON file as input to the `--custom_eq` argument, like this: `--custom_eq="path/to/MyDeviceDefinition.json"`

The format could be something like:

```
{
  "name": "Some Device",
  "gain_increment": 1,
  "preamp": false,
  "filter_count": 5,
  "filters": [
    {
      "frequencies": [80, 105, 135, 175],
      "q_factors": [0.6, 0.8, 1]
    },
    {
      "frequencies": [220, 300, 385, 500],
      "q_factors": [0.6, 0.8, 1]
    },
    {
      "frequencies": [650, 780, 1100, 1400],
      "q_factors": [0.6, 0.8, 1]
    },
    {
      "frequencies": [1800, 2400, 3000, 4100],
      "q_factors": [0.6, 0.8, 1]
    },
    {
      "frequencies": [6900, 9000, 11700, 13000],
      "q_factors": [0.6, 0.8, 1]
    }
  ]
}
```

or this for ranges:

```
{
  "name": "Some Device",
  "gain_increment": 0.5,
  "preamp": true,
  "filter_count": 5,
  "filters": [
    {
      "min_frequency": 20,
      "max_frequency": 219,
      "min_q_factor": 0.5,
      "max_q_factor": 1.5
    },
    {
      "min_frequency": 220,
      "max_frequency": 649,
      "min_q_factor": 0.5,
      "max_q_factor": 1.5
    },
    {
      "min_frequency": 650,
      "max_frequency": 1799,
      "min_q_factor": 0.5,
      "max_q_factor": 1.5
    },
    {
      "min_frequency": 1800,
      "max_frequency": 6899,
      "min_q_factor": 0.5,
      "max_q_factor": 1.5
    },
    {
      "min_frequency": 6900,
      "max_frequency": 12999,
      "min_q_factor": 0.5,
      "max_q_factor": 1.5
    }
  ]
}
```

**Comment by jaakkopasanen** [comment]
The parametric eq optimizer V2 is under construction and coming along nicely. The new optimizer will have ability set minimum and maximum values for Fc, Q and gain as well as fix these to a single value. Separately for each filter of course. There will be set of pre-made configurations to cover most of the popular equalizers and an option to define these with a YAML file. So all in all very much what you requested.

The list of accepted values, instead of range or a single fixed value, won't be supported. I feel like that's super niche use case and worth the extra complexity, especially this would require a completely different optimization approach.

**Comment by nogaff** [comment]
Ah, well that all sounds very promising indeed! I look forward to it!

So, if a list of values per filter won't be possible, might there perhaps be an option to output some kind of "similarity-to-target" metric after calculating an EQ with fixed values?

That way, the user could at least test different combinations of fixed values and see which combinations produce the mathematically closest matches, plus the metric could be used to perform scripted batch tests and analyse the results.
