### ISSUE TITLE
What is the command line syntax for getting a HiFiMan Sundara sound like HD650 and HD800S?

### ISSUE THREAD

**Issue by bishshoy** [jaakkopasanen/AutoEq#523]
Hi,

I am new to all of this. Can anyone help me get the impulse wav that makes a HiFiMan Sundara sound like the HD650 and the HD800S?

Thanks.

**Comment by jaakkopasanen** [comment]
See [Using sound signatures](https://github.com/jaakkopasanen/AutoEq#using-sound-signatures) section for instructions.

**Comment by vaisest** [comment]
The README.md seems to be outdated. When I try the examples, I get an error: `autoeq.py: error: unrecognized arguments: --max_filters=5+5`.

Also, if that is removed the result for e.g. `python .\autoeq.py --input_dir="measurements/oratory1990/data/onear/Beyerdynamic DT 1990 (analytic earpads)" --output_dir="my_results/DT to HD 800S" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results/oratory1990/harman_over-ear_2018/Beyerdynamic DT 1990 (analytic earpads)/Beyerdynamic DT 1990 (analytic earpads).csv" --equalize --parametric_eq --bass_boost=4` has 0db gain for each filter.

**Comment by jaakkopasanen** [comment]
The documentation issue was resolved some time ago and I just double checked that examples don't have `--max_filters` anymore. Closing the issue as I believe it is resolved.
