### ISSUE TITLE
How to generate result throw Oratory target curve?

### ISSUE THREAD

**Issue by timsofteng** [jaakkopasanen/AutoEq#525]
Hello. If i got correctly the "Results" folder contains impulses according to harman curve. How to produce impulse for oratory curve for particular headphones according to oratory's measurements?

**Comment by jaakkopasanen** [comment]
See [Equalizing](https://github.com/jaakkopasanen/AutoEq#equalizing) instructions. The [compensation](https://github.com/jaakkopasanen/AutoEq/tree/master/compensation) folder contains the oratory1990's target curves.
