### ISSUE TITLE
[REQUEST] Samsung Galaxy Buds2 Pro

### ISSUE THREAD

**Issue by arctic-penguin** [jaakkopasanen/AutoEq#528]
Published on crinacle:

https://crinacle.com/wp-content/uploads/2022/08/Buds2-Pro-Passive.jpg

![](https://crinacle.com/wp-content/uploads/2022/08/Buds2-Pro-Passive.jpg)

**Comment by NostromoUS** [comment]
I'd like to reiterate this! Would be good to get both Passive and ANC in. Since most people will be using in ANC mode as well!

**Comment by sebas05000** [comment]
If possible also add the EQ options please thanks

https://crinacle.com/graphs/iems/samsung-galaxy-buds2-pro/

![image](https://user-images.githubusercontent.com/66391171/197370273-b45497c4-56ce-46a2-95ae-d842e6f50003.png)

![image](https://user-images.githubusercontent.com/66391171/197370284-8d737ced-de63-4f47-8d96-f07fa7ef3583.png)

![image](https://user-images.githubusercontent.com/66391171/197370286-5d4a682a-4a7e-473c-9adb-be974764e33b.png)

![image](https://user-images.githubusercontent.com/66391171/197370288-230db026-41f7-4f8d-85ac-28c78fedabee.png)

![image](https://user-images.githubusercontent.com/66391171/197370294-fca87d07-233e-4d4c-868d-8c97f6d515af.png)

**Comment by jaakkopasanen** [comment]
[Samsung Galaxy Buds2 Pro (ambient mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(ambient%20mode))
[Samsung Galaxy Buds2 Pro (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(ANC%20mode))
[Samsung Galaxy Buds2 Pro (bass boost EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(bass%20boost%20EQ)%20(ANC%20mode))
[Samsung Galaxy Buds2 Pro (blear EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(blear%20EQ)%20(ANC%20mode))
[Samsung Galaxy Buds2 Pro (dynamic EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(dynamic%20EQ)%20(ANC%20mode))
[Samsung Galaxy Buds2 Pro (Passive mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(Passive%20mode))
[Samsung Galaxy Buds2 Pro (soft EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(soft%20EQ)%20(ANC%20mode))
[Samsung Galaxy Buds2 Pro (treble boost EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(treble%20boost%20EQ)%20(ANC%20mode)%20(sample%201))

**Comment by UzziBPM** [comment]
> [Samsung Galaxy Buds2 Pro (ambient mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(ambient%20mode)) [Samsung Galaxy Buds2 Pro (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(ANC%20mode)) [Samsung Galaxy Buds2 Pro (bass boost EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(bass%20boost%20EQ)%20(ANC%20mode)) [Samsung Galaxy Buds2 Pro (blear EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(blear%20EQ)%20(ANC%20mode)) [Samsung Galaxy Buds2 Pro (dynamic EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(dynamic%20EQ)%20(ANC%20mode)) [Samsung Galaxy Buds2 Pro (Passive mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(Passive%20mode)) [Samsung Galaxy Buds2 Pro (soft EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(soft%20EQ)%20(ANC%20mode)) [Samsung Galaxy Buds2 Pro (treble boost EQ) (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds2%20Pro%20(treble%20boost%20EQ)%20(ANC%20mode)%20(sample%201))

please can you readd the bass boost eq i really need it

**Comment by benoe77** [comment]
Hi @jaakkopasanen, 

Samsung has changed the sound of the buds2 pro with the firmware updates from the beginning of 2023. I assume the current measurements in AutoEQ are with the earlier firmwares, which are good (firmware downgrade is possible), but we don't have a recent measurement for the current firmware.

Rtings has retested all the [Sound](https://www.rtings.com/headphones/reviews/samsung/galaxy-buds2-pro-true-wireless#test_321) tests using firmware R510XXU0AWI2 in Nov 21, 2023. 
Could you please import those measurements into AutoEQ?
Thanks!
