### ISSUE TITLE
Kz edx been measured, could the profile been done??

### ISSUE THREAD

**Issue by diegoandrade-iuv** [jaakkopasanen/AutoEq#530]
> Unfortunately there's nothing I can do since these haven't been measured by one of the supported sources yet. If they do get measured, they will eventually end up here.

https://reference-audio-analyzer.pro/en/report/hp/kz-edx.php

_Originally posted by @thefexcos791 in https://github.com/jaakkopasanen/AutoEq/issues/243#issuecomment-1188554637_

**Comment by jaakkopasanen** [comment]
Looks like RAA site has gone through quite large rework. I will most likely not update the crawler to encorporate this change but instead drop RAA completely from AutoEq. I've been thinking this for quite a while now because their measurements are very unreliable.

**Comment by jaakkopasanen** [comment]
As promised, I dropped Reference Audio Analyzer entirely. These measurements won't end up in AutoEq now.
