### ISSUE TITLE
[Headphone Request] Google Pixel Buds Pro

### ISSUE THREAD

**Issue by stopthebadpuns** [jaakkopasanen/AutoEq#533]
Hi, I believe the Google Pixel Buds Pro were just added to rtings and I was wondering if they could be added to autoeq please

https://www.rtings.com/headphones/reviews/google/pixel-buds-pro-truly-wireless

**Comment by jaakkopasanen** [comment]
[Google Pixel Buds Pro](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_in-ear_2019v2/Google%20Pixel%20Buds%20Pro)
