### ISSUE TITLE
FixedBand and Parametric zip in results folder

### ISSUE THREAD

**Issue by RuudBurger** [jaakkopasanen/AutoEq#534]
I would love to have both the fixedband and parametric csv in a zip (or include it in the current one).
This would make downloading (and using) the results a lot easier, because there would be no need to run the python scripts.

Maybe instead of putting them in code, make a "release" on github and add the zips there.

**Comment by jaakkopasanen** [comment]
Thanks for the idea but honestly this doesn't seem like it's impactful enough of an improvement that I would invest time into it. I'm sure you can achieve this with a simple command line command. On Mac and Linux that would be something like `ls -r results | grep ParametricEQ.txt | xargs -I {} cp {} parametric-eqs/` and on Windows probably powershell has something similar but I'm not so familiar with it that I would be able write one from the top of my head.
