### ISSUE TITLE
[Feature Request / Query / Suggestion] Ability to directly create impulse response from REW measurements

### ISSUE THREAD

**Issue by nibirrayy** [jaakkopasanen/AutoEq#535]
I just bought Final VR3000 and looking to equalize ti to harman_in-ear_2019v2. The problem is it that I don't have a measurement rig and I could not find the measurements anywhere.

I posted my problem on reddit and someone pointed out that [Squig.link](https://squig.link)'s super*review database has a measurement of Final VR3000. Squig link do provide a auto eq tool but the tool provided you parametric eq but I am using viper4android on my phone and the best option there is convolver plugin so I need a impulse response

 I could not see any way to just downlaod the raw measurements from squig link but if you open inspect element and go to the network tab you can find a get request with raw REW measurements.

Here is the raw REW measurement of Final VR3000
https://squig.link/data_mrs/Final%20VR3000%20L.txt

if you go to https://squig.link/data_mrs/ you will find the entire database

I did try to use these measurements to generate a impulse response from auto eq but the script seems to accept measurements only in csv format. And after looking at csv already in the project I couldn't figure out how do I even convert these measurements to the required csv format.

Can someone help me with the conversion of the measurements to csv format and we should also add support  
for raw REW measurements to  the project as well

And while at it can we integrate the entire squig.link database into the project?

**Comment by jaakkopasanen** [comment]
Did you try simply using the txt file you linked as the measurement in AutoEq? I think it should work as is.
