### ISSUE TITLE
Request: AirPods Pro 2

### ISSUE THREAD

**Issue by ImmortalZypther** [jaakkopasanen/AutoEq#536]
Crinacle's graphs here: https://crinacle.com/graphs/iems/apple-airpods-pro-2/

ANC Mode:
![image](https://user-images.githubusercontent.com/21045587/193377746-e2a16189-0b0f-4319-bb06-d2dee20fdb90.png)

Passive Mode: 
![image](https://user-images.githubusercontent.com/21045587/193377748-0d4bf62b-a749-4597-ab30-45f92aeddb3d.png)

Transparency Mode:
![image](https://user-images.githubusercontent.com/21045587/193377750-bbeb54dc-75f5-4e5f-9b38-65ce82f10279.png)

**Comment by mianmur** [comment]
+1 on this

**Comment by paulgribble** [comment]
+1 yes please

**Comment by jaakkopasanen** [comment]
[Apple AirPods Pro 2 (ANC mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Apple%20AirPods%20Pro%202%20(ANC%20mode))
[Apple AirPods Pro 2 (ANC off)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Apple%20AirPods%20Pro%202%20(ANC%20off))
[Apple AirPods Pro 2 (ANC on)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Apple%20AirPods%20Pro%202%20(ANC%20on))
[Apple AirPods Pro 2 (passive mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Apple%20AirPods%20Pro%202%20(passive%20mode))
[Apple AirPods Pro 2 (transparency mode)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/Apple%20AirPods%20Pro%202%20(transparency%20mode))

**Comment by beningodfrey4** [comment]
Forgive my ignorance and bumping this issue, but what's the difference b/w ANC mode and ANC on? Is ANC off the same as passive mode?

**Comment by totalitarian** [comment]
> Forgive my ignorance and bumping this issue, but what's the difference b/w ANC mode and ANC on? Is ANC off the same as passive mode?

Same question...
