### ISSUE TITLE
Some headphones seem to be categorized wrongly and thus equalized to the wrong targets

### ISSUE THREAD

**Issue by Tremontaine** [jaakkopasanen/AutoEq#537]
**Describe the bug**
Some headphones seem to be categorized wrongly and thus equalized to the wrong targets. I have only checked Rtings as I noticed the problem while using my headphones which are only measured by Rtings. I think the problem is limited toa few Rtings measurements, but I haven't checked all. These headphones for example are not in ear but listed and compensated as if they are: Jabra Elite 85h, Anker Soundcore Life Q20, Turtle Beach Recon 70.

**To Reproduce**
This one, for example: https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Jabra%20Elite%2085h

**Expected behavior**
Over-ear headphones should be compensated as over-ear headphones.

**Comment by jaakkopasanen** [comment]
Thanks for reporting. I'll fix these (eventually)

**Comment by jaakkopasanen** [comment]
All fixed now
