### ISSUE TITLE
Headphone Request: SteelSeries Arctis Nova 7X (Wireless)

### ISSUE THREAD

**Issue by yugi1408** [jaakkopasanen/AutoEq#540]
Opening an issue to request that the Arctis Nova 7X be added to the AutoEQ list as it has been measured by Rtings, see link below:
https://www.rtings.com/headphones/reviews/steelseries/arctis-nova-7x-wireless

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/SteelSeries%20Arctis%20Nova%207X
