### ISSUE TITLE
"Extreme" results with the new parametric equalizer

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#541]
Hi,
I was looking at the new results with the new parametric equalizer.
I see here that now we could have a "bit extreme" positive and negative correction in narrow bands (+18db and -16.5dB):

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2019v2/1MORE%20Quad%20Driver#parametric-eqs

Is this something expected with the new approach?

**Comment by jaakkopasanen** [comment]
The filter gains are limited to -20 dB to +20 dB range. So yes, it's all according to expectations.

**Comment by bhack** [comment]
Ok thanks
