### ISSUE TITLE
Getting error after windows 11 22h2 update

### ISSUE THREAD

**Issue by andrewb0922** [jaakkopasanen/AutoEq#543]
**Describe the bug**
I keep getting error: unrecognized arguments: -–equalize -–parametric_eq

**To Reproduce**
python autoeq.py --input_dir="measurements/oratory1990/data/onear/AKG K371 (Brainwavz oval earpads)" --output_dir="my_results/AKG K371 (B pads)_Harman" --compensation="compensation/harman_over-ear_2018.csv" -–equalize -–parametric_eq --parametric_eq_config="my_results/peq.yaml" --max_gain=10 --convolution_eq --fs=44100,48000

**Expected behavior**
code keeps spewing out error: unrecognized arguments: -–equalize -–parametric_eq
I'm pretty sure it worked before the windows update so I'm farely confident that i did not type anything wrong

**System:**
 - OS: Windows 11
 - Version 22H2

**Comment by jaakkopasanen** [comment]
Look at the hyphens in front of equalize and parametric_eq. It's supposed to be two hyphens (minus signs) but you have a dash and a hyphen.

**Comment by andrewb0922** [comment]
??!!! That is so stupid of me. But I didn't change a single command and I have other templates i've written and those didn't work as well.... they all worked before the update but didn't work after the update. Maybe windows corrected my type or I'm just delusional and should be headed to asylum. Nonetheless I'll try again with the correction tomorrow and close this issue if it works. So sorry for wasting your valuable time.

**Comment by andrewb0922** [comment]
Yup it worked like a charm. Still have no idea why it worked before...
