### ISSUE TITLE
[Question] Is there anything already exsists that has GUI for this project?

### ISSUE THREAD

**Issue by Lazy-Pupu** [jaakkopasanen/AutoEq#545]
Hello,
I just discovered this project can help me generate EQ profiles to let me use my headphone to simulate another headphone. It took me about a year since I knew about this project. I had only seen this feature exsists behind a pay wall and can only work inside of certain music app.
I wanted to share my joy with other people who know little or nothing about programming. Is there some tools can do that already? If not, is there any plan for making such a tool? Or, is there anyway for me to contribute for making such a tool?
Thanks

**Comment by jaakkopasanen** [comment]
Hello,

there's no GUI just yet but I plan to create a web app (web site) for this purpose. No need to use command line or install anything, just browse to the site and start using.

**Comment by Lazy-Pupu** [comment]
Hello, that sounds awesome! Thanks for your reply, is there any way to contribute to this?

**Comment by jaakkopasanen** [comment]
Without programming know how there's not really anything you can do to help. Unless you're skilled (professional) with UX and visual design.

**Comment by Lazy-Pupu** [comment]
Well, I won't describe myself as professional. My best wishes for the plan to go smoothly! Thank you all for your work.
