### ISSUE TITLE
Add option to generate convolution filter from parametric eq

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#548]
The new PEQ is amazing for providing a base to later tweak to preference. It would be great if one could make a convolution filter out of that tweaked eq.
Support for EqualizerAPO format and crinacle's graphtool exported files would be best.

**Comment by Slava848** [comment]
#548

**Comment by 23jonq** [comment]
> El nuevo PEQ es increíble porque proporciona una base para modificar más tarde según las preferencias. Sería genial si uno pudiera hacer un filtro de convolución a partir de esa ecuación modificada. La compatibilidad con el formato EqualizerAPO y los archivos exportados de graphtool de crinacle sería lo mejor.

**Comment by 23jonq** [comment]
Excelente

**Comment by 23jonq** [comment]
Muy bien

**Comment by 23jonq** [comment]
#541

**Comment by Suznyan** [comment]
In the meantime, you can put PEQ values into REW EQ tool and use "Export filters impulse response as WAV"

**Comment by eduardoeae** [comment]
> In the meantime, you can put PEQ values into REW EQ tool and use "Export filters impulse response as WAV"

Nice! Thanks

**Comment by jaakkopasanen** [comment]
Thanks @Suznyan for the workaround! I won't implement this in AutoEq as there already exists a working solution
