### ISSUE TITLE
EasyEffects GraphicEQ Help

### ISSUE THREAD

**Issue by Hioness** [jaakkopasanen/AutoEq#550]
Hello there, 
So I use AutoEq through Wavelet on my phone and EasyEffects on my laptop. In EasyEffects, there isn't support for equalizers with more than 32 bands, so even though I can use the Parametric EQ, I can't use the GraphicEQ files. I would like to use them since they have a more detailed EQ profile, but I can't really get that working in EasyEffects. What do you think is the best solution to this?

**Comment by eduardoeae** [comment]
You can use the convolution filters in EasyEffects. It is even more detailed than GraphicEQ

**Comment by Slava848** [comment]
> Hello there, 
> So I use AutoEq through Wavelet on my phone and EasyEffects on my laptop. In EasyEffects, there isn't support for equalizers with more than 32 bands, so even though I can use the Parametric EQ, I can't use the GraphicEQ files. I would like to use them since they have a more detailed EQ profile, but I can't really get that working in EasyEffects. What do you think is the best solution to this?

[]()

**Comment by Hioness** [comment]
> You can use the convolution filters in EasyEffects. It is even more detailed than GraphicEQ

Thank you, I realized that earlier today, but this is an affirmation of that. Thanks again!
