### ISSUE TITLE
[Question] Bass is usually -2 or less dB lower than Harman

### ISSUE THREAD

**Issue by kji46w** [jaakkopasanen/AutoEq#552]
Why is it that every time I use the EQ on the headphones (Moondrop Aria, Sennheiser HD 560S, KZ ZS10 Pro, and Airpods 2nd generation), I have to add 2 or more dB of bass in order for it to match Harman when I use Crinacle's Headphone Graph Comparison Tool?

![autoeq1](https://user-images.githubusercontent.com/117544242/200141638-934cc3f4-e36a-4e42-b4ec-6dc559c74fed.PNG)

Picture above shows the EQ saved from recommended results for Moondrop Aria on the Graph Comparison Tool.

**Comment by NekoAlosama** [comment]
In the README.md:
> None of these targets have bass boost seen in Harman target responses and therefore a +4dB boost was applied for all over-ear headphones, +6dB for in-ear headphones and no boost for earbuds. Harman targets actually ask for about +6dB for over-ears and +9dB for in-ears but since some headphones cannot achieve this with positive gain limited to +6dB, a smaller boost was selected.

**Comment by bhack** [comment]
Why we have this limit? Are we not having a 20db range? See https://github.com/jaakkopasanen/AutoEq/issues/541#issuecomment-1277743397

**Comment by NekoAlosama** [comment]
@bhack We do have the +/-20db filter range, but we also have preamp to reduce it back down below the +6db max-gain (to make it so one doesn't need to use an amplifier when using the pre-computed results).

**Comment by bhack** [comment]
As the pre-amp is often negative we are going to penalize many Headphones models.  
Probably we could iterate between 6db and 4db in the case we are going to suprpass +6db.

**Comment by jaakkopasanen** [comment]
Many open backs cannot do the full Harman bass shelf without significant EQ boost, which would require a lot of negative preamp to prevent clipping. I can't know what kind of amps users are using to drive their headphones so it's wise to try to limit the maximum gain so that users don't lose too much volume.

**Comment by bhack** [comment]
> I can't know what kind of amps users are using to drive their headphones so it's wise to try to limit the maximum gain so that users don't lose too much volume

I understand this but we could just make a first pass with a bass boost at 6db and eventually fallback to 4db on the models  where we detected that we are going to surpass the +6db limit so we could but a special nite on the relative models Readme in results

**Comment by bhack** [comment]
Also, are we still in this case in the +6b limit or we are excluding shelf filter in this limit?

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2019v2/1MORE%20Quad%20Driver

**Comment by jaakkopasanen** [comment]
I've changed the default bass boost to 6 dB and 9.5 dB on over-ears and in-ears, respectively. I started to think that the max gain already handles the volume issue and I had no reason to assume why the bass should be limited extra.
