### ISSUE TITLE
Reproducing pre-computed results

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#553]
It seems that I cannot reproduce the last results in the repo using the params specified in the readme:

https://github.com/jaakkopasanen/AutoEq#examples

Are these still valid/updated?

**Comment by jaakkopasanen** [comment]
Good catch! The issue was different parametric eq configuration in the examples as what's really used for pre-computed results.

Can you please confirm that you can now reproduce and close the issue if you do?

**Comment by bhack** [comment]
I will test in the next days. 
Do you think that it could be useful to add in the readme that if we don't need to rely on filters subset it is better to use `8_PEAKING_WITH_SHELVES`?

I suppose that we will have a better filter "budget" allocation right?
