### ISSUE TITLE
Question: APO + Peace or just one of them?

### ISSUE THREAD

**Issue by yepMad** [jaakkopasanen/AutoEq#556]
Hello,

I'm new in this world. Should I use APO with Graphic EQ.txt + Peace with ParametricEQ.txt settings? Or is just the APO with the GraphicEQ.txt settings enough?

Thanks at all,

**Comment by Suznyan** [comment]
APO is enough. Peace if you don't like APO interface

**Comment by yepMad** [comment]
Thank you so much!
