### ISSUE TITLE
SONY LINKBUDS S DONT APPEAR IN THE APP

### ISSUE THREAD

**Issue by baculit0s213** [jaakkopasanen/AutoEq#558]
literally what the title says, the app cant search for sonylinkbuds S but i can see it on github [https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Sony%20LinkBuds%20S](url) any one knows how to import this on the app?

**Comment by douglascamata** [comment]
Which app, @baculit0s213? This project doesn't have any official app. You should get in touch with your app's developer.

**Comment by jaakkopasanen** [comment]
Exactly what @douglascamata said. Raise this issue with the app developer, whatever app that might be.
