### ISSUE TITLE
Sennheiser HD 206 is missing but present at RAA

### ISSUE THREAD

**Issue by snakecase** [jaakkopasanen/AutoEq#561]
Hi there! I hope this issue doesn't upset anyone but I opened it only because Sennheiser HD 206 is missing here but a report on it is present at [RAA](https://reference-audio-analyzer.pro/en/report/hp/sennheiser-hd-206.php). I would be really grateful if someone can add them.

**Comment by snakecase** [comment]
Used the official [guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9) which is handy (though outdated a bit). Since I didn't hear any noticeable difference using them with Equalizer APO I'm leaving all I got for anyone interested.
[Sennheiser HD 206.zip](https://github.com/jaakkopasanen/AutoEq/files/10096521/Sennheiser.HD.206.zip)

**Comment by jaakkopasanen** [comment]
Looks like RAA site has gone through quite large rework. I will most likely not update the crawler to encorporate this change but instead drop RAA completely from AutoEq. I've been thinking this for quite a while now because their measurements are very unreliable.

**Comment by jaakkopasanen** [comment]
As promised, I dropped Reference Audio Analyzer entirely. These measurements won't end up in AutoEq now.
