### ISSUE TITLE
Argument --max-gain not recognized

### ISSUE THREAD

**Issue by tfpbatelaan** [jaakkopasanen/AutoEq#568]
Hi,

When I tru to run the example command from the readme.md where the max-gain of the curve is increased, I get this error:
__main__.py: error: unrecognized arguments: --max_gain=8. 

(I would love to increase the max gain because the quite high treble boost required to eq my LinkBuds S to the harman target gets chopped off when I use the default settings.)

python -m autoeq --input-dir="measurements/innerfidelity/data/onear/HiFiMAN HE400S" --output-dir="my_results/HE400S (99 Noir)" --compensation="measurements/innerfidelity/resources/innerfidelity_harman_over-ear_2018_wo_bass.csv" --sound-signature="results/oratory1990/harman_over-ear_2018/Meze 99 Noir/Meze 99 Noir.csv" --parametric-eq --parametric-eq-config=8_PEAKING_WITH_SHELVES --ten-band-eq --bass-boost=4 --max_gain=8

**Comment by jaakkopasanen** [comment]
Hi,

You have `--max_gain` with underscore instead of `--max-gain` with hyphen
