### ISSUE TITLE
Using --preamp produces wrong PEQ and Fixed EQ graph

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#569]
For example, using "python -m autoeq --input-dir="measurements/innerfidelity/data/onear/Sennheiser HD 650" --output-dir="my_results/HD650" --compensation="measurements/innerfidelity/resources/innerfidelity_harman_over-ear_2018_wo_bass.csv" --bass-boost=4 --convolution-eq --parametric-eq --ten-band-eq --fs=44100,48000 --preamp -6" generates this:
![Sennheiser HD 650](https://user-images.githubusercontent.com/2060444/204549796-95d9a092-91d4-4f79-80f9-186db389d7d0.png)

**Comment by eduardoeae** [comment]
Also, can --preamp support floating point numbers?

**Comment by jaakkopasanen** [comment]
This graph behavior was actually by design but perhaps I need to reconsider it.

> Also, can --preamp support floating point numbers?

It already should

**Comment by eduardoeae** [comment]
> It already should

You are right, my bad.

**Comment by jaakkopasanen** [comment]
I'm gonna call this "working as intended". Might be controversial but that's how I see it.
