### ISSUE TITLE
Suggested: Update to #equalizerapo in instructions

### ISSUE THREAD

**Issue by amphyvi** [jaakkopasanen/AutoEq#570]
Hi! I'd like to suggest a revision to [#equalizerapo](https://github.com/jaakkopasanen/AutoEq#equalizerapo) on the usage/instructions page.

Currently, the section contains the following text:
> **EqualizerAPO**
> It's possible to use plain [EqualizerAPO](https://sourceforge.net/projects/equalizerapo/) and edit configuration file in `C:\Program Files\EqualizerAPO\config\config.txt`. Replace contents of the file with the GraphicEQ.txt file found in results.

There's no need to edit `config.txt` as outlined above. In the default EqualizerAPO interface, `.txt` configuration files can be loaded using the button shown in the below screenshot. I used APO's default interface this way for several years due to being (admittedly) intimidated by Peace's UI. `config.txt` is just the default configuration 🙂

![Load Configuration button](https://user-images.githubusercontent.com/51802000/205460986-88129b0b-99ab-44af-9cfa-7f7864d72207.png)

**Comment by jaakkopasanen** [comment]
I removed all the instructions from the readme as they now live in https://autoeq.app
