### ISSUE TITLE
MiniDSP Ears Measurement Rig and included Compensation Files - possible to incorporate into Impulcifer? 

### ISSUE THREAD

**Issue by jerrolds** [jaakkopasanen/AutoEq#573]
So i was actually able to do binaural recordings using my old minidsp EARS headphone rig.  https://www.minidsp.com/products/acoustic-measurement/ears-headphone-jig

And it came out really well the first time. 

Minidsp does include Headphone compensation files (for flat EQ Target, original hp compensation, iem diffisue field compensation, and no compensation (raw)) 

Is it possible to incorporate one of these compensation files into my HRIR for even more accurate virtualization?

Thanks

**Comment by jaakkopasanen** [comment]
This is not Impulcifer repo...
