### ISSUE TITLE
About the treble eq

### ISSUE THREAD

**Issue by JoonSumisu** [jaakkopasanen/AutoEq#574]
Hi jaakkopasanen, thank for your work!

I am eqing my venus, and here is the result I get, but does not work well upper 5000hz.

![venus](https://user-images.githubusercontent.com/77182770/207246990-9886cae8-9a37-4ac9-9f7c-e4421f49f21d.png)

I try to pinpoint the area by - type: PEAKING fc: 5200(6000 9000) in peq.yaml , which does not actually work. It seens like few peaks can solve this problem. 

Am I using the peq.yaml correctly? or any else parameter can be adjusted for a better result?
best

**Comment by jaakkopasanen** [comment]
This seems to be due to the slope steepness limiter AutoEq has. The slope steepness is limited to prevent the equalizer filters from ringing. In any case you won't have perfectly accurate results at that frequency range because the measurements won't be perfectly accurate for you ears.

**Comment by JoonSumisu** [comment]
Thank a lot jaakkopasanen!

yeah the perfectly accurate means nothing, and less possible to audible. 

Just, you know, seems like it only needs a single peak to make it perfect.
