### ISSUE TITLE
innerfidelity's "Koss Pro4AAA 1970s" is mislabeled as "Koss Pro4AA" on AutoEQ

### ISSUE THREAD

**Issue by staticV3** [jaakkopasanen/AutoEq#575]
**Describe the bug**
innerfidelity's "Koss Pro4AAA 1970s" is mislabeled as "Koss Pro4AA" on AutoEQ
here are his PDFs to cross-reference: https://www.stereophile.com/content/innerfidelity-headphone-measurements

**Comment by jaakkopasanen** [comment]
Thanks for reporting this! It's fixed now and the entry is called Koss Pro4AAA as it is in the PDF.
