### ISSUE TITLE
Is the Sennheiser CX Plus profile correct? 

### ISSUE THREAD

**Issue by spectromas** [jaakkopasanen/AutoEq#576]
I've been playing with autoeq for my CX Plus but the profile in wavelet doesn't sound right to me. The sound is very shrill with not much bass at all. I also have some DT880s which I am using with autoeq on my phone and on my computer and they sound good but the CX Plus sounds drastically different and I'm struggling to believe that the profile is correct. If I turn the strength down to <50% then it's bearable but much more than that and it sounds terrible. 

I am using comply tips with them so I thought that may have some effect on it but I tried with the stock tips and it's doesn't make much of a difference. 

So I am wondering if anyone else has these headphones and can confirm that something doesn't seem right?

**Comment by kongming819** [comment]
I have the CX Plus Trues and I remember when I got them and compared them with the Grados, I noticed overly strong mid-low and somewhat unclear trebles. In my opinion, the AutoEQ sound is correct, but you might want to check that the audio player you're playing from isn't doing its own EQing, or that you don't have a EQ profile already assigned with the files you're playing.
