### ISSUE TITLE
HyperX Cloud Alpha S Clarifications

### ISSUE THREAD

**Issue by oGrqpez** [jaakkopasanen/AutoEq#578]
I have HyperX Cloud Alpha S headphones, and I got the eq profiles. I am trying to get the best sound possible, so...

Should 7.1 be turned on or off?
What mode should the bass sliders be at?

**Comment by jaakkopasanen** [comment]
You might get some hints from the original Rtings review https://www.rtings.com/headphones/reviews/hyperx/cloud-alpha-s
