### ISSUE TITLE
From Graphic Eq to Parametric Eq (with no equalization)

### ISSUE THREAD

**Issue by chiavez** [jaakkopasanen/AutoEq#579]
Hello and thank you for your great work.

You implemented nice algorithms that give outputs for fixed band EQs. Is there a way to use these algorithms _without_  equalizing the input signal?

The point is that I did the equalization by myself and modified manually various bits of the AutoEQ results. it might be useful to get some simple quick settings for mobile devices (in case wavelet is not installed etc.). I wanted to use AutoEq algorithms to get my signal in CSV/Equalizer APO format and transform it in fixed band eq settings (so that I can use that for phones, sony app, etc). It seems it is not possible to do so though.

Summarising:
Is it possible to do the following with AutoEQ?

- Input: a frequency response in CSV or Equalizer APO graphic EQ format
- Output: fixed band eq settings

Thanks,

Lorenzo

PS
- I should probably learn how to use the interpolation algorithms instead of bothering people, sorry
- I gotta say that it does not really seem right to ask for an app called AutoEQ to output results without equalization...

**Comment by jaakkopasanen** [comment]
Hey!

You can use `compensation/zero.csv` as the input data and the CSV you got as the target. Then just do the regular thing with fixed band equalizer and you should get the filter gains which you need.

**Comment by chiavez** [comment]
Hi!

Thanks for the quick answer!
