### ISSUE TITLE
Correct Compensation for ATH-M50xBT2?

### ISSUE THREAD

**Issue by ChiefBigFeather** [jaakkopasanen/AutoEq#580]
Hi,

which one is the correct compensation file for ATH-M50xBT2s? I tried this line:
python -m autoeq --input-dir="measurements/rtings/data/onear/Audio-Technica ATH-M50xBT2" --output-dir="my_results/Audio-Technica ATH-M50xBT2 (app)" --compensation="measurements/rtings/resources/rtings_harman_over-ear_2018.csv" --parametric-eq

But the outcome in  both the Audio-Technica ATH-M50xBT2 ParametricEQ.txt and the readme.md is different from the one on the github page.
I also tried rtings_harman_over-ear_2018_wo_bass.csv and the harman_over-ear_2018 from the compensation folder.

Also: I'm not 100% clear on how to change the parametric eq settings. I would like to limit gain to +/-6 db and q>=0.4

Thanks in advance for help on this matter!

**Comment by jaakkopasanen** [comment]
You have the correct compensation but you're seeing different values because you have different bass boost level. You can stick with the one you have and add `--bass-boost=-2` or switch to the compensation curve which doesn't have bass boost and add `--bass-boost=6`

**Comment by ChiefBigFeather** [comment]
Thanks! Now the differences look like small rounding errors.

I also managed to get the yaml to work. If you only got 5 filters to work with, would you remove the highshelf/lowshelf filters?
