### ISSUE TITLE
--window-size doesn't work

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#583]
--window-size only affects the graph (Error Smoothed). Equalization remains unchanged.

**Comment by eduardoeae** [comment]
`python -m autoeq --input-dir="measurements/innerfidelity/data/onear/Sennheiser HD 650" --output-dir="my_results/HD650" --compensation="measurements/innerfidelity/resources/innerfidelity_harman_over-ear_2018_wo_bass.csv" --bass-boost=4 --convolution-eq --parametric-eq --ten-band-eq --fs=44100,48000 --window-size 2`

![Sennheiser HD 650](https://user-images.githubusercontent.com/2060444/213584029-0d778ce0-c2e2-449e-9e30-662d39d0944e.png)

**Comment by jaakkopasanen** [comment]
Indeed. This is intended. The equalizer target uses it's own smoothing which works together with the maximum slope.
