### ISSUE TITLE
Please recheck that the original data is up to date

### ISSUE THREAD

**Issue by LannyDabriz** [jaakkopasanen/AutoEq#585]
As an example, Oratory1990's measurement data was updated in December 2022 with new measurements, including new results for Philips Fidelio X2HR, but the data in the Result column did not update them.

**Comment by bhack** [comment]
I think we have other examples:
https://www.reddit.com/r/oratory1990/comments/zqll2l/oratory1990s_list_of_eq_presets_update_20122022/

**Comment by LannyDabriz** [comment]
> I think we have other examples: https://www.reddit.com/r/oratory1990/comments/zqll2l/oratory1990s_list_of_eq_presets_update_20122022/

This is not the first time this issue has come up. When Oratory1990 updates his database, AutoEq updates them simultaneously. However, AutoEq's updates are often incomplete, and some updated headset measurements are missed.

**Comment by jaakkopasanen** [comment]
All measurements were just updated. The latest and greatest measurements should now be available.
