### ISSUE TITLE
AutoEQ is incorrectly using LS & HS instead of LSC & HSC in ParametricEQ ?

### ISSUE THREAD

**Issue by matas-g** [jaakkopasanen/AutoEq#586]
After applying ParametricEQ settings the lower part of resulting graph looks different than "Parametric Eq" line in the provided picture with EQ graphs.
(_When using "Equalizer APO" graph gets fixed after changing LS & HS to LSC & HSC in the config file_)

**To Reproduce**
1. Go to: https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x ;
2. Import ParametricEQ config to "Equalizer APO" ([Audio-Technica ATH-M30x ParametricEQ.txt](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x/Audio-Technica%20ATH-M30x%20ParametricEQ.txt));
3. Compare left part of the resulting EQ graph (44 Hz, 105 Hz, 253 Hz filters) to the expected graph ("Parametric Eq" line) in file "[Audio-Technica ATH-M30x.png](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x/Audio-Technica%20ATH-M30x.png)".

**Expected behavior**
Resulting EQ graph (_see link in Files section_) should look very similar to the "Parametric Eq" line in the expected graph picture: [Audio-Technica ATH-M30x.png](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x/Audio-Technica%20ATH-M30x.png).

**Files**
- ParametricEQ config file: [Audio-Technica ATH-M30x ParametricEQ.txt](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x/Audio-Technica%20ATH-M30x%20ParametricEQ.txt);
- Expected EQ graph picture (see "Parametric Eq" line): [Audio-Technica ATH-M30x.png](https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/Audio-Technica%20ATH-M30x/Audio-Technica%20ATH-M30x.png);
- Actual resulting EQ graph picture (it's not from "Equalizer APO", but looks the same): [Resulting ATH-M30x ParametricEQ Graph.png](https://drive.google.com/file/d/1V6gf3XrEgUgIIUMfm_LuEa3p5GXyd2kf/view?usp=share_link).

**System:**
 - OS: Windows 10
 - Version: latest

**Additional Info**
Resulting EQ graph was made using "ReaEQ" in "Reaper DAW", but graph looks the same when config is imported to "Equalizer APO".

**Comment by coda101** [comment]
I think it could be because AutoEQ is using LS instead of LSC which is usually the default.

**Comment by matas-g** [comment]
Thank you, I think it could be the issue, because it also happened when I
tried to make EQ for another headphones.

I didn't have time to properly check/test it though. But I will do it as
soon as I can.

Also thank you for this great project ;)

Kind regards,
Matas

**Comment by matas-g** [comment]
In Equalizer APO I tried to change low-shelf and high-shelf filter types from Corner Frequency to Center Frequency (in config file it's: LS -> LSC and HS -> HSC). And now graph seems to match the expected line.

So, as my issue now is solved, please feel free to close this ticket if it is expected behavior and not a bug. Thank you for your help @jaakkopasanen

**Comment by coda101** [comment]
It was actually me who commented, looks like I deleted my comment somehow, but yes it was that AutoEQ is incorrectly using LS & HS instead of LSC & HSC.

**Comment by matas-g** [comment]
Sorry, my bad, I got confused when writing the initial reply by email. Thanks @coda101 👍

**Comment by jaakkopasanen** [comment]
Fixed! Thanks a lot for pointing this out to me!
