### ISSUE TITLE
No version number on headset results

### ISSUE THREAD

**Issue by Dustie** [jaakkopasanen/AutoEq#59]
Looking at the results listing I see that there are no version numbers on the headsets in the list. For example I own the Astro A50 which is in the listing, but the A50 has at least 5 different versions (generation 1 to 5) some of which sound very different. 

It would be helpful if the list said which set the results are actually made for.

**Comment by jaakkopasanen** [comment]
Rtings review page say it the wireless Xbox One variant but no mention about generation. I'm afraid this is all the info I got.

https://www.rtings.com/headphones/reviews/astro/a50-wireless
