### ISSUE TITLE
Usage instructions for parametric eq

### ISSUE THREAD

**Issue by dinotheextinct** [jaakkopasanen/AutoEq#590]
Usage instructions are bit unclear 
![image](https://user-images.githubusercontent.com/32158581/212535480-7d4e071a-027c-4a7a-9932-db1a25fc4789.png)
Why are lowshelf (bass) and highshelf not separated from the 5 parametric entries? I am using a RMI-ADI2 DAC and it feels weird to set the first filter to shelf, while I would have the option to use bass and treble gains and 5 separate filters. e.g. oratory1990 is doing exactly that in his results. 
![image](https://user-images.githubusercontent.com/32158581/212535618-541f9c3e-c359-4acc-89e3-6acd40d3ae29.png)

**Comment by jaakkopasanen** [comment]
The pre-computed results aren't created specifically for RME ADI2-DAC but rather an attempt to be compatible with as many parametric equalizers as possible. You can create your own with custom parametric eq configuration if you wish to get everything out of the device.

**Comment by dinotheextinct** [comment]
> You can create your own with custom parametric eq configuration if you wish to get everything out of the device.

Can you elaborate or link me what you mean by that?

**Comment by jaakkopasanen** [comment]
See the equalization instructions in them documentation and peq.yaml for example configuration.

**Comment by dinotheextinct** [comment]
Alright thank you, I will check it out!
