### ISSUE TITLE
Meze 109 Pro

### ISSUE THREAD

**Issue by einfacharthur** [jaakkopasanen/AutoEq#596]
Please add the Meze 109 Pro to AutoEq.
[Meze 109 Pro.pdf](https://github.com/jaakkopasanen/AutoEq/files/10538221/Meze.109.Pro.pdf)

**Comment by Retik** [comment]
I'll second this request

**Comment by Tecko71** [comment]
+1 for me , I am going to buy this headphones

**Comment by jaakkopasanen** [comment]
This is now included in AutoEq.
