### ISSUE TITLE
Bit confused about --compensation and --sound-signature

### ISSUE THREAD

**Issue by vexikola** [jaakkopasanen/AutoEq#598]
Following the example for equalizing the Sennheiser HD 800 to sound like Sennheiser HD 650 in the README, I used the following command to equalize the Philips Fidelio X2HR to the Sennheiser HD 560S measurements:

`python -m autoeq --input-dir="measurements/oratory1990/data/onear/Philips Fidelio X2HR/" --output-dir=/home/me/temp/ --compensation="compensation/harman_over-ear_2018.csv" --sound-signature="results/oratory1990/harman_over-ear_2018/Sennheiser HD 560S/Sennheiser HD 560S.csv" --convolution-eq --fs=48000`

I also tried the following command:

`python -m autoeq --input-dir="measurements/oratory1990/data/onear/Philips Fidelio X2HR/" --output-dir=/home/me/temp/ --compensation="measurements/oratory1990/data/onear/Sennheiser HD 560S/Sennheiser HD 560S.csv" --convolution-eq --fs=48000`

The first command seems to get the bass wrong, while the second produces results that look accurate in the generated .png. Is compensating to the appropriate Harman .csv and using `--sound-signature` to match a target headphone only needed when equalizing an over-ear headphone measured by someone other than Oratory1990? If so, might it be worthwhile to change the README's example of equalizing the Sennheiser HD 800 to sound like the Sennheiser HD 650, as both were measured by Oratory1990? I'm worried I might be missing something!

Thanks!

**Comment by jaakkopasanen** [comment]
I'd now recommend simply going to https://autoeq.app and
1. Select HD 800
2. Click the headphones icon in sound signature
3. Select HD 650
4. Select equalizer app
5. Enjoy
