### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Perrna** [jaakkopasanen/AutoEq#6]
What a great project! However, current installation script does not work. (Python 3.6.6, Win10-64)

tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.15.2 which is incompatible.
tensorflow 1.10.0 has requirement setuptools<=39.1.0, but you'll have setuptools 40.4.3 which is incompatible.

**Comment by jaakkopasanen** [comment]
Try with tensorflow 1.8. There was another user with similar problems and I think tensorflow 1.8 solved the issue.

**Comment by jaakkopasanen** [comment]
I fixed Tensorflow version to 1.8. Closing the issue. Reopen if the problem persists.
