### ISSUE TITLE
Data  and naming corrections

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#60]
Hello,
when comparing the measurement of the soundmagic e10 to the pdf from innerfidelity, it looks like the compensated curve got parsed instead of the raw measurement. This leads in a double compensated result

I found a few naming errors as well that were copied from their sources:
- Xaiomi Piston 3 Youth Edition. Should be Xiaomi Piston 3 Youth Edition
- Some headphones are posted twice because some are named with and without a '-', of which many are from audio-technica
- HiFiMAN RE-400 can be found in the list as hifiman re400, hifiman ie400 and hifiman re 400

**Comment by jaakkopasanen** [comment]
You're right. There has been some mishap with SoundMagic E10. I'll fix that and the name inconsistencies at some point.

Thanks for reporting the issue.

**Comment by jaakkopasanen** [comment]
Fixed. All Audio-Technicas are named with dash. Hifiman inears are all REXYZ without dash or space.

**Comment by Pittvandewitt** [comment]
In the meantime a few other naming issues have popped up:
AKG K271 MK.II / AKG K271 MKII
Creative Aurvana Live 2 / Creative Aurvana Live! 2
Denon AHGC20 -> Denon AH-GC20
Etymotic / Etymotic Research
Final audio / Final audio design
HiFiMan RE0 / HiFiMan ReZero
Ikko OH-1 / Ikko OH1
Klipsch image / Klipsch
KZ AS10 / KZ AS-10
MEElectronics / MEE audio
Meze classics xx / Meze xx Classics
Noble / Noble audio
Sennheiser HD 212Pro / Sennheiser HD 212 PRO
Sennheiser IEXX need spaces. There's some duplication here
Sony MDR-7550/ Sony MDR7550
Sony MDRV-SA5000 and Sony MDRV-CD3000 don't exist. The V needs to be removed
VE Monk IE Biggie -> Venture Electronics Monk IE Biggie
Vision Ears VE 8 custom / Vision Ears VE8 custom
VSonic GR07 Bass Edition / Vsonic GR07 BE
