### ISSUE TITLE
Logitech g pro X GrapicEQ didnt update as the other settings

### ISSUE THREAD

**Issue by DoYouNotice** [jaakkopasanen/AutoEq#603]
**Describe the bug**
Logitech g pro X GrapicEQ didnt update as the other settings did. still from 2 years

**To Reproduce**
just look in [link](https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Logitech%20G%20Pro%20X/Logitech%20G%20Pro%20X%20GraphicEQ.txt)

**Expected behavior**
should have been updated

**Comment by jaakkopasanen** [comment]
I updated all measurements just now. Should be the latest version.
