### ISSUE TITLE
Tanchjim Oxygen updates

### ISSUE THREAD

**Issue by video904** [jaakkopasanen/AutoEq#605]
Hi

the results from 2 years ago corresponded quite well to the Harman target curve vs the Tanchjim set
but the latest results seems completely off like if the files was mixed up or maybe it is me who don't
understand the goal,

Would you light up my mind

**Comment by jaakkopasanen** [comment]
The measurements and results were updated just now. I see that Oxygen is relatively close to the target.

![](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/crinacle/711%20in-ear/Tanchjim%20Oxygen/Tanchjim%20Oxygen.png)
