### ISSUE TITLE
Where can I find the foobar plugin?

### ISSUE THREAD

**Issue by LordSzechenyi** [jaakkopasanen/AutoEq#606]
Since the page says:

> Windows
has [EqualizerAPO](https://github.com/jaakkopasanen/AutoEq#equalizerapo), [Peace](https://github.com/jaakkopasanen/AutoEq#peace) and many media players with parametric equalizers such as [Neutron](https://www.microsoft.com/en-us/p/neutron-music-player/9nblggh4vp2h?activetab=pivot:overviewtab), [Roon](https://roonlabs.com/) and [Foobar2000](https://www.foobar2000.org/).

So where is it?

Also I tried using EAPO with Peace
 and no matter what I did it wouldn't work.
I tried every comment from here: https://www.reddit.com/r/headphones/comments/ojxnc3/how_do_you_set_up_equalizer_apopeace_gui_to_use/
and it still wouldn't work

**Comment by Katzenwerfer** [comment]
I'm pretty sure it just meant you can use whatever built-in equalizer Foobar2000 has.
