### ISSUE TITLE
 RuntimeWarning: divide by zero encountered in double_scalars change_rate = d_loss / d_time if len(self.history.moving_avg_loss) > n else 0.0

### ISSUE THREAD

**Issue by Tennplate** [jaakkopasanen/AutoEq#609]
Trying to emulate the sound of the Aeon 2 open on my Sundaras, i get an error, could someone explain what i am doing wrong? Win 10 64

python -m autoeq --input-dir="measurements/oratory1990/data/onear/HIFIMAN Sundara (pre-2020 earpad revision)" --output-dir="my_results/HIFIMAN Sundara (pre-2020 earpad revision) (Aeon 2 Open)" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound-signature="results/oratory1990/harman_over-ear_2018/Dan Clark Audio Aeon 2 Open/Dan Clark Audio Aeon 2 Open.csv" --parametric-eq --parametric-eq-config=8_PEAKING_WITH_SHELVES --ten-band-eq --bass-boost=4 --convolution-eq --fs=44100,48000

:\Users\Dator\AutoEq\autoeq\[peq.py:644](http://peq.py:644/): RuntimeWarning: divide by zero encountered in double_scalars
change_rate = d_loss / d_time if len(self.history.moving_avg_loss) > n else 0.0
C:\Users\Dator\AutoEq\autoeq\[peq.py:644](http://peq.py:644/): RuntimeWarning: divide by zero encountered in double_scalars
change_rate = d_loss / d_time if len(self.history.moving_avg_loss) > n else 0.0

**Comment by jaakkopasanen** [comment]
I've made several fixes to parametric eq optimizer.

Could you try in https://autoeq.app? Select Aeon 2, click headphone icon in sound signature (under advanced), select Sundara and select your eq app.
