### ISSUE TITLE
Crinacles measurements used instead of Oratory1990s

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#613]
As I understand it, oratory1990s measurements are used in place of  Crinacles when both have measured the same IEM. I've found a discrepancy with Moondrop KXXS and Moondrop Kanas Pro.

**Comment by jaakkopasanen** [comment]
AutoEq doesn't have KXXS and Kanas Pro from oratory1990. It's been awhile since I updated the database so maybe he measured them since the last update. If that's the case then this will be fixed eventually.

**Comment by jaakkopasanen** [comment]
Those two in oratory1990's list of preset are made with Crinacle's measurements. AutoEq skips all PDFs which say measured by Crinacle.
