### ISSUE TITLE
Request: Tanchjim Zero

### ISSUE THREAD

**Issue by MCPEngu** [jaakkopasanen/AutoEq#614]
Hello @jaakkopasanen and other contributors to this project,

I was wondering if this IEM has been measured by Crinacle before but not in AutoEq results list so could you add it please ?
https://crinacle.com/graphs/iems/tanchjim-zero/
![Zero-Tanchjim](https://user-images.githubusercontent.com/73783232/221852176-0aaac0a1-9166-4a02-b3f7-f12c2a5f2c3b.jpg)

Best regards,
MCPEngu

**Comment by jaakkopasanen** [comment]
These are now added.
