### ISSUE TITLE
Outdated Oratory1990 compensation

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#615]
I looks like https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/oratory1990.csv uses an old revision of the target
![target](https://user-images.githubusercontent.com/15148553/221852730-28b78853-8e4b-4d57-82c3-6ed28ac39bb8.png)

Compare to https://kurin.squig.link/data/Oratory%20IE%20Target.txt
![image](https://user-images.githubusercontent.com/15148553/221853218-2eaaf658-dedf-4c0c-b1e7-ec7b4b741a7b.png)

**Comment by bhack** [comment]
Yes nice catch. I missed to notice it.

**Comment by jaakkopasanen** [comment]
Updated the target. There's also the target without bass shelf available.

![](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/compensation/oratory1990.png)

https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/oratory1990.csv
