### ISSUE TITLE
Koss KSC75X phantom entry?

### ISSUE THREAD

**Issue by Stelvey** [jaakkopasanen/AutoEq#616]
**Describe the bug**
Distro has two same headphones, they are also rated differently in ranking.

**Additional context**
[Koss Earpads](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Koss%20KSC75X%20(Yaxi%20earpads))
[Same earpads but mistyped](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Koss%20KSC75X%20(Yaxi%20arpads))

**Comment by jaakkopasanen** [comment]
Good catch! Thanks for reporting. Will be sorted out.

**Comment by jaakkopasanen** [comment]
Fixed!
