### ISSUE TITLE
Hi Bro there is no preset for akg k52 Headphones. It would be great if you could add akg k52 preset. 

### ISSUE THREAD

**Issue by studiosnabeel** [jaakkopasanen/AutoEq#619]
**Headphone requests**
@jaakkopasanen 
Kindly go to the following link. And in search bar just right AKG K52 you will find the akg k52 files over there and you can download those Wav files. I tried to drag them here but wav file type is not supported here.

https://phones.killdozer.uk/

**Comment by coda101** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/AKG%20K52
