### ISSUE TITLE
I have a peripheral tools for AutoEq

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#62]
That's it:  
https://github.com/mhtvsSFrpHdE/autoeq-batch-generator  

User can set just two value and start the process for their eq settings,  
without a lot of commands typed in.  

The first time run,  
it can install virtualenv, and other dependencies listed in ```requirements.txt``` automatically.  
During this action, it allows setting custom pip mirror.  

There was "target curve" json config file,  
by defining a series of target curve in ```targetCurve.json```,  
the input headphone will have multiple eq generated based on these curve.  

There was "multi headphone mode", by defining a series of headphone in  
```multiHeadphone.json```, it can loop through it,  
and generate multiple eq settings defined in targetCurve for each headphone.  

And an easter egg feature called "All to All",
it uses the previous two feature, by scan the AutoEq-master folder,  
makes all headphone to simulate all headphone(up to 6,250,000 eq settings).  

Do you have advertising space for this peripheral tool?  
And any suggestion about how to set the default command and values is also great.  
Again, thank you for bringing AutoEq project to us.  

Um, I know, there are already a lot of pre-results out there,  
so they can just pick one of them.  
This one may stand for quick headphone simulate.

**Comment by jaakkopasanen** [comment]
Hi. Looks cool, nice job! I'm afraid I don't have any ad-space to promote this project but perhaps you could post about it in Reddit, Head-fi and other relevant forums. Some people might find your tool very useful.

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen I later gonna to use python to do it again. I was just thought it as a very small script at the beginning... But it unexpected growth. And I want to even have a GUI now. I'm exciting.

**Comment by jaakkopasanen** [comment]
There is going to be a GUI in form of a webapp. I already have a domain autoeq.app for it but haven't had the time to start implementing the website. This should make it very easy to tune the EQ or simulate other headphones. I'll probably even add a music player to the webapp which allows the user to test the EQ live.
