### ISSUE TITLE
Please help me to understand / Soundcore Liberty 4 support / .csv import

### ISSUE THREAD

**Issue by AhoyThere** [jaakkopasanen/AutoEq#621]
Hey there,

I heard a lot of good things about Wavelet and I wanted to give it a try. However, not matter what I try I don't understand anything and the "easy ways" or "easy guides" are everything but easy to understand.

I own the Soundcore Liberty 4 and while this page https://github.com/jaakkopasanen/AutoEq/tree/master/results lists them, the in-App search itself does not list them. So I searched around a little and found this site: https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_in-ear_2019v2/Anker%20Soundcore%20Liberty%204

But I failed importing the .csv file from there into Wavelet. Obviously that .csv file and much bigger and contains much more data than needed. So I don't know what to do from this point on.

Can someone explain how to get the Liberty 4 work with Wavelet like I'm 6 years old?

**Comment by GalaxyNight** [comment]
Import GraphicEQ text file, not csv

**Comment by AhoyThere** [comment]
Thank you for your answer.

I downloaded the text file. Turns out it's as bloated as the .csv file. Obviously you need to copy the raw data from it into an own .txt file. I didn't know that and I bet I'm not the only one. I find all the GitHub stuff pretty complicated tbh.

But ok. it worked now. Unfortunately the EQ settings for the Liberty 4 basicly destroyed their audio quality completely. Comparing them to the Sony Linkbuds S, which I also own, the Liberty 4 now sound very very sad while the Linkbuds S really sound enriched by using AutoEQ. So I either did something wrong (again) or the Libery 4 really don't sound that good.
