### ISSUE TITLE
Truthear Hola

### ISSUE THREAD

**Issue by HoodedMenace9** [jaakkopasanen/AutoEq#626]
please add Truthear Hola.. I couldn't find who your supported sources were so I'm sorry if they haven't recorded these.

**Comment by artemklevtsov** [comment]
![изображение](https://user-images.githubusercontent.com/603798/227840519-a80f3a45-6405-4211-8b65-f04b73e31ecf.png)

- https://crinacle.com/graphs/iems/truthear-hola/

**Comment by Ashvith10** [comment]
I have generated files from CSV, but I am unsure if they're proper. Where should I add them? They're based on crinacle's graph btw. Pinging @artemklevtsov .

**Comment by jaakkopasanen** [comment]
Seems to be missing from Crinacle's Drive folder. I let him know and will add this once he adds it there.

**Comment by jaakkopasanen** [comment]
Added.
