### ISSUE TITLE
Can't Import .wav file into Convolver. 

### ISSUE THREAD

**Issue by ProgKing** [jaakkopasanen/AutoEq#627]

**Comment by SvdB-nonp** [comment]
I am on Fedora (38, Gnome) and have an issue that could be related. I do use EasyEffects (v 7.0.4), not sure if that is very much different than PulseEffects.

For me EasyEffects does not crash, but it raises the error "Only Stereo Impulse Files Are Supported". Unfortunately this error is also raised when importing files that are generated in autoeq.app with the Stereo toggle turned on. I tried this for both Meze 99 (Classics) and Focal Elegia, but the headphone does not seem to make a difference.

So, assuming the error is correct, I think the stereo toggle does not work and it always generates a mono file, but I am uncertain how to check this.

![Screenshot from 2023-05-16 08-59-25](https://github.com/jaakkopasanen/AutoEq/assets/61807052/93a06cca-3e36-4791-bacf-3ae8117fa576)
![Screenshot from 2023-05-16 08-59-01](https://github.com/jaakkopasanen/AutoEq/assets/61807052/cb77dc19-88c0-42b6-b27e-5317d02cdc96)

**Comment by jaakkopasanen** [comment]
I solved #647 

@ProgKing can you test and confirm if your issue is solved now?

**Comment by SvdB-nonp** [comment]
I can at least confirm that for me it now imports succesfully in EasyEffects.
