### ISSUE TITLE
Request Truthear Hexa

### ISSUE THREAD

**Issue by artemklevtsov** [jaakkopasanen/AutoEq#628]
![изображение](https://user-images.githubusercontent.com/603798/227839956-cb9db6c9-0d5a-48ee-9527-a04e483b086f.png)

- https://crinacle.com/graphs/iems/truthear-hexa/

**Comment by jaakkopasanen** [comment]
Seems to be missing from Crinacle's Drive folder. I let him know and will add this once he adds it there.

**Comment by jaakkopasanen** [comment]
Added.
