### ISSUE TITLE
[question] cannot reproduce Innerfidelity results

### ISSUE THREAD

**Issue by brolyxxx** [jaakkopasanen/AutoEq#63]
Hi,
first of all thanks for this great project! 

For my **Sennheiser Momentum M2 Over-Ear** I wanted to produce a parametric eq that would be closer to my taste (I find the original results a lacking in the bass region), but before I start experimenting with different options etc I wanted to make sure I was able to reproduce the measurements exactly as in /results/innerfidelity/sbaf-serious/Sennheiser Momentum M2/ but I'm not able to achieve what you did.

this is the command I ran first:

`python frequency_response.py --input_dir innerfidelity/data/onear/Sennheiser\ Momentum\ M2/ --output_dir my_results/innerfidelity/Sennheiser_Momentum_M2/ --compensation innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv --equalize --parametric_eq --max_filters=5+5 --show_plot --bass_boost=4`

and this is what I get:
### Parametric EQs
In case of using parametric equalizer, apply preamp of **-7.1dB** and build filters manually
with these parameters. The first 5 filters can be used independently.
When using independent subset of filters, apply preamp of **-7.1dB**.

| Type    | Fc      |    Q | Gain    |
|:--------|:--------|:-----|:--------|
| Peaking | 14 Hz   | 0.65 | 4.8 dB  |
| Peaking | 105 Hz  | 0.57 | -1.9 dB |
| Peaking | 2273 Hz | 0.42 | -5.5 dB |
| Peaking | 3665 Hz | 1.76 | 10.8 dB |
| Peaking | 6270 Hz | 3.96 | 6.2 dB  |
| Peaking | 1225 Hz | 1.78 | 1.9 dB  |
| Peaking | 1907 Hz | 2.22 | -2.1 dB |
| Peaking | 2407 Hz | 1.08 | 2.2 dB  |
| Peaking | 4368 Hz | 0.17 | -1.6 dB |
| Peaking | 9874 Hz | 0.43 | 1.5 dB  |

which is different from what originally computed in the project folder.

I also tried with the option `--ten_band_eq` but it seems to return only 7 measurements in my case.

What am I doing wrong here?

**Comment by jaakkopasanen** [comment]
It's actually quite normal to get different parameters for the parametric eq filters because the filter parameters are generated by a non-deterministic process. The end result should however be very closely the same each time. You can confirm this by visually comparing the thick light green curves of the pre-computed result and your result.

`--ten_band_eq` should always produce 10 filters. There was a bug however which stopped the fixed band eq section to appear in the README.md if there wasn't also a parametric eq generated but I don't know if this is relevant here. Can you confirm that you actually get fixed band eq section in the README and that has 10 filters? Also do you have a FixedBandEQ.txt file in your folder and if so then how many lines does it have?

**Comment by brolyxxx** [comment]
Hi,

sorry for the late response. I've experimented a little more and can confirm the fixed band eq in the README file has 10 filters. 

However, at this point I'm not really sure I understand the purpose of option `--max_filters` as it seems to have no effect on the final number of filters, either parametric or fixed-band.
For instance, I ran the script 4 different times, every time only changing `--max_filters` and `--ten_band_eq`.

`python frequency_response.py --input_dir innerfidelity/data/onear/Sennheiser\ Momentum\ M2/ --output_dir my_results/innerfidelity/Sennheiser_Momentum_M2/ --compensation innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv --equalize --parametric_eq --fixed_band_eq --bass_boost=4 --max_filters=5+5 --ten_band_eq`

**Case 1**
`--max_filters=5+5`

ParametricEQ.txt has 10 filters
FixedBandEQ.txt has 8 filters

**Case 2**
`--max_filters=5+5`
`--ten_band_eq`

ParametricEQ.txt has 10 filters
FixedBandEQ.txt has 10 filters

**Case 3**
`--max_filters=10`

ParametricEQ.txt has 8 filters
FixedBandEQ.txt has 8 filters

**Case 4**
`--max_filters=10`
`--ten_band_eq`

ParametricEQ.txt has 8 filters
FixedBandEQ.txt has 10 filters

**Case 5**
`--max_filters=20`

ParametricEQ.txt has 8 filters
FixedBandEQ.txt has 8 filters

**Case 6**

`--max_filters=20`
`--ten_band_eq`

ParametricEQ.txt has 8 filters
FixedBandEQ.txt has 10 filters

In all cases the README file shows information consistent with the txt results.

If this is the desired behaviour then what effect has `--max_filters` on the output?

My results are here: https://mega.nz/#F!gMcDEIzA!bi7AQXZ4x4brbNoxAqpPjg

cheers

**Comment by jaakkopasanen** [comment]
Now I understand what's going on in here. When you specify `--fixed_band_eq` but don't give '--fc' it will actually produce parametric eq in the fixed band eq file and this was not intended. `--ten_band_eq` is a shortcut for setting `--fc=31,62,125,250,500,1000,2000,4000,8000,16000 --q=1.41` so when that is given it produces true fixed band eq. I fixed this by adding a check that `--fc` and `-q` are given when `--fixed_band_eq` is given.

`--max_filters` is the maximum number of filters produced and not the exact number. If you set `--max_filters=3` you should get 3 filters. The algorithm removes filters that don't do a whole lot so you might actually get fewer filters than what is the maximum number.

**Comment by brolyxxx** [comment]
Hi, thanks for the explanation and the quick fix! I'll now close the issue, cheers
