### ISSUE TITLE
Harman adherence points calculation seems off

### ISSUE THREAD

**Issue by ManeGarrincha** [jaakkopasanen/AutoEq#634]
Hi, 

I would like to know what exact procedure and mathematical formulae are used to compute the point score that calculates the compliance to the Harman target. For me it seems not possible that IEMs like the Moondrop Chu, the Tripowin Olina or the Salnotes Zero achieve higher point ratings than the Moondrop Variations, which is the closest to the Harman curve I have every seen in measurements, especially in the one from crinacle which are apparently used for the calculation.
Please be specific, I will understant the details as I have a PhD in theoretical physics.

Best regards

ManeGarrincha

**Comment by douglascamata** [comment]
Feel free to consult the source code: https://github.com/jaakkopasanen/AutoEq/blob/master/autoeq/frequency_response.py.

**Comment by douglascamata** [comment]
You can also refer to the README: https://github.com/jaakkopasanen/AutoEq#results

**Comment by ManeGarrincha** [comment]
Thanks for the answer, which is, alas, rather generic. In the README I could not find any details on the score calculation, besides a general description on how optimization works. And although I program in Python myself, I don't have the time to go through more than 1000 lines of code. So it must be some kind of distance metric calculation tht is applied and I would like to know which exactly and how it can produce such counterintuive results.

**Comment by douglascamata** [comment]
@ManeGarrincha the answer isn't generic, it's precisely pointing you at what to read to understand it. 1000 lines of code that are short, calling a bunch of well known scientific & numeric processing functions by name... should be easy for someone with such a degree and prior knowledge as you. As you said you don't have the time read it, do you expect others to have the time to explain it with the deepest details?

**Comment by ManeGarrincha** [comment]
Well ok, this is not very cooperative, strange for an open-source project, but be it as it may, you must have your reasons. I  just want to ask you now straight, if you believe the results of your algorithms, methods and calculations, do you personally honestly think the Moondrop Chu, the Tripowon Olina and the Salnotes Zero are closer to Harman, and according to your definition, sound better than the Moondrop Variations? If so I cannot believe any results that is coming from you.

**Comment by douglascamata** [comment]
These “results” are all done by numerical optimization (https://github.com/jaakkopasanen/AutoEq#parametric-equalizer-optimization). People working on this Github project do not own all the headphones that are supported. There is no “believe”, it’s mathematically close to Harman. Wether one like this or a different target it’s a waste of time to discuss.

**Comment by douglascamata** [comment]
> Well ok, this is not very cooperative, strange for an open-source project

Yes, it isn’t really a collaboration when one wants a deeply detailed explanation about how the project works and refuses to read code and documentation.

I work with open source projects on my job, every day from 9 to 5, and sometimes on my spare time. I can tell you, if you think asking this type of question is collaboration you’ll be disappointed.

**Comment by ManeGarrincha** [comment]
"> These “results” are all done by numerical optimization (https://github.com/jaakkopasanen/AutoEq#parametric-equalizer-optimization). People working on this Github project do not own all the headphones that are supported. There is no “believe”, it’s mathematically close to Harman. Wether one like this or a different target it’s a waste of time to discuss."

So whatever optimization there was used, when looking at the the original measured frequency responses, one must use a really weird distance measure  (for sure nor least squares) to come up with this score points. But I am not interested anymore, I did have my doubts from the start and now knowing how the people working in this project behave, I am out.

**Comment by ManeGarrincha** [comment]
It would be very interesting to see an algorithm, that puts the Chu closer to the Harman curve than the Variations. Maybe with a weight of 99% at 5kHz? Anybody who takes the output of some numerical procedure (in this case optimization) as an unquestionable result and is not checking and plausibilizing the results is not a serious researcher/programmer/scientist.
![Frequency response Harman target IE 2019v2 Moondrop Chu vs Moondrop Variations](https://user-images.githubusercontent.com/130615968/233886573-8d01a968-6d38-4520-aaf9-adafd96a0ecf.png)

**Comment by jaakkopasanen** [comment]
The exact methods can be found starting from https://github.com/jaakkopasanen/AutoEq/blob/master/autoeq/frequency_response.py#L1242

These methods have been developed with the [Listen Inc. Excel sheet](https://www.listeninc.com/products/test-sequences/free/prediction-of-listener-preference-of-in-ear-headphones-using-the-harman-model/#tab-id-1) as reference and I have ensured they produce exactly the same scores as the excel. Therefore I'm positive that the methods work correctly. The Excel sheet was developed together with Sean Olive himself.

Also [ranking](https://github.com/jaakkopasanen/AutoEq/blob/master/results/RANKING.md) tables tell you all the different components which go into this as well as their values. There you see that Chu has slightly lower standard deviation from the target, better slope adherence (linear regression) and about the same mean error as Variations so it gets slightly better score. Keep in mind that the two units in the table are from different sources. Chu was measured by Oratory1990 and Variations by Crinacle.

**Comment by ManeGarrincha** [comment]
Hi,

thanks Jaakko, this was the first valid information given here, your assistent does not seem to be able or willing to do so.
A few comments:

- Comparing mesurements from different sources is very questionable
- Why does the score calculation in line 1281 starts only from 40 Hz, while the optimization in line 1273 correctly from 20 Hz? That sounds a bit like cheating and will not benefit the good bass performance of the Variations.
-Also normalizing to 500Hz might change the outcome of the comparisons.
-While I know that measurements above 10kHz are not so reliable, it is nevertheless obvious that the Chu has a huge dip there and above and profits unrightly from the upper bound. So a cut-off of 15kHz would be more just, I guess.

Best regards
Garrincha

**Comment by jaakkopasanen** [comment]
@ManeGarrincha you can refer to the papers published by Sean Olive et al. about the headphone listener preference research. I did not do this research, I only implemented their method into AutoEq.

I'm closing this issue as I don't believe there's anything that needs to be done on AutoEq. If you wish to have a general discussion with other headphone enthusiasts, I suggest starting a thread in Head-Fi or Audio Science Review. These Github issues aren't really the right place for general discussion.
