### ISSUE TITLE
RockIt Sounds R50

### ISSUE THREAD

**Issue by JimBeam5** [jaakkopasanen/AutoEq#638]
RockIt Sounds R50 have been measured by innerfidelity but don't appear to be an option in AutoEq. Could these be added please?

**Comment by jaakkopasanen** [comment]
The index doesn't know these measurements: https://www.stereophile.com/content/innerfidelity-headphone-measurements

Where did you find the PDF?

**Comment by JimBeam5** [comment]
The pdf is on the page that you linked to.

https://www.stereophile.com/images/ifmeasure/AllGraphs.pdf

**Comment by jaakkopasanen** [comment]
Thanks. There have been other instances too where some PDFs aren't in the index page. Glad to have the all graphs PDF!

**Comment by jaakkopasanen** [comment]
Added. I hope no one finds anything else because I don't have the PDF parser anymore and had to do this by hand.
