### ISSUE TITLE
how to make over-ear headphone sound like an iem?

### ISSUE THREAD

**Issue by firebfm** [jaakkopasanen/AutoEq#639]
Is this even possible? I tried this command. python -m autoeq --input-dir="measurements\oratory1990\data\onear\Sennheiser HD 600" --output-dir="my_results/hd600_oratory to dunu sa6" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound-signature="results\crinacle\harman_in-ear_2019v2\DUNU SA6 (default mode)\DUNU SA6 (default mode) ParametricEQ.txt" --parametric-eq --parametric-eq-config=8_PEAKING_WITH_SHELVES --ten-band-eq --bass-boost=4 --convolution-eq --fs=44100,48000

But I got this error ValueError: x and y should have a same length.

I'm planning to purchase an iem but I want to hear what it sounds like first.

**Comment by jaakkopasanen** [comment]
https://autoeq.app/

Select your IEM, click the headphones icon in sound signature (under advanced), select the over-ear headphone and select an equalizer app. Done.

There were once some issues with different length input, compensation and sound signature data. Those should be resolved now. Please reopen if the issue persists.
