### ISSUE TITLE
KZ ZSN Pro meassurement from oratory1990 is wrong

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#645]
In [oratory's preset list](https://www.reddit.com/r/oratory1990/wiki/index/list_of_presets) it is listed as "KZ ZSN Pro", but the [document](https://www.dropbox.com/s/ypy9b7chwl77vmh/KZ%20ZSN%20Pro%20X%20%28Harman%20In-Ear%20LI%29.pdf?dl=0) shows that it is actually "KZ ZSN Pro X". It should be removed/renamed.

**Comment by jaakkopasanen** [comment]
Thanks for pointing out

**Comment by jaakkopasanen** [comment]
Renamed it
