### ISSUE TITLE
Focal Clear MG Parametric EQ: The abbreviation of low shelf (LSC) and high shelf (HSC) leads to error when importing the preset to Soundsource. It works with LS and HS. 

### ISSUE THREAD

**Issue by Rael1967** [jaakkopasanen/AutoEq#646]
**Describe the bug**

**To Reproduce**
What command was used? Describe all steps needed to reproduce the problem.

**Expected behavior**

**Files**
If applicable, add input and output CSV and other files needed to investigate and to reproduce the problem.

**System:**
 - OS: [e.g. Windows 10]
 - Version [e.g. 22, latest one in CHANGELOG.md]

**Additional context**

**Comment by jaakkopasanen** [comment]
Sort of expected. AutoEq labeled the shelf filters incorrectly for EqualizerAPO (was LS and HS, is now LSC and HSC). Clearly SoundSource only parses LS and HS. I'll let the devs know.

**Comment by jaakkopasanen** [comment]
I reverted back to `LS` and `HS` for SoundSource

**Comment by Rael1967** [comment]
Thanks a lot.
