### ISSUE TITLE
autoeq.app does not download a stereo impulse file despite enabling the option

### ISSUE THREAD

**Issue by MechanoPixel** [jaakkopasanen/AutoEq#647]
**Describe the bug**
Despite toggling `Stereo` to generate a stereo impulse file, a mono file is downloaded instead.
This is an issue because EasyEffects on Linux requires a stereo impulse file. Attempting to import the generated "stereo" impulse file fails with the error message "Impulse File Not Imported: Only Stereo Impulse Files Are Supported".

This is confirmed by using mediainfo to check that both the mono and "stereo" files only have one channel. Additionally, using md5sum reveals that regardless of toggling the Stereo switch, downloaded files are always identical.

**To Reproduce**
1. Go to autoeq.app
2. Select headphones (In my case, `Logitech G435 LIGHTSPEED`)
3. Select `EasyEffects / PulseEffects` as equalizer app
4. Turn on Stereo
5. Click on download icon

**Expected behavior**
A stereo impulse file is downloaded and is able to be imported into EasyEffects.

**Files**
[samples.zip](https://github.com/jaakkopasanen/AutoEq/files/11486140/samples.zip)
Both Edge and Chromium produced files with the same md5sum:
`e266c0e4fd64d9432679218f2ca1d010`

Firefox produced a file with a different md5sum:
`8727c9aeac285212034d1d537a936baf`

However, both browsers' respective mono and "stereo" generated files are the same:
```
e266c0e4fd64d9432679218f2ca1d010  edge_chromium_mono.wav
e266c0e4fd64d9432679218f2ca1d010  edge_chromium_stereo.wav
8727c9aeac285212034d1d537a936baf  firefox_mono.wav
8727c9aeac285212034d1d537a936baf  firefox_stereo.wav
```

**System:**
 - OS: Arch Linux
 - Browser(s) Tested: Mozilla Firefox 113.0.1, Microsoft Edge 113.0.1774.42, Chromium 113.0.5672.92
 - Version: 3e4ef66 (Latest commit as of writing this issue)

**Comment by DeastinY** [comment]
Same here
OS: Ubuntu
Browser: Mozilla Firefox 113.0
Same version

**Comment by DeastinY** [comment]
Related: https://github.com/jaakkopasanen/AutoEq/issues/627

**Comment by jaakkopasanen** [comment]
This is fixed now
