### ISSUE TITLE
AutoEQ.app - Apple Earpods option unselectable/unresponsive

### ISSUE THREAD

**Issue by echaskaris** [jaakkopasanen/AutoEq#648]
**Describe the bug**
Selecting other options generates data. Selecting Apple Earpods does not. The option lingers and when clicked does nothing.
This includes other Apple products as well.
Thank you.

Is the site new? Thank you for simplifying the process!

**System:**
 - OS: Win 10, Microsoft Edge

**Comment by jaakkopasanen** [comment]
Recommended target curve was missing for earbuds type headphones. It should work now.
