### ISSUE TITLE
Treble controls for target personalization

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#649]
I think the current options to personalize the bass target are great. 

For the treble range I would like to propose a two control implementation, corner frequency and post-tilt.

The first one defines where the post 1kHz pinna rise peaks, in Hz. The second control defines the tilt of the upper end range, in dB/octave. Default settings should resemble for instance Harman IE 2019 as much as possible, but it can't match 100%. The lack of a 100% match could be an acceptable trade off, personalization and target compliance cant be equal goals. The need for personalization mainly lies outside of 300Hz-3kHz either way, ranges where coupler accuracy suffers, and ranges where target research efforts have less consensus.

To illustrate the function of the two controls, with simple graphics:
![Screenshot 2023-05-17 161913 copy](https://github.com/jaakkopasanen/AutoEq/assets/15148553/14a3c2cd-a408-4264-9696-ed4a91a8c3d6)
![Screenshot 2023-05-17 161820 copy](https://github.com/jaakkopasanen/AutoEq/assets/15148553/4f32f8ea-aa0a-4151-bdb1-20b3910f135e)

A personalized target might look something like this for an average user:
![image](https://github.com/jaakkopasanen/AutoEq/assets/15148553/d060f80e-8a25-45f0-965c-4857ae7cd4b1)

Just to propose a means of treble personalization that would be intuitive for the end user, and help generate subjectively appealing results. It's understood this is one idea of out many possible avenues of treble personalization. It's understood that work would be required for it's implementation, and discussions of whether this method is better would have to come first. My guess is there would need to be functions for live generation of arbitrary amounts of pinna rise, that transitions into a down slope, by some averaged window. I think for the upper end range a pure linear tilt should be OK, even if it differs from established targets at the very top end. The post 1kHz pinna rise is something that maybe can be modelled with an exponential function, to roughly match Harman targets, at default settings.  

There's more to flesh out about my idea, and why it may, or may not, bet better than other ideas. I've spent hours browsing graphs and trying EQ matching function to various targets curves, but my single data point means I will appreciate honest feedback. As far as specific justification for claims I've made, I'll be glad to provide them, should this evoke more discussion.

**Comment by jaakkopasanen** [comment]
You can do this already quite easily with sound signature:

```
frequency,raw
20,0
2000,0
20000,-3
```

Also the treble level already has a control knob. I see no need for other dedicted controls.

**Comment by markanini** [comment]
Unless you want to talk about reducing the user facing controls for treble personalization, that's basically what my suggestion is about. Besides Sound signature I see four options relating to treble personalization, and your solution modifies an existing target. My suggestion generates a target parametrically, potentially reducing the total amount of controls for treble personalization down to two.
