### ISSUE TITLE
Edifier TWS200 autoeq config

### ISSUE THREAD

**Issue by ymnltd** [jaakkopasanen/AutoEq#652]
@jaakkopasanen 
Is there any autoeq config for Edifier TWS200? Can you please help me to find it? (Using Equalizer APO+Peace)

**Comment by ymnltd** [comment]
@jaakkopasanen 
https://github.com/jaakkopasanen/AutoEq/tree/master/results
I couldn't find edifier tws200 can you please help me on this?

**Comment by jaakkopasanen** [comment]
There's nothing I can do for you as I don't measure headphones myself. All the measurements are from the few sources that are included in this project and if none of the have measured the headphones then they won't be found in AutoEq.
