### ISSUE TITLE
CSV file won't upload to site

### ISSUE THREAD

**Issue by GrantoidOnGit** [jaakkopasanen/AutoEq#653]
I created a CSV file in Notepad++ to upload to the site, but it's giving me an "Internal Server Error" message. I used the article you wrote forever ago to map the points from an image. I formatted it the way you described, but it won't accept the file.

**Comment by jaakkopasanen** [comment]
Can you please share the file here so that I can try to reproduce?

**Comment by jaakkopasanen** [comment]
Did you by any chance drag and drop the CSV file to the headphone select field before clicking anything else on the page?

**Comment by Grantoid** [comment]
I tried both dragging it in and clicking the upload button.

[Air3.csv](https://github.com/jaakkopasanen/AutoEq/files/11519998/Air3.csv)

**Comment by jaakkopasanen** [comment]
The error message certainly wasn't very helpful. I fixed that and now AutoEq will tell you that you file has duplicate values which you need to fix manually.

**Comment by Grantoid** [comment]
@jaakkopasanen You rock man, thanks for the quick reply and being so helpful
