### ISSUE TITLE
Hyperx Cloud Alpha Wireless RTINGS incorrect measurement

### ISSUE THREAD

**Issue by Nescor** [jaakkopasanen/AutoEq#655]
RTINGS did their frequency response measurements using the 'balanced' EQ in the HyperX app. The app however, introduces a noticeable latency of around 300ms and leads to sound problems.

RTINGS recently performed a new measurement using the default headphone settings. The previous measurement used in AutoEQ are unfortunately unusable. As a result, these headphones should be updated to the new measurements instead.

**Comment by jaakkopasanen** [comment]
Thanks for pointing this out. I updated the measurement and what you find now in AutoEq should be the new one.
