### ISSUE TITLE
High GPU usage on autoeq.app website due to swirly lines animation

### ISSUE THREAD

**Issue by TheForcer** [jaakkopasanen/AutoEq#658]
**Describe the bug**
When visiting autoeq.app, I've noticed my PC fans spinning up, even though I did nothing else computionally. In Task Manager I can see a consistant ~30/40% GPU usage while on the site, which goes down to 0 after closing the page. This happens in Chrome/Firefox/Edge.

**To Reproduce**
Visit autoeq.app. Monitor GPU usage via Task Manager.

**Expected behavior**
I expect roughly no GPU usage when visiting the site 😁

**System:**
 - Win 10 22H2
 - Firefox/Edge/Chrome 113

**Additional context**
The swirly lines effect on the bottom of the page seems to be the culprit. I created a uBlock Origin Filter (`autoeq.app##.css-ny5in9 > svg:nth-child(1)`) which removes the effect, and GPU load is 0 now. I think it would be for the better if the effect was removed or replaced with a less demanding effect ;)

**Comment by jaakkopasanen** [comment]
I understand the point of view but I implemented the waves knowing fully their performance impact and therefore they're going stay. Computers work for us, noticed the other way around.

**Comment by amurzeau** [comment]
I guess this won't change anyway, but I wanted to let you know that this animation cause the app to be laggy on the phone, this is a bit unfortunate.
