### ISSUE TITLE
Output format for Rockbox parametric EQ - example included

### ISSUE THREAD

**Issue by julianhughes** [jaakkopasanen/AutoEq#659]
It would be great for the autoeq.app to offer a downloadable eq file compatible with Rockbox https://www.rockbox.org/
Rockbox uses a 10 band parametric EQ with low and high shelf, 8 peaking filters modified by q factor, and a pre-cut, so it is compatible with autoeq parametric results.  I include an example to show formatting.  It seems the Rockbox Q numbers need to be rounded up or down compared to the original but aside from that I can't see any difference.  The closest in format and required output is probably the EqualizerAPO ParametricEq output by autoeq.app

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/in-ear/Final%20Audio%20E1000
```
You can use filters 1-5 or 1-10. Apply preamp of -6.2 dB or -6.2 dB, respectively.

# 	Type 	Fc (Hz) 	Q 	Gain (dB)
1 	LowShelf 	105 	0.7 	6.4
2 	Peaking 	42 	2.2 	0.8
3 	Peaking 	213 	0.33 	-3.7
4 	Peaking 	2484 	0.18 	2.9
5 	Peaking 	5975 	3.02 	-5.5
6 	Peaking 	1238 	4.55 	-0.7
7 	Peaking 	2134 	2.52 	1
8 	Peaking 	3067 	3.82 	-1.5
9 	Peaking 	4374 	4.37 	0.6
10 	HighShelf 	10000 	0.7 	0.3
```

And from those results added to a Rockbox player and saved:

```
# .cfg file created by rockbox 0f941488af-230525 - http://www.rockbox.org

eq enabled: on
eq precut: 62
eq low shelf filter: 105, 7, 64
eq peak filter 1: 42, 22, 8
eq peak filter 2: 213, 3, -37
eq peak filter 3: 2488, 2, 29
eq peak filter 4: 5975, 30, -55
eq peak filter 5: 1238, 45, -7
eq peak filter 6: 2134, 25, 10
eq peak filter 7: 3067, 38, -15
eq peak filter 8: 4374, 44, 6
eq high shelf filter: 10000, 7, 30

```

**Comment by jaakkopasanen** [comment]
Does Rockbox support parametric filters? AutoEq currently has a Rockbox option in the command line interface but that's a standard 10-band graphic eq.

**Comment by julianhughes** [comment]
Yes, it does support a full parametric equalizer with 10 bands including Low Shelf, High Shelf and precut,  as described in my initial post.  For further information I attach an extract from the pdf manual, a screenshot of the EQ screen for my Moondrop Quarks IEMs on my Fiio M3K running Rockbox, and the Rockbox config file for that same EQ, as it appears in the Rockbox OS as a text file. In Rockbox the file is a .cfg file but github does not allow attaching .cfg so I changed it to .txt

[rockbox_manual_extract.pdf](https://github.com/jaakkopasanen/AutoEq/files/12708305/rockbox_manual_extract.pdf)

![eq_screen_fiio_rb](https://github.com/jaakkopasanen/AutoEq/assets/34354299/522c9652-f9f2-4908-9a97-d36c72c3a6f0)

[QUARKS.txt](https://github.com/jaakkopasanen/AutoEq/files/12708302/QUARKS.txt)

**Comment by jaakkopasanen** [comment]
Rockbox is available in the webapp as an eq app option.
