### ISSUE TITLE
[question] does impulse response frequency matters?

### ISSUE THREAD

**Issue by Frugipon** [jaakkopasanen/AutoEq#66]
Hello,
sorry if this is a noobish question but I am wondering if the the frequency of the impulse response matters. I suppose it does but to what extent?
I would use a rooted smartphone with Viper4Android connected to an OTG USB DAC (thus bypassing Android mixer) so the files I'd play would have various sample frequencies (44.1, 48, 88.2, 96, 176.4, 192).
So generally speaking, which impulse file should I get: the 44.1 or 48 one and why?

Thanks

**Comment by jaakkopasanen** [comment]
Impulse response sampling rate must match exactly the sampling rate of the incoming signal. I don't use Viper4Android myself so I don't know how it works and how does it handle different sampling rates. I would assume that it has sampling rate converter before convolution engine so you could use impulse response with any sampling rate with any file. Perhaps people at Viper4Android forums would be of more help than me.

**Comment by Frugipon** [comment]
Thanks @jaakkopasanen, that's what I feared and from what I gathered so far, Viper4Android might not be suitable for bit perfect playback on android.
Guess I'll have to find another way to apply the EQ presets (UAPP + plugin seems to be the best solution, I just hate its UI).
