### ISSUE TITLE
Adjustable frequency range to ease/bypass equalization

### ISSUE THREAD

**Issue by miimar** [jaakkopasanen/AutoEq#663]
First of all, i want to congratulate you and everyone involved for making Autoeq.app!
Creating equalizer profiles for headphones took a huge leap forward with this one.

I've been playing around with it quite a bit and found perfect settings that make even the higher frequencies just right for my liking, but this introduces a huge boost around 9500 hz, which i suppose is caused by a dip in Gras measurements. I can ofcourse use parametric equalizer to carve that boost out, but would an adjustable region for easing/bypassing equalization on a specific frequency range be a possible feature in the future? 

For example in my case i would set it 9000-10000 hz and adjust it to do only ~25 % of what it is currently doing and leave rest of the eq like it is.

Harman_over-2018.csv target and Oratory's measurement of Hifiman Edition XS were used to produce 96 khz 32 bit convolution eq with 5 hz frequency resolution.
Settings: Max gain and max slope set at 36 db, smoothing 0.05/oct, treble smoothing 0.5/oct, treble gain multiplier 0.5 and transition region 10000-20000 hz.

**Comment by jaakkopasanen** [comment]
It's already possible to set a multiplier like this, but for the entire treble range. In the UI it's called Treble Gain Multiplier. It cannot focus on a limited range like 9 to 10 kHz though and honestly I don't think there is a compelling enough use case for it to put in the effort to implement such a thing. If you have spare filters available in your eq app, you can add one extra to do the trick.
