### ISSUE TITLE
Ruby gem for generated audio-filter strings from AutoEQ results

### ISSUE THREAD

**Issue by jslabovitz** [jaakkopasanen/AutoEq#664]
Sorry if this isn't an 'issue,' per se, but I couldn't find any other place to submit this. I can't find a list of non-app support (like bindings) for AutoEQ; if you don't have that, maybe you'll just find this of interest. (You can close this issue if you like.)

I've just published a Ruby library that works with the AutoEQ result files. I've been using this in a personal music player, and just split off the AutoEQ code to be more maintainable and useable by other people. Here's the summary:

> This is a Ruby gem that works with the collection of headphone equalizations generated by the [AutoEQ](https://autoeq.app) project. With the gem, you can load the full set of equalizations, find one or more equalizations by name, and generate **audio filter** strings. These strings can then be used with projects like [MPV](https://mpv.io), [FFmpeg](https://ffmpeg.org), or other projects that use [libavfilter](https://ffmpeg.org/libavfilter.html) to process audio. Canonical information about filters can be found at [FFmpeg Filters Documentation](https://ffmpeg.org/ffmpeg-filters.html).

It's at https://github.com/jslabovitz/autoeq_loader or by running `gem install autoeq_loader`.

**Comment by jaakkopasanen** [comment]
Looks cool! Not sure what to do about this though. There doesn't seem to be anything that needs to be done on AutoEq's end so I'll just close the issue as you suggested.
