### ISSUE TITLE
App doesn't produce convolutional Eq WAV file with the selected sample rate

### ISSUE THREAD

**Issue by AlexSKaye** [jaakkopasanen/AutoEq#668]
Just came back to this repo to find you've built a full fledged (and smooth) app out of it. Amazing! Unfortunately, I've noticed that no matter what the sample rate is set to in the 'Convolutional Eq' settings, the downloaded WAV file is always 48k. Bit depth and stereo options seem to work ok, and the base64 data under the 'fir' key returned from /equalize seems to vary with sample rate.

**Comment by jaakkopasanen** [comment]
Good catch and thanks for reporting. I'll fix this shortly.

**Comment by jaakkopasanen** [comment]
This is fixed now 🎉 

The problem was AudioContext resampling the audio data automatically when decoding.
