### ISSUE TITLE
Fiio BTR7 EQ as option

### ISSUE THREAD

**Issue by wwinter86** [jaakkopasanen/AutoEq#669]
Please as FIII BTR7 as an EQ option

**Comment by jaakkopasanen** [comment]
Looks like there is a parametric eq available. While I'm not too eager to add every eq app and device to AutoEq's list of eq app options, I did write some instructions on how to work with apps that are not supported. See https://github.com/jaakkopasanen/AutoEq/wiki/Choosing-an-Equalizer-App#parametric-equalizers
