### ISSUE TITLE
Porting to Python 3.7

### ISSUE THREAD

**Issue by brolyxxx** [jaakkopasanen/AutoEq#67]
Hi, just wandering if there's a plan to port the script to Python 3.7 and, if so, the expected time of completion? 

I tried running the script on my Arch Linux box where python3.7 is the default version: the script complaints about a few deprecated functions but it seems to complete successfully. I can send you the output if you want.

**Comment by jaakkopasanen** [comment]
Python 3.6 is mentioned in the documentation because at the time Tensorflow didn't work with Python 3.7. If requirements get installed without any problems then everything is ready for 3.7

**Comment by brolyxxx** [comment]
perfect, thanks
