### ISSUE TITLE
Add support for Foobar2000 EQ

### ISSUE THREAD

**Issue by razvanab** [jaakkopasanen/AutoEq#670]
Support for Foobar2000 audio player EQ.

Here is an example for the EQ format:

Metal:
`4
5
5
3
0
-1
-2
-1
0
1
1
1
1
0
-1
-1
-1
-1
`
Pop
`6
5
3
0
-2
-4
-4
-6
-3
1
0
0
2
1
2
4
5
6
`
Clear
`0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
`

**Comment by ryne** [comment]
I'm curious about the rationale behind this. Wouldn't it be more convenient to have the equalizer settings applied universally, eliminating the need for equalization at the app level?

**Comment by razvanab** [comment]
That is true, but unfortunately, there is no way to import presets into the Realtek audio app, which most people use.

**Comment by ryne** [comment]
The general recommendation is to setup [Peter's Equalizer APO (Peace)](https://sourceforge.net/projects/peace-equalizer-apo-extension/) and import presets there. There were a few guides on r/headphones on how to do so but it looks like the subreddit is still locked down in protest. It should be compatible with your setup.

**Comment by razvanab** [comment]
I'll try that, thank you.

**Comment by nihil-admirari** [comment]
Desktop foobar2000 has both a [convolver](https://www.foobar2000.org/components/view/foo_convolve) and a [standard 31-band equaliser](https://www.foobar2000.org/components/view/foo_dsp_xgeq), both of which are better than the default equaliser, and both of which are already supported, though none of these plugins have been recompiled for x64.

**Comment by JuhaTP** [comment]
I have released some code to build presets for Foobar2k EQ directly from AutoEq command line. It's still a suggestion to Jaakko (might pull a request after more testing done) but, if interested, you can find the code listed at [Head-Fi](https://www.head-fi.org/threads/autoeq-app-is-a-web-application-for-equalizing-headphones-the-easy-way.968185/post-17672917).

**Comment by razvanab** [comment]
Thank you.

**Comment by jaakkopasanen** [comment]
If Foobar has convolver available then that's really what should be used. The standard Convolution Eq option in the web app should cover the needs for that. Therefore I won't be implementing anything custom for Foobar.

**Comment by JuhaTP** [comment]
/"On 9.8.2023 11.02, Jaakko Pasanen wrote://
/
//

/If Foobar has convolver available then that's really what should be 
used. The standard Convolution Eq option in the web app should cover the 
needs for that. Therefore I won't be implementing anything custom for 
Foobar."/


AFAIK, Foobar2k Mobile version does not include convolver. Foobar Mobile 
on iOS, has no other way to get a decent equalizer other than build-in 
SuperEQ."

**Comment by elandorr** [comment]
SuperEQ support would be super @jaakkopasanen. fb2k is a must have (and others also use SuperEQ).
@JuhaTP already did all the work apparently, can't you simply use it?

@JuhaTP FYI If you're still interested in this: Your fork fails with a keyerror for `fs`. Probably simple to fix, but not my area of expertise at all.
