### ISSUE TITLE
is the csv file in measurements/rtings /data/ the raw data?

### ISSUE THREAD

**Issue by sasasqt** [jaakkopasanen/AutoEq#671]
in rtings_crawler.py line 133: fr.raw += target.raw 
https://github.com/jaakkopasanen/AutoEq/blob/402ccd4c0497e70a01263a9a77691535de6f8b8c/measurements/rtings/rtings_crawler.py#LL133C1-L133C1
(And target is either OVEREAR_TARGET 'rtings_compensation_w_bass.csv' or INEAR_TARGET =rtings_inear_compensation_w_bass.csv'
)

it seems to me that the fr added the target as compensation before writing to the csv file.

is this the expected behaviour? isn't the data folder supposes to be the raw measurements without compensation?

Bests

**Comment by jaakkopasanen** [comment]
Rtings data in their JSON files is compensated and therefore to get the raw data, the compensation needs to be added.

**Comment by sasasqt** [comment]
nice to know, thx!
