### ISSUE TITLE
Is adding a 20-band graphic equalizer easy enough to implement?

### ISSUE THREAD

**Issue by kylxbn** [jaakkopasanen/AutoEq#676]
A music app which I use always called "AIMP" has support for 20-band graphic equalizers. It is similar to a 10-band graphic equalizer, but can set the values in between the normal bands, so it has bands that start like 31Hz, 43Hz, 63Hz, 87Hz, 125Hz, 175Hz, 250Hz, 350Hz, 500Hz, 700Hz, 1kHz, 1.4kHz ... until 22kHz.

If 20-band graphic equalizer settings are available, it would be really easy to configure this equalizer. It might also be better to have a 20-band setting since I think it could offer better accuracy when available.

For now, I'm using the Wavelet configuration available in [https://autoeq.app/](https://autoeq.app/) but it's not an exact match and if possible, I would like to use more accurate values. I would be really thankful if there is a 20-band graphic equalizer option!

I actually tried to edit the source code myself to produce the desired settings, but I'm kinda lost at which Q-value I should use... I think I better leave this to the experts.

Thank you very much.

**Comment by Matojeje** [comment]
Regarding AIMP on **Windows**: I can confirm that the same EQ bands appear on [AIMP v5](https://www.aimp.ru/v2/pages/features/afw_dsp_2-en.png), but they've only been added recently, so the bands on [v4](https://github.com/jaakkopasanen/AutoEq/assets/3956863/2dccf9a3-e26f-4a3a-a25a-7bdb45a41319) and v3 are a bit different.

![obrazek](https://github.com/jaakkopasanen/AutoEq/assets/3956863/4bdfb5f9-0680-4b84-ab12-fadab3af060b)


Here's the screenshots of the equalizer on Android (AIMP v4.00.133RC):

![obrazek](https://github.com/jaakkopasanen/AutoEq/assets/3956863/42ceb0fd-fa5a-4cbe-a12a-25ad21bfb0d6)

**Comment by jaakkopasanen** [comment]
I'm not too keen on adding every exotic eq app in AutoEq but I did write instructions in the wiki on how you can configure any graphic or parametric equalizer using Custom Parametric Eq option:

https://github.com/jaakkopasanen/AutoEq/wiki/Choosing-an-Equalizer-App#non-standard-graphic-equalizers

I even used this 20-band app as an example for the graphic eq. Hope this helps.

I'll close this issue as I won't implement AIMP in AutoEq (or 20-band GEQ).

**Comment by kylxbn** [comment]
@jaakkopasanen I'm very grateful! That's actually a good response since supporting every app is impossible. Now everyone can use their favorite equalizers. Thank you very much!
