### ISSUE TITLE
Target is +3db...

### ISSUE THREAD

**Issue by kmitchel** [jaakkopasanen/AutoEq#677]
Just getting started with AutoEQ 3.0.0 Python 3.9 on ArchLinux.

In the graph, and generated CSV file the target field is +3 greater than what is specified in the compensation file. Using my own file and the zero.csv from the repo.

Using a venv with command line `python -m autoeq --input-file test.csv --output-dir out --compensation zero.csv --parametric-eq` on a frequency response generated with REW.

I would expect the target values to match the compensation file, unless some preamp was specified maybe (doesn't appear to move target line.

I'm trying to compare AutoEq against REW.  I'm hoping AutoEQ will be a little bit "smarter".  For the time being I'll just generate a new target with a -3 offset.  I'm currently trying out AudioFrog, but their provided file is really stepped, so I apply 1/1 smoothing with REW.

After putting a -3 offset on my target, it generates +6, so still +3 over the intended target.

**Comment by jaakkopasanen** [comment]
AutoEq is actually being "smart" here. What happens is that all of the curves are shiften in such a way that error curve is centered around 0 dB (100 Hz to 10 kHz). Moving error obviously means the target needs to be moved also when the original frequency response is kept fixed.
