### ISSUE TITLE
Fibae-3 48k irs issue

### ISSUE THREAD

**Issue by adamcathersides** [jaakkopasanen/AutoEq#68]
Hi,

Firstly thanks so much for all of the hard work you have put into this project.  It is absolutely fantastic.

I just wanted to flag with you that the [fibae3 48kHz irs file](https://github.com/jaakkopasanen/AutoEq/blob/master/results/custom/Custom%20Art%20FIBAE%203/Custom%20Art%20FIBAE%203%20minimum%20phase%2048000Hz.wav) seems to be showing a sample rate of 44.1kHz.   Not a huge problem really, just wanted to share while I remembered :)

Thanks

**Comment by jaakkopasanen** [comment]
Thanks for noticing and creating the issue. I decided to "fix" this by removing the custom result. It's not very convenient to update the custom results and there is a measurement and results by Crinacle for FIBAE 3. Recommended results now point to Crinacle's result and that should be correct.
