### ISSUE TITLE
what does "raw" and "error" mean??

### ISSUE THREAD

**Issue by TheBestKmanEver** [jaakkopasanen/AutoEq#684]
i know what everything else is but what do those "raw" and "error" lines mean exactly??
![Sennheiser HD 599](https://github.com/jaakkopasanen/AutoEq/assets/35676228/7164bfda-831b-41a6-91a6-88cacc74bbb5)

**Comment by jaakkopasanen** [comment]
Raw is the raw (unsmoothed) frequency response of the headphone. Error is the difference between target and the raw frequency response.
