### ISSUE TITLE
EasyEffects requires stereo impulse files

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#685]
EasyEffects requires stereo files for convolver plugin.
The WebApp should automatically enable this option (stereo) when selecting EasyEffects as equalizer app.

**Comment by tiagofreire-pt** [comment]
![image](https://github.com/jaakkopasanen/AutoEq/assets/41837236/a023cfd1-64ad-4f3d-b2fb-76f78d383145)
Seems the support for stereo impulse is available but needs to be turned-on manually.

**Comment by jaakkopasanen** [comment]
Changed EasyEffects into parametric eq. See #700
