### ISSUE TITLE
Ability to upload audio files

### ISSUE THREAD

**Issue by derkrasseleo** [jaakkopasanen/AutoEq#686]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to upload my own audiofile for comparison.

**Describe alternatives you've considered**
Downloading the EQ-Preset and trying myself.

**Comment by jaakkopasanen** [comment]
Just to make sure I understand the request: you want to upload your own songs to the audio player in the web app?

**Comment by derkrasseleo** [comment]
Yes

**Comment by jaakkopasanen** [comment]
After some long consideration I've decided not to implement this. I believe AutoEq offers sufficient capabilities as is for evaluating the equalizer profiles. Any further testing can always be done on the device itself.
