### ISSUE TITLE
ATH-MSR7: 16k roll-off (typo?)

### ISSUE THREAD

**Issue by Robotnik247** [jaakkopasanen/AutoEq#687]
I understand that everyone has different tastes but the roll-off at 16k seems kinda exaggerated (already was at stock). I assume the actual number is -2.5 and not 5.2?

**Comment by jaakkopasanen** [comment]
It's not a typo. These results are generated automatically so typos aren't really possible. The frequency response is a fair bit below the target in the >10 kHz region so boost is required to reach the target. But as you said, take these with a grain of salt and adjust the last band or two to your tastest. The measurements are not going to be representative of what the frequency response will be on your head anyways.
