### ISSUE TITLE
Dumb question, but merely curious 

### ISSUE THREAD

**Issue by thisfixesit** [jaakkopasanen/AutoEq#688]
Are 61.5, 62 and 63 roughly all the same frequencies on a 10-band EQ?  And why do some 31-band EQ bands that are generated by Autoeq.app not always match the 
![10-band SBC Eq](https://github.com/jaakkopasanen/AutoEq/assets/141692869/58b070eb-b64d-42d7-a82d-020478746ab7)
same 31-band frequencies on say Musicolet?  I've read a lot about equalizers, and I'm familiar, but this concept is just sort of difficult for me to visualize without someone just saying, "yes" they're functionally all the same frequencies.  Thankyou for your time.

**Comment by jaakkopasanen** [comment]
It's supposed to be 62.5 Hz, since 125 / 2 is 62.5. Often it's rounded to 63 and I suppose some UI's might round down (`int(62.5)`).

**Comment by thisfixesit** [comment]
Thankyou so very much for taking the time to answer that.  I really
appreciate it and all the work you do.

-Ryan
