### ISSUE TITLE
Clarify naming of SteelSeries Arctis Nova Pro csv files/names within autoeq.app

### ISSUE THREAD

**Issue by Loxrie** [jaakkopasanen/AutoEq#690]
**Describe the bug**

Currently the names of the CSV files/names on autoeq.app are:

SteelSeries Arctis Nova Pro.csv
SteelSeries Arctis Nova Pro for Xbox.csv

It’s not clear which devices in the series these are for, and RTings have since updated the names in their review  Can they be called:

SteelSeries Arctis Nova Pro.csv
SteelSeries Arctis Nova Pro Wireless.csv

As I don’t believe the XBox variants have a different frequency response, it’s just whether it’s wired or wireless.  The new names on RTings feflect this change as well.

**To Reproduce**
N/A

**Expected behavior**
To be able to clearly identify which one to choose for the wired version of the Nova Pro (or indeed the wireless).

**Files**
```
measurements/rtings/data/over-ear/SteelSeries Arctis Nova Pro.csv
measurements/rtings/data/over-ear/SteelSeries Arctis Nova Pro for Xbox.csv
```

**System:**
Web

**Additional context**
N/A

**Comment by jaakkopasanen** [comment]
Fixed 🎉 The second on is called Wireless now.
