### ISSUE TITLE
"Anker Soundcore Space A40" not working on autoeq.app

### ISSUE THREAD

**Issue by phu54321** [jaakkopasanen/AutoEq#691]
**Describe the bug**
Selecting `Anker Soundcore Space A40` incurs following error message
```
TypeError: Cannot read properties of undefined (reading 'gain')
```

Closing the error message box and re-selecting A40 let me get to the next stage

**To Reproduce**

1. Go to https://www.autoeq.app/
2. Type `A40`
3. Select `Anker Soundcore Space A40`

<img width="444" alt="image" src="https://github.com/jaakkopasanen/AutoEq/assets/775265/cd54dd15-dbbc-47aa-8deb-62ccebf02e4e">

**Expected behavior**
This graph should be shown

<img width="1134" alt="image" src="https://github.com/jaakkopasanen/AutoEq/assets/775265/2900bcff-4205-4f40-b663-7837a61251fc">

**System:**
 - OS: Windows 11, Chrome 115.0.5790.171
 - Version 2023-08-18 (IDK what exact version this is... There is no `CHANGELOG.md` on the repo)

**Comment by lohsiewweng** [comment]
thanks

박현우 ***@***.***> 於 2023年8月18日 週五 12:38 寫道：

**Comment by jaakkopasanen** [comment]
@phu54321 could you take a full screen capture, instead of just the frequency response graph?

**Comment by phu54321** [comment]
Somehow this is now fixed??

This screen is now shown as intended.

<img width="1280" alt="image" src="https://github.com/jaakkopasanen/AutoEq/assets/775265/a584b319-dbdf-494c-b78e-1764be8b6927">
