### ISSUE TITLE
Why doesn't the oratory1990 HD 600 chart match the autoeq.app chart?

### ISSUE THREAD

**Issue by sofakng** [jaakkopasanen/AutoEq#692]
I'm new to EQ but I'm looking at the [orratory1990 EQ chart](https://www.dropbox.com/s/pn3heg2rkwzeh34/Sennheiser%20HD600.pdf?dl=0).

It shows the following settings:
<img width="753" alt="Screenshot 2023-08-19 at 10 12 15 PM" src="https://github.com/jaakkopasanen/AutoEq/assets/2228499/052d4e46-df68-4499-8404-47011abcf2b6">

...but the autoeq.app settings don't seem to match:
<img width="515" alt="Screenshot 2023-08-19 at 10 13 14 PM" src="https://github.com/jaakkopasanen/AutoEq/assets/2228499/5cab87fb-5458-4248-8c61-51a37d9f3af0">

Am I looking at the wrong things or doing something wrong?

**Comment by jaakkopasanen** [comment]
AutoEq doesn't pick up the filter parameters from the PDFs, only the frequency response measurement. AutoEq generates new filter parameters based on the frequency response and user selections live. With the default parameters, the resulting equalizer frequency response should be quite close (not identical) although the filter parameters can be very different.
