### ISSUE TITLE
convolution eq doesnt work - creates white noise

### ISSUE THREAD

**Issue by stunlocked1** [jaakkopasanen/AutoEq#694]
I selected Superlux HD 681 evo, convolution eq, didn't touch other settings
I don't remember where I found this but this is a normal convolution response for those headphones
![image](https://github.com/jaakkopasanen/AutoEq/assets/76593873/0a630555-8983-4488-a223-c2d71bf3d810)
![image](https://github.com/jaakkopasanen/AutoEq/assets/76593873/b3816512-fbb1-40ca-ae45-0494d86e7a29)

and this is what I get when i press convolution eq in the website - just white noise
![image](https://github.com/jaakkopasanen/AutoEq/assets/76593873/bdf69db7-f278-4f48-80de-a628fd2b9dfa)
![image](https://github.com/jaakkopasanen/AutoEq/assets/76593873/83d4b305-e141-47a7-bc65-69181509f592)

**Comment by jaakkopasanen** [comment]
FIR filters created by AutoEq work for me, except 32-bit floats created in Firefox. Would you have any details or clues for how I could try to reproduce this?

**Comment by stunlocked1** [comment]
> FIR filters created by AutoEq work for me, except 32-bit floats created in Firefox. Would you have any details or clues for how I could try to reproduce this?

in brave browser the shield breaks it maybe digital fingerprint protection

**Comment by jaakkopasanen** [comment]
@stunlocked1 does this happen only in Brave browser?

**Comment by stunlocked1** [comment]
> @stunlocked1 does this happen only in Brave browser?

yeah only with the shield enabled

**Comment by jaakkopasanen** [comment]
Brave browser very small market share and therefore I can't justify spending my time on fixing an issue that's specific to this one browser. The workaround is obvious: disable shield or use another browser.
