### ISSUE TITLE
Convolution EQ broken when using 32fp

### ISSUE THREAD

**Issue by Skorrr** [jaakkopasanen/AutoEq#695]
Hi, following #668 now convolution eq in 32fp gives no sound at all, either in the app preview or in the dowloaded IR.

**Comment by jaakkopasanen** [comment]
Are you by any chance using Firefox?

I can reproduce this on Firefox but not on Chrome. Apparently Firefox doesn't know how to decode 32-bit floats: https://bugzilla.mozilla.org/show_bug.cgi?id=1349658

**Comment by Skorrr** [comment]
I am indeed! I can confirm it works on chromium based Brave as well as Edge

**Comment by Skorrr** [comment]
I am indeed! I can confirm it works on chromium based Brave as well as Edge.

**Comment by jaakkopasanen** [comment]
I added a warning message in the convolution eq app if the audio decode fails with instruction to try another browser. Not much else I can do here.
