### ISSUE TITLE
Why is this step necessary?“Shift error by it's mean in range 100 Hz to 10 kHz”

### ISSUE THREAD

**Issue by Jinbiao-Liu** [jaakkopasanen/AutoEq#697]
```python
# Set error
        self.error = self.raw - self.target
        if min_mean_error:
            # Shift error by it's mean in range 100 Hz to 10 kHz
            delta = np.mean(self.error[np.logical_and(self.frequency >= 100, self.frequency <= 10000)])
            self.error -= delta
            self.target += delta
``` 
<img width="649" alt="autoeq_set-error" src="https://github.com/jaakkopasanen/AutoEq/assets/71210720/beecbe5f-d3c5-418e-96a0-462a4fad6afa">

**Comment by jaakkopasanen** [comment]
Removing the "DC bias" of frequency response (error) ensures there is a balanced amount of boosts and cuts in the eq profile. It's not really super crucial but might make it a bit neater for the parametric eq optimizer generate the filter parameters.
