### ISSUE TITLE
Adding the SoundGuys Target Curve and measurements to AutoEQ

### ISSUE THREAD

**Issue by Hastings014** [jaakkopasanen/AutoEq#698]
My request is to have the SoundGuys target house curve added to headphone target curves, and to add them as a source for headphone measurements.

Please see the SoundGuys explanation of their house target curve: https://www.soundguys.com/soundguys-house-curve-54290/

Their website has extensive reviews and measurements of most headphone models available, and they also have their own custom target curve from which they compare all of these headphones. I find their reviews very useful and I really like their target curve sound. I think it would be great if this were added to AutoEQ because I imagine a lot of people in the headphone community refer to them for reviews.

**Comment by jaakkopasanen** [comment]
I've decided not to add any curves that aren't based on science if there is a science-based curve available. The only exception is my own AutoEq target for in-ears but that's very very close to Harman anyways.

**Comment by Hastings014** [comment]
Okay thanks for letting me know!

**Comment by isavcic** [comment]
@jaakkopasanen how about now when the SoundGuys curve is actually widely accepted and recognized as preferred? See https://aes2.org/publications/elibrary-page/?id=22696
