### ISSUE TITLE
Applying EQ to treble? Is this good or dumb

### ISSUE THREAD

**Issue by ARDEACT** [jaakkopasanen/AutoEq#701]
I've always thought the treble 5K and above is the headphones' timbre, and I always find it sounds weird if you apply EQ to this frequency region. Do I have logic in this thinking?

**Comment by jaakkopasanen** [comment]
"Timbre" is defined by the entire frequency response. Above 2-4 kHz the individual differences start to play a large role and equalizing those based on dummy head measurements is not going to be as accurate but I wouldn't say it's more "correct" to leave them untouched either.
