### ISSUE TITLE
Some entries can not be parsed from INDEX.md due to broken URL

### ISSUE THREAD

**Issue by dmitrykos** [jaakkopasanen/AutoEq#702]
Some URLs can not be reconstructed from INDEX.md if they contain name with slash, for example:

`AutoEq/results/crinacle/Bruel & Kjaer 4620 in-ear` 

contains 

`BLON Annotation/BLON Annotation` 

working URL to the raw `BLON Annotation ParametricEQ.txt` file inside that folder is

`https://raw.githubusercontent.com/dmitrykos/AutoEq/master/results/crinacle/Bruel%20%26%20Kjaer%204620%20in-ear/BLON%20Annotation/BLON%20Annotation/BLON%20Annotation%20ParametricEQ.txt`

note here is double `BLON%20Annotation/BLON%20Annotation`

but then INDEX.md has only single `BLON%20Annotation` like this:

`- [BLON Annotation](./crinacle/Bruel%20&%20Kjaer%204620%20in-ear/BLON%20Annotation) by Crinacle, Bruel & Kjaer 4620`

and URL based on this entry becomes:

`https://raw.githubusercontent.com/dmitrykos/AutoEq/master/results/crinacle/Bruel%20&%20Kjaer%204620%20in-ear/BLON%20Annotation/BLON%20Annotation%20ParametricEQ.txt`

Due to missing one more `BLON%20Annotation` entry this URL is broken.

To get working URL the correct entry in the INDEX.md would be:

`- [BLON Annotation](./crinacle/Bruel%20&%20Kjaer%204620%20in-ear/BLON%20Annotation/BLON%20Annotation) by Crinacle, Bruel & Kjaer 4620`

The proposal is to simplify name `BLON Annotation/BLON Annotation`  to `BLON Annotation`, so 3-rd party parser could parse the database.

**Comment by jaakkopasanen** [comment]
Thanks for reporting! I reworked the entire indexing script and this should be an issue no longer.
