### ISSUE TITLE
Let us disable smoothing up until 10kHz

### ISSUE THREAD

**Issue by Xorio71** [jaakkopasanen/AutoEq#706]
**Is your feature request related to a problem? Please describe.**
Due to the treble smoothing, peaks at 8-9kHz don't get equalized. This leads to harsh audio.

**Describe the solution you'd like**
Would it be possible to introduce a toggle in the web app that disables smoothing up until the 10kHz mark?

**Describe alternatives you've considered**
A band-aid solution is to play with the transition window (which defaults to 6kHz-8kHz) but that causes big dips in the 10kHz mark which normally wouldn't be there.

**Additional context**
Nothing to add.

**Comment by jaakkopasanen** [comment]
Using the transition window is indeed a correct way to go about this. However keep in mind that equalizing those peaks close or beyond 10 kHz might not work as expected. The location of the peaks at high frequencies depends on the individual ears geometry and acoustic imbedance. There's nothing that can be done feature wise in AutoEq.

If you're using parametric eq and have spare filters, you can try adding some at the frequencies you experience hot. But this is of course manual exercise.

**Comment by Xorio71** [comment]
I see. Thanks a bunch for the reply!
