### ISSUE TITLE
Request to add "Ranking" data

### ISSUE THREAD

**Issue by Hastings014** [jaakkopasanen/AutoEq#707]
When I'm trying to fit different headphone target curves to a given headphone, it can sometimes be difficult to figure out which target curve most closely aligns with that headphone. However, this issue has already been addressed for the Harman target on the AutoEQ Github's "Headphone Ranking" page. 

Because of this, my feature request is to add some kind of "Ranking"-type section to the app that calculates and outputs stuff like:

- all of the data fields in the headphone ranking data table (listener preference score, standard deviation of the error, slope of the logarithimc regression fit of the error, average of the absolute error) for a given selected headphone and target curve pairing. 

- error data across given band sizes (octave, 1/2 octave etc)

- etc.

Okay! That's my request! Hope this makes it in!

**Comment by jaakkopasanen** [comment]
The Harman preference scores are only defined for GRAS measurement systems and Harman targets. They even have different equation for the score for over-ear and in-ear headphones so it's not reasonable to assume the equations would translate to other rigs and targets as is.

**Comment by Hastings014** [comment]
Yeah, that's what I thought for the Harman Target, that preference score is only specific to that Target. In any case, maybe this means that "Ranking" is just the wrong word. Sorry about this, not trying to be overly pushy or anything, I want to try to clarify further. I would encapsulate the request as just wanting additional error data, like standard deviation etc. If you remove from the request all of the "harman specific" stuff, is this something you would consider for the project?

**Comment by jaakkopasanen** [comment]
I see. That makes more sense but still I'm not feeling too hot about this. AutoEq is about producing equalizer profiles for headphones, not comparing headphones unequalized or checking how well they adhere to a target, even if some people are using it for that.
