### ISSUE TITLE
Is there an error importing AutoEQ cfg as an EqualizerAPO GraphicEq?

### ISSUE THREAD

**Issue by Vakke** [jaakkopasanen/AutoEq#710]
I'm using Morphit pregenerated EQ profile for a reference to my Beyerdynamic DT 880 Edition 32 ohms and refer to AutoEQs frequency curve and Rtings freq curve.

It seems that AutoEQs frequencies start with -0.8 decibel for 20hz and in freq curve shows that it should be almost +6 db correction.

Is there something im doing wrong or is the import on EqualizerApo broken somehow?

**Comment by jaakkopasanen** [comment]
Could you provide some screenshots or other context to help me understand what exactly is your issue?

**Comment by Vakke** [comment]
![Näyttökuva 2023-10-07 170832](https://github.com/jaakkopasanen/AutoEq/assets/30244745/e11c739c-9d5e-4f8f-95f9-f9b822ccd141)
![Näyttökuva 2023-10-07 170619](https://github.com/jaakkopasanen/AutoEq/assets/30244745/9fb61f7b-a71e-4aab-b92a-4052f348161c)

There's images of the EQ curve on flat default. The default gain is -12db but when I set it to 0 db the gain just goes to -0.2db

In the graph it seems that the lower frequency should be boosted rather than minus boost them

**Comment by jaakkopasanen** [comment]
Seems like you're talking about the max gain parameter. This sets a ceiling for the equalizer positive gain (which is compensated with negative preamp to prevent clipping). Reducing max gain is a solution for the volume becoming too low due to the preamp when the headphone amplifier does not have enough analog gain to compensate.

Why are you setting max gain to 0 dB?

**Comment by Vakke** [comment]
> Seems like you're talking about the max gain parameter. This sets a ceiling for the equalizer positive gain (which is compensated with negative preamp to prevent clipping). Reducing max gain is a solution for the volume becoming too low due to the preamp when the headphone amplifier does not have enough analog gain to compensate.
> 
> Why are you setting max gain to 0 dB?

That's not what I meant, sorry for the misunderstanding. 

The images are just meant for the comparison of the EQ profile generated for the EqualizerAPO. As shown in the upper images yellow line the correction at lower frequency should have a boost as a positivie number rather than negative. When I take away the max gain it seems that the generated profile has a maximum upper limit of -0.2 db and it doesn't go higher even though it should.

For example the generated profile by the Morphit app has a very similar generated EQ profile for EqualizerAPO but it correctly follows and implements the positive db boost. 

![Näyttökuva 2023-10-09 113302](https://github.com/jaakkopasanen/AutoEq/assets/30244745/2b2c475f-4035-4802-bad3-3f357a3cef64)

It seems that the default generated flat profile by AutoEq to EqualizerAPO has a -6.8db for 20hz and in the image it seems that the correction as in the yellow line should be around +5.8db. Also at the peaks on 6000hz the correction should be around -8.8db and in the profile it has a correction of over -20db.

I'm new to these things so I don't know do I understand this wrong but the sound generated by the AutoEq profile is very different to the one generated by Morphit where they both aim to achieve most neutral there is.

**Comment by jaakkopasanen** [comment]
Thanks. I think I understand now. The GraphicEQ.txt has normalization built in to eliminate need of separate preamp. Eq shouldn't boost any frequency because that can lead to clipping. With parametric eq you would use negative preamp to ensure the gain is never positive but here it's built into the curve itself. The AutoEq UI doesn't show this.

**Comment by Vakke** [comment]
Hmm okay. I'll include all the different EQ profiles below here so you can see how the end product EQ curve is and does it seem normal to you and is the fix for me to have more volume or something.

First one is the default EqualizerAPO EQ:

![default](https://github.com/jaakkopasanen/AutoEq/assets/30244745/1ce7c866-8084-4ee9-9480-0d35c17ff304)

Second one is the Morphit EQ:

![morphit](https://github.com/jaakkopasanen/AutoEq/assets/30244745/a285ab96-e366-49a3-a3b7-cf688a30168c)

Third Graphic EQ:

![graphiceq](https://github.com/jaakkopasanen/AutoEq/assets/30244745/115d5d5e-b9fb-48f7-a907-55c925b98452)


Fourth Parametric EQ:

![parametriceq](https://github.com/jaakkopasanen/AutoEq/assets/30244745/898918f8-df72-4881-9332-4da4dcf02f45)

**Comment by jaakkopasanen** [comment]
You are using "Flat" as your target and on the website screenshot you can see that the 20 kHz of the equalizer curve is at 12 dB while the 6 kHz is at -9 dB. What is the configuration you're using with Morphit? And why are you using Flat as the target? You should never use that with uncompensated headphone frequency responses.

**Comment by Vakke** [comment]
>  And why are you using Flat as the target? You should never use that with uncompensated headphone frequency responses.

What do you mean by this? Like I said I'm a beginner on these but I've usually tried to use flat as I have a slight tinnitus and avoid high frequencies if possible. Would you recommend using somehthing other?

**Comment by jaakkopasanen** [comment]
AutoEq selects an appropriate target for you automatically. If you wish to protect your hearing, just turn down the volume. Or alternatively you can move the treble boost frequency to lower and set negative treble boost gain.

The way headphones are measured, the 3 kHz elevation is expected. The measurement system simulates human ears and it's the ear that creates that, not the headphone. Therefore using flat as the target means countering what your ears do naturally.
