### ISSUE TITLE
Can we expect profile for Oppo enco buds 2?

### ISSUE THREAD

**Issue by o2rhkzqx** [jaakkopasanen/AutoEq#711]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Expecting oppo enco buds 2 sound profile.

**Describe the solution you'd like**
Oppo enco buds 2 sound profile to be added

**Describe alternatives you've considered**

**Additional context**

**Comment by jaakkopasanen** [comment]
If they get measured by oratory1990, crinacle or Rtings, yes. Otherwise no.
