### ISSUE TITLE
Error in Sennheiser 560S Parametric Setting

### ISSUE THREAD

**Issue by skycyclepilot** [jaakkopasanen/AutoEq#712]
In your recommended parametric settings for the Sennheiser 560S headphones, the first setting is for a low shelf filter at 105 Hz, Q of 0.7, and a gain of **9.1 dB**.  With the recommended overall gain setting of -6.4 dB, that pushes the gain well into the red when used with Equalizer APO.  That 9.1 dB recommendation can't be right...

![Equalizer APO](https://github.com/jaakkopasanen/AutoEq/assets/11599277/544f6325-b73f-408f-84c4-95638580ad07)

**Comment by jaakkopasanen** [comment]
The positive gain is below 20 Hz. AutoEq only optimizes 20 Hz to 20 kHz range. There's not really ever any content below 20 Hz so this is not a concern.
