### ISSUE TITLE
Why the score of headphone change over time？

### ISSUE THREAD

**Issue by ILOVETHEUSA** [jaakkopasanen/AutoEq#714]
For example ,the score of akg k371 two years ago is 89,now the score is 85

**Comment by jaakkopasanen** [comment]
oratory1990 remeasures headphones occasionally, or just measures more units. Due to unit variance, the frequency response, and therefore the preference score will change.

**Comment by ILOVETHEUSA** [comment]
> oratory1990 remeasures headphones occasionally, or just measures more units. Due to unit variance, the frequency response, and therefore the preference score will change.

Thank you for reply,Is the displayed score the average of multiple measurements or the score from the most recent measurement?

**Comment by jaakkopasanen** [comment]
Average measurement. oratory1990 for example keeps measuring more units of the same models and updates his published measurements with the new averages. AutoEq does the same for Crinacle's measurements, since he has data separately for different units.

**Comment by ILOVETHEUSA** [comment]
> Average measurement. oratory1990 for example keeps measuring more units of the same models and updates his published measurements with the new averages. AutoEq does the same for Crinacle's measurements, since he has data separately for different units.

But i find some earphone score change in your list while  dont change in oratory1990's result;
Take moondrop chu as an example,the oratory1990 score of moondrop chu has been 86 until now  ,and your score changed from 85 to 81

**Comment by jaakkopasanen** [comment]
Thanks for insisting! I found a bug where the IEM scores weren't using Harman 2019 target but instead what happened to be in the result, and since I switched to AutoEq in-ear target from Harman in-ear some time ago, the scores were different. This is fixed now and Moondrop Chu is back to 85.
