### ISSUE TITLE
Question on the physics of headphone correction

### ISSUE THREAD

**Issue by ARDEACT** [jaakkopasanen/AutoEq#715]
I'm using Autoeq for my HD600 to bring back some of the sub bass because they are open-back, but this made discover a question.
**How do you know that the headphones will accurately depict the target signature after corrections are made, considering material properties in real life?**
These factors include the diagram material, the chassis, and open-back or closed-back.
I would suspect that another frequency reading is made after making software corrections towards the target, to see where peaks deviant caused by real-life factors... Or maybe all of that is already taken into account from the initial reading itself?

**Comment by jaakkopasanen** [comment]
The impact of equalizer on the headphone's frequency response is as expected. At high boost levels (or similarly high volume levels) the headphones can start to produce harmonic distortion, but you shouldn't push the headphones so high, mostly for the sake of your own hearing.

If you wish to have more detailed explanation, I suggest asking in https://reddit.com/r/oratory1990
