### ISSUE TITLE
add Skullcandy Hesh 2 Wireless

### ISSUE THREAD

**Issue by HUNT3Rdotme** [jaakkopasanen/AutoEq#716]
link to RTINGS' review and analyses: https://www.rtings.com/headphones/reviews/skullcandy/hesh-2-wireless

**Comment by jaakkopasanen** [comment]
Skullcandy Hesh 2 is available. Rtings calls is Hesh 2 Wireless but they add "wireless", "truly wireless" and things like that themselves to the headphone names. Do you have a reason to suspect there exists different models for "Hesh 2" and "Hesh 2 Wireless"?

**Comment by HUNT3Rdotme** [comment]
.....Honestly, not really.

I think the only reason I thought that distinction exists was when trying to use stock profiles through RootlessJamesDSP, combined with the assumption that Skullcandy wouldn't needlessly put a word in their model name that would imply a wired variant. That's all on me, though.

Fortunately, I'm getting by with a 31-band setup made using the instructions from the Medium article in the meantime.

Sorry about this. 😅

**Comment by jaakkopasanen** [comment]
Thanks for confirming.
