### ISSUE TITLE
Galaxy Buds measurement by Oratory

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#72]
It looks like the Samsung Galaxy Buds measurement by Oratory is missing the bass boost that's normally applied on other IEMs. The error plots of the same IEM by RTINGS and crinacle confirm this assumption.
Could you look into this please?

**Comment by jaakkopasanen** [comment]
Thanks for this. I had placed the Samsung Galaxy Buds into earbud folder so they got no bass boost. I moved the to inear folder and redid the results.
