### ISSUE TITLE
Import Headphone IR as input instead of .csv

### ISSUE THREAD

**Issue by rwaldspur** [jaakkopasanen/AutoEq#720]
**Is your feature request related to a problem? Please describe.**
When creating AutoEQ settings for headphones, it would be fantastic to be able to import an IR directly for a given pair of headphones that has been sampled.

**Describe the solution you'd like**
Import a .wav file (or other) that contains an impulse response (presumably mono or stereo), and gives back the output of AutoEq as mono or stereo (as per usual in chosen format) as headphone settings.

**Describe alternatives you've considered**
Sure, one can transform the IR to a frequency response, and then export as a plot, which I'm currently doing.

**Additional context**
It would be great to give AutoEq the full dataset (actually IR) to be able to work with.
When processing a lot of IRs / running experiments every extra step slows things down.

Thanks for listening.

**Comment by rwaldspur** [comment]
A brief follow-up, which I forgot to mention.

If AutoEQ had access to the IR instead of a simple data plot, it would be great to be able to equalize the phase response for binaural rendering applications, where a BRIR is taken with the same microphone as the headphone IR.

**Comment by jaakkopasanen** [comment]
After some serious consideration, I've come to conclusion that I won't be implementing this feature. The ask is too niche for me to justify spending my time working on it.
