### ISSUE TITLE
why some handphone disappear from the Headphone Ranking list

### ISSUE THREAD

**Issue by ILOVETHEUSA** [jaakkopasanen/AutoEq#721]
for exmaple
moondrop blessing 2 dusk ,
beats solo pro

**Comment by ILOVETHEUSA** [comment]
solo pro now Reappear ，but last week i cant find it on the Headphone Ranking list

**Comment by jaakkopasanen** [comment]
Looks like the ranking script ignores measurements for IEMs that have Bruel & Kjaer 4620 measurement from crinacle available.

**Comment by jaakkopasanen** [comment]
Should be fixed now. The problem was as I expected.
