### ISSUE TITLE
Download the entire equed curve as a new headset

### ISSUE THREAD

**Issue by Manu99it** [jaakkopasanen/AutoEq#722]
**Is your feature request related to a problem? Please describe.**
Sometimes you have access not to a unique powerful equalizer, but to multiple equalizers, one applied after another one

**Describe the solution you'd like**
I would like to download the final equalized curve (not only the equalization) as a new "raw curve", as a CSV to import it and apply another eq.

**Describe alternatives you've considered**
For now I used the custom Parametric EQ to apply the first equalization of, say for example 5band. After that I fixed the max and min gain to these band in the filter section and added other filters, even duplicate ones for same bands (to apply on another eq). It suits a particular case as apply two fixed band equalizer, or two Parametric equalizers etc. However you can't download as irs or EqualizerAPO GraphicEQ setting

**Additional context**
The Xbox Wireless Headset has a fixed 5-band eq (125, 250, 1K, 4K, 8K hz) [and is 1.41Q the default for a fixed 5-band eq? On the Xbox accessories app the Q factor is not specified unfortunately]. This 5band equalization is retained into the headset and carried even with Xbox shutdown, to use for example on other devices. 
I would like to apply the fixed 5-band eq to always carry the best baseline on every device, and after apply another equalization to have the best equalization on devices where I have access to equalization. To do this, I need to treat an already eqed FR as a raw input to apply another EQ

**Comment by jaakkopasanen** [comment]
Seems like you have a very specific edge use-case there. The web app doesn't allow you to do this but you can do it with the "good ol' way". See [Command Line Use](https://github.com/jaakkopasanen/AutoEq#command-line-use) for instructions on how to install AutoEq on your PC and running the equalizer locally. This will produce CSV file that contains the `equalized_raw` curve. Rename that column as raw and delete the existing raw column in Excel (or Google Sheets, or LibreOffice Calc) and you can use that as a basis for another round of equalization.

**Comment by jaakkopasanen** [comment]
And just to clarify, I won't add this as a new feature to AutoEq web app.

**Comment by jaakkopasanen** [comment]
Alternatively, and perhaps a lot easier, you can take a screenshot of the graphs on the web app and use WebPlotDigitizer to get the equalized curve. Once you have CSV file for that, you can open the file as a new measurement. No need to install AutoEq or mess with CLI.

**Comment by Manu99it** [comment]
@jaakkopasanen it's not a big deal to use cli ahah😅, it's fine. I just didn't know autoeq would produce new CSV values, I believed it only had as output filters for equalization. But thinking about it I could have deducted it by the fact that you were producing graphs in that way, even much before the webapp. I'll use autoeq from cli without any problems 👍🏻👍🏻
