### ISSUE TITLE
EQ Headphone to another headphone using autoeq.app

### ISSUE THREAD

**Issue by Gershy13** [jaakkopasanen/AutoEq#723]
It would be really nice to have a easy feature on the website that would allow you to set another headphone as the target, for instance if i wanted to EQ my TYGR 300R to a pair of DT 1990s. Having either an option in the target section and being able to choose from the same list as i used earlier for selecting my headphones, or if it asks if i want to eq to a target or a specific headphone (maybe as a little pop up window or something).

One possible workaround to do it now is to go to the github and find the csv file i need and upload that as a target? Not sure if that would actually work?

Thanks
Gershy13

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#can-i-use-autoeq-to-simulate-a-different-headphone

**Comment by Gershy13** [comment]
> https://github.com/jaakkopasanen/AutoEq/wiki#can-i-use-autoeq-to-simulate-a-different-headphone

Thank you! I missed the wiki page. The link on the website to the wiki does not work for me.

Do you have any idea what the settings for fab filter pro q are? I remember reading somewhere that you had to multiply the Q by 1.41? Is this accurate?

**Comment by X6205** [comment]
> https://github.com/jaakkopasanen/AutoEq/wiki#can-i-use-autoeq-to-simulate-a-different-headphone

I am propably retarded :( but i cannot find that headphone button in step 2

**Comment by Gershy13** [comment]
> > https://github.com/jaakkopasanen/AutoEq/wiki#can-i-use-autoeq-to-simulate-a-different-headphone
> 
> I am propably retarded :( but i cannot find that headphone button in step 2

You have to enable show advanced in the section with knobs on the left. Then it's in the text box that was numbers and "frequency, raw" in it
