### ISSUE TITLE
AutoEq Spotify Equalizer Configuration Missing 1KHz Frequency Setting

### ISSUE THREAD

**Issue by williamandresr** [jaakkopasanen/AutoEq#724]
There is an inconsistency in the frequency settings between the Spotify built-in equalizer and the AutoEq application when configuring the equalizer for Spotify.

**To Reproduce**
Open the Spotify application.

Access the built-in equalizer settings.

Observe the available frequency settings, which include:

60Hz
150Hz
400Hz
1KHz
2.4KHz
15KHz
Launch the AutoEq application and select the Spotify built-in equalizer option.

Review the frequency settings provided by AutoEq, which exclude the 1KHz setting:

60Hz
150Hz
400Hz
2.4KHz
15KHz
The absence of the 1KHz frequency setting is the issue.

**Expected behavior**
I expected the AutoEq application to provide all the same frequency settings available in the Spotify built-in equalizer, including the 1KHz option.

**Comment by jaakkopasanen** [comment]
Oopsy daisy! Will fix. Thanks for reporting.

**Comment by jaakkopasanen** [comment]
Fixed 🎉
