### ISSUE TITLE
AirPods Pro 2 + Custom EQ

### ISSUE THREAD

**Issue by choodique** [jaakkopasanen/AutoEq#728]
hi, 
I use yandex.music which has a built-in equalizer:

<img width="449" alt="image" src="https://github.com/jaakkopasanen/AutoEq/assets/47228554/796fa609-5476-41e9-8551-efe1010a7778">

Is there any way to find out the value of the parameters of this equalizer for Apple AirPods Pro 2 headphones?

**Comment by jaakkopasanen** [comment]
This is possible with Custom Parametric Eq option. You just need to configure the frequencies for both the min fc and max fc for each respective filter. Similarly every filter should have -12 dB as min gain and 12 dB as max gain. Make sure all of the filters are PEAKING (by default there's two shelf filters).

Now the quality (Q) is a different beast. Typically that's the same for all filters in graphic equalizers but here the ratio of neighboring filter frequencies doesn't stay the same (600 -> 1k = 1.5x but 1k -> 3k = 3x). You could try setting min Q and max Q for each filter to 1.41 and then just adjusting 12k, 14k and 16k bands manually.

This is really a strange equalizer that you have there. Nothing much more I can advice you unfortunately.
