### ISSUE TITLE
 How can I use it to calibrate my studio monitors?

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [jaakkopasanen/AutoEq#73]
Hi, is there any way to use this with studio monitors?
I have a Sonarworks xref20 measurement microphone and I would like to find a open source tool to calibrate my studio monitors.

**Comment by jaakkopasanen** [comment]
Hi. AutoEQ is really meant for headphones and although it would work for speakers as well, there are better tools for it. Namely [RoomEQWizard](https://www.roomeqwizard.com/).

I hope that helps you.

**Comment by FelipeSanchezCalzada** [comment]
Thank you very much for your answer, it has really been a great help!
