### ISSUE TITLE
Nothing X app

### ISSUE THREAD

**Issue by Tacocat263** [jaakkopasanen/AutoEq#734]
I would like the Nothing X app to be added to the equalizer list. I know it's not as extensive as other apps in the form of EQ but it would be useful because I wouldn't need to install the equalizer on all of my devices.

**Comment by TheScreechingBagel** [comment]
it does seem to have some sort of import via qr code functionality, although I haven't looked at it at all yet, so idk if it's a link to data hosted by nothing or EQ data encoded right in the qr code
