### ISSUE TITLE
How to restore old results? 

### ISSUE THREAD

**Issue by itkind** [jaakkopasanen/AutoEq#737]
Hi, I don't know what happened but the new results make my headphone sound dull. Eg. the [AWKT](https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/GRAS%2043AG-7%20over-ear/Audio-Technica%20ATH-AWKT) had a gain of +7.4 at 8758hz with Q 0.5 but now it has at 8684 a Q of 2.23. It had a +6.5 at 28hz Q0.6. Nothing of that is left. How come? How can I restore the old good results?

**Comment by itkind** [comment]
> You can click the "History" button, which leads you to https://github.com/jaakkopasanen/AutoEq/commits/master/results/crinacle/GRAS%2043AG-7%20over-ear/Audio-Technica%20ATH-AWKT
> 
> However, if you compare the different versions, you'll see that this particular one hasn't changed almost at all.
> 
> Do you mean even older than April?

Yes, older than April

**Comment by jaakkopasanen** [comment]
Where did you find those results?

**Comment by jaakkopasanen** [comment]
That's almost two years. Safe to say things have changed during this period, but I don't have good changelogs from the time so it's hard to say what exactly.
