### ISSUE TITLE
Tensorflow Issue

### ISSUE THREAD

**Issue by ButterInHD** [jaakkopasanen/AutoEq#74]
When i go to use AutoEQ's python program, it can't find Tensorflow or something in that vein, what's happening?

ERROR: Could not find a version that satisfies the requirement tensorflow>=1.12.1 (from -r requirements.txt (line 9)) (from versions: none)
ERROR: No matching distribution found for tensorflow>=1.12.1 (from -r requirements.txt (line 9))

**Comment by jaakkopasanen** [comment]
Hi. We've encountered similar problems before. Which version of Python you have installed?

**Comment by ButterInHD** [comment]
Python 3.7

**Comment by jaakkopasanen** [comment]
This could also be related to 64-bit vs 32-bit Python. AutoEQ only works with 64-bit. Could you try this out?

**Comment by jaakkopasanen** [comment]
This should be fixed by 64-bit Python. Closing the issue. Please reopen if the issue persists.
