### ISSUE TITLE
Update the ananda eq for ananda v3 (Stealth Magnets)

### ISSUE THREAD

**Issue by Master-Antonio** [jaakkopasanen/AutoEq#741]
Can you please update the eq of ananda, ananda is at v3 version with stealth magnets, v1 and v2 are discontinued.
Under you can find the eq.

**Comment by Master-Antonio** [comment]
Ananda V2 (Stealth Magnets)
![immagine](https://github.com/jaakkopasanen/AutoEq/assets/9674957/ea546f6d-8777-471c-8a5f-c838ec4723ea)

**Comment by jaakkopasanen** [comment]
This all depends on if they get measured by any of the supported databases. I've added squig.link to AutoEq but not all sites there. Many authors have not responded to my inquiry about using their data in AutoEq. vsg is one of these. Right now there's nothing I can do here.
