### ISSUE TITLE
Add support for Earful 

### ISSUE THREAD

**Issue by ForceConstant** [jaakkopasanen/AutoEq#747]
Earful is a frequency testing app, that can take a headphone eq correction file. https://distortaudio.org/earful.html The format is simply a csv such as below.The format of the file is simple: frequency followed by comma, followed by dBr response at that frequency

```
frequency_Hz,raw_dBr 
20.00,-6.19
20.20,-6.19
20.40,-6.18
20.61,-6.18
20.81,-6.17
...
```

**Comment by jaakkopasanen** [comment]
Interesting!

Why do you you think this would be a needed i.e. why not use any of the other supported apps, such as EqualizerApo?

**Comment by ForceConstant** [comment]
Personally I don't like to use systemwide EQ's since I use a variety of
outputs, different headphones, monitors, etc.Plus it might be useful for
others, as you could just label it Generic CSV, so you could save CSV to be
used in arbitrary tools.
