### ISSUE TITLE
Akg k270 studio

### ISSUE THREAD

**Issue by Ruslansviridkov** [jaakkopasanen/AutoEq#748]
Hello! Can I ask the developers to add akg k270 studio to AutoEq?

http://alexmod.do.am/forum/14-372-1
https://www.headphonereviews.org/headphone/AKG/K270S
https://www.head-fi.org/showcase/akg-k-270-studio.13225/

**Comment by Ruslansviridkov** [comment]
![Screenshot_20221125-085259(1)](https://github.com/jaakkopasanen/AutoEq/assets/153586372/b9a3d5ec-250e-427a-8a84-0821cf49f622)
![Screenshot_20221125-085303(1)](https://github.com/jaakkopasanen/AutoEq/assets/153586372/2550f8a3-c9cf-46e5-bdfc-21261f6c8b2f)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#my-headphones-are-not-in-autoeq-can-you-add-them
