### ISSUE TITLE
Soundpeats Free2 Classic 

### ISSUE THREAD

**Issue by UHVT123** [jaakkopasanen/AutoEq#749]
These are hailed as one the best if not the best soundpeats iem.

The thing is I can't seem to find frequency I am not sure if I am not that into audio. 

I found these 

https://hifitrends.com/2022/07/18/soundpeats-free2-classic-review-the-best-true-wireless-earbuds-under-25/

https://www.thephonograph.net/soundpeats-free2-classic-review/

I found this photo only but couldn't find the raw data, it's the same one in the link

I would really appreciate it, I really want to try these with autoeq, thanks in advance whatever the out come. 

![download (8)](https://github.com/jaakkopasanen/AutoEq/assets/148382683/38dffdc9-65fe-40d6-ad62-3c7c87b4bf20)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#my-headphones-are-not-in-autoeq-can-you-add-them
