### ISSUE TITLE
Using local path for images auto generated script

### ISSUE THREAD

**Issue by Banbeucmas** [jaakkopasanen/AutoEq#75]
Basically, the current script generates images and defines its path in the readme by using the github url.

This however, doesn't work really well when people trying to fork the project and use it as it renders the picture of some self complied results unavailable in the Readme. The minor fix for this is to edit the generation scripts and change the repository owner in the set_url method but I think fixing this from the main branch is better.

Github Markdown seem to support local files. So we can link that instead.

You can check https://github.com/Banbeucmas/AutoEq/blob/master/results/banbeucmas/Tin%20Audio%20T2%20(Camfire%20Audio%20IO)/README.md and check the equalization graph image path and you will see what I mean.

Just a little suggestion that would ease a minor issue for people who might fork this project and use them alone.

**Comment by jaakkopasanen** [comment]
I see. This is pretty nice. Shouldn't be a too tedious change so you can expect this to be implemented in the near future.

**Comment by jaakkopasanen** [comment]
Done. Thanks for the idea and the issue!
