### ISSUE TITLE
>> Pioneer HRM-7 <<

### ISSUE THREAD

**Issue by usrsnm** [jaakkopasanen/AutoEq#750]
**Headphone requests**

Pioneer HRM-7
https://www.kopfhoerer.de/test/pioneer-hrm-7/

Scroll down just a little, there is the graph, incl. meassurement data "Messdaten /Frequenzgang".
Klick on the graph's image, there you have the relevant data.

Many thanks! & Keep it up!
Cheers 
Chris

**Comment by usrsnm** [comment]
![hrm-7](https://github.com/jaakkopasanen/AutoEq/assets/154252573/acc9a257-944c-4a1a-b330-297760e57035)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#my-headphones-are-not-in-autoeq-can-you-add-them
