### ISSUE TITLE
Kz Pr1 measurements wildly inaccurate 

### ISSUE THREAD

**Issue by dhelgerson** [jaakkopasanen/AutoEq#752]
**Describe the bug**
The measurements of the kz pr1 are very inaccurate. 

**To Reproduce**
Chose kz pr1
Chose familiar target
Apply EQ 

**Expected behavior**
Headphones sound like target 

**Actual Behavior**
Headphones lack body and treble is very piercing, like measurements are biased to mids and against highs

**System:**
 - OS: all, tested: windows 11, macOS, Linux (Ubuntu and Arch, pipe wire backend)
 - Version: all

**Comment by jaakkopasanen** [comment]
There are two different measurements available for this headphone, one from crinacle and one from Fahryst. You may want to try both to see if either one is more to your liking. To see both, you need to click "all" at the bottom of the headphone selector first. Additionally you can play with treble boost knobs, tilt knob and sound signature to make the headphones sound closer to what you want. I don't measure headphones myself and therefore there's nothing I can do about the measurements themselves.
