### ISSUE TITLE
Dime 3 (Rtings) missing

### ISSUE THREAD

**Issue by kylagit** [jaakkopasanen/AutoEq#753]
The Skullcandy Dime 3 headphones have a measurement on Rtings.com, however they are not included in AutoEQ, please update AutoEQ with new measurements from Rtings including this one.

Link to Skullcandy Dime 3 on Rtings
https://www.rtings.com/headphones/reviews/skullcandy/dime-3-true-wireless

Do not use the measurement for the right ear, as they have said that it's inaccurate on the page.

**Comment by jaakkopasanen** [comment]
Another case of measurement being available in the v1.6 set. I need to update the crawler first.

**Comment by jaakkopasanen** [comment]
Crawler updated and new measurements added
