### ISSUE TITLE
Monoprice M1570C velours earpads and leather earpads Oratory1990

### ISSUE THREAD

**Issue by hottyson** [jaakkopasanen/AutoEq#756]
Monoprice M1570C (velours earpads) Oratory1990
https://www.dropbox.com/scl/fi/m7ie464i66kz1mp0dsw2u/Monoprice-M1570C-velours-earpads.pdf?rlkey=x54bofa5ye4sf6law4wmwulq2&dl=0

Monoprice M1570C (leather earpads) Oratory1990
https://www.dropbox.com/scl/fi/9bv06tweai39cih0l2yz9/Monoprice-M1570C-leather-earpads.pdf?rlkey=y2vkalvjsqzer1ukgh5611uxp&dl=0

**Comment by jaakkopasanen** [comment]
Done, enjoy

**Comment by hottyson** [comment]
Thank you! :)
