### ISSUE TITLE
Add FIIO x Jade Audio JD1 IEM

### ISSUE THREAD

**Issue by Dhwanil20** [jaakkopasanen/AutoEq#757]
Hello I have frequency Please add in AutoEQ Headphone DataSet i have uploaded in attachment Please Check
[FIIO JD1 Filters.txt](https://github.com/jaakkopasanen/AutoEq/files/13807616/FIIO.JD1.Filters.txt)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#my-headphones-are-not-in-autoeq-can-you-add-them
