### ISSUE TITLE
Compensated targets for squig.link sources

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#759]
Like with Crinacles measurements before, will you provide targets compensated for coupler differences?

**Comment by jaakkopasanen** [comment]
I won't. The couplers average errors are smaller than deviations and so calibrating the average error isn't justified.

More details are available at https://github.com/jaakkopasanen/audio-research-stuff/blob/main/Calibration/calibration.ipynb

**Comment by markanini** [comment]
Sounds like a sensible course, if that's what the data shows.
