### ISSUE TITLE
[Request] Generate filters for DynamicsProcessing

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#76]
Hi Jaakko,
It took some time but I found the source of the DynamicsProcessing library [here](https://android.googlesource.com/platform/frameworks/av/+/master/media/libeffects/dynamicsproc)
This should point to how the cutoff frequency and bandwidth are calculated

I asked @james34602 if he could look at it and deduce what filters are used on which he replied:
> FFT the input and N IFFT to obtain N bands time domain data, and finally N bands DRC on time domain.
> Also use FFT to obtain band signal power
> A Eigen linear alegbra library included is for parallelize the N FFT operations.

And how the bandwidth is calculated:
> Band grouping I guess, bandwidth depend on FFT length

I hope this will give a little headstart

**Comment by jaakkopasanen** [comment]
Thanks for this. I don't understand anything he wrote but maybe I can figure it out from the source code.

**Comment by james34602** [comment]
@Pittvandewitt 
1. I'm not sure DynamicsProcessing do actual subband DRC, if yes, you can group the bands you need and multiply N magnitude masks in complex domain and perform N IFFT to get N time domain subband, thus DRC can be applied on each subband.

2. Longer the FFT length, more frequency resolution you get, if you manage to send frequency-gain data from Java to native, perhaps find a efficient way to get your current frequency scale(Something like N-nodes in EqualizeAPO) interpolate to DynamicsProcessing scale.
For example, interpolate N-nodes from logarithmic scale to uniform linear grid on 16384 FFT length, and send it to the native side.

**Comment by Pittvandewitt** [comment]
After more experimenting I came to the conclusion that not only eq bands in dynamicsprocessing suffer from clipping when setting a low cutoff frequency, but also multibands with low cutoff frequency.
This issue cannot be solved by generating different filters. The only solution to prevent clipping is to set a high frame duration.
Thanks to both of you for willing to look into this
