### ISSUE TITLE
Please add QCY H3

### ISSUE THREAD

**Issue by imlambertf** [jaakkopasanen/AutoEq#761]
Headphone: QCY H3 
Link: https://www.qcy.com/lang-en/productview/1312.html

43dB Hybrid ANC: Your Oasis of Silence
Adaptive Dual-Mode: ANC & Audio Enhancement
3-Mic Clarity: Clear Calls, No Compromises
Transparency Mode: Conversations with Your Headphones On
Hi-Res Audio: Pure Sound Quality
40mm Titanium Drivers: Relish Theater-Grade 3D Sound
60H Playtime: Music that Never Stops
Lossless Sound: Type-C/AUX Options
Bluetooth version: 5.4

**Comment by SkyAFS** [comment]
this thing is selling like hotcakes i already have 7 friends asking for eq, i also would like a profile for than, so far the only thing i notice is that -10 to -12 db on 200hz makes the headphone a lot more close to flat response, also +3 on 1000 gives color, im still testing but i would like to see a full eq

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/audio-research-stuff/blob/main/Calibration/calibration.ipynb
