### ISSUE TITLE
EPOS H6 Pro - similar profiles to use

### ISSUE THREAD

**Issue by sutex** [jaakkopasanen/AutoEq#762]
There is no profile for the H6 Pro and No Frequency response graphs for the epos h6 pro.  So what profile is close enough to be good enough to use? thanks

**Comment by jaakkopasanen** [comment]
You can't use a measurement for a different headphone because, well, they are different.

https://github.com/jaakkopasanen/audio-research-stuff/blob/main/Calibration/calibration.ipynb
