### ISSUE TITLE
Poweramp now natively support AutoEq presets

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#763]
https://github.com/jaakkopasanen/AutoEq/blob/3d2a902942c92ea673063d729cf7b0809615894b/webapp/ui/src/equalizers.js#L176

Since May it has built-it/preinstalled AutoEq presets updated at every release:
https://forum.powerampapp.com/files/file/84-powerampequalizer-build-963-uniapk/

**Comment by jaakkopasanen** [comment]
Good to know. Thanks!
