### ISSUE TITLE
YAMAHA HPH MT7 ADD REQUEST

### ISSUE THREAD

**Issue by GreatHenRocks** [jaakkopasanen/AutoEq#765]
![mt7 frequency response graph](https://github.com/jaakkopasanen/AutoEq/assets/97775703/da1c4959-b358-4c31-8871-9f3f5dec9e4e)

I found this frequency response graphs for the Yamaha HPH MT7 headphones and was wondering if this is what i should provide to have them added. Thank you

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/audio-research-stuff/blob/main/Calibration/calibration.ipynb
