### ISSUE TITLE
Add oratory1990's Sennheiser-HD660S2 measurements

### ISSUE THREAD

**Issue by Ramblurr** [jaakkopasanen/AutoEq#766]
**Headphone requests**

oratory1990 has recently added the Sennheiser-HD660S2:

https://www.dropbox.com/scl/fi/v4wkt7t98ghc08nhfl3ur/Sennheiser-HD660S2.pdf?rlkey=em9ocbjw0t0u3orpyc15cqibu&dl=0

**Comment by jaakkopasanen** [comment]
Done, enjoy
