### ISSUE TITLE
Add EQ to Targets and Specify Optimization Frequency Bands

### ISSUE THREAD

**Issue by Hastings014** [jaakkopasanen/AutoEq#767]
**Is your feature request related to a problem? Please describe.**
When I'm EQ'ing headphones with AutoEQ, one thing that I find myself wanting is more user-friendly EQ control for shaping the target curve.  

**Describe the solution you'd like**
I recognize that AutoEQ currently has a high and low shelf that can be added to the target, as well as a csv for sound signature.  What I'd like is for additional custom PEQ controls to shape the target.  This is very useful when wanting to prevent AutoEQ from correcting a large null in a response, or just for quick-shaping that doesn't involve having to generate and copy-paste a sound signature 

**Describe alternatives you've considered**
I wouldn't so much list this as a complete alternate, but more of a compliment.  This would be a feature that lets the user define an arbitrary amount of frequency bands where AutoEQ will correct the response, and ignore regions not specified.   

**Additional context**
These features are useful for for allowing the user to work hand in hand with AutoEQ, as a sort of combined human-machine team to optimize the correction.   

**Add any other context or screenshots about the feature request here.**

**Comment by eduardoeae** [comment]
I do something like this manually. Using crinacle's graph tool or another similar one I use a 8khz, 3 Q, -3 gain for reducing the sibilance on my iems. I export it with the Graphic EQ and after editing it I end up with a csv file to use as "Sound signature".

A tool to ease this process would be great. Maybe not on the same interface though. Something apart that produces a detailed (Graphic Eq is made for Wavelet and it doesn't have much precision) signature file to use on AutoEq would be ideal, I think.

**Comment by jaakkopasanen** [comment]
This can be done quite easily with sound signature without help of any external tools, like Excel. The sound signature CSV doesn't care about how many data points you add and so if you just want to take down 3 kHz you can do

```
frequency,raw
20,0
2000,0
3000,-6
4500,0
20000,0
```

I don't see reason to add any more tweaking options.
