### ISSUE TITLE
Negative gain values in --bass-boost and --treble-boost produce error

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#769]
Using a negative gain in --bass-boost and --treble-boost, with all three arguments (gain,frequency,quality) fail with the error:
`__main__.py: error: argument --treble-boost: expected one argument`

Using a negative gain only (without frequency and quality) works fine.

**Comment by jaakkopasanen** [comment]
Can you share the full command you've used?

**Comment by eduardoeae** [comment]
For example (just tried it):
 
 `python -m autoeq --input-file "measurements/KZ ZSN Pro.csv" --output-dir "/tmp/autoeq.tmp" --target "targets/Harman IE.csv" --treble-boost -2,10000,0.7 --tilt -1.0 --treble-f-lower 4500 --treble-f-upper 9000`
 
 The exact same command, using a positive gain for the treble, does not cause an error.
