### ISSUE TITLE
Please stop changing all settings when changing target curves or headphones

### ISSUE THREAD

**Issue by dhelgerson** [jaakkopasanen/AutoEq#770]
**Is your feature request related to a problem? Please describe.**
I love autoeq but it's insanely annoying to be going through different targets only to have all the advanced settings reset to their defaults (especially the bass boost. I always disable it and it's incredibly annoying to have to turn it down every time)

**Describe the solution you'd like**
just store each setting as a browser cookie and don't change when changing targets

**Describe alternatives you've considered**
tying settings to a google account or something would be super nice for cross-device coherence

**Additional context**
I use multiple headphones on multiple devices regularly and it would be nice if autoeqq.app was more consistent across those devices

**Comment by jaakkopasanen** [comment]
This is actually by desing and quite a lot of effort went into implementing this 😄 

Different targets ask for different bass shelves and measurements done on different measurement systems ask for different targets as do different headphone types.

I agree that while cross-device syncing would be nice, it would require user accounts. Right now AutoEq app doesn't know anything about the user and I intend to keep it that way.
