### ISSUE TITLE
Anker Soundcore P20i / P25i

### ISSUE THREAD

**Issue by dniminenn** [jaakkopasanen/AutoEq#772]
Please add Anker P20i. Here is the link to Rtings measurements

https://www.rtings.com/headphones/reviews/anker/soundcore-p25i-p20i-true-wireless#page-test-results

Thank you:)

**Comment by jaakkopasanen** [comment]
Thanks for letting me know about this. Looks like Rtings has added a yet another version of their measurements, and so I need to update the crawler to get these.

**Comment by jaakkopasanen** [comment]
Crawler updated and new measurements added
