### ISSUE TITLE
Documentation Revision/update

### ISSUE THREAD

**Issue by radioaddition** [jaakkopasanen/AutoEq#774]
On [this](https://github.com/jaakkopasanen/AutoEq/wiki/Choosing-an-Equalizer-App) section of the documentation, the RootlessJamesDSP app can be made to work with DRM-controlled streaming services (eg Spotify) without root, but it requires patching the app (a reputable program that can do this without too much effort is [ReVanced Manager](https://github.com/ReVanced/revanced-manager)). Thought that at least some of this information could be included in the EQ app documentation

**Comment by jaakkopasanen** [comment]
I added a short note about this in the table.
