### ISSUE TITLE
Add a date or version of the profile in the webapp

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#775]
**Is your feature request related to a problem? Please describe.**
It would be nice to see in the webapp the date of the measurement scraping.

**Describe the solution you'd like**
We could add a data or any versioning solution

**Describe alternatives you've considered**
Always check the github repository for new relevant commits.

**Additional context**

**Comment by bhack** [comment]
P.s. Are you planning a result refresh?

**Comment by jaakkopasanen** [comment]
New measurements just added.

I don't think I'll add dates or versioning. Paying attention to different versions is just splitting hairs and vast majority of the users won't care. You can always find the old stuff in Github.

**Comment by bhack** [comment]
It would be nice to know from the webui when it was retrieved.
