### ISSUE TITLE
Missing target selection

### ISSUE THREAD

**Issue by osiwaru** [jaakkopasanen/AutoEq#776]
**Describe the bug**
When using autoeq.app in my browsers, I no longer see a selection of targets.

**To Reproduce**
Firefox and Edge display this behavior

**Expected behavior**
On the left side, there was a section where you could change the target, as far as I remember.

**Files**
![autoeq-app-firefox](https://github.com/jaakkopasanen/AutoEq/assets/2129564/34010f0a-b5c2-4f9d-bf14-8c775746ab76)

**System:**
 - OS: Windows 11 Pro 23H2 (build 222631.3007)
 - Firefox 122.0.1
 - MS Edge 121.0.2277.112

**Additional context**
None

**Comment by jaakkopasanen** [comment]
Can you scroll that? The UI layout changes depending on the screen size. In this layout it's below. Could be hidden under advanced, if you haven't opened that yet on this device.
