### ISSUE TITLE
Denon/Marantz receivers new equalizer app

### ISSUE THREAD

**Issue by Red5goahead** [jaakkopasanen/AutoEq#777]
I would like to suggest adding an EQ for Marantz and Denon receivers that is very similar to the 10-band EQ but with the cutoff at 31 Hz. thus missing

This is a detail from the manual of my Marantz SR-7012

[![image33973f8f3eca0387.md.png](https://add.pics/images/2024/02/15/image33973f8f3eca0387.md.png)](https://add.pics/Yvwgum)

**Comment by jaakkopasanen** [comment]
You can simply ignore the 31 Hz band in this case. Or adjust the 62 Hz a bit. In any case bass should be adjusted to taste.

I won't add this as an eq app option because I want to keep the list fairly short and clean and this is such a niche option.
