### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'`

### ISSUE THREAD

**Issue by CFCF** [jaakkopasanen/AutoEq#78]
Running the example code

`python frequency_response.py --input_dir="oratory1990/data/onear/Sennheiser HD 800" --output_dir="my_results\Sennheiser HD 800 (HD 650)" --compensation="compensation\harman_over-ear_2018_wo_bass.csv" --sound_signature="results\oratory1990\harman_over-ear_2018\Sennheiser HD 650\Sennheiser HD 650.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4`

Triggers the following error message:

```
python frequency_response.py --input_dir="oratory1990/data/onear/Sennheiser HD 800" --output_dir="my_results\Sennheiser HD 800 (HD 650)" --compensation="compensation\harman_over-ear_2018_wo_bass.csv" --sound_signature="results\oratory1990\harman_over-ear_2018\Sennheiser HD 650\Sennheiser HD 650.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4

frequency_response.py:179: UserWarning: Resetting data of "smoothed", "error", "error_smoothed", "equalization", "parametric_eq", "equalized_raw", "equalized_smoothed", "target". These need to be regenerated if they are still needed!
  '", "'.join(reset_data)
Traceback (most recent call last):
  File "frequency_response.py", line 1869, in <module>
    FrequencyResponse.main(**FrequencyResponse.cli_args())
  File "frequency_response.py", line 1687, in main
    fs=fs
  File "frequency_response.py", line 1580, in process
    peq_filters, n_peq_filters, peq_max_gains = self.optimize_parametric_eq(max_filters=max_filters, fs=fs)
  File "frequency_response.py", line 645, in optimize_parametric_eq
    fs=fs
  File "frequency_response.py", line 310, in optimize_biquad_filters
    tf.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph' 
```

**Comment by CFCF** [comment]
Found the cause and the solution: requirements.txt installed TensorFlow 2 but the code contains symbols as contained in TensorFlow 1.2+.

I created a new virtualenv and made sure pip is up to date
`py -m pip install --upgrade pip`
then I installed TensorFlow 1.5rc
`pip install tensorflow==1.15rc2`
before installing the other packages with requirements.txt
'pip install -r requirements.txt'

Now everything works fine.

**Comment by jaakkopasanen** [comment]
Thanks a lot for reporting this and providing the solution!

I set Tensorflow version as <1.15.0 in the requirements and verified the installation on both Python 3.6 and Python 3.7 so this should be fixed now.
