### ISSUE TITLE
request TRN MT1 Pro

### ISSUE THREAD

**Issue by StarS2112** [jaakkopasanen/AutoEq#780]
would be happy if TRN MT1 Pro added .. although its not far off from the og TRN MT1

measurement graph :
https://ianfann.squig.link/?share=TRN_MT1_PRO

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/wiki#my-headphones-are-not-in-autoeq-can-you-add-them
