### ISSUE TITLE
Oratory Hi-x15 measurement?

### ISSUE THREAD

**Issue by Prolatus** [jaakkopasanen/AutoEq#781]
[Austrian Audio Hi-X15](https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/over-ear/Austrian%20Audio%20Hi-X15) by oratory1990

What is wrong with this database/page?
The Hi-X25bt and Hi-X15 ares the same measurement I see on the Oratory1990 list.

Can it be fixed?

**Comment by jaakkopasanen** [comment]
Looks like there's only one PDF and that's linked to both Hi-X15 and Hi-X25BT on oratory1990's reddit measurement index. In AutoEq it's called Hi-X15. Since the PDF itself mentions both, I assume they are acoustically identical.

**Comment by Prolatus** [comment]
Thanks... I noticed both headphones on one pdf indeed.
Now I can use the Autoeq for the  x25bt..
