### ISSUE TITLE
Some more Equalizer options

### ISSUE THREAD

**Issue by Riekopo** [jaakkopasanen/AutoEq#784]
I own many gaming headsets and am trying to use the Auto.EQ app to adjust them. However, I don't see a 5 band graphic EQ option or a 10 band parametric EQ option in the EQ list. SteelSeries Sonar uses a 10 band parametric EQ and Logitech G Hub uses a 5 band graphic EQ for some headsets and a 10 band parametric EQ for others.

**Comment by jaakkopasanen** [comment]
5 band graphic eqs are all so different that there's no one configuration that fits all. You can configure what you need with custom parametric eq. Just set the min and max values for frequency and Q to same. Q should be 1.0 (ish).

10 band parametric eq is easier. You should be able to just use Peace, or almost any other PEQ option.

I try to keep the list somewhat short and my intention is not to add every imaginable eq app there.
