### ISSUE TITLE
Adjust eq profile to 8-band equalizer from soundcore app

### ISSUE THREAD

**Issue by GiakomoZ** [jaakkopasanen/AutoEq#786]
Hi, I'm trying to use the EQ settings from your website on the official Soundcore app for my Q20 headphones. I want to have the same EQ profile on all my devices by syncing it with the headphones, but the app's EQ has only 8 bands—100, 200, 400, 800, 1600, 3200, 6400, and 12800 Hz. I don't know how to make the website's EQ profile work with these bands, especially since the website's graph doesn't show precise values. Any hints on how to crack this?
![Screenshot_20240327_101620_soundcore](https://github.com/jaakkopasanen/AutoEq/assets/85363938/244cddb4-1613-4c35-b113-e144705cf8db)

**Comment by jaakkopasanen** [comment]
You can use Custom Parametric Equalizer. Configure 8 peaking filters with min and max frequency of each band to the value your app has. Use 1.41 as Q for min and max form every filter.

**Comment by GiakomoZ** [comment]
> You can use Custom Parametric Equalizer. Configure 8 peaking filters with min and max frequency of each band to the value your app has. Use 1.41 as Q for min and max form every filter.

So I should do something like this:
![image](https://github.com/jaakkopasanen/AutoEq/assets/85363938/4a7f824d-188c-437d-bd80-ddfa964cae84)

the app's eq now is like this (I can't go under -6 db for the 100hz band):
![Screenshot_20240327_113939_soundcore](https://github.com/jaakkopasanen/AutoEq/assets/85363938/e13eb416-fa80-408e-9420-a1788fa62c80)

**Comment by jaakkopasanen** [comment]
Looks about right. You can also set min and max gains in the custom peq based on the range your app allows. Might not make a huge difference with graphic eq though.

**Comment by GiakomoZ** [comment]
> Looks about right. You can also set min and max gains in the custom peq based on the range your app allows. Might not make a huge difference with graphic eq though.

Thank you! one last thing: the app only permits to modify a band by entire dbs (like +1, -1, but not -1.4 or + 2.7). is there a way to specify this on the website?

**Comment by jaakkopasanen** [comment]
Unfortunately not. Just round to the closest integer.

**Comment by atari-64** [comment]
Old one, but use wavelet :)

**Comment by KraXen72** [comment]
for anyone here, i managed to get the precise eq values by using the [openscq30](https://github.com/Oppzippy/OpenSCQ30) app. you can enter the eq values there (up to decimal level for each band) and save it as a new custom eq preset.
for me it then even showed up in the official soundcore app (you might have to toggle a few eqs back and forth in the official soundcore app)

**Comment by KraXen72** [comment]
Could this app be added as a preset to the website, please? @jaakkopasanen 
Thank you!
