### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by dmitrykos** [jaakkopasanen/AutoEq#787]
There are some broken URLs found (error 404) while parsing the database or while viewing via the web interface:

Web interface:
http://github.com/jaakkopasanen/AutoEq/blob/master/results/Regan%20Cipher/in-ear/1MORE%20PistonBuds%20Pro%20Q30
http://github.com/jaakkopasanen/AutoEq/blob/master/results/Kuulokenurkka/over-ear/ZMF%20Bokeh%20(protein%20earpads,%20no%20mesh)

URL to the preset:
http://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/Regan%20Cipher/in-ear/1MORE%20PistonBuds%20Pro%20Q30/1MORE%20PistonBuds%20Pro%20Q30%20ParametricEQ.txt
http://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/Kuulokenurkka/over-ear/ZMF%20Bokeh%20(protein%20earpads,%20no%20mesh)/ZMF%20Bokeh%20%28protein%20earpads%2C%20no%20mesh%29%20ParametricEQ.txt

In general there are quite many failing URLs if parsing current database.

**Comment by Soppilif** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/over-ear/HIFIMAN%20Ananda%20Stealth as well.

**Comment by lizn0421** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/over-ear/Anker%20Soundcore%20Space%20Q45%20(wired,%20passive)

as well

**Comment by DrCWO** [comment]
I also found two broken links and mailes Jaakko. 
Let's see is something happens...

**Comment by jaakkopasanen** [comment]
Thanks for reporting! Looks like my IDE didn't actually commit the files to Git. Now all of those links work as expected.
