### ISSUE TITLE
Broken Links!!

### ISSUE THREAD

**Issue by DrCWO** [jaakkopasanen/AutoEq#788]
Hi Jakko,
I encountered an issue with your Links on the "results" page.

Blow "Recommended Results" is a linked the list of headphones.
If I click on [Bowers & Wilkins Px8](https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/over-ear/Bowers%20&%20Wilkins%20Px8) UI see a 404 Page not found.

Would you please be so kind to fix it. One of my customers complained that the link 

https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/over-ear/Bowers%20&%20Wilkins%20Px8/Bowers%20&%20Wilkins%20Px8%20minimum%20phase%2044100Hz.wav?raw=true

I use to retrieve your filters did not work. 
This is probably not the reason why it fails but I ask myself it is a good practice to have an unquoted "&" in the link...

Thank you
Best DrCWO

**Comment by jaakkopasanen** [comment]
#787
