### ISSUE TITLE
Is this warning normal?

### ISSUE THREAD

**Issue by arne00** [jaakkopasanen/AutoEq#79]
Hello! 

My equalization seems to be normal, but when I used AutoEq there were bunch of warnings..

For example: 
WARNING:tensorflow:From frequency_response.py:308: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From frequency_response.py:433: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From frequency_response.py:530: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From frequency_response.py:539: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From frequency_response.py:540: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

I even got many more warnings (such as "FutureWarning"), but it would be a bit too long to post it.

Is this normal to get some warnings when creating the presets? Did my equalization work just fine? :)

Thank you.

**Comment by 4steps-svg** [comment]
No it isn't normal

ср, 9 окт. 2019 г., 20:54 arne00 <notifications@github.com>:

**Comment by jaakkopasanen** [comment]
Tensoflow has recently gotten very keen on warning developers about future compatibility. AutoEq has Tensorflow version fixed to <1.15.0 so there's no risk that any of these scenarios would come true. If I need to upgrade Tensorflow at some point I will make sure the code works.

So nothing to worry about. AutoEq runs just as intended.
