### ISSUE TITLE
EQ for iBasso IT01

### ISSUE THREAD

**Issue by AlexBrodianoi** [jaakkopasanen/AutoEq#8]
Measurements avaialbe at:
https://www.head-fi.org/threads/crinacles-iem-fr-measurement-database-315-entries.830062/
https://www.head-fi.org/threads/ibasso-it01-a-fun-iem-single-multilayered-graphene-driver-99-usd.865037/page-121#post-14144166

**Comment by jaakkopasanen** [comment]
Crinacle's measurements are going to be supported in the future but that will take some time. In the meanwhile you can use [WebPlotDigitizer](https://apps.automeris.io/wpd/) and run the equalization yourself.

I'll update here when Crinacle's measurements have been added.

**Comment by jaakkopasanen** [comment]
I'm still waiting for crinacle to get the raw numeric data done for his measurement database. However I got the guide written: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)

**Comment by jaakkopasanen** [comment]
See [Issue 21](https://github.com/jaakkopasanen/AutoEq/issues/21) for updates on progress on crinacle's measurements.
