### ISSUE TITLE
Parametric eq vs convolution 

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#80]
Hi,
When given a choice, should one prefer convolution over a parametric eq, or the other way around?

**Comment by jaakkopasanen** [comment]
Usually there's not much difference. Some convolvers introduce delay equal to the FIR filter length and in those cases parametric eq would be preferred. EqualizerAPO has very good implementations of both so there it doesn't matter. Parametric eq might be a bit less accurate but the difference might not be audible.
