### ISSUE TITLE
Tensorflow issues 

### ISSUE THREAD

**Issue by venkatesh63** [jaakkopasanen/AutoEq#81]
@jaakkopasanen i reinstalled again and again still not getting proper result.And i am getting Futurewarnings.And i updated to tensorflow<1.15.0.

 python frequency_response.py --input_dir="oratory1990/data/onear/Sennheiser HD 800" --output_dir="my_results/Sennheiser HD 800 (HD 650)" --compensation="compensation/harman_over-ear_2018_wo_bass.csv" --sound_signature="results/oratory1990/harman_over-ear_2018/Sennheiser HD 650/Sennheiser HD 650.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
frequency_response.py:177: UserWarning: Resetting data of "smoothed", "error", "error_smoothed", "equalization", "parametric_eq", "equalized_raw", "equalized_smoothed", "target". These need to be regenerated if they are still needed!
  '", "'.join(reset_data)
WARNING:tensorflow:From frequency_response.py:308: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From frequency_response.py:433: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From frequency_response.py:530: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From frequency_response.py:539: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From frequency_response.py:540: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow\python\ops\math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From frequency_response.py:548: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

1/1 (100.0%) 33s: Sennheiser HD 800

**Comment by jaakkopasanen** [comment]
You don't have to worry about the future warnings. What do you mean by not getting proper results?

**Comment by venkatesh63** [comment]
@jaakkopasanen i seen and installed this issue in this article https://github.com/tensorflow/tensorflow/issues/31249
Do you have multiple versions of numpy installed in your system?
pip show numpy
Can you uninstall all numpy versions and later install numpy==1.16.4?
pip uninstall numpy (till you uninstall all versions)
pip install numpy==1.16.4

And i'm not Futurewarnings now.
you can include above numpy version in requirements.
i mean proper results is without errors whlie executing or compile the below result.
 
python frequency_response.py --input_dir="innerfidelity/data/onear/Sennheiser HD 650" --output_dir="my_results/HD650" --compensation="innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv" --equalize --bass_boost=4
1/1 (100.0%) 10s: Sennheiser HD 650

**Comment by jaakkopasanen** [comment]
I upgraded to Tensorflow 2 just now. Try reinstalling dependencies with
```
pip install -U -r requirements.txt
```

**Comment by venkatesh63** [comment]
@jaakkopasanen i tried but still getting Fututewarnings.
 python frequency_response.py --input_dir="innerfidelity/data/onear/Sennheiser HD 650" --output_dir="my_results/HD650" --compensation="innerfidelity/resources/innerfidelity_compensation_sbaf-serious.csv" --equalize --bass_boost=4
WARNING:tensorflow:From C:\Users\dvenk\Documents\GitHub\AutoEq\venv\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
1/1 (100.0%) 7s: Sennheiser HD 650

**Comment by venkatesh63** [comment]
Thanks @jaakkopasanen Limited dependency versions to patch number upgrades was good now and executing without errors.
