### ISSUE TITLE
Correction for Hifiman HE4XX measurement, plus other new headphones added by Oratory1990

### ISSUE THREAD

**Issue by mttu** [jaakkopasanen/AutoEq#82]
Hi, Oratory1990 has measured around 15 new headphones recently, including the Noble K10 IEM, the Focal Spirit Classic, the AKG K361, and an updated measurement of the Hifiman HE4XX performed by Oratory1990 himself, as the previous one was actually done by head-fi.org and found to be inaccurate in the bass, likely due to an improper seal. Could you add these new measurements to AutoEQ? Thanks

**Comment by mttu** [comment]
Here's a full list of headphones added / with updated measurements: https://www.reddit.com/r/oratory1990/comments/do8987/oratory1990s_list_of_eq_presets_update_281019/

And all the measurement pdfs on Dropbox: https://www.dropbox.com/sh/654wxtmhlq0dhqa/AAAKT-RIbEKpsl-JW7mOnu_9a

**Comment by jaakkopasanen** [comment]
Done. You'll find HE4XX here: https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Massdrop%20x%20Hifiman%20HE4XX
