### ISSUE TITLE
[Headphone Request] 1More Sonoflow

### ISSUE THREAD

**Issue by ActiveNL** [jaakkopasanen/AutoEq#845]
I'd like to make a request for the 1More Sonoflow.

I found these measurements:
https://www.audiosciencereview.com/forum/index.php?threads/1more-sonoflow-nc-headphone-review.42849/

When I try to make a .csv from them I keep receiving an error when uploading to AutoEq: **Error: x must be increasing if s > 0**

**Comment by Valkyrjur82** [comment]
[1More Sonoflow.txt](https://github.com/user-attachments/files/17676190/1More.Sonoflow.txt)
This file was converted to import the preset to autoeq with programs like wavelet on Android.
Credits to ezdiy for posting it on ASR forums.
