### ISSUE TITLE
Harman In-ear 2019 v2 Target

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#85]
Sean Olive and Licten inc have developed a new target response for IEMs. This needs to be added to compensations and made the only available result on Crinacle and oratory1990.

https://www.reddit.com/r/headphones/comments/dnliv4/does_anyone_have_information_on_this_new_inear/

**Comment by Pittvandewitt** [comment]
It seems that Crinacle has this measurement available. He has used it to compensate a frequency response in this post https://crinacle.com/2019/11/15/tin-hifi-t4-review-benchmark/
Looks like it should solve the extreme dip in the upper treble in some of the results provided

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/harman_in-ear_2019v2.png
https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/harman_in-ear_2019v2.csv

All pre-computed Crinacle and oratory1990 IEM results use now only this new 2019 target.

**Comment by ILOVETHEUSA** [comment]
> Sean Olive 和 Licten inc 为 IEM 开发了新的目标响应。这需要添加到补偿中，并在 Crinacle 和 oratory1990 上成为唯一可用的结果。
> 
> https://www.reddit.com/r/headphones/comments/dnliv4/does_anyone_have_information_on_this_new_inear/

Hi,can you tell me the sourse of harman target curve 2019（original artical or paper) plz,I have been seeking it for a long time.
