### ISSUE TITLE
Parametric EQ Filter Ringing Prevention

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#86]
Parametric eq filters can be optimized in a way that rining is avoided. The absolute value of the first derivative of the filter transfer function tells how much the filter self oscillates. Need to find out the threshold value. Parametric eq optimizer loss function should incorporate this to punish for too high values.

https://www.reddit.com/r/oratory1990/comments/do8987/oratory1990s_list_of_eq_presets_update_281019/f5p7zcx?utm_source=share&utm_medium=web2x

**Comment by NekoAlosama** [comment]
@jaakkopasanen  Is this related to the new limited slope equalization?

**Comment by jaakkopasanen** [comment]
Yes it is. However the parametric eq optimizer can still produce high Q filters even if the total equalizer frequency response target doesn't have so high Q features (because of the slope limit algorithm). Extra safeguards need to be implemented for parametric eq.
