### ISSUE TITLE
Few request [Klipsch R6 & OneOdio DJ PRO]

### ISSUE THREAD

**Issue by shadowzoom** [jaakkopasanen/AutoEq#9]
Hi there! If somebody can get parameters for this headphones:
https://www.amazon.com/OneOdio-Adapter-Free-Headphones-Monitoring-Isolation/dp/B01B2L6Z54
https://www.amazon.com/Klipsch-1062411-0-R6-On-Ear-Headphones/dp/B0169N84LI
This will be great, thanks!

**Comment by jaakkopasanen** [comment]
If you find the frequency response measurements for these you can create the eq settings yourself: [Equalizing Headphones the Easy Way](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9)
