### ISSUE TITLE
Idea: Fixed Band EQ in steps

### ISSUE THREAD

**Issue by Hermit121** [jaakkopasanen/AutoEq#93]
a option to limit the fixed band eq to steps would be pretty helpful for people using eq apps or portable players that for example only allow 0.5db steps and not 0.1db

**Comment by jaakkopasanen** [comment]
Hey. Thanks for the idea. However I don't think this would be necessary because users can simply round the fixed band eq gains to the closest available step. There might be ever so slight difference in end result (think 0.1 dB) but that should not be an audible concern.
