### ISSUE TITLE
BlitzWolf® BW-ES2 Dual Dynamic Drivers In-ear Earphone Headphone With Mic

### ISSUE THREAD

**Issue by venkatesh63** [jaakkopasanen/AutoEq#96]
@jaakkopasanen can you include files for BlitzWolf® BW-ES2.

**Comment by jaakkopasanen** [comment]
There's really nothing I can do if the said headphones have not been measured by any of the supported sources (oratory1990, Innerfidelity, ...). You can however add them yourself if you manage to find some frequency response graph for the headphones. See the linked guide in the results page.
