### ISSUE TITLE
EQ for AirPods Pro

### ISSUE THREAD

**Issue by cubarco** [jaakkopasanen/AutoEq#98]
Hi @jaakkopasanen ,
There has already been a review for AirPods Pro on RTINGS with a raw frequency response curve. Could you please add an EQ for AirPods Pro based on that?

link to RTINGS: [https://www.rtings.com/headphones/reviews/apple/airpods-pro-truly-wireless](https://www.rtings.com/headphones/reviews/apple/airpods-pro-truly-wireless)

**Comment by evanheckert** [comment]
@cubarco I was able to follow the instructions to produce this output:

# Apple AirPods Pro
See [usage instructions](https://github.com/jaakkopasanen/AutoEq#usage) for more options and info.

### Parametric EQs
In case of using parametric equalizer, apply preamp of **-3.2dB** and build filters manually
with these parameters. The first 5 filters can be used independently.
When using independent subset of filters, apply preamp of **-1.6dB**.

| Type    | Fc       |    Q | Gain     |
|:--------|:---------|:-----|:---------|
| Peaking | 25 Hz    | 0.1  | 1.1 dB   |
| Peaking | 501 Hz   | 0.7  | -3.6 dB  |
| Peaking | 860 Hz   | 2.06 | 3.1 dB   |
| Peaking | 1993 Hz  | 2.94 | -2.4 dB  |
| Peaking | 19187 Hz | 0.64 | -13.7 dB |
| Peaking | 20 Hz    | 2.24 | 1.8 dB   |
| Peaking | 869 Hz   | 0.25 | 1.1 dB   |
| Peaking | 13447 Hz | 1.24 | 3.8 dB   |
| Peaking | 15479 Hz | 2.53 | -4.9 dB  |
| Peaking | 18529 Hz | 3    | 2.4 dB   |

### Fixed Band EQs
In case of using fixed band (also called graphic) equalizer, apply preamp of **-2.7dB**
(if available) and set gains manually with these parameters.

| Type    | Fc       |    Q | Gain    |
|:--------|:---------|:-----|:--------|
| Peaking | 31 Hz    | 1.41 | 1.7 dB  | -1
| Peaking | 62 Hz    | 1.41 | 0.1 dB  |-2.6
| Peaking | 125 Hz   | 1.41 | 1.2 dB  |-1.5
| Peaking | 250 Hz   | 1.41 | -0.5 dB |-3.2
| Peaking | 500 Hz   | 1.41 | -2.6 dB |-5.3
| Peaking | 1000 Hz  | 1.41 | 3.0 dB  |0.3
| Peaking | 2000 Hz  | 1.41 | -2.2 dB |-4.9
| Peaking | 4000 Hz  | 1.41 | 0.7 dB  |-2.0
| Peaking | 8000 Hz  | 1.41 | 0.9 dB  |-1.8
| Peaking | 16000 Hz | 1.41 | -9.2 dB |-11.9

**Comment by jaakkopasanen** [comment]
Now there's an "official" ones from Crinacle and Rtings:
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2017-1/Apple%20AirPods%20Pro
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/usound/Apple%20AirPods%20Pro
https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/Apple%20AirPods%20Pro

**Comment by ratheader** [comment]
In my opinion, this setting does not fit in the low frequency range. For some other headphones I have tried settings from your list (among others: Stax Lambda L700, Audeze LCD-i4, Sennheiser IE80 and IE800). They all fit very well. But the setting for the Airpods Pro does not fit at all, in my opinion.

I use Roon. The wired headphones and Stax amp get their signals converted by a Chord Hugo2. So I think that I have enough comparison possibilities. What the settings deliver on the Airpods Pro is way too treble-heavy - no room, no decent fundamental range.

Translated with www.DeepL.com/Translator (free version)
